### ISSUE TITLE
预览

### ISSUE THREAD

**Issue by chasentech** [vnotex/vnote#1003]
OS Version (操作系统):Linux

VNote Version 2.7.2

Symptoms (表现):按ctrl+T，进入预览时，代码段中的空格太窄，缩进的视觉效果不太好。

How to Repro (如何复现):

**Comment by chasenzhang5** [comment]
可以有什么办法让空格显示的宽一点吗？

**Comment by tamlok** [comment]
有截图吗？是等宽字体吗？可能你电脑上少了某个字体吧。

**Comment by chasenzhang5** [comment]
![2019-10-15 08-07-52屏幕截图](https://user-images.githubusercontent.com/31985757/66790624-19f6a880-ef23-11e9-9c82-4eb9791f72af.png)
![2019-10-15 08-07-31屏幕截图](https://user-images.githubusercontent.com/31985757/66790642-28dd5b00-ef23-11e9-9679-121dfab0b948.png)

**Comment by tamlok** [comment]
如果是默认的样式的话，安装一下上面提到的两个等宽字体吧

**Comment by chasenzhang5** [comment]
我试着换了了一下设置里面的字体，只是编辑模式下的字体会发生变化，预览的字体还是窄的。然后我也换了主题，发现v_simple这个主题的预览模式字体正常，其他的都偏窄。不知道是不是makedown渲染的问题？

**Comment by tamlok** [comment]
markdown渲染没啥问题的，就是字体的问题，你可以用chrome连接上去看看。

https://doc.qt.io/qt-5/qtwebengine-debugging.html
