### ISSUE TITLE
[macOS]笔记列表显示不全

### ISSUE THREAD

**Issue by ynnie** [vnotex/vnote#1004]
OS Version (操作系统):  macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): 笔记列表下方横向滚动条会遮盖最后一条笔记名称，显示不全。

How to Repro (如何复现): 新建名称较长的笔记，此时笔记列表下方会出现横向滚动条，此滚动条会遮盖最后一条标题，将纵向滚动条下滑也无法显示全。

**Comment by tamlok** [comment]
hi，github已关闭issue里面搜一下“mac 滚动条”即有解决办法。应该是要设置滚动条不要自动隐藏。

**Comment by ynnie** [comment]
OK, 已解决。

1. 将原始启动文件改名为VNote.real
cd /Applications/VNote.app/Contents/MacOS
mv VNote VNote.real

2.添加启动参数，新建脚本VNote，并填入以下内容：
#!/bin/bash
cd "/Applications/VNote.app/Contents/MacOS"
"/Applications/VNote.app/Contents/MacOS/VNote.real" -style Fusion
