### ISSUE TITLE
打开别的markdown文档

### ISSUE THREAD

**Issue by OSOPEN** [vnotex/vnote#1010]
OS Version (操作系统): Windows, Linux, macOS
Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.6
Symptoms (表现):
打开文档乱码

How to Repro (如何复现):
![image](https://user-images.githubusercontent.com/26252361/67252049-edeba200-f4a3-11e9-8821-87390dd5dd2f.png)
打开我上传的问题文件就能复现

**Comment by tamlok** [comment]
有没有可能是字体问题？其他问题中文显示正确吗？如果显示正确，那可能是这个文件的编码问题，是vnote创建的吗？如果不是，转成utf8试试。
