### ISSUE TITLE
C#代码高亮不准确

### ISSUE THREAD

**Issue by xp44mm** [vnotex/vnote#1016]
OS Version (操作系统): **Windows**, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.7.2
Symptoms (表现):

How to Repro (如何复现):
```C#
Observable.Interval(TimeSpan.FromSeconds(1))
    .Buffer(2)
    .Subscribe(x => Trace.WriteLine(
        $"{DateTime.Now.Second}: Got {x[0]} and {x[1]}"));
```
这段代码高亮不准确。

**Comment by xp44mm** [comment]
错误好像是源于`highlightjs`的解析器？

**Comment by xp44mm** [comment]
github的高亮好像也是错误的

**Comment by tamlok** [comment]
是的，vnote是调用highlightjs的高亮。

**Comment by xp44mm** [comment]
highlightjs位置在哪个文件夹里？

**Comment by tamlok** [comment]
VNote里面内嵌了，源代码在 https://github.com/tamlok/vnote/tree/master/src/utils/highlightjs

**Comment by xp44mm** [comment]
@tamlok 
建议不要内嵌，可以读取后保存在内存中，现在的计算机不差这一点性能了。

**Comment by xp44mm** [comment]
我向highlightjs发issue了，他们给了我jsfiddle的模板，希望我能再现问题，我用这个模板测试了有问题的高亮代码，结果是在他们的展示页面高亮和在vnote中的高亮是不同的，展示页面的高亮基本正确，而vnote中是要差一些，是否引用了错误的版本或有其它的误用情况，他们给出的展示链接是：
https://jsfiddle.net/ajoshguy/a1kntyg4/
希望对你有所帮助。

**Comment by tamlok** [comment]
新版使用prism了
