### ISSUE TITLE
重新载入路径失败

### ISSUE THREAD

**Issue by jpfss** [vnotex/vnote#1031]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2（protable）

Symptoms (表现):
公司上上传就截图总是失败，整理场景如下：
(1)打开VNote创建了笔记本的文件夹。
(2)给已经创建的笔记文件夹中添加了几个Markdown文件。
(3)利用右键选择“从磁盘中重新加载”，提示对话框“打开文件夹XXX失败，请检查目录“E:XXXX”是否存在”。
注意：
(1)文件夹路径是存在的。
(2)笔记本文件夹路径含有中文和英文
(3)最后一级文件夹名字的英文为首字母大写的，改成小写的可以重新加载。不过也无法加载出来文件夹下的markdown文件。

最后，能否利用重新从磁盘加载的功能，加载笔记文件夹下已经存在的markdown文件到左侧笔记列表？如果可以的话，没看到怎么操作。上面即使换成小写重新加载也不能显示出来已有的markdown文件到笔记列表。
How to Repro (如何复现):
通过github直接回复即可

**Comment by tamlok** [comment]
Hi,

如果是把vnote当做笔记软件使用，推荐在vnote里面新建/维护文件夹和文件。在操作系统自行新建的文件需要手动添加到vnote. json索引文件中才能让vnote看到。

如果经常需要绕过vnote新建文件，可以把vnote仅仅当做是一个编辑器使用。左上角笔记本按钮旁边有一个浏览器按钮，能浏览系统上的文件系统，编辑外部文件。

**Comment by jpfss** [comment]
ok，刚换到这个软件不太会用，谢谢回答
