### ISSUE TITLE
编辑模式和阅读模式的渲染引擎是否不同？阅读模式无法使用MacType渲染

### ISSUE THREAD

**Issue by poly-1** [vnotex/vnote#1034]
OS Version (操作系统): Windows

VNote Version: 2.7.2 （当前最新版）

# Symptoms (表现):

启动MacType后，菜单栏等GUI界面均可被MacType渲染，编辑模式下所有文字也可被MacType渲染，但阅读模式的文字无法通过MacType渲染。

因为个人用惯了MacType，VNote也是一个神器，如果在阅读模式也能通过MacType渲染文字将会很赞。

# 期待的解决方案

这个问题解决起来应该有难度，但可否增加一个选项可以设置阅读模式和编辑模式的文字渲染引擎？如果阅读模式可以设置成与编辑模式一样的文字渲染引擎，应该也可被MacType渲染成功。

**Comment by tamlok** [comment]
阅读模式就是一个Chrome核心，应该是没问题的。

可以参考以下几个相关issue，看有没有帮助:

https://github.com/tamlok/vnote/search?q=is%3Aissue+is%3Aclosed+mactype+&type=Issues

**Comment by poly-1** [comment]
> 阅读模式就是一个Chrome核心，应该是没问题的。
> 
> 可以参考以下几个相关issue，看有没有帮助:
> 
> https://github.com/tamlok/vnote/search?q=is%3Aissue+is%3Aclosed+mactype+&type=Issues

感谢回复。如果是Chrome核心那就可以理解了，因为Chrome应该用的是Directwrite渲染字体，MacType不支持，不过核心里应该有相应选项可以设置…

**那么编辑模式用的是什么内核渲染的呢？**如果能把阅读模式改成跟编辑模式一样的核心也能解决这个问题。

**Comment by tamlok** [comment]
Chrome应该是支持MacType的吧？我看issue里面有用户成功设置的。

阅读模式其实就是一个网页，编辑模式是一个cpp的编辑器部件，不可能做到一样的。
