### ISSUE TITLE
是否可以有全局黑暗模式？类似于VSCODE，而不仅仅阅读模式可以修改渲染样式。

### ISSUE THREAD

**Issue by interjz4** [vnotex/vnote#1035]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
vnote支持主题，也支持单独设置编辑阅读样式。

文件菜单-主题，有6个内置主题供选择。需要重启vnote。

**Comment by supengchuan** [comment]
试了 Vnote 的6个主题，感觉总是怪怪的，建议有css大佬的，可以分享下自己自定义的主题给作者
