### ISSUE TITLE
On Windows, VNote UI uses Microsoft YaHei instead of locale-specific font

### ISSUE THREAD

**Issue by nyanpasu64** [vnotex/vnote#1038]
## OS Version (操作系统): Windows, Linux, macOS
Windows 10 x64, English (US) locale

## VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.7.2

## Symptoms (表现):
All UI elements use a font slightly different from most other Windows programs. In my locale (English USA), the default font is Segoe UI, but the font used by VNote looks more like Microsoft YaHei.

I think this is caused by https://github.com/tamlok/vnote/blob/16b6f2f/src/resources/themes/v_native/v_native.qss#L547 and other lines in similar files.

## How to Repro (如何复现):

Install VNote and look at any part of the UI with text.

## Solution:

A while back, I wrote some code which (on Windows) extracts the Windows locale-specific font, along with the proper size. I have two versions:

- Original: https://github.com/dolphin-emu/dolphin/pull/8359/files
- My own project: https://gitlab.com/nyanpasu64/exotracker-cpp/blob/master/src/win32_fonts.h

Do you want to incorporate this code into VNote, and remove the .qss rules overriding font in QWidget? I think removing the QSS rules will restore application font, but I have not built VNote to test.

Note that removing the .qss rules will affect other platforms as well, switching it to the platform/locale's native font, not a hard-coded font stack. I think this is a good thing, but it needs testing to ensure there's no broken Unicode (even if you think this fix is a good idea).

**Comment by tamlok** [comment]
Hi,

If you want to use default font you could just remove that line in the `qss` file. You could open the configuration folder in the `File` menu, and then go to the `themes` folder. No compilation is needed.

VNote overrides the default font is mainly for CJK users. I will consider to remove it by default. In that case, there is no need to add extra logic to handle it, right?

Thanks!
