### ISSUE TITLE
标题换行后，Tab键后内容自动转换成行内代码了

### ISSUE THREAD

**Issue by AiKier** [vnotex/vnote#1039]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2,  d78e892d5cc  etc..

Symptoms (表现):
在文档编辑中，一行设置为标题后
空格换行后，按tab键 进行空格
再输入文字或者粘贴文字  会出现 将字符串转换为行内代码

How to Repro (如何复现):
新建笔记 ==> 设置一行标题 ==> 回车键换行 ==> Tab键自动空格后 ==> 输入文字
就会发现自动 转换成行内代码了。

**Comment by AiKier** [comment]
另外在保存后，阅读模式下不知道为何，之前的Tab键空出的空格全部消失了
也就是文字段落 前面没有空白。

**Comment by tamlok** [comment]
Hi,

1. Markdown里面四个空格缩进同样也可以表示代码块；
2. Markdown里面空格一般都会被去掉，如果想要首行缩进，请自行使用搜索引擎搜索各种已有的解决方案；
3. 更多Markdown基本语法，可以参考帮助菜单的语法指南。
