### ISSUE TITLE
Render View don't show up

### ISSUE THREAD

**Issue by WingDust** [vnotex/vnote#1053]
![image](https://user-images.githubusercontent.com/45911286/68671021-53a1ea00-0589-11ea-9794-5ab377c9627b.png)

![image](https://user-images.githubusercontent.com/45911286/68671046-65838d00-0589-11ea-99a0-47f05c0435ce.png)

![image](https://user-images.githubusercontent.com/45911286/68671073-703e2200-0589-11ea-9c59-44ef07ca9e04.png)

**Comment by WingDust** [comment]
我正在写 “>”空格“+” 的markdown 语法，当转到渲染页面时，页面无法滑动翻页，重启后就出现了渲染不出页面了

**Comment by WingDust** [comment]
![image](https://user-images.githubusercontent.com/45911286/68672616-f27c1580-058c-11ea-9014-795c2afd3a0e.png)

![image](https://user-images.githubusercontent.com/45911286/68672659-06277c00-058d-11ea-98c6-065ce52f8615.png)

我的图片全没了

**Comment by tamlok** [comment]
hi，

md里面加号也是可以实现无序列表的吗？换乘减号试试？

其他笔记会出现无法预览的情况吗？

在标签页上右键打开笔记所在文件夹，然后去到v_images看看图片看看是否还在？如果不在需要找回的话，可以在笔记本的回收站找回。

另外，是否开启自动保存？建议关闭，使用交换文件的方式。

**Comment by WingDust** [comment]
我的图片文件是空的 
![image](https://user-images.githubusercontent.com/45911286/68749724-a9ce6600-0639-11ea-9f22-f0a77483ef00.png)

笔记本的回收站是指电脑的回收站吗

自动保存我是没有打开的

**Comment by tamlok** [comment]
暂时没有什么好的头绪。

可以试试不要在标题前面加`+`列表。

每个笔记本有一个文件夹充当回收站，在标签页上右键即可打开：

![image](https://user-images.githubusercontent.com/5763157/68752307-0e8bbf80-063e-11ea-984f-8ae59271d427.png)

**Comment by WingDust** [comment]
谢谢

**Comment by WingDust** [comment]
不过 我试了多次 markdown 中 
>空格+空格
它就会出现这种情况
最好复现一下

**Comment by WingDust** [comment]
‘>’空格+空格
