### ISSUE TITLE
当把笔记本内的一个文件夹变成一个笔记本后，该文件夹下的文件不能显示在文件浏览框里

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#1061]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
把文件夹的路径复制后，在vnote中新建一个笔记本，粘贴路径后新建笔记本。
文件浏览框无文件。

至于子文件夹的内容依然可以在文件浏览框看到。

此外，既然有一个额外的文件浏览器。可否增加一下交互操作。比如按一个快捷键，跳转到浏览器界面，再按一个快捷键跳回到笔记本界面对应的文件夹？

**Comment by tamlok** [comment]
文件夹方面的操作后面会大改。

另外，一个笔记本里面将一个文件夹作为一个笔记本的操作肯定是不能支持的。

**Comment by HgyHgyHgy** [comment]
为什么不能支持？

此外，感觉笔记本下的根文件夹，为什么要和其他文件不一样？功能上完全没区别。
这个区分，也让新建文件夹在笔记本底下，和在文件夹底下，具有不必要的区别。不能用同样的快捷键和按钮实现。

把某个文件夹作为一个新笔记本，可以简化vnote的显示。由于vnote不能只显示某个文件夹，而隐藏其他文件夹。这个是变通的方法。
