### ISSUE TITLE
win10  vnote 版本 2.7.2  预览窗口一片漆黑，无法查看

### ISSUE THREAD

**Issue by nigoolasi** [vnotex/vnote#1068]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
按你们说的方法，改集成显卡，添加环境变量均不好使，

**Comment by tamlok** [comment]
重启系统了吗？opengl的值都每个尝试了吗？vnote都得重启。

**Comment by nigoolasi** [comment]
是的，全部都试了，也重启了系统



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Le Tan <notifications@github.com&gt;
发送时间: 2019年11月16日 17:59
收件人: tamlok/vnote <vnote@noreply.github.com&gt;
抄送: nigoolasi <243877075@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tamlok/vnote] win10  vnote 版本 2.7.2  预览窗口一片漆黑，无法查看 (#1068)




重启系统了吗？opengl的值都每个尝试了吗？vnote都得重启。

**Comment by tamlok** [comment]
预览窗口是指阅读模式吗？能否给个整个软件的截图？

**Comment by nigoolasi** [comment]
对，阅读窗口，现在截图不是很方便，电脑不在身边，不好意思



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Le Tan <notifications@github.com&gt;
发送时间: 2019年11月17日 09:07
收件人: tamlok/vnote <vnote@noreply.github.com&gt;
抄送: nigoolasi <243877075@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tamlok/vnote] win10  vnote 版本 2.7.2  预览窗口一片漆黑，无法查看 (#1068)




预览窗口是指阅读模式吗？能否给个整个软件的截图？

**Comment by tamlok** [comment]
是Windows吧？另外可以试试更新系统/显卡驱动等，或者试试32位的vnote。如果还不行，我也没啥好办法了，环境问题不太好处理。有空可以补一个截图。

**Comment by nigoolasi** [comment]
截图来啦






发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Le Tan <notifications@github.com&gt;
发送时间: 2019年11月17日 09:22
收件人: tamlok/vnote <vnote@noreply.github.com&gt;
抄送: nigoolasi <243877075@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[tamlok/vnote] win10  vnote 版本 2.7.2  预览窗口一片漆黑，无法查看 (#1068)




是Windows吧？另外可以试试更新系统/显卡驱动等，或者试试32位的vnote。如果还不行，我也没啥好办法了，环境问题不太好处理。有空可以补一个截图。

**Comment by tamlok** [comment]
已支持双边预览： https://github.com/vnotex/vnote/releases/tag/v3.10.0
