### ISSUE TITLE
VNote与github同步后，由于github的markdown语法是GFM，因此不会自动识别VNote里的换行，这个目前有办法解决吗？

### ISSUE THREAD

**Issue by liviuslw** [vnotex/vnote#1071]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

Symptoms (表现):VNote的文件git push到github之后，由于语法问题，github不会自动分行，因此所有的都在一行，如果每行后面加上<br\>或者两个空格太麻烦了；此外github在图片缩放的部分，与VNote的语法也不同，不过这个可以通过不设置缩放来解决。想问下目前有办法让VNote转换成github默认的语法GFM吗？
![image](https://user-images.githubusercontent.com/25994425/69005246-4eaeb300-095a-11ea-8ad4-724b7b923828.png)
这些分行都没有显示

**Comment by liviuslw** [comment]
找到了一个比较快速的办法，在markdown文件里，每行结尾加上2个空格。不过还是很不优雅。不知道有没有其他优雅的办法解决

**Comment by tamlok** [comment]
GFM里面如果没有自动换行的选择，那vnote好像也做不了什么~~那应该是GFM应该做的事情了。

所以还是推荐行末两个空格强制换行这种标准语法吧。

缩放也是markdown-it的扩展，不属于基本语法，如果考虑到GFM，建议不要使用。
