### ISSUE TITLE
重启电脑，重新下载，只能够通过任务管理器关闭后台，版本：2.72

### ISSUE THREAD

**Issue by lightningmn** [vnotex/vnote#1077]
OS Version (操作系统): Windows 

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
不能够关闭软件，只能够通过任务管理器关闭软件
How to Repro (如何复现):
一打开软件，就不显示底部的任务栏

**Comment by tamlok** [comment]
关闭VNote，将`C:\Users\xxx\AppData\Roaming\vnote\session.ini`文件删除，打开VNote看看。
