### ISSUE TITLE
安装文档操作将so移动到了plug里面，也修改了权限，还是不能切换fcitx

### ISSUE THREAD

**Issue by laterXXX** [vnotex/vnote#1085]
OS Version (操作系统): KDE neon
VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

确认一下fcitx-qt5是否设置正确，您试试执行`fcitx-diagnose`命令，看看输出里面关于Qt的模块和变量是否已经安装设置正确。

参考：

https://github.com/tamlok/vnote/issues/962

https://github.com/tamlok/vnote/issues/49

**Comment by laterXXX** [comment]
谢谢您这么快回复。输出Environment variable QT_IM_MODULE is set to "fcitx" correctly.Found fcitx im module for Qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`. 然后那个so大小是473.4，我又重新编译了fcitx-qt5，我的QT是5.13.2。有点崩溃了，弄了一天，也看了很多解决方法，没有解决，最开始qt creator也不能切换到fcitx，将so复制过去可以了，但vnote不行，我又重新编译vnote还是没有解决

**Comment by tamlok** [comment]
vnote目前只支持qt 5.9。fcitx和qt5的恩恩怨怨我也很难说清楚。😂

**Comment by laterXXX** [comment]
好的，谢谢啦！  那应该是qt版本的鬼。

**Comment by o-github-o** [comment]
安装了qt5.9还是不能输入中

**Comment by tamlok** [comment]
@o-github-o 就是linux下面qt5和fcitx的配置问题，是一个普遍问题，可以多查一下尝试一下。

**Comment by o-github-o** [comment]
> @o-github-o 就是linux下面qt5和fcitx的配置问题，是一个普遍问题，可以多查一下尝试一下。

thx，通过合成重新编译安装fcitx-qt5解决了

**Comment by henices** [comment]
#985
