### ISSUE TITLE
一直没明白那个左右分栏的作用，是文件预览吗？可是又无法预览。

### ISSUE THREAD

**Issue by JackieZheng** [vnotex/vnote#1093]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2,  d78e892d5cc  etc..

Symptoms (表现):如题

How to Repro (如何复现):总是

**Comment by tamlok** [comment]
VNote不提供两边预览（除了图表功能提供），左右分割窗口是可以在两个窗口同时打开不同的文件，方便对照编辑，代码编辑器的一个常用特性。

**Comment by JackieZheng** [comment]
> VNote不提供两边预览（除了图表功能提供），左右分割窗口是可以在两个窗口同时打开不同的文件，方便对照编辑，代码编辑器的一个常用特性。

收悉，Thks。其实左右文件对照功能可以有，但不同的文件的对比个人感觉没必要，除非是同一文件不同版本比对。因为习惯了边编辑边预览，倒是希望能有此功能，现在的原窗口预览虽然可以通过快捷键切换，仍觉得左右窗口预览更方便。文件对比功能可以参照Beyond Compare功能，可能更实用。纯属个人意见。支持VNote！
