### ISSUE TITLE
mermaid 时序图 多个else失败

### ISSUE THREAD

**Issue by trotyzyq** [vnotex/vnote#1098]
alt  全部充值成功
           xx -->> 结算中心 : 返回成功
    else 部分充值失败或超时
        xx -->> 结算中心 : 返回失败
        xx ->> 人工 : 预警机制
    else 部分充值失败或超时
        xx -->> 结算中心 : 返回失败
        xx ->> 人工 : 预警机制
    end
多个else绘图失败，在其他编辑器是可以的

**Comment by tamlok** [comment]
mermaid版本没有更新，估计是兼容问题。
