### ISSUE TITLE
急~~~Vnote.exe主程序被趋势软件拦截

### ISSUE THREAD

**Issue by Thomas-trian** [vnotex/vnote#1106]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8

Symptoms (表现):
打开Vnote时被趋势软件拦截，提示威胁。

![image](https://user-images.githubusercontent.com/50693188/70417649-abeedd80-1a9c-11ea-99b4-84da3d030cfc.png)

![image](https://user-images.githubusercontent.com/50693188/70417708-c9bc4280-1a9c-11ea-91c6-547bfd80f37c.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
hi，

如果是从 https://github.com/tamlok/vnote/releases/tag/v2.8 下载的，大可放心使用，添加例外，不必理会即可。

当前暂时没有提供md5，所以也无法验证是否经过篡改。一般来说才github下载的应该问题不大。
