### ISSUE TITLE
通用入口Ctrl+G不能查找中文

### ISSUE THREAD

**Issue by tangyb828** [vnotex/vnote#1110]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
系统？是否自编译？

**Comment by tangyb828** [comment]
正版Win10，VNote也是上午下载的。

**Comment by tamlok** [comment]
什么输入法？

应该是显卡驱动问题，可以按照置顶issue操作一波：

https://github.com/tamlok/vnote/issues/853
