### ISSUE TITLE
感谢楼主更新 mermaid ，再提两个绘图方便的建议

### ISSUE THREAD

**Issue by Gowa2017** [vnotex/vnote#1113]
OS Version (操作系统): macOS
Symptoms (表现):
我想用如下代码：

>\`\`\`circo
>digraph {
>a -> {b c d e f g h i j k l m n}
>}
>\`\`\`

实现这种效果不知是否可行：
![image](https://user-images.githubusercontent.com/33367355/71001191-b69e1800-2117-11ea-814c-1dd981ece0c9.png)

**Comment by tyskink** [comment]
另外
A-->B-->C
这种连续指向的不能被识别

如果能同Typora一样原地预览图片就好了

**Comment by tamlok** [comment]
@tyskink 这是mermaid的语法吗？能不能具体贴出来一个完整的代码段？
