### ISSUE TITLE
程序闪退，无法打开

### ISSUE THREAD

**Issue by lichking2019** [vnotex/vnote#1114]
OS Version (操作系统): macOS Catalina 10.15.2

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.1

Symptoms (表现):
安装VNote 2.8.1 版本后，闪退，尝试多次仍然闪退

**Comment by Nobiel** [comment]
+1 重启也无法解决，回滚到2.8版本正常

**Comment by tamlok** [comment]
现在尝试一下帮忙下载最新构建版本测试一下？github主页有链接。

**Comment by oceanlvr** [comment]
同样的问题，在安装了opencv后出现，应该与动态库或者 `openGL` 有关.

**Comment by July-X** [comment]
vnote: 2.9
macOS:10.15.3 (19D76)

启动失败

**Comment by tamlok** [comment]
应该已经修复
