### ISSUE TITLE
桌面窗口显示问题

### ISSUE THREAD

**Issue by Jontyshaw** [vnotex/vnote#1119]
OS Version (操作系统):Linux manjaro gnome

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.1,  d78e892d5cc  etc..

Symptoms [(表现):在gnome上打开vnote主题显示上面有一部分黑有一部分白

How to Repro (如何复现):

**Comment by tamlok** [comment]
详细一点呀！是否自行编译？是不是官网的appimage？哪个主题？效果给个图片说明一下？

**Comment by Jontyshaw** [comment]
就是这种情况，github好像没法添加图片，我就从QQ邮箱上发送了

---原始邮件---
发件人: "Le Tan"<notifications@github.com&gt;
发送时间: 2019年12月19日(周四) 上午8:04
收件人: "tamlok/vnote"<vnote@noreply.github.com&gt;;
抄送: "Jonty Shaw"<jontyshaw@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tamlok/vnote] 桌面窗口显示问题 (#1119)



详细一点呀！是否自行编译？是不是官网的appimage？哪个主题？效果给个图片说明一下？

**Comment by tamlok** [comment]
github直接粘贴图片就会自动上传。

**Comment by Jontyshaw** [comment]
![2019-12-19 08-44-49屏幕截图](https://user-images.githubusercontent.com/34794522/71135209-05dd6900-223c-11ea-9ced-87dd328b5f87.png)
![2019-12-19 08-45-13屏幕截图](https://user-images.githubusercontent.com/34794522/71135210-0675ff80-223c-11ea-9ec8-21bca28ef2d9.png)

**Comment by Jontyshaw** [comment]
@tamlok 当qt5风格配置为Kvantum时他的显示就有问题，但是换成fushion就正常了

**Comment by tamlok** [comment]
如果系统设置了qt5的风格，请使用v_native主题。
