### ISSUE TITLE
建议: 强化笔记管理。

### ISSUE THREAD

**Issue by tyskink** [vnotex/vnote#1123]
OS Version (操作系统): Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

### 主要是第三方渲染器与Typora之间的差别:
1. 不支持iframe
2. 不支持js script, 例如嵌入github代码.
3. 编辑模式时候原地显示图片
4. 原地预览Mermaid等插件: 可以实时查看有没有搞错
5. 插入一些html元素之后，markdown-it和marked如果不能成功渲染（主要是嵌入的iframe或者网络视频导致的）的话，后面的内容就不能继续渲染了。剩下两个渲染器会卡很久才能出结果
6. 操作逻辑不太统一：笔记列表里点一下就打开笔记，标签列表里要双击才能查看标签下的笔记。
7. 不支持HTML剪贴板。例如复制一段包含图片的文字，图片就没了；复制一个超链接，超链接就变成纯文本了。

### 这里要道歉，标题里写放弃编辑器是骗眼球的。
自有编辑器是很有必要的，况且VNote在编辑体验上还有很多地方比Typora做的好，比如预设片段, 小推车，标题自动编号。可以添加设置：默认外部编辑器打开。
另外最重要的：简直完美的大纲视图（自动折叠和展开，索引参考线）

因此我觉得Vnote如果能提高本地markdown笔记管理上，支持用Typora或者其他外部编辑器当作默认编辑器。在笔记管理上反超Joplin。
毕竟编辑器上跟Typora差距是很明显的。做一个类似Zotero的markdown管理器。
Zotero也可以管理markdown，但这个软件的问题是它把所有的文件都编上自己的guid，挪到一个文件夹里，他的配置文件可编辑和可读性太差，对其他软件不友好。Joplin也是这个问题。这里我就认为VNote的思路很好，markdown+js配置，无论在什么设备上都可以脱离Vnote访问文件。所以markdown文件管理这方面，vnote做的最好了，但还是不够。

### 增强管理方案如下

![image](https://user-images.githubusercontent.com/22754217/71317934-2e779400-24c4-11ea-8078-bfdb6485e2a9.png)
详见[Google Docs](https://docs.google.com/presentation/d/1n2kZ6UvM5MHf-EcVGPwl-Oi_-A5yRjZuQINtguElMa8/edit?usp=sharing)

自我吐槽：
这个想法感觉能把软件重做一遍了。
交流一下想法，作者看看就好。

所以针对现阶段，我提几个个小建议，让VNote更像一个笔记管理器。
1. 用户可选择禁止编辑器
2. 禁止编辑器时候，单击笔记不打开，只显示大纲。双击笔记使用外部编辑器打开。
3. 让笔记本，历史，标签这三个窗口可以同时显示。
4. 把搜索框从右边挪到左边。

**Comment by tamlok** [comment]
Hi,

前面那7点很多看得不是很懂，或许是您还没有熟悉VNote的一些功能？可以看一下这个展示录屏（其中就展示了第7点直接粘贴HTML）：https://www.bilibili.com/video/av77455284

**Comment by tyskink** [comment]
> Hi,
> 
> 前面那7点很多看得不是很懂，或许是您还没有熟悉VNote的一些功能？可以看一下这个展示录屏（其中就展示了第7点直接粘贴HTML）：https://www.bilibili.com/video/av77455284
> 
> 关于笔记管理的很多建议，后面会逐一考虑。
> 
> 谢谢！

原来如此, 是我没搞懂怎么用. 重新学习了一下, 还有这样几个问题:

#### 关于插入script和iframe的问题
前面几点, 是指能渲染在vnote中插入的<iframe>和<script>

比如
`<script src="https://gist.github.com/tyskink/236d2309800ee57f5eee44e724753e83.js"></script>`
<script src="https://gist.github.com/tyskink/236d2309800ee57f5eee44e724753e83.js"></script>
`<iframe src="//player.bilibili.com/player.html?aid=9940487&cid=16433563&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>`
<iframe src="//player.bilibili.com/player.html?aid=9940487&cid=16433563&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>
`<iframe height='265' scrolling='no' title='Fancy Animated SVG Menu' src='http://codepen.io/jeangontijo/embed/OxVywj/?height=265&theme-id=0&default-tab=css,result&embed-version=2' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>`
<iframe height='265' scrolling='no' title='Fancy Animated SVG Menu' src='http://codepen.io/jeangontijo/embed/OxVywj/?height=265&theme-id=0&default-tab=css,result&embed-version=2' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>

typora里都可以正常渲染, vnote用的四个渲染器都不行,markdown-it 和markede这两个, 如果遇到这种不能成功渲染的标签的话, 这之后的内容就不会被渲染了, 最终效果是文章只能看到一半. 另外两个会卡很久, 然后在原地显示源代码, 
能否渲染这个问题,大概除非换渲染器大概没法解决? 但能不能搞成这样: 遇到不能渲染的模块, 直接显示源代码. 

#### 使用 img html标签插入的图片貌似不能实时预览

#### mermaid 如果使用 A-->B-->C这种连续箭头, 则无法被显示 

#### 最后就是标签要双击才能显示笔记的问题. windows用习惯了, 喜欢单击显示, 双击打开
