### ISSUE TITLE
pannel面板建议

### ISSUE THREAD

**Issue by duansheli** [vnotex/vnote#1125]
截图的 plsql developer 界面 
铆钉设计  

当取消铆钉时， 需要点击【链接】 才会显示【链接】 面板
![image](https://user-images.githubusercontent.com/8579595/71415971-65eb6980-2699-11ea-8a0a-ae8a026348f4.png)

当铆钉固定时， 则【链接】【文件】【窗口列表】都能显示
![image](https://user-images.githubusercontent.com/8579595/71416011-97643500-2699-11ea-8657-5c2ccd1486f5.png)

即有几个铆钉固定的就默认显示几个， 没有则都不显示 
当点击不显示的标题 ，则显示出来，但失去鼠标聚焦则隐藏

**Comment by tamlok** [comment]
右侧工具栏和搜索栏就是这样的浮动窗口，左侧笔记本不是，后面都会变成这种浮动窗口

**Comment by tamlok** [comment]
现在全部都是浮动窗口部件了，但qt不支持自动隐藏和显示。
