### ISSUE TITLE
找不到实时预览在哪里

### ISSUE THREAD

**Issue by primejava** [vnotex/vnote#1127]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by primejava** [comment]
这应该是一款写作工具而不是debug工具,没有实时预览,感觉很鸡肋

**Comment by tamlok** [comment]
您指的是双边实时预览？markdown设计的初衷就是足够简单，双边预览占用大量桌面空间，本来就不是一个好的解决方案（是软件一个偷懒取巧的方案）。vnote使用的是原地预览。具体请参考首页设计初衷。很多人熟悉后并不觉得鸡肋。

**Comment by Fxiao1** [comment]
> 这应该是一款写作工具而不是debug工具,没有实时预览,感觉很鸡肋

或许你可以试试`ctrl+t`

**Comment by tamlok** [comment]
已支持双边预览： https://github.com/vnotex/vnote/releases/tag/v3.10.0
