### ISSUE TITLE
建议增加“导入文件”和“导入文件夹”功能

### ISSUE THREAD

**Issue by huilin-hub** [vnotex/vnote#1128]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现): 复制文件/文件夹到Vnote目录，但无法识别。

How to Repro (如何复现): 随时可复现。

建议：

VNote的markdown + 笔记管理的特色，让我觉得眼前一亮，难得的好软件。而其中一个特点，就是md文件独立存放，方便用户使用第三方手段迁移，比如我用坚果云来同步。文件始终在自己手里，安全放心；而且md文件用其他软件可以轻松编辑和浏览。相对于强大的onenote来说，我更喜欢VNote的这个特点。但是，与此特点配套的“导入文件”和“导入文件夹”的功能，居然没有？不知道是否是我自己没找对方法，我已经存在的md文件，我找不到方法让它加入VNote中。我现在唯一想到的方法，是把所有文件重新复制粘贴，在VNote中新建一遍？

这个让我有些惊讶，我个人粗浅的认为，这个功能是最基础的“人权”功能。只见过有软件对用户是“只许进不许出”的（有导入无导出），从来没见过有软件对用户是“只许出不许进”的（有导出但没有导入）。我在网上查了，有网友为了这个功能，自己写了Python脚本来实现导入已有的md文件和文件夹。既然用户有如此硬性需求，甚至不惜自己写脚本来实现，也没有选择离开VNote，那么官方为何不考虑直接在VNote中实现呢？目前已经2.8版本的，我觉得这个功能在1.0版本时还未出现，就已经是产品同学的失误，而且是不可理解的失误，无论是出于什么其他困难考虑。

我看到有用户之前的issue中提到“自动识别新的文件”，这个我倒觉得没必要，也不安全，会扰乱笔记管理。而增加“导入文件”和“导入文件夹”的手动功能，由用户按需使用，是非常必要的，也便于用户从其他笔记软件迁移过来。比如我现在使用atom，无法迁移VNote，就是因为这个原因。

以上建议请参考，爱之深责之切，话有点多，望海涵。对于最基础的“人权”功能，希望作者可以高度重视

谢谢

**Comment by Fxiao1** [comment]
软件中的“导出”功能并不是用来备份，而是用来分享的（虽然我刚开始也这样以为）。如果想备份形式的导出的话，可以直接在文件目录将整个文件夹复制出来。关于这种形式导出的文件夹如果想导入应该怎么做呢？步骤如下（如果非程序员的话，可能稍微有点晦涩）：
1. 将文件夹直接复制到目标位置，比如复制到`我的笔记本/生活/`这个目录
2. 在当前位置下应该有个描述文件`_vnote.json`
3. 备份该文件，假如待会改坏了还有后悔药。
3. 编辑该文件，“sub_directories”对应的数组里面增加一个对象：键为“name”，值为文件名。
```json
"sub_directories": [
        {
            "name": "流"
        },
	{
           "name":"放进来的文件夹名"
	}
    ],
```
5. 在软件中对应的根目录上选择“从磁盘中重新加载”

**Comment by Wheeling** [comment]
@Fxiao1 谢谢大佬。之前我也有尝试修改过 `_vnote.json`，但这个搞定了目录，却搞不定目录下的文件，按您的例子来说，就是在`"放进来的文件夹名"`下面，还需要再有一个 `_vnote.json`，里面是该目录下所有文件的信息，包括创建时间、修改时间、附件地址、附件名称等等。 而如果还有更深层的子目录，逻辑会再复杂一些。所以才有网友自己写了Python脚本，来实现这个导入功能。对普通用户来说，应该不太会这样做。无法从其他笔记软件中，导入自己多年的心血笔记，这是阻碍软件发展的大障碍。我觉得大部分人，不太可能从0开始。 最多也就是使用VNote整理下零碎的知识点。当成自己笔记的第二软件或第三软件来使用。


关于“导出”功能，我的是2.8.2版本，我尝试了一下，确实如您所说，不是用来备份的。导出的东西，并非按照笔记的组织结构来导出，每个md文件上层，多了个目录。这个有点奇怪，多层目录也意味着确实无法当成备份。 备份的最好方式，确实是整个目录直接手工复制出来。

不知道是不是我们的姿势不对，只能等作者解答或优化了。

谢谢

**Comment by Fxiao1** [comment]
我以为你说的是符合vnote结构的目录。如果目录都不一样的话，确实难搞了。这个作者恐怕呀难以解决吧，毕竟不是从vnote出来的文件，结构是不可控的。你可能觉得自己以前的markdown笔记结构很规范，但是没法保证所有人的笔记都是这个结构，作者可能没发写一个统一的导入功能。
以上是个人的一点拙见。

**Comment by pdlife** [comment]
文件菜单第二个选项，“从文件新建笔记”应该就是你说的导入md文件的功能。我目前就是重新建个文件夹，然后用这个导入MD文档。

**Comment by tamlok** [comment]
Hi,

新建笔记本的时候，可以选择一个现有的非空文件夹，VNote会尝试递归遍历并建立一个笔记本。

文件菜单里面，`从外部文件新建笔记`可以导入多个文件到当前文件夹。

如果已经是一个比较成熟的文件夹体系，可以使用左上角第三个标签的`浏览器`功能来浏览编辑外部文件，不一定要导入到VNote的笔记本中。

后面会改进。

**Comment by tamlok** [comment]
VNote 3已经添加了该功能，并对外部文件能自动识别。
