### ISSUE TITLE
一个代码块渲染问题

### ISSUE THREAD

**Issue by Tsangtim** [vnotex/vnote#1142]
OS                   : Debian testing
VNote Version  : 2.2,  d78e892d5cc  etc..
Symptoms (表现):

在编号的下方使用代码块时, 在 ``` 之前增加3个空格会有缩进的效果, 这个功能和Typora一样但Vnote 更稳定, 我很喜欢用, 今天导入一段BASH脚本时突然发现这个问题.

![Vnote issue](https://user-images.githubusercontent.com/49815779/71731227-21bd4d80-2e7f-11ea-94e5-d70a1b1ccada.png)

**Comment by tamlok** [comment]
Hi,

这种语法问题，最好能把原文本贴出来，我这边好复现和调试。

根据图片初步推测，是因为`#!bin/bash`之后的行没有统一缩进，即列表下面嵌套一个代码块的内容应该统一缩进。

可以参考文章：https://www.jianshu.com/p/7c4637c72900

markdown-it demo: https://markdown-it.github.io/

**Comment by Tsangtim** [comment]
Hi, 的确是这个原因 "因为#!bin/bash之后的行没有统一缩进"

**Comment by Tsangtim** [comment]
Hi,

的确是这个原因, 即 "#!/bin/bash之后的行没有统一缩进", 导致 "#!/bin/bash/ 之后的代码没有被正确解析成代码块. 因为 Typora 是所见即所得方式的渲染所以不存在这个问题. 但是 Typora 这种所见即所得的即时渲染方式, 在遇到大文件的时候非常非常慢, 哪怕机器是 AMD R7 2700 + 32GB 内存

因为这个原因所以最近转换到 Vnote 了, 链接的文章我仔细看看再回复你, 谢谢你的回复
