### ISSUE TITLE
MacOS下某些情况下程序无法启动

### ISSUE THREAD

**Issue by zeroleo12345** [vnotex/vnote#1143]
OS Version (操作系统): macOS 10.13.6

VNote Version (Help - About VNote - Version: )(VNote版本): v2.8.2

Symptoms (表现):
程序启动后， 马上闪退， Dock栏程序图标闪现。
错误日志显示如下:
fail to create shared memory segment
fail to attach to the shared memory segment "QSharedMemoryPrivate::initKey: unable to set key on lock"
加了一些log, 错误码=7, UnknowError.

How to Repro (如何复现):
一旦出现, 需重启电脑才能恢复正常。正常后， 比较难找到复现路径。

**Comment by zeroleo12345** [comment]
找到相同issue  #1103

**Comment by tamlok** [comment]
添加了一个启动参数`-m`，可以跳过共享内存的检查。不过VNote多开有可能会造成冲突和数据不一致，请自行确认只操作一个VNote实例。

**Comment by tamlok** [comment]
已经修复
