### ISSUE TITLE
阅读模式大纲消失

### ISSUE THREAD

**Issue by xiesp** [vnotex/vnote#1147]
OS Version (操作系统): Win10 64 bit

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):
编辑模式下可以看见大纲,但是在阅读模式下不可见

How to Repro (如何复现):
特定md文件,目前只发现1个

![Snipaste_2020-01-06_15-34-27](https://user-images.githubusercontent.com/13922181/71802850-0da16800-309a-11ea-92b7-a3814d12f2e3.png)

**Comment by tamlok** [comment]
应该是md文件里面包含特殊字符或语法错误。可以把文件发我邮箱或自行二分调试一下。

**Comment by xiesp** [comment]
感谢,我已经找到原因了,但是这是否是一个bug呢,是这样解决的
![Snipaste_2020-01-06_19-12-00](https://user-images.githubusercontent.com/13922181/71814777-713a8e00-30b8-11ea-945b-f40214cb92f0.png)

**Comment by tamlok** [comment]
Hi,

如果想在列表中嵌套代码块，代码块需要整个缩进4个空格。具体语法可以参考：

https://www.jianshu.com/p/7c4637c72900

**Comment by xiesp** [comment]
OK,这是因为刚从Typora迁移过来,Typora检查没那么严格,我的意思是,代码块里面的元素,应该不要影响到整个大纲,您觉得呢

**Comment by tamlok** [comment]
后面我看看。您可以去markdown-it demo官网看看能否正常渲染。

**Comment by xiesp** [comment]
好的,感谢
