### ISSUE TITLE
vnote输入框问题

### ISSUE THREAD

**Issue by Jontyshaw** [vnotex/vnote#1149]
OS Version (操作系统): Manjaro 18.1.5

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):最近vnote在一些街面上输入，鼠标指针会从一个竖线编程四个箭头形状
![图片](https://user-images.githubusercontent.com/34794522/71829954-a529a980-30e0-11ea-8a26-2737877aa74d.png)

How to Repro (如何复现):具体表现目前发现是中文目录会出现此问题，英文目录下正常

**Comment by tamlok** [comment]
Hi,

是从`vnote-bin` AUR 安装的吗？或者是AppImage？如果不是，请从上面两个途径安装再测试一下。代码里面是没有控制光标形状的，所以正常都是一个竖线。

**Comment by Jontyshaw** [comment]
是从archLinuxcn安装的vnote-git



---原始邮件---
发件人: "Le Tan"<notifications@github.com&gt;
发送时间: 2020年1月7日(周二) 上午7:26
收件人: "tamlok/vnote"<vnote@noreply.github.com&gt;;
抄送: "Jonty Shaw"<jontyshaw@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tamlok/vnote] vnote输入框问题 (#1149)



Hi,
 
是从vnote-bin AUR 安装的吗？或者是AppImage？如果不是，请从上面两个途径安装再测试一下。代码里面是没有控制光标形状的，所以正常都是一个竖线。

**Comment by tamlok** [comment]
`vnote-git`是用Qt 5.13编译的，重新安装`vnote-bin`吧。
