### ISSUE TITLE
Remove word-break 'a' style from default styles (links get chopped up)

### ISSUE THREAD

**Issue by louwers** [vnotex/vnote#1151]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2.

Symptoms (表现):

Links are cut off in the middle of words.

![image](https://user-images.githubusercontent.com/649392/71857370-98f51a80-30e7-11ea-8293-3dea8b866926.png)

How to Repro (如何复现):

Copy & paste the text below. Resize window vertically to see how the cut-off points differs for the link.

```md
# Test

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce accumsan accumsan purus, eget iaculis nisl vulputate non. Integer at ultrices quam. Nulla fringilla erat vel ex gravida, ac fermentum leo condimentum. Aliquam eget sodales dolor, ac lobortis mi. Aenean gravida nisi at urna laoreet suscipit. Duis consectetur diam et dui fermentum vulputate. Suspendisse potenti. Donec in lorem sollicitudin, congue sem quis, viverra risus. In aliquam est dui. Duis ornare aliquet finibus. 

[Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce accumsan accumsan purus, eget iaculis nisl vulputate non. Integer at ultrices quam. Nulla fringilla erat vel ex gravida, ac fermentum leo condimentum. Aliquam eget sodales dolor, ac lobortis mi. Aenean gravida nisi at urna laoreet suscipit. Duis consectetur diam et dui fermentum vulputate. Suspendisse potenti. Donec in lorem sollicitudin, congue sem quis, viverra risus. In aliquam est dui. Duis ornare aliquet finibus.](http://google.com)
```

**Comment by tamlok** [comment]
Hi,

Check this out: https://github.com/tamlok/vnote/issues/1051

**Comment by louwers** [comment]
That would make sense!
But I don't think you should change it to `break-word`, you should just remove it or change it to `normal` (the default). Otherwise words aren't cut off at dashes like they are supposed to. :)

**Comment by tamlok** [comment]
@louwers If we remove the `word-break`, then a very long long link without any word separator will extend the whole page's width. See the long scrollbar caused by the first link.

![image](https://user-images.githubusercontent.com/5763157/127500905-1a931d7e-f15b-4b0e-894b-24df37c8a526.png)

Sorry for the late reply.
