### ISSUE TITLE
阅读模式空白

### ISSUE THREAD

**Issue by xiesp** [vnotex/vnote#1153]
OS Version (操作系统): Win10 64

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):
笔记本阅读模式空白,涉及大量数学公式

How to Repro (如何复现):
请看下面附件
[sample.txt](https://github.com/tamlok/vnote/files/4029252/sample.txt)

**Comment by libra146** [comment]
![image](https://user-images.githubusercontent.com/17448639/71941664-8e28ab80-31f5-11ea-96c0-c6b6f51ebed2.png)
![image](https://user-images.githubusercontent.com/17448639/71941697-ab5d7a00-31f5-11ea-958b-ee6db03a3277.png)
![image](https://user-images.githubusercontent.com/17448639/71941802-01cab880-31f6-11ea-95b1-13aa5089b624.png)
![image](https://user-images.githubusercontent.com/17448639/71941864-3dfe1900-31f6-11ea-9e8e-02f9d81f1aba.png)
如图所示，公式开头不能有空格，所以导致有些公式不能渲染。至于为什么阅读模式空白，我不清楚，只能协助测试

**Comment by xiesp** [comment]
好的,非常感谢,感觉VNote的校验严格很多,从Typora迁移难度很大...

**Comment by tamlok** [comment]
看看是不是opengl的问题，看置顶issue
