### ISSUE TITLE
拷贝一个 Markdown 到目录中，怎么才能刷新出来？

### ISSUE THREAD

**Issue by tedeum** [vnotex/vnote#1154]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

我拷贝了一个已有的 Markdown，在笔记中没有显示出来。
How to Repro (如何复现):

**Comment by tamlok** [comment]
文件菜单，从外部文件新建笔记，可以将多个文件导入到当前文件夹内。

或者手动修改文件夹下面的_vnote.json文件。

**Comment by tamlok** [comment]
已经支持显示外部文件，右键重新加载即可
