### ISSUE TITLE
输入%help%时，幻词提示一闪即逝

### ISSUE THREAD

**Issue by Ideaye** [vnotex/vnote#1158]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):新建笔记时,在笔记名输入框中输入%help%时,内置幻词的提示一闪即逝,起不到提示作用。而在VNote中也没有其他内置幻词的提示入口

How to Repro (如何复现):在新建笔记名输入框中输入%help%

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/72025493-4700f000-32b3-11ea-8b4c-ac6bc62d4d32.png)

我这里测试还好，后面会考虑在编辑器中也支持%help%。

**Comment by Ideaye** [comment]
又试了一下,动图如下
![1](https://user-images.githubusercontent.com/42933710/72025746-12416880-32b4-11ea-8079-3057f58cbb6c.gif)

**Comment by tamlok** [comment]
直接输入`%help%`呢？不要提前输入`%%`试试。

**Comment by Ideaye** [comment]
结果是一样的,反复试过多次了.

**Comment by tamlok** [comment]
已经没有幻词了，统一使用片段
