### ISSUE TITLE
建议将一些常用功能添加到工具栏

### ISSUE THREAD

**Issue by Ideaye** [vnotex/vnote#1159]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Suggestion:建议将当前放置在片段中的一些功能,如文本黄色高亮,字体标红,插入特定代码块等常用功能添加到工具栏中并配置相应快捷键,有道云那个工具栏就挺不错,希望VNote越来越好用
![](https://gitee.com/ideaye/VNotePic/raw/master/1578499907_20200109001127745_11070.png)

**Comment by tamlok** [comment]
片段支持自定义快捷键，具体参考官方文档。

**Comment by Ideaye** [comment]
这个我设置了,但是感觉快捷键有点复杂,还是希望作者内置这些常用功能到工具栏

**Comment by tamlok** [comment]
OK

**Comment by Ideaye** [comment]
![image](https://user-images.githubusercontent.com/42933710/72025858-6c422e00-32b4-11ea-8854-98e3c937718e.png)
