### ISSUE TITLE
如何放大左侧文件夹以及下面的md文件字体，以及右侧的标签栏字体

### ISSUE THREAD

**Issue by HiRa1nbow** [vnotex/vnote#1174]
OS Version (操作系统): Linux(manjaro)

VNote Version (Help - About VNote - Version: )(VNote版本): lastest

Symptoms (表现):
显示器较小，显示比较模糊，样式文件试了很多都没用
![DeepinScreenshot_select-area_20200118133015](https://user-images.githubusercontent.com/56363329/72659729-db2b2f80-39f6-11ea-8907-b5a22a293b2c.png)
![DeepinScreenshot_select-area_20200118133053](https://user-images.githubusercontent.com/56363329/72659730-db2b2f80-39f6-11ea-99c8-3d178633c3ef.png)

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/1214
