### ISSUE TITLE
Mermaid text have extra space below

### ISSUE THREAD

**Issue by sapphire008** [vnotex/vnote#1181]
Mermaid version 8.4.3 (current version of Vnote) 

Extra space / padding below text

Simple example

```mermaid
graph LR
    ABC --> DEF
```

Renders (by Atom's markdown-preview-enhanced with 8.4.4, and VNote with 8.4.3) as 

![image](https://user-images.githubusercontent.com/3713023/73282274-504cf080-41bf-11ea-8751-5c424042c897.png)

OS: Windows 10

**Comment by tamlok** [comment]
It is weird.

Something similar: https://stackoverflow.com/questions/60789251/how-to-adjust-padding-inside-mermaid-node
