### ISSUE TITLE
粗体斜体删除线在某些情况下无法正常显示

### ISSUE THREAD

**Issue by Acxpd** [vnotex/vnote#1182]
OS Version: Windows 10 专业版 版本1909（OS 内部版本 18363.592）

VNote Version: 2.8.2

Symptoms (表现):
若将一段以句号结尾的文字加粗且被加粗的文字后面还有其他内容，加粗格式在阅读模式下将无法正常显示。

编辑模式下：
![image](https://user-images.githubusercontent.com/57132408/73588453-37687600-4504-11ea-9224-48766c0b8bc3.png)

阅读模式下：
![image](https://user-images.githubusercontent.com/57132408/73588459-4a7b4600-4504-11ea-8c44-d3e88d133208.png)

How to Repro (如何复现):

**Comment by Acxpd** [comment]
斜体和下划线格式也测试过，同样有上述问题。

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/996
