### ISSUE TITLE
笔记文件夹复制到另一台电脑，打开后tag丢失

### ISSUE THREAD

**Issue by ijoblee** [vnotex/vnote#1184]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):笔记文件夹复制到另一台电脑后，用vnote打开，原来的tag全部丢失。

How to Repro (如何复现):如上

**Comment by tamlok** [comment]
请问是怎么打开呢？您需要在vnote里面新建笔记本，然后笔记本根文件夹选择你复制过来的那个笔记本对应的文件夹，VNote会提示正在导入一个此前创建的笔记本，这样才能完整导入笔记本到VNote中，才有标签数据。

**Comment by ijoblee** [comment]
谢谢作者的耐心指导，上次出错是因为导入的时候选成了上级目录。
