### ISSUE TITLE
笔记文件夹复制到其他电脑上，用vnote打开后，所有tags丢失

### ISSUE THREAD

**Issue by ijoblee** [vnotex/vnote#1186]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):笔记文件夹复制到其他电脑上，用vnote打开后，所有tags丢失

How to Repro (如何复现):笔记文件夹复制到其他电脑上，用vnote打开后，所有tags丢失

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/1184
