### ISSUE TITLE
需求：像真正vim一样支持“.”重复上一次操作 

### ISSUE THREAD

**Issue by relunctance** [vnotex/vnote#1188]
OS Version (操作系统): Windows, Linux, macOS

macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
不支持 `.` 重复上次操作

How to Repro (如何复现):

像真正vim一样支持`.`重复上一次操作

**Comment by lecher23** [comment]
+1

**Comment by tamlok** [comment]
已经支持
