### ISSUE TITLE
阅读模式下渲染异常

### ISSUE THREAD

**Issue by rihalvnium76** [vnotex/vnote#1189]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2
OS: Win10 x64
Symptoms (表现):
```
aaa**测试()**aaa
```
以上markdown代码在编辑状态下正常显示，但在阅读模式下显示异常，表现为下面的效果
aaa\*\*测试()\*\*aaa
而不是
![image](https://user-images.githubusercontent.com/57667144/73753680-00ad8c80-479e-11ea-86ea-5acdf332c608.png)

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/996
