### ISSUE TITLE
多级标题的主题样式更明显区分（颜色、字体）

### ISSUE THREAD

**Issue by blinderjay** [vnotex/vnote#1190]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

请问是否可以更改多级标题的字体和颜色，我想更明显区分，因为很多时候不会预先明确大纲结构，不会使用1 1.1 这样的标识符

**Comment by tamlok** [comment]
Hi,

VNote可以自动为标题进行编号，所以无需提前写标号，可以在设置中开启该功能。

自定义样式请参考官网文档，修改MDHL和CSS文件即可。
