### ISSUE TITLE
代码块阅读模式下样式被强制改变无法保持原有样式

### ISSUE THREAD

**Issue by laiqinghua** [vnotex/vnote#1191]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
> 使用代码块将shell制表符输出的结果实时复制粘贴进来时，样式工整与原来的shell制表符输出的样式一致，但是切换阅读模式制表符无法正常的被阅读导致 表格样式对齐不工整。
- 复现方式：
    -  例如使用有正常制表符格式输出的shell内容，复制下来。
    -  然后粘贴到代码块中，就会出现无法正确的使用制表符的情况。
    -  其他的markdown编辑工具也有类似的问题，希望能够解决这个问题，VNote成为markdown编辑器中不可替代的一员。
    -  希望VNote越来越好！
    -  很显然github也有这个问题，就像下面一样。

How to Repro (如何复现):
```shell
|---------------------------------------------------------------------------|
| list            | List available plugins.                                 |
|---------------------------------------------------------------------------|
| back            | Go to the previous menu.                                |
| exit            | Exit w3af.                                              |
|---------------------------------------------------------------------------|
| mangle          | View, configure and enable mangle plugins               |
| evasion         | View, configure and enable evasion plugins              |
| audit           | View, configure and enable audit plugins                |
| auth            | View, configure and enable auth plugins                 |
| grep            | View, configure and enable grep plugins                 |
| bruteforce      | View, configure and enable bruteforce plugins           |
| output          | View, configure and enable output plugins               |
| infrastructure  | View, configure and enable infrastructure plugins       |
| crawl           | View, configure and enable crawl plugins                |
|---------------------------------------------------------------------------|
```

```

**Comment by laiqinghua** [comment]
编辑模式下显示是正常的，制表符格式工整，但是切换到阅读模式就无法准确的显示制表符的内容了。

**Comment by tamlok** [comment]
Hi,

暂时不知道问题是什么。把内容复制到一个代码块中，一切都正常：

![image](https://user-images.githubusercontent.com/5763157/73838767-67d74980-484f-11ea-980e-12a0bcfe24e0.png)

阅读模式：

![image](https://user-images.githubusercontent.com/5763157/73838778-70c81b00-484f-11ea-80ec-58379478f3e3.png)

**Comment by laiqinghua** [comment]
即使放到一个代码块中也无法正常显示的呢。
![image](https://user-images.githubusercontent.com/39586055/73841900-81c85a80-4856-11ea-9c0a-859b811dba02.png)

**Comment by laiqinghua** [comment]
即使放到一个代码块也无法正常显示的呢
编辑模式：
![image](https://user-images.githubusercontent.com/39586055/73841999-b5a38000-4856-11ea-9062-3108511bedfc.png)
阅读模式：
![image](https://user-images.githubusercontent.com/39586055/73842033-ca801380-4856-11ea-9844-7a050893459c.png)

**Comment by laiqinghua** [comment]
@tamlok zhenxiao教授辛苦了。我看到你的信息公开太多了，你这样很容易被窃取信息哦，要注意保密呢。

**Comment by tamlok** [comment]
你把你的笔记md文件直接贴上来我这边看看~~我不是肖教授呀😂哪里看到的个人信息呢？

**Comment by laiqinghua** [comment]
@tamlok 我已经发送到您的tam***veer邮箱中了，请注意查收，可能是我认错了。

**Comment by tamlok** [comment]
应该是系统字体问题，没有使用等宽字体。
