### ISSUE TITLE
Sorting folders

### ISSUE THREAD

**Issue by DutchPete** [vnotex/vnote#1194]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现): Sorting folders does not work.

How to Repro (如何复现): select a folder, right-click on it, select "Sort", then click on 1 of the buttons (Up, Down, Top, Bottom), but nothing happens.

**Comment by tamlok** [comment]
Should be fixed.
