### ISSUE TITLE
VB6 代码注释部分着色错误

### ISSUE THREAD

**Issue by jason-cpc** [vnotex/vnote#1195]
OS Version (操作系统): Microsoft Windows 10 x64 10.0.18363.592

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现): 如下，VB6 代码注释部分着色错误。

\```vb
Dim fileNum As Integer
Dim binBytes() As Byte

fileNum = FreeFile()
Open "C:\A.exe" For Binary As #fileNum
ReDim binBytes(LOF(fileNum) - 1)  ' 这行注释着色正常
Get #fileNum, , binBytes()  ' 这行注释着色有误
Close #fileNum

Open "C:\B.exe" For Binary As #fileNum
Put #fileNum, , binBytes()  ' 这行注释着色有误
Close #fileNum
\```

How to Repro (如何复现): 
如果把 \```vb 改为 \```vbs，则以上 3 行注释着色均正常。

**Comment by tamlok** [comment]
Hi,

VNote是使用[highlight.js](https://highlightjs.org/)这个JS库来进行语法着色的，如果有任何问题，可能需要去官网提Issue，等待上游解决。

谢谢！

**Comment by jason-cpc** [comment]
感谢您的回复。我去反馈下问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Le Tan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 中午11:18
收件人:&nbsp;"tamlok/vnote"<vnote@noreply.github.com&gt;;
抄送:&nbsp;"Ahn"<ahn.chen@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tamlok/vnote] VB6 代码注释部分着色错误 (#1195)




Hi,
 
VNote是使用highlight.js这个JS库来进行语法着色的，如果有任何问题，可能需要去官网提Issue，等待上游解决。
 
谢谢！
