### ISSUE TITLE
重启之后,子目录选中保持

### ISSUE THREAD

**Issue by dry11orange** [vnotex/vnote#1205]
OS Version (操作系统): Windows, Linux, macOS
- Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
- 2.72

Symptoms (表现):

- vnote关闭前
![](https://s2.ax1x.com/2020/02/14/1jCp0x.png)
- vnote重新打开后
![](https://s2.ax1x.com/2020/02/14/1jCSn1.png)

How to Repro (如何复现):
- 期望打开前后一致

**Comment by tamlok** [comment]
已经支持
