### ISSUE TITLE
表格里面如果有“|”怎么输入？

### ISSUE THREAD

**Issue by yhcad** [vnotex/vnote#1208]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by yhcad** [comment]
找到输入方法了，用反斜杠
Markdown 可以利用反斜杠来插入一些在语法中有其它意义的符号，例如：如果你想要用星号加在文字旁边的方式来做出强调效果（但不用 <em> 标签），你可以在星号的前面加上反斜杠：\|

**Comment by tamlok** [comment]
Hi,

Markdown里面表格如果有`|`，需要转义，即输入`\|`即可。
