### ISSUE TITLE
Vnote能否支持自定义按键设置功能？

### ISSUE THREAD

**Issue by xzlabs** [vnotex/vnote#1211]
OS Version (操作系统): Windows

VNote Version 2.8.2

Symptoms (表现):

Vnote是否有自定义按键设置功能？我想实现在编辑器中按下Enter按键的时候，自动换行并新增一个空行（相当于按2次Enter键），或者其它一些按键重映射功能。

我看设置中有键盘映射设置，但没有Enter按键，另外设置了好像也没有效果

**Comment by tamlok** [comment]
Hi,

暂时不支持！关于换行，你可以试试`Shift+Enter`，会在行末插入两个空格然后换行。
