### ISSUE TITLE
VNote全屏后很多按钮点了没反应，然后底部栏强制消失，只能按Win键才能退出这个软件。。。

### ISSUE THREAD

**Issue by theBookofRabbit** [vnotex/vnote#1215]
Win10系统，应该是最新版的VNote，
VNote全屏后，很多按钮点了没反应，然后底部栏强制消失，只能按Win键才能退出这个软件。。。
编辑过程中点全屏，就会出现这种bug，很是无奈。

**Comment by tamlok** [comment]
看github置顶issue，opengl的问题，很好解决。
