### ISSUE TITLE
Vnote能够将md导出为doc或docx文档吗？

### ISSUE THREAD

**Issue by yhcad** [vnotex/vnote#1223]
Vnote能够将md导出为doc或docx文档吗？

**Comment by tamlok** [comment]
Hi,

VNote可以调用任意工具进行导出，包括Pandoc，而或者是可以转换为DOCX的。具体请参考[官方文档](https://tamlok.gitee.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%AF%BC%E5%87%BA.md#toc_10) 。

谢谢！
