### ISSUE TITLE
文件夹监听功能能实现文件的自动导入

### ISSUE THREAD

**Issue by youmoxiaozi** [vnotex/vnote#1224]
现在如果一个文件夹里有很多文件，
打开vnote是不能自动添加到vnote里的资源管理器的

**Comment by tamlok** [comment]
如果是绕开vnote管理文件的，请使用“浏览器”功能浏览外部文件。如果想要导入多个文件到笔记本，请使用文件菜单的从外部文件新建笔记功能。

后面会改进。

**Comment by zzczx** [comment]
浏览器功能在哪里？ 从菜单里找不到。

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/75940653-a270e800-5ec8-11ea-9525-bb878ec77bf6.png)

左上角

**Comment by tamlok** [comment]
vnote3目前支持显示外部文件并可以方便导入
