### ISSUE TITLE
阅读模式进入编辑模式的快捷键是什么？

### ISSUE THREAD

**Issue by geekmai** [vnotex/vnote#1226]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
如题，我打开了一篇笔记，处在阅读模式，如何快速进入编辑模式呢？快捷键是什么？

How to Repro (如何复现):

**Comment by tamlok** [comment]
`Ctrl+T`，具体请看帮助菜单的快捷键说明。
