### ISSUE TITLE
中间的 编辑渲染模块 能否 单独供第三方调用(其他qt程序)

### ISSUE THREAD

**Issue by 625781186** [vnotex/vnote#1227]
如题.

**Comment by tamlok** [comment]
Hi,

VNote采用的是MIT协议，所以里面的各个部件都可以在MIT协议的前提下使用。

**Comment by 625781186** [comment]
> Hi,
> 
> VNote采用的是MIT协议，所以里面的各个部件都可以在MIT协议的前提下使用。

啊，我的描述有点歧义。
我想表达的是能否开一个单独的项目把中间的模块隔离出来。

**Comment by tamlok** [comment]
Hi,

目前暂时先不动了，后面VNoteX的编辑器模块是独立项目，可以留意一下。

**Comment by 625781186** [comment]
> Hi,
> 
> 目前暂时先不动了，后面VNoteX的编辑器模块是独立项目，可以留意一下。

VNoteX仓库开了吗 , 我没搜索到.

**Comment by tamlok** [comment]
还没开源。

**Comment by tamlok** [comment]
https://github.com/vnotex/vtextedit

LGPL-v3
