### ISSUE TITLE
问下有可能在vnote里实现简单的思维导图功能吗?

### ISSUE THREAD

**Issue by jimorsm** [vnotex/vnote#1229]
vnote很好用, markdown 整理文档,笔记很完美. 但在整理思绪, 罗列知识点时, 思维导图更有优势. 现在总是在xmind 和 vnote之前切换, 要是可以在一个软件里实现就完美了.

**Comment by tamlok** [comment]
有可能的，后面会支持，请耐心等待~

**Comment by zhenghaixiang** [comment]
vnote 集成的 plantuml 现在能画思维导图了。

https://plantuml.com/zh/mindmap-diagram

**Comment by Fxiao1** [comment]
> vnote 集成的 plantuml 现在能画思维导图了。
> 
> https://plantuml.com/zh/mindmap-diagram

请问应该怎么使用呢？我已经再vnote里面添加 plantuml 的 jar 文件，并测试成功了

我在文档里面写的语法如下，但在预览的时候并没有出现预想的思维导图，是不是还有启动开关呢？2.8的vnote和现在最新版本的vnoteX都试了不行

```
@startmindmap
* root node
	* some first level node
		* second level node
		* another second level node
	* another first level node
@endmindmap
```

**Comment by Fxiao1** [comment]
> 有可能的，后面会支持，请耐心等待~

大佬，现在还有计划吗？

**Comment by tamlok** [comment]
PlantUML画思维导图可能需要在线服务才行。

![image](https://user-images.githubusercontent.com/5763157/157594109-847fab88-ee71-4740-b73b-5532cc0e8aec.png)

还有计划的。

**Comment by Fxiao1** [comment]
> PlantUML画思维导图可能需要在线服务才行。
> 
> ![image](https://user-images.githubusercontent.com/5763157/157594109-847fab88-ee71-4740-b73b-5532cc0e8aec.png)
> 
> 还有计划的。

感谢大佬点拨！

惊喜的发现，本地文件也是可以的（[plantuml-1.2022.2.zip](https://github.com/vnotex/vnote/files/8220558/plantuml-1.2022.2.zip)），原来是我的语法不对，我没有用代码块包起来，写的是

```
@startmindmap
* root node
	* some first level node
		* second level node
		* another second level node
	* another first level node
@endmindmap
```

实际上应该是

```markdown
```puml
@startmindmap
* root node
	* some first level node
		* second level node
		* another second level node
	* another first level node
@endmindmap
\`\`\`
```

具体使用办法是

1. 将上面的那个压缩包解压出来的jar文件放置在任意位置（建议在vnote根目录下创建一个名为“lib”的文件夹，将这个jar放置
在里面）
2. 在vnote里面引入上述jar文件，如下图
![Snipaste_2022-03-10_13-22-19](https://user-images.githubusercontent.com/40653617/157595439-c63fbd7f-680e-48c2-8c13-1f4156ffdd65.png)

3. 然后就可以写了
![Snipaste_2022-03-10_13-23-11](https://user-images.githubusercontent.com/40653617/157595177-06db1c8b-355a-4c3a-9061-da324171aca0.png)

**Comment by tamlok** [comment]
已支持思维导图：

![image](https://github.com/vnotex/vnote/assets/5763157/d01087c2-f995-4804-a5f7-94892fc2193b)
