### ISSUE TITLE
导出pdf格式时 边界部分显示不全

### ISSUE THREAD

**Issue by ylzcdyhm** [vnotex/vnote#1230]
OS Version (操作系统): Windows, Linux, macOS
Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.8.2
Symptoms (表现):

导出pdf格式时 边界部分显示不全
How to Repro (如何复现):
画的流程图很大

**Comment by tamlok** [comment]
hi，

- 是通过什么导出？
- 有没有截图说明一下情况？
- 有对应示例文件给出吗？

**Comment by ylzcdyhm** [comment]
导出HTML时，显示如下：
![image](https://user-images.githubusercontent.com/12742044/75938709-65562700-5ec3-11ea-96a2-08eefd81b306.png)
导出PDF时，显示如下：
![image](https://user-images.githubusercontent.com/12742044/75938916-e7dee680-5ec3-11ea-93bd-bcfcdf0d9822.png)

能否显示成 有左右上下的滚动条显示？

**Comment by tamlok** [comment]
是用哪个选项导出的？

**Comment by ylzcdyhm** [comment]
vnote里自带的导出

**Comment by ylzcdyhm** [comment]
文件->导出->目标格式  选择pdf 或者HTML

**Comment by ylzcdyhm** [comment]
html导出时 ，导出页面 设置如下
![image](https://user-images.githubusercontent.com/12742044/75940083-009ccb80-5ec7-11ea-80c7-5618c28a7594.png)
pdf导出时，导出页面 设置如下
![image](https://user-images.githubusercontent.com/12742044/75940144-25913e80-5ec7-11ea-967d-d6b542011532.png)

**Comment by tamlok** [comment]
Should be fixed in VNote 3.
