### ISSUE TITLE
导出的大钢的宽度有BUG，同时导出HTML时可否将大纲放在左边。

### ISSUE THREAD

**Issue by ssdngs** [vnotex/vnote#1232]
OS Version (操作系统): Windows, 

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8,2
Symptoms (表现):
1、导出的大钢的宽度有BUG
2、导出HTML时可否将大纲放在左边。 

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi，

宽度有Bug能否截图具体说明一下？

如果熟悉HTML和CSS可以通过修改`common.css`来加入自定义的样式，看能不能把大纲挪到左边。
