### ISSUE TITLE
上传图片提示不支持类型，建议取消图床的格式限制

### ISSUE THREAD

**Issue by luhua** [vnotex/vnote#1234]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现):
从网上复制过来的图没有后缀，无法上传gitee图床，提示不支持的类型，如下图，因为现在很多图片复制保存过来是没有后缀的，建议取消格式限制。
![image](https://user-images.githubusercontent.com/3127313/75749625-30c85b00-5d5d-11ea-9d00-45e8b5005687.png)

How to Repro (如何复现):
去掉图片的后缀（jpg,png...），文章中也去掉图片后缀，上传到图床。

**Comment by tamlok** [comment]
已经取消。
