### ISSUE TITLE
发现一个正则问题

### ISSUE THREAD

**Issue by feloxx** [vnotex/vnote#1235]
OS Version (操作系统): 

win7 sp1

VNote Version (Help - About VNote - Version: )(VNote版本): 

2.8.2

Symptoms (表现):

执行一个正则后,程序会持续占用高额cpu和内存,直到崩溃

How to Repro (如何复现):

打开任意笔记,或者新建任意笔记;  
点开搜索,勾选正则,输入正则`(.*)`,并点击查找下一个即可复现

**Comment by libra146** [comment]
已复现，感觉可能是内存泄露问题，CPU高，内存占用直线升高。

**Comment by feloxx** [comment]
3版本已经修复了，欢迎大家用最新版本
