### ISSUE TITLE
Ctrl+Q 为什么作为退出的快捷键，并且还不能改！

### ISSUE THREAD

**Issue by topsoft-support** [vnotex/vnote#1238]
OS Version (操作系统): Windows, Linux, macOS
Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.8.2
Symptoms (表现):
我经常使用Ctrl+Q作为一些操作非常频繁的快捷键，例如查看详情、预览、等等，vnote 作为退出的快捷键，经常就按到了，为啥不搞个ctr+f4呢 或者其他的，Crtl+q是一个操作非常方便的快捷键，退出不需要操作方便吧

How to Repro (如何复现):

**Comment by tamlok** [comment]
因为macos规定了~~

**Comment by tamlok** [comment]
VNote 3应该可以修改了。
