### ISSUE TITLE
试用一周后的感觉和建议（之前使用cherrytree和typroa）

### ISSUE THREAD

**Issue by topsoft-support** [vnotex/vnote#1246]
OS Version (操作系统): Windows, Linux, macOS
Windows10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.8.2
Symptoms (表现):
* 全屏功能有bug，有时候开启全屏就回不去了，我解决办法是删掉配置文件后重新进入。
* 建议将文件夹和笔记进行可收缩展开的树形层级形式整合在一起，就像cherrytree的树形一样，这样我感觉在展开状态能快速找到我的笔记，而不是一层一层去点文件夹，这个和windows文件夹一层一层往下找没区别了（对于笔记有点多的人，需求迫切）
* 大纲建议可拖动到左侧，不是最左侧，在笔记那个位置（根据word的使用习惯）
![image](https://user-images.githubusercontent.com/53323942/76695290-83d4d300-66b8-11ea-858a-f27724f0243b.png)
* 如果能像`typroa`那样进一步实现**所见即所得**就完美了，或者将typroa嵌入编辑区域，目前只能通过外部程序打开的方式，感觉有点麻烦。
* 在阅读模式下，建议记录当前窗口的位置在多少行，切换到编辑模式就滚动到该行，而不是`focus`首行
* 建议增加单文件笔记模式，像cherrytree使用sqlite作为数据库，脱离系统的资源管理器的目录和文件这种形式，这样备份更容易更方便
* 因为基本都是基于MD的，如果有可能，建议在后期支持富文本。
* 补充个问题：下划线在表格中没有能识别，typroa识别正常
```
|      系统变量      |                                 变量值                                 |
| ------------------ | ---------------------------------------------------------------------- |
| MINGW_HOME         | D:\dev\Dev-Cpp\MinGW64                                                 |
| C_INCLUDE_PATH     | %MINGW_HOME%\lib;%MINGW_HOME%\lib\gcc\x86_64-w64-mingw32\4.9.2\include |
| LIBRARY_PATH       | %MINGW_HOME%\lib;%MINGW_HOME%\lib\gcc\x86_64-w64-mingw32\4.9.2         |
| CPLUS_INCLUDE_PATH | %MINGW_HOME%\lib\gcc;                                                  |


```

用了很多笔记本，百度10页内的网站基本都试用过，最终选择了cherrytree和typroa，现在开始试用vnote。
cherrytree功能很强大，做笔记比较合适，但是目前也是在忍受，有些bug，向官网报告了很久也没修复，还有就是界面比较丑。
typroa在对MD的编辑相当爽，做一些MD单文件的编辑器很不错。

希望vnote越做越好，你们幸苦了。
How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

感谢试用VNote并详细反馈！

* 全屏功能如果是再Windows下面，是由显卡驱动造成的，可以参考GitHub置顶Issue解决；
* 文件夹和文件是独立还是混合展示，这个见仁见智；VNote里面可以通过通用入口快速查找笔记；后面版本会混合展示；
* 大纲的问题也是使用习惯问题~后面所有面板都可以拖动；
* 关于所见所得，这个是VNote的设计初衷问题，VNote选择的是一种折衷的原地预览；个人觉得Typora的方式刚开始使用就惊艳，对于Markdown来说用多就不爽了（Typora和使用快捷键操作Word没啥区别），具体可以参考GitHub首页说明；
* 定位问题后面会改进；
* 关于单文件笔记模式，也是VNote的初衷问题，VNote希望即使后面VNote不再更新，用户也可以使用任意第三方编辑器方便地管理和编辑自己的笔记数据，而不是绑定在VNote上面；就像现在您绑定在CherryTree上面一样，迁移数据会非常不便。VNote里面一个笔记本就是对应一个文件夹，只需要把该文件夹同步和备份好，一切数据都在；
* 富文本后面会支持；
* 表格问题，我在VNote里面测试如下，不知道有什么问题哦（另外，Typora的语法是非标准的）：
    ![image](https://user-images.githubusercontent.com/5763157/76697308-b8ed1f80-66d0-11ea-8098-dca81196c0d3.png)


最后，您可以尝试用VNote的方式去使用VNote，一定会感到非常得心应手（例如通用入口、Vim、导航模式、导出等等）。

谢谢！
