### ISSUE TITLE
能否将note和notebook两个栏目合并？

### ISSUE THREAD

**Issue by charles-lyc** [vnotex/vnote#1250]
如题。
每次点开notebook还要去留意Note就很难受了，就简单的在notebook的folder下面显示可以吗？

![Annotation 2020-03-18 140858](https://user-images.githubusercontent.com/9509201/76930694-090ef080-6922-11ea-9231-ee5c8dfcdd62.png)
![InkedAnnotation 2020-03-18 140858_LI](https://user-images.githubusercontent.com/9509201/76930882-7753b300-6922-11ea-9f4b-1c7b67f93772.jpg)

**Comment by tamlok** [comment]
Hi，

这个当初主要是参考为知笔记等常见软件设计的，后面新版会整合。

**Comment by YipCharles** [comment]
> Hi，
> 
> 这个当初主要是参考为知笔记等常见软件设计的，后面新版会整合。

太棒了！ 可以close了~~

**Comment by Nriver** [comment]
我觉得现在的设计挺好, 等笔记多了, 目录层级也多了之后, 我发现这个设计能避免你找笔记文件要左右拖动水平滚动条才能看到文件名, 浏览会更方便.
如果决定整合到一起的话, 希望能保留一个选项切换成现在的样子.

**Comment by YipCharles** [comment]
我喜欢所见即所得，而且笔记的层次不应该太高（3层），我们又不是为了分类而去记笔记。

**Comment by tamlok** [comment]
现在已经是混合了，后面会将原来分栏的方式添加回来。
