### ISSUE TITLE
edit和preview的切换问题

### ISSUE THREAD

**Issue by charles-lyc** [vnotex/vnote#1252]
是否可以做成双屏，左边edit右边preview呢？
最好做个快捷键之类的~~

**Comment by tamlok** [comment]
Hi,

VNote的设计点可以参考GitHub的ReadMe，VNote是介于双边实时预览和Typora方式之间的一种折衷的原地预览。（就是不爽双边预览和Typora，才有VNote）

当然，为了拓展用户，后面VNote会支持双边预览。

**Comment by YipCharles** [comment]
好，那应该要有快捷键~~

**Comment by tamlok** [comment]
快捷键是ctrl-t
