### ISSUE TITLE
一点小的期望

### ISSUE THREAD

**Issue by ZeronoFreya** [vnotex/vnote#1255]
使用了几天，虽然有点小毛病，但总体感觉很不错，在此想提点小建议。
1. 希望笔记可以以拖拽的形式连接其他笔记，目前需要先复制笔记路径
2. 代码块中不能包含空格，否则样式解析出错
![](https://raw.githubusercontent.com/ZeronoFreya/Gallery/master/0.png)

**Comment by tamlok** [comment]
hi，

关于第二点是md语法问题，代码块开始标记前面空一行即可。
