### ISSUE TITLE
文件被vnote自动删除了

### ISSUE THREAD

**Issue by woshihaozhu** [vnotex/vnote#1258]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
自己新创建了一个文件夹吗，不过存放的地方错了，于是就删除了，可是连我的笔记也一并删除了呀，这个是怎么回事呀，也不是全部的笔记都删除了，他只删除了一个文件夹内的笔记，求帮助呀！

How to Repro (如何复现):

**Comment by tamlok** [comment]
如果删除一个文件夹，那么这个文件夹下面得所有笔记以及子文件夹都会被删除，这个应该是和操作系统的操作逻辑也一致的。

可以在笔记本列表那里，右键菜单，回收站，去里面找回误删的文件，重新在文件菜单“从外部文件新建笔记”那里导入回来。

**Comment by woshihaozhu** [comment]
我看了回收站，没有被删除的文件，应该被完全删掉了，被删除的时候，我特意看了vnote日志，它没写什么原因删除的，就是写file is missing when check file ‘s outside change ，然后我又搜索了磁盘，发现没有我的笔记了，我猜肯定被完全删除了，我就用diskgenius恢复文件，果然是删除了，虽然找到了笔记，但笔记所占空间有些已经被覆盖了，绝望呀，我当时又创建了一个笔记试了试，肯定是被我给覆盖了，不应该手贱的呀，哎，我还是搞不清楚什么原因，这么会不通过回收站呢，而且日志也没写我哪里操作引起的，烦。

**Comment by tamlok** [comment]
暂时不清楚原因了~
