### ISSUE TITLE
Difference between space-separated keywords and &&

### ISSUE THREAD

**Issue by DutchPete** [vnotex/vnote#1261]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

Symptoms (表现): when using the *Advanced Search* what is the difference between space-separated keywords and &&? According to the VNote documentation they both mean AND.

In fact, from what I find a space gap acts as an OR criterion, **not** as an AND criterion.
Please explain.

How to Repro (如何复现):

**Comment by DutchPete** [comment]
@tamlok : is there actually a difference?

**Comment by tamlok** [comment]
Hi,

1. The logic depends on the last `AND` or `OR`;
2. If there is no `AND` or `OR`, then a space should mean `AND`;

Thanks!

**Comment by DutchPete** [comment]
@tamlok : re your point 2, in practice I notice that a space does not act as `AND`, it acts as `OR`.
In other words, if I search for `dutchpete tamlok`, if finds notes with `dutchpete` only, notes with `tamlok` only, as well as notes containing both `dutchpete` and `tamlok`.

**Comment by tamlok** [comment]
Hi @DutchPete ! Are you still using VNote? :)

From VNote 3, it should behave like `AND`.

Like searching `vnote vi`:

![image](https://user-images.githubusercontent.com/5763157/127658997-f4a7c02b-b34f-4196-8cec-5d20eb81905b.png)
