### ISSUE TITLE
导出文件失败

### ISSUE THREAD

**Issue by woshihaozhu** [vnotex/vnote#1262]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
![图片](https://user-images.githubusercontent.com/35716657/77500795-0f0c5080-6e91-11ea-969e-aed1cdd143b8.png)

![图片](https://user-images.githubusercontent.com/35716657/77500826-24817a80-6e91-11ea-8957-b6ebaa01e66a.png)

How to Repro (如何复现):

**Comment by woshihaozhu** [comment]
大佬，这是什么问题呀，路径错误吗，应该没错呀，我查了路径

**Comment by tamlok** [comment]
分隔符问题，看文档呀：

![image](https://user-images.githubusercontent.com/5763157/77502146-eede9080-6e94-11ea-8a99-c7befdae98a2.png)

**Comment by woshihaozhu** [comment]
谢谢，不过好像还是有问题
![图片](https://user-images.githubusercontent.com/35716657/77503791-77f7c680-6e99-11ea-810a-4e33b229568d.png)

**Comment by tamlok** [comment]
windows下面`pandoc`最好换成绝对路径，或者测试一下cmd里面能正确运行这条命令。
