### ISSUE TITLE
关于一段话的首行缩进

### ISSUE THREAD

**Issue by ethansung1996** [vnotex/vnote#1264]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8

Symptoms (表现):
一段话的首行按tab都是代码块，可以设置成按tab就是四个或者2个空白吗

How to Repro (如何复现):

**Comment by tamlok** [comment]
这是md语法规定，不是一个软件能改变的哦！具体搜索md首行缩进，网上很多解决办法。

**Comment by tamlok** [comment]
vnote3目前支持设置里面开启阅读时首行缩进
