### ISSUE TITLE
提示音

### ISSUE THREAD

**Issue by Oislop** [vnotex/vnote#1265]
OS Version (操作系统): Windows10 1909

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):在切换主题然后重启的时候会有提示音，能否关掉提示音

How to Repro (如何复现):切换主题后点击重启vnote

**Comment by tamlok** [comment]
这是操作系统弹窗的提示音吧，是系统主题所致，非VNote相关代码。除非VNote不弹窗提示，但不提示很多用户又会发Issue来问为啥切换主题不生效。
