### ISSUE TITLE
[咨询&建议]关于左侧目录树展示的用户检验问题

### ISSUE THREAD

**Issue by huilin-hub** [vnotex/vnote#1266]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2

目前默认的左侧目录树的展示，是文件夹目录在左上方，文件在左下方 (必须点击对应文件夹名字，在左下方才能看到文件)。但是我个人使用习惯是希望像windows文件目录树那样，一目了然，文件直接在目录里展开就能看到，点击文件即可编辑。 不知道是否有什么方法设置？可能是我使用windows习惯，对vnote默认的这种目录树结构，有些不太适应（尤其是管理的内容越来越多时），不知道其他同学有没有类似的感受。

如果目前没有办法做目录树显示方式做设置的话，是否可以考虑增加这个功能呢？因为”目录在左上，文件在左下“的模式，即便不考虑我个人习惯，从客观上说，我觉得它也很容易肉眼漏查目录里的文件。望考虑，谢谢。

**Comment by huilin-hub** [comment]
我目前知道的是，左边有个“浏览器”tab，是可以间接实现我的需求的。 但是我还是希望在“笔记本”tab下，直接就可以如此。  不知道是不是有什么地方可设置，只是我没找到？

**Comment by tamlok** [comment]
按一下那个两扇门一样的按钮就可以目录在左侧，文件在右侧了（常见笔记软件的做法）。后面会尝试两者都提供。

**Comment by tamlok** [comment]
vnote3默认提供这种方式了。
