### ISSUE TITLE
6M大小md文件打开出现在无响应

### ISSUE THREAD

**Issue by imvvip** [vnotex/vnote#1270]
OS Version (操作系统): Windows,10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2, 

Symptoms (表现):打开一接口文档，大小在6M多一点，vnote无响应，内存占用大概上升到近400M，等待约3分钟后，恢复正常。但在编辑过程中很容易出现短时无响应的情况。
![image](https://user-images.githubusercontent.com/50021124/77813812-7ec74900-70e6-11ea-87cb-c43e4d051c50.png)

How to Repro (如何复现):打开大文件

**Comment by tamlok** [comment]
直接右键以编辑模式打开看看？VNote的预估流畅处理上限是10万字。

**Comment by imvvip** [comment]
> 直接右键以编辑模式打开看看？VNote的预估流畅处理上限是10万字。

补充一下，是编辑模式打开的。

**Comment by tamlok** [comment]
右下角字数统计那里，显示是多少文字？

**Comment by tamlok** [comment]
方便的话，可以将该文件发我邮箱。

**Comment by imvvip** [comment]
![image](https://user-images.githubusercontent.com/50021124/77814162-80464080-70e9-11ea-8b13-e21d959435e3.png)
确实是超过上限。不过比typora表现要好些，typora直接飞掉了。因为是公司开发接口文档，不适合外发，不好意思了。希望vnote越来越好，越来越强大。
