### ISSUE TITLE
plantuml编译出错

### ISSUE THREAD

**Issue by wslsf01** [vnotex/vnote#1271]
OS Version (操作系统): Windows7

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9
Symptoms (表现):
1.离线编译：
![plantuml问题](https://user-images.githubusercontent.com/24824774/77814750-fef1ac80-70ee-11ea-974c-38e0484f7550.PNG)

2.在线编译：
       报错

**Comment by tamlok** [comment]
Hi,

本地PlantUML：

1. 安装JRE运行环境了吗?在命令行CMD直接运行`java`调用`plantuml.jar`，是否正常？
2. 尝试把`plantuml.jar`放在一个没有空格的路径下面，例如`c:\plantuml.jar`；

在线PlantUML:

1. 你这里就没有提供PlantUML服务器的地址，当然出错了，尝试输入`http://www.plantuml.com/plantuml`看看。

**Comment by wslsf01** [comment]
1.在线编译，我之前输入网址进入了，但是编译还是出错
![4](https://user-images.githubusercontent.com/24824774/77820713-2fe9d580-711f-11ea-85b2-e3d6b2edfd7d.PNG)
2.离线编译
2,.1 配置了jre环境，编译成功
![2](https://user-images.githubusercontent.com/24824774/77820743-69badc00-711f-11ea-9998-dc9e754cd07d.PNG)
2.2 测试依据出错
![3](https://user-images.githubusercontent.com/24824774/77820757-7b03e880-711f-11ea-8fc8-6a4265733955.PNG)

**Comment by wslsf01** [comment]
![6](https://user-images.githubusercontent.com/24824774/77820796-dc2bbc00-711f-11ea-84c6-26705d76eeda.PNG)
这是vnote.ini的内容

**Comment by wslsf01** [comment]
![7](https://user-images.githubusercontent.com/24824774/77820842-47758e00-7120-11ea-817c-089e0e440556.PNG)
日志

**Comment by tamlok** [comment]
plantuml是什么版本呢？看样子是什么1.8或者1.7的问题，你搜一下第一张图的错误信息看一下怎么解决吧。

**Comment by tamlok** [comment]
把第一张图的command那里的整条命令放到cmd里面执行看出不出错？

**Comment by wslsf01** [comment]
plantuml 是最新版的

**Comment by wslsf01** [comment]
command 指令没反应

**Comment by wslsf01** [comment]
你这个不支持jdk1.8吗

**Comment by tamlok** [comment]
简单搜一下第一张图的错误提示，可以发现应该是你机器上面多个JAVA版本混乱的原因：

https://stackoverflow.com/questions/29697543/registry-key-error-java-version-has-value-1-8-but-1-7-is-required

**Comment by wslsf01** [comment]
搞定了
方法：
重新下载jdk1.7安装即可

谢谢博主thanks
