### ISSUE TITLE
是否可以自定义Markdown渲染引擎？

### ISSUE THREAD

**Issue by chenbin11200** [vnotex/vnote#1278]
OS Version (操作系统): Windows

VNote Version: 2.9

Symptoms (表现):
感觉我的需求很多朋友都需要，但是至今没有一个解决方案。当然，这不是Vnote的问题，Vnote使用至今感觉非常优秀，也是我尝试了不少代码笔记软件后留下的最优方案，由衷的感谢作者的无私付出。
我的需求：
在代码块中使用自定义的HTML inline style。例如，我可以再代码块中使用：
```
<span style="background-color:#FFFF00">codes I want to emphasise.</span>
```
希望代码可以显示一个黄色背景，而不是一个raw html代码。
这个在普通模式，甚至是引用块中都是支持的，但是在code block中不支持。我必须用这个形式：
```
<pre>
<code>This is my <span style="background-color:#FFFF00">code.</span>
</code>
</pre>
```
这样的话，代码高亮又会失效。
当然，这不是vnote的问题，我尝试在markdown-it的github提交问题，得到的回复是我可以重写render来实现我想要的功能。https://github.com/markdown-it/markdown-it/issues/657

我可以尝试重写，但是问题是，我不知道vnote是不是支持使用自定义的markdown渲染引擎？我知道现在vnote可以使用自定义的界面外观样式了，但是渲染引擎我不是很确定？

一旦实现，我觉得很多问题就迎刃而解了，比如这个兄弟的问题：
https://github.com/tamlok/vnote/issues/1257 就可以使用code block，嵌套html inline style，配合等长字符的字符集。

最后希望Vnote越做越好！

**Comment by tamlok** [comment]
后面vnote会考开放阅读模式的诸多接口，可以关注。如果你写了一个新的md-it插件，目前可以很方便添加到vnote中。

**Comment by chenbin11200** [comment]
本来是打算直接fork markdown-it的，如果添加插件比较容易，也可以试试……要如何添加md-it插件到VNote呢？

**Comment by tamlok** [comment]
你可以参考markdown-it.js这个文件

**Comment by chenbin11200** [comment]
非常感谢！大概了解了。那fork了修改了以后，还是要重新release的吧？还是说有别的方式可以更快（比如把markdown-it.js 修改了以后放在某个文件夹下）？

**Comment by tamlok** [comment]
需要重新编译vnote，你先写好，再把它给我就好了

**Comment by chenbin11200** [comment]
你好。这两天读了一下markdown-it代码，尝试写了一下。Escape HTML问题倒不大，现在卡在了，如果我在code block里写了HTML，highlight.js 就不认这个源代码了，也不会代码高亮，那这个功能就失去意义了。
我以后有空再看看有什么解决方案吧，现在看来除了直接修改渲染后的代码（这个方法最直接，但是我觉得不适用于markdown或者是vnote，你怎么看？），可能就是修改highlight.js的代码了，但是要适配各种格式的代码，不太容易，而且工作量太大。
再次感谢你这两天的帮助。:-)

**Comment by tamlok** [comment]
我觉得要在code block里面写html本来就是一个悖论~~codeblock里面的内容本来就是说不要渲染的，结果还弄了个html~
