### ISSUE TITLE
pdf多合一输出时是否可以设置文件不单独另起一页？

### ISSUE THREAD

**Issue by Qiangest** [vnotex/vnote#1279]
您好，谢谢您的作品！
我在使用pdf多合一功能时，因为我每个md文件内容只有小半页，在合成时每个文件都会单独占一页pdf。想请问一下wkhtmltopdf是否可以设置多合一pdf时不单个文件分页吗？这样输出的pdf更节省空间。我看了一下wkhtmltopdf的文档，好像没有此选项，多谢！

**Comment by tamlok** [comment]
如果wkhtml2pdf没有提供的话，那就不行了。

**Comment by Qiangest** [comment]
> 如果wkhtml2pdf没有提供的话，那就不行了。

觉得可以先把所有md合并成一个文件，然后再使用wkhtmltopdf转换成pdf可能可以，希望您有机会可以考虑下这个功能，谢谢~

**Comment by tamlok** [comment]
由于精力有限，这种需求就不处理了。这个可以通过写脚本来合成，VNote里面自定义导出里面，先用你的脚本导出，然后脚本处理后再调用wkhtmltopdf来处理。
