### ISSUE TITLE
关于图床功能的若干建议

### ISSUE THREAD

**Issue by Ideaye** [vnotex/vnote#1280]
现在的图床功能已经比以前不支持图床的时候方便很多了,但是在使用过程中还是有许多痛点,包括图床迁移不方便和多文件上传等,另外我还是希望上传图片之后本地能保留备份.所以提出以下几点建议,望采纳:
1. 选中文件夹,上传文件夹内包括子目录中的图片
2. 图床支持自定义路径,而不是将图片全部传至仓库根目录
3. 导出Markdown文件时将图片从图床down下来
4. 上传至图床时保留本地图片(本地备份)
5. 支持图床迁移

**Comment by tamlok** [comment]
1. 这样感觉要求有点复杂了，像是一个专业的图床管理软件做的事情；
2. 目前已经实现；
3. 如果导出的时候，是需要本地图片的，感觉写文档的时候直接使用本地图片会比较好？
4. 我觉得图床就是为了分享，和本地应该是两个互斥的，不然管理比较混乱；
5. 同样，这也是一个图床管理软件该做的事情。

这些功能都过于专业化了，或者需要等到vnote支持插件后，再细化深耕了。谢谢！
