### ISSUE TITLE
v2.9版本导出pdf特别慢，但是typora很快不知道是啥回事

### ISSUE THREAD

**Issue by wslsf01** [vnotex/vnote#1282]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
问题详细一点最好，能给出的信息都给出，这样才知道什么事情。什么系统？自身导出还是通过wohtml2pdf导出？

**Comment by wslsf01** [comment]
OS Version (操作系统): Windows7

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
     通过wkhtmk2pdf导出，特别慢，但是同一个markdown文件，typora导出为pdf要快的多
How to Repro (如何复现):

**Comment by tamlok** [comment]
VNote 是为了保存一些js能被执行完毕，所以等待了几秒。
