### ISSUE TITLE
存在xss漏洞

### ISSUE THREAD

**Issue by Rambo-996** [vnotex/vnote#1284]
OS Version (操作系统): Windows上发现的，理论上来说应该都有
VNote Version (Help - About VNote - Version: )(VNote版本): 
-2.9(最新版本）

Symptoms (表现):
![image](https://user-images.githubusercontent.com/41468257/77896867-7bc98580-72ab-11ea-9a3f-c6e32038f80e.png)

How to Repro (如何复现):
创建一个markdown文档，编辑模式输入如下代码
`<img src=x onerror=alert()>`

然后点击`保存更改并阅读`

**Comment by loztzou** [comment]
渲染器的问题吧，换个渲染器试试？

**Comment by tamlok** [comment]
的确会有这个问题，因为没有禁用JS，也没有过滤JS脚本。但VNote主要是自用笔记（自己创作的内容），所以这个暂时就先不处理吧。等后面重构完了，再看看怎么弄一个过滤关键词吧。

**Comment by tamlok** [comment]
Fixed. Turned off by default due to its personal use and perf issue.

https://github.com/vnotex/vnote/blob/315d5433998b122fdba68d2492dbd71290b13f44/src/data/core/vnotex.json#L222
