### ISSUE TITLE
markdown下划线ctrl+u，这里是删除到首行，那么下划线在vnote中怎么弄

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1286]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
下划线不是标准语法，目前暂时不支持，可以通过html标记实现`<u>abc</u>`，可以通过vnote的片段快速输入。
