### ISSUE TITLE
wkhtmltopdf采用pdf导出数学公式无法显示空白

### ISSUE THREAD

**Issue by wslsf01** [vnotex/vnote#1288]
OS Version (操作系统): Windows7

VNote Version 2.9

Symptoms (表现):
 wkhtmltopdf采用pdf导出数学公式无法显示空白
![pic1](https://user-images.githubusercontent.com/24824774/78101799-31671680-741b-11ea-8f3c-e18d59de5ef3.PNG)
![pic2](https://user-images.githubusercontent.com/24824774/78101801-3330da00-741b-11ea-80df-f36cc09c25ef.PNG)

如何不采用wkhtmltopdf，数学公式则能显示出来

**Comment by tamlok** [comment]
Should be fixed in VNote 3 now.
