### ISSUE TITLE
有时候觉得分割线（---）特太长了，影响美观，能控制长短吗？

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1293]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
什么分割线？提问题详细一点呀！这样一来一回的，好浪费时间的！

**Comment by One010101** [comment]
`---`这个不是一个分割线吗？请问能控制它显示效果长短吗？我说的话不难理解吧

**Comment by tamlok** [comment]
`---`分割线在阅读模式下面显示太长。

可以通过修改CSS样式自定以`<hr>`的样式。

https://www.baidu.com/s?wd=hr%20%E9%95%BF%E5%BA%A6%20css&rsv_spt=1&rsv_iqid=0xb814cdaf000052fe&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=cn&tn=baiduhome_pg&rsv_enter=1&rsv_dl=tb&oq=hr%2520css&inputT=3101&rsv_t=2afbP8GsQ1KGBjd%2BwTWoKQ0zlwYiah%2BinPLSNOspH7MbTf76wBNjOYhl3ciBNEOq4rTD&rsv_pq=9201e1bd000295e9&rsv_sug3=31&rsv_sug1=7&rsv_sug7=100&rsv_sug2=0&prefixsug=hr%2520%25E9%2595%25BF%25E5%25BA%25A6%2520css&rsp=1&rsv_sug4=4422

**Comment by One010101** [comment]
谢谢
