### ISSUE TITLE
能否添加 “将网络图片复制到本地” 的功能

### ISSUE THREAD

**Issue by Peter-JXL** [vnotex/vnote#1294]
OS Version (操作系统): Wind10 1909
VNote版本: 2.9

Symptoms (表现):例如将网页复制到Vnote，图片地址是该图片的网络地址，能否设置成自动保存为本地图片或者可以手动复制到图片目录。
例如Typora，就有右键--复制到assets目录的功能，这样就不用担心图片失效的问题

![image](https://user-images.githubusercontent.com/45090349/78418469-ee9d7c80-766e-11ea-85f9-7820c2a52f40.png)

我浏览了相关issue，暂未找到该问题
期待您的回复。

**Comment by tamlok** [comment]
hi，复制网页，在编辑器右键，解析为Markdown并粘贴，所有事情vnote都会搞定，包括下载图片(当然如果因为网络问题下载不了，就不会替换)。
