### ISSUE TITLE
怎么修改代码块的标记

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#1302]
OS Version (操作系统): Windows 10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.8.2
Symptoms (表现):

现在的代码块默认使用两行```把代码括起来，但是在我们公司的网站上显示的时候可能有异常，因此想换成其他的符号，比如三个~~~，不知道怎么修改默认值。

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

VNote软件的帮助菜单里面的语法指南里面写了：

![image](https://user-images.githubusercontent.com/5763157/78851059-6ee72780-7a4b-11ea-994d-dcc09b019006.png)

另外，显示异常是不是因为代码块前面没有空一行呢？代码块前面最好添加一行空行。

**Comment by jackydi** [comment]
> Hi,
> 
> 目前没法修改默认的，可以使用片段功能快速输入`~~~`，也可以分配一个快捷键，具体参考官方文档.
> 
> 另外，显示异常是不是因为代码块前面没有空一行呢？代码块前面最好添加一行空行。

感谢您的回复，不是因为代码块前面没有空行，是因为网站对markdown规则的解释不一样。

**Comment by tamlok** [comment]
后面添加一个配置。
