### ISSUE TITLE
无法读取到gitee的图片

### ISSUE THREAD

**Issue by majamping** [vnotex/vnote#1304]
OS Version (操作系统): Windows10 64bit

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
已经保存的图片上传到gitee，点击图片不显示了。
![图片](https://user-images.githubusercontent.com/14238363/78880772-77aa1e80-7a88-11ea-83d4-d2a9ce7be4a1.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
复制图片链接到浏览器，能否浏览？

**Comment by majamping** [comment]
复制到浏览器地址是可以访问的。

**Comment by tamlok** [comment]
Markdown文本截图看一下?

**Comment by Park-ma** [comment]
应该是因为使用的是私有仓库的原因吧？

**Comment by majamping** [comment]
对，是私仓。

**Comment by Park-ma** [comment]
我换成公仓就显示了

**Comment by majamping** [comment]
可以考虑加密钥吗？
毕竟有些东西是私有。

**Comment by tamlok** [comment]
后面会完善。

**Comment by tamlok** [comment]
考虑了一下，使用图床是为了分享，如果使用私有仓库，那需要把令牌写到markdown文本中，这肯定也不会分享出去。既然不分享，完全可以使用本地图片，然后把这个笔记目录都作为一个gitee的仓库维护即可。所以，考虑到精力有限，不会添加这个功能。
