### ISSUE TITLE
~~删除在查看模式不对

### ISSUE THREAD

**Issue by majamping** [vnotex/vnote#1305]
OS Version (操作系统): Windows10 64bit

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
编辑模式：
![图片](https://user-images.githubusercontent.com/14238363/78881576-99f06c00-7a89-11ea-86b1-ae11db1136c0.png)

查看模式：
![图片](https://user-images.githubusercontent.com/14238363/78881500-7e856100-7a89-11ea-9b23-dcfe3476037f.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
Markdown菜单，渲染引擎，请使用默认的Markdown-It.
