### ISSUE TITLE
导入图片相对链接中斜杠问题

### ISSUE THREAD

**Issue by RainCat1998** [vnotex/vnote#1307]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9
Symptoms (表现):
如题，当图片作为相对链接导入时，链接的左右斜杠会影响路径识别。在编辑界面可以识别左右斜杠，在阅读模式就只能识别左斜杠。
How to Repro (如何复现):
在目录下创建一个1.jpg的图片文件，输入以下内容：
```
![](./1.jpg) 
编辑界面可以识别，阅读模式可以识别。
![](.\1.jpg) 
编辑界面可以识别，阅读模式不能识别。
```

**Comment by tamlok** [comment]
因为url只能识别/
