### ISSUE TITLE
“工具”面板的标题栏能否去掉？

### ISSUE THREAD

**Issue by vagra** [vnotex/vnote#1309]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
“工具”面板，也就是显示文档的目录树的那个面板，它有个标题栏，左边是“工具”俩字，右边是浮动按钮和关闭按钮。

我觉得这样不好看，这个感觉，从一开始就有，因为这个工具面板，跟其它面板不统一，它带个标题栏，其它面板都是没有标题栏的。

我们一般使用其它的软件，每个面板都是统一的，所以看着舒服。这个 VNote 我一直觉得哪里不太对劲儿，刚才我看出来了，就是因为这个工具面板带标题栏，造成它跟其它面板有上下错位的感觉。

能否想办法，把工具面板的标题栏给隐藏，或者跟其它面板一致就可以。

How to Repro (如何复现):

**Comment by vagra** [comment]
还有“搜索”面板，也是这个问题。

**Comment by tamlok** [comment]
现在都统一了
