### ISSUE TITLE
文件夹、笔记、工具、搜索，这几个面板是否可以搞成一组，同时只能打开一个？

### ISSUE THREAD

**Issue by vagra** [vnotex/vnote#1310]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
也就是说，像 VSCode 的布局一样，最左边有个窄的竖条，从上到下依次有文件夹、笔记、工具、搜索，几个图标，点击可以打开对应的面板，但这四个面板共用同一个侧边栏，同一时间内只能打开其中的一个面板。

因为一般来说，找文件时打开文件夹或者笔记面板，编辑和阅读时打开工具面板，不用同时开着好几个面板。

这样的话界面会清爽很多。

How to Repro (如何复现):

![图片](https://user-images.githubusercontent.com/1576687/79053504-83583980-7c70-11ea-896f-149c173784b5.png)

**Comment by tamlok** [comment]
vnote3是这样了，也可以随意拖出来放别的位置。
