### ISSUE TITLE
请问在编辑模式和渲染模式下，分别使用了哪个 js 库来做 Markdown 的解析？

### ISSUE THREAD

**Issue by vagra** [vnotex/vnote#1311]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

这不是报 BUG ，这是提个问题。

我修改了 marked.js 的语法，让它改用 #1、#2、#3……#108 来代表各级标题，并且把支持的标题级别从 6级 扩展到了 108级，修改过的 marked.js 在网页中测试是可以正常识别的。

然后我用修改过的 marked.js 、marked.min.js 替换了源代码中原有的文件，然后重新编译，执行的结果是，编辑模式下，还是在用标准的 markdown 语法来解析的，解析不了我的 #1、#2、#3……，但能正常解析 #、##、###，这说明，编辑界面使用的 markdown 解析库可能并不是  marked.js 。

而阅读模式下直接啥也不显示，整个文档一片空白，但这个无所谓，这个我以后可以慢慢修改。我现在就是想搞清楚：编辑模式和阅读模式下用的 markdown 解析库分别是什么？

在 Markdown > 渲染器 菜单中我是已经选择了 marked 的。

How to Repro (如何复现):

**Comment by vagra** [comment]
我对 marked.js 做了少许修改让它可以用 #1、#2、#3.... #108 的形式支持多达 108级的标题层次，这个我应用到 docsify 中效果就不错：
https://kepan.org/docsify/#/docs/kepan1

现在我是想把 VNote 也做一下修改，让它也可以支持用 #1、#2、#3……#108 支持最大108级标题。

**Comment by tamlok** [comment]
编辑模式是cpp库，peg-markdown-highlight

**Comment by vagra** [comment]
谢谢，我看看。

**Comment by vagra** [comment]
very good.

这个 peg-markdown-highlight ，要用你 fork 的那个仓库。
https://github.com/tamlok/peg-markdown-highlight

git clone 源代码以后，用 MingW 进入源代码根目录，执行 make ；
执行 make ，会根据 pmh_grammar.leg 中编写好的语法规则，生成 pmh_parser.c ；

那么我就修改这个 pmh_grammar.leg 中的语法规则，make ，然后用生成的新的  pmh_parser.c 
替换 vnote/peg-highlight 下面的同名文件即可。

很棒。

**Comment by tamlok** [comment]
是的，原仓库不支持新的代码块语法等等。有空帮忙一起完善这个规则呀，比如现在代码块前面需要空一行才行，我暂时不知道怎么改，应该像标题一样可以不空行

**Comment by vagra** [comment]
改起来确实不太容易，不过现在确实可以（初步）支持 #1、#2、#3……#108 的一百零八级标题了。

![微信图片_20200413134137](https://user-images.githubusercontent.com/1576687/79095263-8e07f100-7d8c-11ea-84a7-949002b83423.png)
