### ISSUE TITLE
“继续上次退出时的页面”存在的BUG

### ISSUE THREAD

**Issue by Vandalizegod** [vnotex/vnote#1313]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
有两种情况：
1. 通过“文件-重启”重启软件，打开的页面不对
2. 在不关闭VNote的情况下，直接电脑关机，下次开机后启动VNote后打开的页面不正确

How to Repro (如何复现):
1. 在“设置-常规”的“启动页面”选项选择“继续上次退出时的页面”
2. 随便打开一个笔记，并退出软件（让它记录登记退出信息）
3. 再次打开软件，然后随便打开另一个笔记
4. 直接关机重启，开机后再次打开VNote

**Comment by null-id** [comment]
Mac版本也有类似的情况，现在我电脑上的vnote已经无法在打开时启动上次关闭的页面了。
