### ISSUE TITLE
点击菜单栏无反应，右键也没反应

### ISSUE THREAD

**Issue by crazyjavar** [vnotex/vnote#1315]
OS Version (操作系统): Windows 10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2  782ee5995d359a00f4526563118dcf7a8f6d7b63 

Symptoms (表现):
不知道按了什么，vnote软件占满桌面，只能alt+Tab切出去。
点击菜单栏无反应，右键也无反应，只能预览笔记，无法进行编辑等其他任何操作

How to Repro (如何复现):不清楚

**Comment by tamlok** [comment]
GitHub置顶Issue： https://github.com/tamlok/vnote/issues/853

**Comment by crazyjavar** [comment]
刚按照文章升级了显卡驱动，添加系统变量QT_OPENGL  software，并且将版本升级到了2.9，现在可以点击菜单栏也可以编辑，但是界面还是全屏状态，，并且右上角的缩小，关闭按键还是不见。只能只能alt+Tab切出去

**Comment by tamlok** [comment]
因为你按了F11，触发了全屏，再按F11即可。

**Comment by crazyjavar** [comment]
确实是这样子，有点尴尬。感谢作者解答。
总结一下：1.升级了驱动。2.更新了vnote。3.删除了系统变量。4.按下F11然后就可以正常使用了。
