### ISSUE TITLE
阅读模式能打开多大的文件？

### ISSUE THREAD

**Issue by Ce1este** [vnotex/vnote#1317]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
![image](https://user-images.githubusercontent.com/51806751/79122582-9e3ec100-7dca-11ea-8138-7b28f732dfc9.png)
文档过大的时候编辑模式正常，但是阅读模式就加载不出来
我只有把它截成编辑模式下5000字左右才能在阅读模式正常打开
不知道跟我插入公式和图片比较多有没有关系
只能手动拆成小文件吗？

补充:
![image](https://user-images.githubusercontent.com/51806751/79249084-547bd680-7eaf-11ea-8ba0-ff4603d91710.png)
今天新导入的这个笔记能在阅读模式正常打开，但是之前的那个文件在阅读模式还是加载不出来
How to Repro (如何复现):
打开大文件

**Comment by Ce1este** [comment]
我现在觉得应该是公式过多的文件在阅读模式下打开有困难

**Comment by tamlok** [comment]
mathjax渲染会有点慢，后面会换成katex

**Comment by tamlok** [comment]
新版用了mathjax3，可以试试
