### ISSUE TITLE
对VNote小小的建议

### ISSUE THREAD

**Issue by ZoruaSama** [vnotex/vnote#1321]
您好，感谢您开发了如此方便好用的markdown编辑器。我可以毫不吝啬地说，这是我用过最好的MD编辑器。尤其是原地预览的特性。在我大致浏览了一下问题列表，似乎没有出现和我的建议重复的。因此我在这里提交一下。
在中文文本的编辑时，不能将输入法直接切为中文标点，因为要输入“。”等标点符号，但是在输入markdown的$ ` > 等符号时又得用Shift或者CapsLock进行切换。
不知能否做成，除了逗号句号感叹号等常用中文标点，其余的中文标点得通过{Ctrl+Shift+按键}进行输入，否则单一的{Shift+按键}只能输出英文标点。
另外{| \}键和{？/}键在中文模式下输出的都是顿号，如果要实行这个方案，只用保持{？/}是问号即可了。

不知上述特性在实现时是否困难或可行。以上只是我的一些个人愚见。若不适合望海涵。

**Comment by ZoruaSama** [comment]
修改一下：
不知能否做成，除了逗号句号感叹号等常用中文标点，其余的中文标点得通过{Ctrl+Shift+按键}进行输入，否则单一的{Shift+按键}只能输出英文标点。

**Comment by tamlok** [comment]
这个感觉应该是换一个自定义丰富一点的输入法即可解决？小狼毫什么的好像都可以自定义符号顺序。

**Comment by ZoruaSama** [comment]
谢谢您。
