### ISSUE TITLE
搜索关键字能不能再大纲中搜索

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1322]
ctrl+f不是在笔记中搜索嘛，我想在大纲中搜一些东西来达到快速定位位置，请问能不能达到？

**Comment by tamlok** [comment]
通用入口，`y`或者`b`即可：

![image](https://user-images.githubusercontent.com/5763157/79676925-bd4faf80-821d-11ea-8374-11e7067329b5.png)
