### ISSUE TITLE
剪切图片，就会清除图片资源，导致图片丢失

### ISSUE THREAD

**Issue by silva6** [vnotex/vnote#1327]
OS Version (操作系统):  macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
比如下面文档中的图片链接，一旦剪切，资源立刻被清理了，导致图片丢失

```
![](_v_images/20200422160426385_911436580.png)
```

How to Repro (如何复现):
迫切求修复，太没安全感了

**Comment by tamlok** [comment]
设置里面把自动保存关闭，使用交换文件即可。

目前逻辑上面有一点问题，保存文件就会把不引用的图片删除，所以自动保存不能开。

被删除的图片可以在笔记本的回收站里面找回来。

**Comment by silva6** [comment]
应该是以前勾选了，现在找不到入口了，我先改成交换文件试试。

另外，回收站在哪儿，所有界面的按钮都过了一遍，没发现入口😓

**Comment by tamlok** [comment]
笔记本下拉列表，右键菜单，或者打开的标签页上面右键。
