### ISSUE TITLE
右边的工具栏（大纲）是否可以像左边的笔记本栏一样直接拉成一条缝来。用的时候再拉回来

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1332]
右边的工具栏（大纲）是否可以像左边的笔记本栏一样直接拉成一条缝来。用的时候再拉回来。提高笔记的视野。
我现在的做法是把大纲工具关闭，编辑完笔记后需要大纲的时候再 选择查看勾选工具，显示大纲。这种做法有点低效。

**Comment by tamlok** [comment]
`Ctrl-E T`，想要更快捷更高级得用法，具体肯定得查看帮助菜单了。

**Comment by Ximeng0918** [comment]
这个建议好，收缩功能

**Comment by tamlok** [comment]
目前qt好像没有提供自动收缩展开功能。还是希望能通过快捷键来扩展内容区域。
