### ISSUE TITLE
阅读模式下的自然段开头空格问题

### ISSUE THREAD

**Issue by Vandalizegod** [vnotex/vnote#1337]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
一篇文章中每个自然段开头都有两个空格，但是在每个标题下面的第一个段落在阅读模式下并没有空出来，请问是渲染的问题还是设置有误呢？
![1](https://user-images.githubusercontent.com/57993778/80444355-259c4080-8944-11ea-9c1f-5fd40b1761fa.JPG)

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

这是Markdown语法问题，可以用搜索引擎搜一下`markdown 首行缩进`，很多解决方案。
