### ISSUE TITLE
MathJax本地安装问题

### ISSUE THREAD

**Issue by SadFdW** [vnotex/vnote#1343]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):配置本地MathJax2.7.8不成功
我以前在另外一台windows10的系统上安装过vnote2.7.2+MathJax2.7.3，当时配置路径的时候需要改为"file:///D:\\\\Programs\\\\Tools\\\\VNote\\\\tools\\\\MathJax-2.7.3\\\\MathJax.js?config=TeX-MML-AM_HTMLorMML"才能成功（此时vnote.ini文件显示“ 
 mathjax_javascript="file:///D:\\\\\\\\Programs\\\\\\\\Tools\\\\\\\\VNote\\\\\\\\tools\\\\\\\\MathJax-2.7.3\\\\\\\\MathJax.js?config=TeX-MML-AM_HTMLorMML"  ”）
但是今天安装vnote2.9.1+MathJax2.7.8的时候此方法不能工作，尝试将路径改为"file://D:\Programs\Tools\VNote\tools\MathJax-2.7.8\MathJax.js?config=TeX-MML-AM_HTMLorMML"等各种形式都不能成功，每次修改之后都重新勾选“原地预览”和“扩展->MathJax”并重启VNote.
检查vnote.log显示：
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:198) Uncaught TypeError: MathJax.texReset is not a function
Info:(main.cpp:215) VNote started "2.9.1" "Thu Apr 30 18:10:07 2020"
Info:(main.cpp:215) VNote started "2.9.1" "Thu Apr 30 18:10:33 2020"
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Info:(main.cpp:215) VNote started "2.9.1" "Thu Apr 30 18:11:41 2020"
Info:(main.cpp:215) VNote started "2.9.1" "Thu Apr 30 18:11:48 2020"
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:75) Uncaught TypeError: MathJax.typesetPromise is not a function
Critical:(mathjax_preview.js:198) Uncaught TypeError: MathJax.texReset is not a function

How to Repro (如何复现):

**Comment by tamlok** [comment]
VNote新版本升级为MathJax 3.0了，试一下

**Comment by SadFdW** [comment]
> VNote新版本升级为MathJax 3.0了，试一下

确实只支持3.0

**Comment by SadFdW** [comment]
> VNote新版本升级为MathJax 3.0了，试一下

确实只支持3.0，thx
