### ISSUE TITLE
保存更改并阅读未展示最新编辑内容

### ISSUE THREAD

**Issue by SuperNoobTao** [vnotex/vnote#1346]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.9.1

Symptoms (表现):
新建笔记(空白页面) -> 写入若干文字 -> 点击“保存更改并阅读” -> 显示空白页面（未展示刚刚编辑的内容）。
关闭刚刚新建的笔记页，重新打开可看到最新编辑内容
ps:这是设计如此还是bug呀？我好像咋试都不行额。

How to Repro (如何复现):
win10，2.9.1版本。

**Comment by tamlok** [comment]
请参考置顶issue: https://github.com/tamlok/vnote/issues/853

**Comment by SuperNoobTao** [comment]
> 
> 
> 请参考置顶issue: #853

好的我试试，作者大大你回复的好快
