### ISSUE TITLE
导入现有的MD文件不太方便

### ISSUE THREAD

**Issue by bdkiller** [vnotex/vnote#1351]
OS Version (操作系统): Windows10

VNote Version(VNote版本): 2.9.1

Symptoms (表现):
将现有的MD文件夹复制到VNOTE笔记本目录中，打开软件没法自动导入，用打开的方式也只能导入打开的文件夹中的文件，而子文件夹的文件却没导入。希望能直接导入文件夹及子文件夹下面的所有MD文件。最好是不管MD文件夹在什么位置，导入后按原目录结构直接复制到MD笔记本中。

How to Repro (如何复现):

**Comment by tamlok** [comment]
vnote3已改进
