### ISSUE TITLE
Bug从磁盘重加加载无效

### ISSUE THREAD

**Issue by qianshen88** [vnotex/vnote#1355]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):

从磁盘重加加载无效。

How to Repro (如何复现):

从本地磁盘新建MD文件，使用VNote 查看目录没有此文件显示，当点击从磁盘重加加载，一样无法加载新建的MD文件。

**Comment by tamlok** [comment]
外部新建md文件需要修改该文件夹下的json索引文件，然后重新加载。

**Comment by qianshen88** [comment]
提个小建议，可不可以改成，点击从磁盘重新加载后，重新在生成这个json文件呢

**Comment by qianshen88** [comment]
> 外部新建md文件需要修改该文件夹下的json索引文件，然后重新加载。

提个小建议，可不可以改成，点击从磁盘重新加载后，重新在生成这个json文件呢

**Comment by tamlok** [comment]
后面会有更方便的逻辑处理这种外来文件。

**Comment by tamlok** [comment]
vnote3已支持外部文件。
