### ISSUE TITLE
MathJax formulas do not display on MacOSX

### ISSUE THREAD

**Issue by bmarcov** [vnotex/vnote#1357]
OS Version: macOS 10.14
VNote Version: 2.9.1

Symptoms: MathJax formulas do not display (neither in editor nor in preview)

How to Repro:

create a new note with the following text

```
# new_note

$x^2$

$$
x^2
$$

\begin{equation}
x^2
\end{equation}
```

renders as

![image](https://user-images.githubusercontent.com/1647614/81398977-2aba7600-9122-11ea-8a95-700fc3c3e218.png)

VNote config looks fine:

![image](https://user-images.githubusercontent.com/1647614/81399096-50e01600-9122-11ea-8a16-3bb93b17a591.png)

**Comment by tamlok** [comment]
In 2.9.1, MathJax is updated to v3.0. Could you check if the configuration woks in 3.0?

My old version VNote works fine:

![image](https://user-images.githubusercontent.com/5763157/81400444-b4d4ff80-915f-11ea-88a6-2973cab1b5c8.png)
