### ISSUE TITLE
How to add an editor style

### ISSUE THREAD

**Issue by sinh927** [vnotex/vnote#1358]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
I want to add or change the editor style without adding a theme.
I read the Editor Styles on the vnotes-doc site.
I copied the v_detorte.mdhl file of the v_detorte theme.
I only wrote "font-size: 20" in the v_detorte.mdhl file I copied.
I put that file in the styles folder.
I restarted Vnote and reopened the notes.
However, the font size remains the same.
Please let me know how I can change or add editor styles.

How to Repro (如何复现):

**Comment by tamlok** [comment]
Did you choose your style in the `Edit` menu -> `Editor Style` and restart VNote?

**Comment by sinh927** [comment]
Yes. I selected it from the menu and rebooted it.

I wanted a separate file because if I edit the original file, it will be overwritten when I upgrade.
It doesn't work, so I'll edit the original file.

**Comment by tamlok** [comment]
Try to rename the file in styles folder?
