### ISSUE TITLE
排序的问题

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#1361]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

目前选择按照名字排序的时候，大写名称（Z）是放在小写名称（a）前面的，能不能**不区分大小写**进行排序？

How to Repro (如何复现):

**Comment by tamlok** [comment]
Fixed: 7cc31a5d6e5ff345bf9b6c6dfbfebbcef058b4dc
