### ISSUE TITLE
对vnote1.0版本的疑惑

### ISSUE THREAD

**Issue by Resbonsiblyat** [vnotex/vnote#1367]
OS Version (操作系统): Windows, 

VNote Version (Help - About VNote - Version: )(VNote版本): 1.0
Symptoms (表现):
您好，我是一名大四学生，我正在从最初的版本看起，希望能学习到一个项目如何一步步更迭的。
我在尝试自己用vs编译您的1.0版本代码时，成功运行，但点击md文件进入preview模式就会提示：

windows提示没有安装可以打开此类链接（data）的应用
![1](https://user-images.githubusercontent.com/32755370/81590681-c6cbd200-93ed-11ea-89ed-64cc67e21bb4.png)

我猜测这是QWebChannel和js的问题，如果您有空，我希望能得到您的指导！万分感谢！

How to Repro (如何复现):
我不知道该怎样描述复现过程，我不确定问题出现的具体位置。您的release版本是正常工作的，但我自己编译就不行。
我在qwebchannel.js中找到了data这个关键字，但我并不使用js，因此很多东西我看不明白。
另外我在1.0版本的rar中，没有找到marked.min.js
这是在template.html中出现的  `<script src="qrc:/utils/marked/marked.min.js"></script>`
我不知道这是否有影响

以上，祝您工作顺利

**Comment by tamlok** [comment]
Hi,

旧版本使用qt 5.7编译即可。
