### ISSUE TITLE
VNote icon appears in system tray when "System tray" option disabled

### ISSUE THREAD

**Issue by jbcaramar** [vnotex/vnote#1368]
OS Version: Linux (5.6.11-arch-1/bspwm)

VNote Version: 2.9.1

Symptoms:
After installing vnote 2.9.1, I tried turning on the "System tray" option in Settings. I decided it wasn't an option I would use, so I turned it off again. The VNote icon continues to appear in the system tray regardless of the state of the "System tray" checkbox.

How to Repro (如何复现):

1. Install VNote on Arch Linux running bspwm and polybar.
2. Launch VNote
3. Select Settings from File menu
4. Enable "System tray" checkbox on "General" panel
5. Close Settings window [Expected result: VNote icon is added to the system tray (works)]
6. Select Settings from File menu
7. Uncheck the "System tray" checkbox
8. Close Settings window [Expected result: VNote icon is removed to the system tray (doesn't work, even after relaunch)]

Expected result: State of VNote "System tray" checkbox determines whether a VNote icon is displayed in the system tray or not.

Observed result: VNote icon continues to appear in the system tray when VNote is launched when  "System tray" option is unchecked.

**Comment by tamlok** [comment]
Hi,

As the tooltip says, VNote will always display a system tray icon. When the `System tray` is enabled, VNote will minimize to the system tray when being closed.

![image](https://user-images.githubusercontent.com/5763157/81623138-53de4d80-9425-11ea-8ad8-868fdab022ff.png)
