### ISSUE TITLE
关于阅读模式和编辑模式下文档阅读位置的问题

### ISSUE THREAD

**Issue by wang92332** [vnotex/vnote#1371]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):在阅读模式下看到文档某个位置需要修改，进入编辑模式后，往往当前阅读的位置会发生变化，有时向上，有时向下，需要手动寻找刚才文字的位置，从编辑模式回到阅读模式同样。看逻辑好像是跳转到最近的一个标题的位置？请问可不可以实现两个模式切换时文档位置不变？大佬辛苦了

How to Repro (如何复现):

**Comment by tamlok** [comment]
已经改进
