### ISSUE TITLE
希望增加列表切换功能

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#1372]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

希望增加一个功能，自动设置无序列表或者有序列表，功能应该是这样的：

无序列表切换功能：对于选定缓冲区中的**非空行**，如果行首没有无序列表符号，则添加符号；如果有无序列表符号，则删除符号。

有序列表切换功能：对于选定缓冲区中的**非空行**，如果不是有序列表，则在每个**非空行**行首按顺序添加有序列表符号；如果是有序列表，则删除行首的有序列表符号。

这个功能比较适合对大块的文本进行批量操作，很多人都应该会需要的。

How to Repro (如何复现):

**Comment by jackywu** [comment]
@tamlok 请问，这个功能现在有么？

**Comment by tamlok** [comment]
木有，重构完后会一个一个都加上

**Comment by tamlok** [comment]
现在应该支持了。
