### ISSUE TITLE
可能存在内存泄漏

### ISSUE THREAD

**Issue by pingplug** [vnotex/vnote#1374]
OS Version (操作系统):  Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1.gbecda2e

Symptoms (表现):
在没有操作的时候内存占用逐渐增加，被我关掉时占用超过6GiB

How to Repro (如何复现):
打开一个包含很多公式、图片的文档编辑一下，静置十分钟？
不清楚是否保证复现。

**Comment by bizwofficial** [comment]
同样发现了这个问题！打算用CE分析一下
    	
    	

    	获取 Outlook for iOS
    
  




On Sun, May 17, 2020 at 7:33 PM +0800, "pingplug" <notifications@github.com> wrote:
















OS Version (操作系统):  Linux



VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1.gbecda2e



Symptoms (表现):


在没有操作的时候内存占用逐渐增加，被我关掉时占用超过6GiB



How to Repro (如何复现):


打开一个包含很多公式、图片的文档编辑一下，静置十分钟？


不清楚是否保证复现。

**Comment by zhyma** [comment]
Windows 10下存在类似的问题，Vnote版本也是2.9.1
正常操作，在文档中添加了一张图片，编辑了几份文档，大概是从早上用到下午的时候，听到笔记本风扇特别响才注意了一下，之后会抽空计时观察一下
![image](https://user-images.githubusercontent.com/2032749/83798467-4c9c0f80-a672-11ea-9911-5a0a446d62f7.png)

**Comment by zhyma** [comment]
全程只开两个标签，一个是文本+graphviz+mathjax，还有一个是文本+图片+mathjax，运行大概三个小时之后内存占到了1.3G。三个Qt Qtwebengineprocess中有一个占了876M，剩下两个占了不到100M。关闭两个标签之后800多M的那个进程还在。

**Comment by tamlok** [comment]
@zhyma 谢谢提供信息，后面这个信息很有用，感觉是用于Preview的那个webengine的内存一直没释放。

**Comment by zhyma** [comment]
猜测是启用MathJax同时启用原地预览的时候出现的问题。

- 测试只使用一个文件，反复打开、切换阅读/编辑模式、关闭这个文件，这个文件除了markdown外只包含MathJax（大概有几十个公式）。

1. 如果不开启原地预览，不会出现额外的Qt Qtwebengineprocess。因此即使反复打开关闭这个文件都不会造成内存占用增大
此外如果只以阅读模式打开文件，不会出现额外的Qt Qtwebengineprocess。关闭后没有遗留。

2. 开启原地预览（右键打开编辑模式），生成一个额外的Qt Qtwebengineprocess，关闭所有标签后这个进程也不会消失。

    1. 如果只是反复切换阅读/编辑模式，内存占用不会增大。
    2. 如果反复关闭、打开这个文件（以编辑模式），内存占用会累积上升。
    3. 如果文件包含公式较少，前几次（大概七八次）打开会使得内存占用增加（从90M一直增加到120M左右，然后会掉回100M左右，一次增加4、5M），之后某一次会使得内存占用减少（打开文件的同时内存占用减小，关闭文件时内存占用不受影响）
    4. 如果文件包含公式较多，每次打开都会使得内存占用增加（几十M上百M），没有观察到有打开后内存突然减小的情况（或者可能减小的不明显导致没有观察到，比如增加100多M之后减小二三十M），这样反复之后内存会占用到几个G

- MathJax版本为3.0.1，配置为render as SVG，添加的是tex-svg.js。尝试选择tex-chtml.js并以CTHML渲染，对实验结果没有造成影响（原地预览开启时内存占用累积增大）

**Comment by tamlok** [comment]
大概确定了原因了，vnote会使用一个单独的webengine（就是一个chrome内核）来专门处理原地预览的，当出现第一个原地预览请求的时候，就会创建一个进程来处理。后面这个进程会一直保留，直到程序结束。想不到chrome的内存需要自己释放，我晚点看看。

**Comment by tamlok** [comment]
3.0里面去掉了这个专门用于预览的进程
