### ISSUE TITLE
手动往笔记目录添加文档，无法被识别到

### ISSUE THREAD

**Issue by nishisheipapa** [vnotex/vnote#1377]
OS Version (操作系统): Windows, Linux, macOS
windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
V2.9.1
Symptoms (表现):
我打开笔记文件夹，往里面放了个.md文档，重启软件，发现目录下没有这个.md文档
文件夹里是有的

How to Repro (如何复现):

**Comment by tamlok** [comment]
这是笔记软件，需要手动添加到json索引文件或者才文件菜单(从外部文件新建笔记)导入。

具体可以搜索已有的issue，老老老问题了。后面会改进

**Comment by tamlok** [comment]
vnote3已经支持显示外部文件。
