### ISSUE TITLE
希望兼容Typora编写的文件

### ISSUE THREAD

**Issue by nishisheipapa** [vnotex/vnote#1378]
OS Version (操作系统): Windows, Linux, macOS
windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
V2.9.1
Symptoms (表现):

使用Typora编写的.md文档，在Vnote里预览不会自动换行等
使用习惯是，在Typora 写笔记，整理完笔记后，放到Vnote目录下，日常预览，搜索，微修改等操作

How to Repro (如何复现):

**Comment by tamlok** [comment]
typora在markdown里面是异类呀~~

自动换行在markdown菜单里面的md-it选项打开即可。

**Comment by nishisheipapa** [comment]
行，谢谢感谢大佬回复
