### ISSUE TITLE
是否支持plantUml

### ISSUE THREAD

**Issue by crc1993** [vnotex/vnote#1379]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
想问下大佬，vnote是否支持通过编码生成uml图，类似于plantuml

**Comment by tamlok** [comment]
首页就写有支持PlantUML呀，帮助菜单的语法帮助里面有用法，设置里面有相关设置。
