### ISSUE TITLE
图片名称里嵌套链接后编辑模式下无法识别图片

### ISSUE THREAD

**Issue by ilolipopi** [vnotex/vnote#1380]
OS Version (操作系统): GNU/Linux (Debian 10)

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
图片名称里嵌套链接，编辑模式下无法识别图片（不显示图片，首次切换至阅读模式时还会询问是否删除未使用图片），但阅读模式正常

How to Repro (如何复现):
```
![[Github](https://github.com/)](_v_images/20200520224220699_606504707.png)
```
或者直接用VNote打开[test.zip](https://github.com/tamlok/vnote/files/4657584/test.zip)

**Comment by tamlok** [comment]
It seems that you could use:

```
[![homepage](http://commonmark.org/help/images/favicon.png)](http://commonmark.org "Redirect to homepage")
```

FYI: https://talk.commonmark.org/t/make-image-act-as-a-hyperlink/2805/3
