### ISSUE TITLE
使用Photoshop打开图片失败

### ISSUE THREAD

**Issue by Vandalizegod** [vnotex/vnote#1382]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
在vnote.ini文件中添加了如下选项：

[external_editors]
Photoshop=‪\"C:\\Program Files‪\\Adobe\\Adobe Photoshop CC 2015.5\\Photoshop.exe‪\" \"%0\"

之后重启并尝试用 其他打开方式-Photoshop 打开图片，然而Photoshop并没有启动。
然后我修改成了
Photoshop=‪C:\\\"Program Files\"‪\\Adobe\\\"Adobe Photoshop CC 2015.5\"\\Photoshop.exe‪ \"%0\"
依然无法启动Photoshop。

为了测试是否是我写得有问题，然后我在命令行里直接输入
"C:\Program Files‪\Adobe\Adobe Photoshop CC 2015.5\Photoshop.exe‪" “图片路径”
结果Photoshop正常打开了图片。

请问这是BUG还是我哪里设置不对呢？

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/82538113-cfef3880-9b7d-11ea-9d41-6eb9e39ca94f.png)

```
Photoshop=‪"\"C:\\Program Files\‪\Adobe\\Adobe Photoshop CC 2015.5\\Photoshop.exe\"‪ \"%0\"
```

**Comment by Vandalizegod** [comment]
不好意思，应该是上面自动将反斜杠弄掉了，我实际上写的是
> [external_editors]
> Photoshop=‪\"C:\\Program Files\‪\Adobe\\Adobe Photoshop CC 2015.5\\Photoshop.exe\"‪ \"%0\"
这种情况下打不开Photoshop

**Comment by Vandalizegod** [comment]
另外，我为了防止是自己电脑环境的问题，所以还测试了下面这条：

> SublimeText=\\"D:\\\\Program Files\\\\Sublime Text 3\\\\sublime_text.exe\\" \\"%0\\"

这个是没问题的，可以正常打开，确实是photoshop无法打开

**Comment by tamlok** [comment]
你把ps的exe弄一个快捷方式到一个简单的路径试试？比如c盘下面ps.exe之类的

**Comment by tamlok** [comment]
实在不行的话，你可以写一个cmd，vnote调用这个cmd，cmd调用ps

**Comment by Vandalizegod** [comment]
所有办法都不行……放弃了，其他程序都能正常打开，只有ps不行，无论用快捷键还是用脚本，明明在命令行里面都能正常调用，但一到Vnote里面就不行了……还是老老实实在文件夹里面打开算了
