### ISSUE TITLE
BUG：阅读模式下错误识别正文为标题的问题

### ISSUE THREAD

**Issue by Andy-AO** [vnotex/vnote#1386]
问题：阅读模式下错误识别正文为标题的
![](https://gitee.com/xrvu_zen/newPicBed/raw/master/thePic/20200522105005.png)
![](https://gitee.com/xrvu_zen/newPicBed/raw/master/thePic/20200522105013.png)
```MarkDown
- TEXT：
  - 
```
环境：OS Version (操作系统): Windows，2.9.1

复现：必现

**Comment by Oilj** [comment]
阅读模式和编辑模式识别不一致，阅读模式下识别为标题并显示在大纲中是错误的

**Comment by tamlok** [comment]
第二行的`-`需要删除或者输入点什么东西，因为markdown里面`-`单独一行是另一种标题的表示方法。

**Comment by Oilj** [comment]
> 第二行的 `-` 需要删除或者输入点什么东西，因为 markdown 里面 `-` 单独一行是另一种标题的表示方法。

1. 编辑界面和阅读界面不一致，如果是标题，应该都是标题才对。
2. Typora不会将-识别为标题，至少要--才行，当然我不懂规定，只是提一下。

**Comment by tamlok** [comment]
Typora的Markdown是很不标准的。

VNote编辑模式和阅读模式是使用两套不同的系统，所以只能尽量一致。

有关markdown渲染的，可以使用这个简单的demo看看效果：https://markdown-it.github.io/

这个是比较遵循标准的。
