### ISSUE TITLE
建议：通过Alt+数字快速切换标签页

### ISSUE THREAD

**Issue by Andy-AO** [vnotex/vnote#1389]
如题

**Comment by tamlok** [comment]
vnote里面是`ctrl-e 1`的方式，具体请参考帮助菜单的快捷键说明。

`Alt+x`一般是菜单的快捷键吧。

**Comment by Oilj** [comment]
> vnote 里面是 `ctrl-e 1` 的方式，具体请参考帮助菜单的快捷键说明。
> 
> `Alt+x` 一般是菜单的快捷键吧。

「Alt+字母」是菜单快捷键，菜单没有用「Alt+数字」当快捷键的，反而有很多用来切换便签页，「VSCode」和「SciTE4」等等，向「VSCode」学习，不过分。

**Comment by Oilj** [comment]
> vnote 里面是 `ctrl-e 1` 的方式，具体请参考帮助菜单的快捷键说明。
> 
> `Alt+x` 一般是菜单的快捷键吧。

「舰长模式」看到了，也是不错的方法，但是「Alt+数字」更方便，少了一个步骤，毕竟VSCode都在用，浪费这个快捷键总是不太好。

**Comment by tamlok** [comment]
ok，后面加上。

**Comment by tamlok** [comment]
hi，

目前vnote支持自定义快捷键，打开配置文件，修改对应按键即可。

谢谢！
