### ISSUE TITLE
建议：增加引用块功能

### ISSUE THREAD

**Issue by Andy-AO** [vnotex/vnote#1390]
如题，快捷键最好与Typora的Ctrl+Shift+Q保持一致

**Comment by tamlok** [comment]
目前可以右键菜单`粘贴为块引用`，后面会增加。

vnote一般不喜欢占用`ctrl+shfit`这种容易和其他软件冲突的快捷键。

**Comment by Oilj** [comment]
> 目前可以右键菜单 `粘贴为块引用`，后面会增加。
> 
> vnote 一般不喜欢占用 `ctrl+shfit` 这种容易和其他软件冲突的快捷键。

有点不是很懂，这个快捷键并不是全局的，为啥会冲突呢？
当然我有一个猜测，就是这种快捷键很容易被某些应用注册为全局，我安装软件的首件事情就是把这些全局快捷键全部给取消。

**Comment by tamlok** [comment]
VNote 3 has the button to insert quotes and you could specify a shortcut for it in the config file.
