### ISSUE TITLE
ubuntu 20.04 fcitx 5下无法切换输入法输入中文

### ISSUE THREAD

**Issue by freefcw** [vnotex/vnote#1391]
OS Version (操作系统):  ubuntu 20.04

VNote Version (Help - About VNote - Version: )(VNote版本):  版本: 2.9.1

Symptoms (表现):

使用fcitx 5, 安装有libpinyin，无法切换输入法，无法输入中文

How to Repro (如何复现):

正常使用

**Comment by tamlok** [comment]
Hi,

可以参考一下： https://github.com/tamlok/vnote/issues?q=is%3Aissue+is%3Aclosed+fcitx

另外，`fcitx-diagnose`看看有什么不正确的。

这是fcitx和qt5的已知问题，网上应该有一般性解决方案，和vnote没多大关系。

**Comment by freefcw** [comment]
> Hi,
> 
> 可以参考一下： https://github.com/tamlok/vnote/issues?q=is%3Aissue+is%3Aclosed+fcitx
> 
> 另外，`fcitx-diagnose`看看有什么不正确的。
> 
> 这是fcitx和qt5的已知问题，网上应该有一般性解决方案，和vnote没多大关系。


duplicate #657 

也是appimage版本

没有fcitx-diagnose，大概是因为装的fcitx5吧，目前不完全

**Comment by tamlok** [comment]
为啥没有fcitx-diagnose呢？要不先把这个解决了？

**Comment by freefcw** [comment]
Ubuntu的fcitx5包没有把这个打进去吧，连前端配置界面都没有
