### ISSUE TITLE
**Bold** text is not rendered as bold in editing mode

### ISSUE THREAD

**Issue by h4tr3d** [vnotex/vnote#1392]
OS Version (操作系统): Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
Text marked as bold (`**bold text**`) is not displayed as bold in text editing:
![image](https://user-images.githubusercontent.com/102082/82721311-74e54f00-9cff-11ea-8ab2-4e3d6b0a7036.png)

How to Repro (如何复现):
Just type: `**bold text**`

PS is it possible to create tasks in English to avoid possible duplications and simplify tasks search for non-Chinese guys?

**Comment by tamlok** [comment]
Hi,

It should work. Could you please paste the related lines of text here? I want to have a try.

In the issue template, I already encourage users to post issue in English first. But maybe lots of them are not good at English.

**Comment by Oilj** [comment]
In this case, it should be a basic operation to provide abnormal text

**Comment by tamlok** [comment]
Fine. It works fine for my notes. Once you give me the original text for repro, I will start to figure it out.

**Comment by h4tr3d** [comment]
> Fine. It works fine for my notes. Once you give me the original text for repro, I will start to figure it out.

I found, it is Font related issue. If I set up any Monospace font for editor, there is not Bold selection. If I change it to variable, all work as expected. Note, "Any Monospace font" means:
* Source Code Pro (exclude Source Code Pro Variable)
* Meslo
* Ubuntu Mono
* Pragmata Pro Mono
* Liberation Mono
* Inconsolata
* Fira Mono
* Droid Sans Mono
* Anka/Coder
* Andale Mono

Exclusion (work as expected):
* DejaVu Sans Mono
* Courier New
* Bitstream Vera Sans Mono
