### ISSUE TITLE
对文字添加链接的问题

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#1394]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1
Symptoms (表现):

选中某些文字后，按下ctrl-l，会弹出添加url链接的对话框，如果选中文字中没有斜线和点之类的字符，文字会被复制到对话框的文字部分，但是如果选中文字中有斜线和点的话，就会被复制到URL框中，怎么样才能让它一直复制到文字部分？

![Snipaste_2020-05-25_09-42-29](https://user-images.githubusercontent.com/50565266/82770730-22757100-9e6c-11ea-9fb2-7f4bb9fe78aa.png)

How to Repro (如何复现):

**Comment by tamlok** [comment]
新版两个都会复制
