### ISSUE TITLE
Windows 10 更新到version 2004后经常出现缺少调用OpenGL 2.0样的消息后崩溃

### ISSUE THREAD

**Issue by Drfoolin** [vnotex/vnote#1397]
OS Version (操作系统): 
Windows 10 version 2004 （preview）

VNote Version (Help - About VNote - Version: )
VNote版本 2.91

Symptoms (表现):
![image](https://user-images.githubusercontent.com/46316807/82809589-1ce05100-9e95-11ea-84af-dda76f534c6e.png)

How to Repro (如何复现):
基本上同时开启的编辑框超过5个，并且内容还比较多的时候，就会出现崩溃。
特别是在Markdown(Ctrl + T)操作的那一下，发生的可能性很高。
所以现在编辑的时候，都只敢同时开不超过3个编辑框。

**Comment by tamlok** [comment]
设置里面opengl换几个值然后重启试试

**Comment by tootal** [comment]
我也遇到了这个问题，把设置里的opengl值换成SoftwareOpenGL后解决了。
