### ISSUE TITLE
Support <u></u> UNDERLINE in Preview Mode

### ISSUE THREAD

**Issue by seaspeak** [vnotex/vnote#1401]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
No `<u></u>` in preview mode. `<u></u>` is a pair of html tag for underline.
Since italic style is not suitable for Asian characters, underline is an import alternative.

How to Repro (如何复现):
`<u>底線</u>` is better than *傾斜* .

**Comment by tamlok** [comment]
Hi,

`<u>` is supported in read mode. Do you mean the style in edit mode?

![image](https://user-images.githubusercontent.com/5763157/127581484-6ca9b738-e99a-42d2-9b72-efecfd9c45f4.png)

![image](https://user-images.githubusercontent.com/5763157/127581492-55b75b0d-481a-4b28-82fd-319e228c2596.png)

**Comment by seaspeak** [comment]
I think I meant Read/Preview mode. Strangely it works now.
As for in Edit mode, <mark>highlighted</mark> is highlighted, but <u></u> doesn't. It is a little inconsistent. But it is a matter of personal preference, some wants to keep it simple.
