### ISSUE TITLE
Bug: 导出为html时，如果图片文件名无后缀则无法嵌入图片

### ISSUE THREAD

**Issue by luo-chuan** [vnotex/vnote#1403]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
从csdn博客中，复制粘贴为markdown，粘贴的图片文件名不含后缀。然后将markdown导出为html并嵌入图片，导出的html无法显示图片。为图片文件名加上后缀（包括原图片文件名），则导出为html则可以嵌入图片并正常显示图片。

## 导出设置

![image](https://user-images.githubusercontent.com/33930736/83343258-64019280-a32a-11ea-8091-996896caa87e.png)

## 无图片文件名后缀时

![image](https://user-images.githubusercontent.com/33930736/83343235-21d85100-a32a-11ea-91f7-40b377d28acc.png)

![image](https://user-images.githubusercontent.com/33930736/83343401-6bc23680-a32c-11ea-9ab9-f5d325b0c30e.png)

## 有图片文件名后缀时

![image](https://user-images.githubusercontent.com/33930736/83343190-a24a8200-a329-11ea-9f73-b9ec01e1635c.png)

![image](https://user-images.githubusercontent.com/33930736/83343197-b9896f80-a329-11ea-9f48-fefc7b0d47b1.png)

**Comment by tamlok** [comment]
Should be fixed in VNote 3 now.
