### ISSUE TITLE
是否可以添加支持yml, sh 等配置脚本文件的编辑，这样在 markdown 里可以引用

### ISSUE THREAD

**Issue by owen2016** [vnotex/vnote#1407]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
现在虽然可以添加 yml,sh ，但是编辑功能没有，只能单独 打开VSCODE 编辑
，有时候想保存一些配置/脚本之类的; 目前都是 跳到外部程序打开。只是个小建议～
How to Repro (如何复现):

**Comment by tamlok** [comment]
vnote3已支持纯文本的编辑，包含语法高亮哦
