### ISSUE TITLE
加粗文字时标点符号带来的BUG

### ISSUE THREAD

**Issue by Vandalizegod** [vnotex/vnote#1409]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):
具体情况请看下面图片：
编辑模式：
![图片](https://user-images.githubusercontent.com/57993778/83588596-57787680-a584-11ea-883f-7c655b050239.png)

阅读模式：
![图片](https://user-images.githubusercontent.com/57993778/83588641-6bbc7380-a584-11ea-8af9-c4ac313485fe.png)

顺带一提，除了加粗，斜体和删除线也有同样问题

**Comment by tamlok** [comment]
老问题了，可以搜一下issue，md-it的问题

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/490
