### ISSUE TITLE
在$latex$等式中的"<"接英文字母会影响公式解析

### ISSUE THREAD

**Issue by zhyma** [vnotex/vnote#1410]
OS Version (操作系统): Windows,
VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
在用“$”和“$”之间插入公式时，如果有"<"并且其后有一个英文字母，会截断公式的解析，如果有可以作为HTML标签的，会优先解析为标签。如果是数字或者符号则不受影响

How to Repro (如何复现):
```
 1. $a=1$
 2. $t_2<s_1$，Firm 2不会进行生产，则$s_2\equiv 0$:

----

 1. $a=1$
 2. $t_2<1_1$，Firm 2不会进行生产，则$s_2\equiv 0$:

----

 1. $a=1$
 2. $t_2>s_1$，Firm 2不会进行生产，则$s_2\equiv 0$:

----

 1. $a=1$
 2. $t_2<s>_1$，Firm 2不会进行生产，则$s_2\equiv 0$:aa
 3. test</s>

----

 1. $a=1$
 2. $t_2< s_1$，Firm 2不会进行生产，则$s_2\equiv 0$:
```

![image](https://user-images.githubusercontent.com/2032749/83591652-6c262180-a526-11ea-80e1-f2b719d88bce.png)

**Comment by tamlok** [comment]
Hi,

是的！我现在才发现这个Bug，就像你所猜测的。已经修复了 (https://github.com/vnotex/vnote/commit/e55434965b5509220f8182fb8b31f9689e7bf4b6)。现在VNote 3.0的效果如下：

![image](https://user-images.githubusercontent.com/5763157/102231594-198fde00-3f29-11eb-888f-e92410005c25.png)

抱歉，6月份的时候正在紧张重构，回复晚了。谢谢反馈！欢迎继续关注！
