### ISSUE TITLE
可否支持文件夹严格按字母排序（包括名称是中文的文件夹）

### ISSUE THREAD

**Issue by zhajianting** [vnotex/vnote#1418]
OS Version (操作系统):  Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1
Symptoms (表现):
同时包含中文文件夹和英文文件夹，按名称排序时，中文名称的文件夹都在前面，英文名称的文件加都在后面，可否让他们都按照字母排序呢？

How to Repro (如何复现):

**Comment by tamlok** [comment]
文件夹树上面右键，排序。但这个是直接修改配置文件的排序，查看排序还没有。

**Comment by zhajianting** [comment]
> 文件夹树上面右键，排序。但这个是直接修改配置文件的排序，查看排序还没有。

抱歉，之前没发现排序文件夹的对话框里可以选择按名称排序，但是选择按名称排序之后的结果是中文文件夹都在前面，英文文件夹都在后面，然后这两部分都是按照名称排序的。

想问一下可不可以让他们完全按照名称排序，而不区分中英文呢？

**Comment by zhajianting** [comment]
考虑了一下，我提的这个功能好像有点鸡肋，现在的排序结果貌似也挺好，不改也行吧。

**Comment by tamlok** [comment]
windows的文件浏览器都是中英文排序分开的吧？
