### ISSUE TITLE
1. "shift+enter"换行；2.两个分割窗口时切换编辑/阅读模式

### ISSUE THREAD

**Issue by zhyma** [vnotex/vnote#1419]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

1. 在按住shift换行时，会在上一行（新的一行的上面）末尾多出两个半角空格。不知道是刻意设计的还是有什么别的原因？在编辑模式时会被高亮（浅灰色），显得比较碍眼。

2. 如果显示两个并列窗口（窗口A和窗口B），A处于阅读模式，将B从阅读模式切换到编辑模式时，A会自动跳转到文档开头。在使用时我希望用A的内容作为参考（始终处在阅读模式，滚动到某一行），B编辑新的笔记，会将B切到阅读模式检查排版/公式/流图效果。这个时候就导致每次预览B的内容我都需要重新把A调整到我要参考的那部分内容去。

How to Repro (如何复现):

**Comment by tamlok** [comment]
1. 末尾空格是md的基础语法，用于换行; 编辑菜单里面可以关闭。
2. 按理说不会发生这个问题，可能是bug

**Comment by zhyma** [comment]
对……你这么一说我想起来md确实有这么个规则，以前依赖别的各种编辑器写md辅助排版，这个忘记了
