### ISSUE TITLE
保存时偶尔程序会崩溃

### ISSUE THREAD

**Issue by CknightX** [vnotex/vnote#1424]
OS Version (操作系统): Windows10 1903
VNote Version : 2.8.2

Symptoms (表现):
写完保存时，偶尔程序会崩溃，只能强制结束进程。创建新笔记时也出现过一次。

How to Repro (如何复现):
概率性事件，无法正常复现

**Comment by tamlok** [comment]
Hi，

参考置顶issue解决一下opengl的问题。
