### ISSUE TITLE
某些情况下会导致*.vswp文件脱离管理而不能被自动删除

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#1426]
# OS Version (操作系统): Windows, Linux, macOS
* win10 1909
# VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
* vnote_v2.8
# Symptoms (表现):
* vnote有时候不能及时清理过时的*.vswp文件，导致会出现一些无法再清理的*.vswp垃圾文件，比如，文件改名之后，旧文件的*.vswp文件还在，这时候这个文件就会脱离vnote的管理而永远存在了，除非手动清理。
![Snipaste_2020-06-24_10-38-57](https://user-images.githubusercontent.com/40653617/85491930-f124c800-b606-11ea-8b17-39719d69cc4a.png)

# How to Repro (如何复现):

创建一个笔记文件然后改名

**Comment by tamlok** [comment]
vnote3已经修复了！我们选择重命名会强制关闭文件😂😂😂
