### ISSUE TITLE
properties代码块样式渲染异常

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#1431]
# OS Version (操作系统): Windows, Linux, macOS
win10
# VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
vnote_v2.8
# Symptoms (表现):
### 测试内容为
```properties
[client]
# 3. 设置mysql客户端默认字符集
default-character-set=utf8
 
[mysqld]
# 4. 设置3306端口
port=3306
# 5. 设置mysql的安装目录
basedir=D:\\software\\mysql-8.0.19-winx64
# 6. 设置 mysql数据库的数据的存放目录，MySQL 8+ 不需要以下配置，系统自己生成即可，否则有可能报错
datadir=${basedir}\\data
# 7. 允许最大连接数（官方默认是100）
max_connections=500
# 8. 服务端使用的字符集默认为8比特编码的latin1字符集
character-set-server=utf8
# 9. 创建新表时将使用的默认存储引擎
default-storage-engine=INNODB
# 这是干嘛的我也不知道，但是不加的话整改审批项目起不起来,如果是自己的私人数据库,这行可以不用
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
### 实际的显示效果却是错误的
![Snipaste_2020-06-28_18-24-06](https://user-images.githubusercontent.com/40653617/85944899-b4d9ca80-b96c-11ea-9b99-a01e1b80c05b.png)
![Snipaste_2020-06-28_18-24-51](https://user-images.githubusercontent.com/40653617/85944900-b60af780-b96c-11ea-8d1f-fc324fe8d57a.png)

# How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

根据 https://highlightjs.org/static/demo/ 显示，应该是支持`properties`高亮的，不过可能是VNote里面使用的版本过低，所以造成VNote里面不支持吧。后面会更新一下。
