### ISSUE TITLE
代码块开启显示行号时，多行注释无法正常高亮

### ISSUE THREAD

**Issue by wang92332** [vnotex/vnote#1439]
OS Version (操作系统): Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1
Symptoms (表现):
开启行号显示时：
![image](https://user-images.githubusercontent.com/22436549/86339310-042e3c80-bc86-11ea-90d2-7771bf4a06e3.png)

关闭行号显示时：
![image](https://user-images.githubusercontent.com/22436549/86339256-f24c9980-bc85-11ea-928b-c560a33f9f5e.png)

How to Repro (如何复现):开启“代码块显示行号”

**Comment by tamlok** [comment]
Should be fixed in 3.
