### ISSUE TITLE
PlantUML 插件是否支持相对路径导入？

### ISSUE THREAD

**Issue by FallenXtar** [vnotex/vnote#1444]
鉴于软件的Portable特性，或许应该考虑将可用的第三方组件以相对路径的形式进行导入。
尝试了PlantUML jar文件的相对路径，但并未成功，路径如下 （文件已放入 Vnote 根目录的 PlantUML文件夹下）
`.\PlantUML\plantuml.jar` 
测试未能成功

**Comment by tamlok** [comment]
Fixed a9005bef23e9970fd7d05d1b52566e6922e7199a
