### ISSUE TITLE
无法记录上次打开的页面

### ISSUE THREAD

**Issue by wenbingzhang** [vnotex/vnote#1445]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现): 无法记录上次打开的页面

How to Repro (如何复现):
dock右键退出无法记录上次打开的页面，菜单栏图表退出可以保存。

**Comment by tamlok** [comment]
Should be fixed in VNote 3.
