### ISSUE TITLE
No preview of equations in edit mode on Linux Fedora 30

### ISSUE THREAD

**Issue by vlisivka** [vnotex/vnote#1454]
OS Version (操作系统): Linux Fedora 30 x86_64

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1 8a549ea323c91d0e227f9c5c3038ec2d9d10c8ab , compiled from source

Symptoms (表现):

Math formulas preview is not working in edit mode. Math formulas are shown OK in read mode.

How to Repro (如何复现):

1. Start vnote.
2. Open a note in edit mode.
3. Enter an equation, e.g. $\sqrt{2}$.

Expected result: preview of formula.
Actual result: no preview. Text of formula highlighted in green.

Log contains "MathJax.texReset is not a function" error.

[vnote.log](https://github.com/tamlok/vnote/files/4907466/vnote.log)

**Comment by tamlok** [comment]
Are you using a customized MathJax? From 2.9.1, VNote uses MathJax 3.0.

**Comment by vlisivka** [comment]
I use default settings: https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.1/es5/tex-mml-chtml.js

**Comment by tamlok** [comment]
Could you rollback to 2.8.2 for now? I am busy working on VNoteX.
