### ISSUE TITLE
建议增加功能

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1455]
按下ctrl+v在原来的基础上加上插入Java代码或者其他代码（可自定义），就不用手动Ctrl+m添加标记了

**Comment by One010101** [comment]
第三行的取消可以去掉，如果用户想取消直接按ESC键就可以了

**Comment by Tridu33** [comment]
希望能够批量导入已有的md文件到笔记本中

**Comment by tamlok** [comment]
这个感觉不太通用，很难检测是不是java代码。暂时不会实现。后面片段会支持脚本，这个时候可以自定义。
