### ISSUE TITLE
Linux上鼠标悬挂，便选中对象

### ISSUE THREAD

**Issue by foreverhappylxc** [vnotex/vnote#1456]
OS Version (操作系统): Linux（ubuntu 20.04）

VNote Version (Help - About VNote - Version: )(VNote版本):2.9.1

Symptoms (表现):

鼠标扫过文本或者目录结构，便会是选中文本或者其目录；
鼠标点击对象之后，松开，移动便会拖动所选中的对象

How to Repro (如何复现):

可能环境导致的，之前很好的，现在突然出现的bug

**Comment by tamlok** [comment]
其他软件有这个问题吗？应该不是vnote的bug。会不会是qt的设置之类的。

**Comment by plus-zhang** [comment]
> 其他软件有这个问题吗？应该不是vnote的bug。会不会是qt的设置之类的。

我得也有这个现象，2.9.1
