### ISSUE TITLE
请问如何设置能在预览和编辑模式切换的时候可以让光标在原来位置

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1457]
每次编辑完ctrl+t后都会回到标题位置

**Comment by One010101** [comment]
如何让他不要跳到标题而是把焦点放在刚才编辑模式的编辑处

**Comment by tamlok** [comment]
这是个难题，目前不支持，后面会支持。

**Comment by One010101** [comment]
> 这是个难题，目前不支持，后面会支持。

可以借鉴一下typora，那个软件就可以，但是我还是喜欢用大佬的vnote ^_^

**Comment by zhyma** [comment]
有的时候ctrl+t切换得太快了（如果连按的话）光标会直接跳回文档最开头

**Comment by tamlok** [comment]
已经修复
