### ISSUE TITLE
bug提交, 带*号的latex公式不能正常显示：示例与解决方法

### ISSUE THREAD

**Issue by Superkeyv** [vnotex/vnote#1458]
OS Version (操作系统):  Linux,

VNote Version (Help - About VNote - Version: )(VNote版本): 
2.9.1

Symptoms (表现):
编写Latex公式如下
```
   p^*=d^*=L(x^*,\alpha^*,\beta^*)
```
在预览界面无法正常转换成公式

原因应该在于，程序错误解析`*`。公式修改为
```
   p^\*=d^\*=L(x^\*,\alpha^\*,\beta^\*)
```
此时预览正常。

建议修改此bug

How to Repro (如何复现):

**Comment by tamlok** [comment]
For 2.8.1, it works fine.

![image](https://user-images.githubusercontent.com/5763157/87736562-05757280-c80b-11ea-832b-7381ff4702f3.png)

I am not sure if it is caused by MathJax v3 which is used in 2.9.1.

**Comment by zhyma** [comment]
2.9.1，windows版本，MathJax3.0.1测试没有问题

**Comment by Superkeyv** [comment]
> For 2.8.1, it works fine.
> 
> ![image](https://user-images.githubusercontent.com/5763157/87736562-05757280-c80b-11ea-832b-7381ff4702f3.png)
> 
> I am not sure if it is caused by MathJax v3 which is used in 2.9.1.

可能是linux系统的问题，我同样测试了win下2.9.1版本的程序，没有出现这个问题

**Comment by tamlok** [comment]
@Superkeyv Which linux distribution you are using?

**Comment by Superkeyv** [comment]
> @Superkeyv Which linux distribution you are using?

I'm using ArchLinux，
Linux kernel = 5.4.42 , 
qt5-webengine, qt5-svg = 5.15.0

**Comment by tamlok** [comment]
Are you using AppImage download from GitHub? If not, please try it out.

**Comment by Superkeyv** [comment]
@tamlok 问题已经解决了。我估计是程序冲突，不是vnote的bug。
之前的错误已经无法复现，应该是属于个例
