### ISSUE TITLE
vnote 各级标题区分不明显

### ISSUE THREAD

**Issue by bfbz** [vnotex/vnote#1459]
各级标题，如二级标题和三级标题看着并不明显，希望优化下。

**Comment by tamlok** [comment]
可以自定义样式修改标题字号大小，具体参考文档

**Comment by bfbz** [comment]
> 可以自定义样式修改标题字号大小，具体参考文档
我知道，我就是提下建议，我已经通过修改样式解决。

**Comment by tamlok** [comment]
可以分享一下修改后的样式，我看后面默认能不能改进
