### ISSUE TITLE
图片处理及软件界面

### ISSUE THREAD

**Issue by unihon** [vnotex/vnote#1460]
OS Version (操作系统): Linux

VNote Version (VNote版本): 2.9.1

---

Symptoms (表现):

# 图片处理

## 需求

- 图片插入时，选择转换的形式，希望有切换为HTML语法的选项
- 图片文件夹希望有相关的**变量**，支持以文章名等为图片存放的文件夹

## 功能优化

- 希望有更多图片大小定义的语法选择，目前个人感觉`=123x`的后缀定义方式不太通用（这也是为什么希望可以转换HTML语法）

- 笔记拖到到不同的文件夹时，笔记相关的图片虽然可以复制到目标文件夹，但原文件夹的图片并没有被删除。
如多次移动，图片文件夹则会生成重复的图片文件

# 软件界面

软件界面有4K屏下，显示过小。目前GUI的配置中只能更改工具图标的大小，希望有相关的配置缩放界面。

![image](https://user-images.githubusercontent.com/42078581/87867258-c2a7cc00-c9bd-11ea-874b-8301db61acf6.png)

How to Repro (如何复现):

##

**Comment by unihon** [comment]
软件界面问题

可在主题配置文件`*.qss`中加入如下样式设置全局的默认字体大小。
``` css
*{
   font-size: 12pt;
}
```

**Comment by lovelock** [comment]
可能是你用的发行版对高分屏的支持不好的原因吧，黑苹果用4k屏还挺正常的

**Comment by lovelock** [comment]
我提一个我遇到的问题，图片粘贴进去之后就变糊了，找不到合适的不糊的大小。这个还挺重要的
