### ISSUE TITLE
如何把灰色的背景修改成护眼色，是css吗，配置文件哪个位置？

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1468]
如何把灰色的背景修改成护眼色，是css吗，配置文件哪个位置？

**Comment by tamlok** [comment]
Add a color by modifying `vnote.ini` https://github.com/tamlok/vnote/blob/8a549ea323c91d0e227f9c5c3038ec2d9d10c8ab/src/resources/vnote.ini#L230

Then you could choose your color in the `Markdown` menu.

**Comment by succ-secret** [comment]
字体颜色怎么设置，找不到

**Comment by tamlok** [comment]
设置里面，外观，主题，打开路径，里面的css文件是对应阅读模式，theme文件是对应编辑模式。

![image](https://user-images.githubusercontent.com/5763157/115718798-0fd22780-a3ae-11eb-8712-1571a7a9f78b.png)
