### ISSUE TITLE
vnote 上传图床时是否可以自动创建文件夹

### ISSUE THREAD

**Issue by yisuixinq** [vnotex/vnote#1469]
OS Version (操作系统): Windows,

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
设置好github做图床时，点击上传图片会将所有图片上传在同一个目录，是否可以设置自动按照文件名在github仓库中创建目录，这样不容易导致混乱

**Comment by tamlok** [comment]
Fixed.
