### ISSUE TITLE
请问原地预览如何开启或关闭？

### ISSUE THREAD

**Issue by huilin-hub** [vnotex/vnote#1470]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1
Symptoms (表现):

我近期在使用vnote记录数据公式，深刻体会到 原地预览 的优势，非常喜欢。

但不知道是我自己动了什么设置，还是其他什么原因，现在我的公式没有原地预览了。（已经写了的公式是有的，新复制粘贴的公式没有），我新建md文件，手写公式，仍然没有原地预览。

请问原地预览，是否有设置开关？我没有找到。谢谢

How to Repro (如何复现):

**Comment by tamlok** [comment]
markdown菜单下面的图片预览？

**Comment by huilin-hub** [comment]
![image](https://user-images.githubusercontent.com/12319182/88475742-50a72800-cf65-11ea-95d8-a34282f8e449.png)

就是比如说，这样的公式，以前在编辑状态时，如果公式正确，会直接显示公式预览结果。现在是没有了。

**Comment by huilin-hub** [comment]
![image](https://user-images.githubusercontent.com/12319182/88475812-d4611480-cf65-11ea-9d25-09697541c30b.png)

markdown菜单下面，“原地预览”是勾选状态。

**Comment by tamlok** [comment]
可能是网络问题，试试本地mathjax吧

**Comment by zhyma** [comment]
希望能在设置的markdown里添加一个mathjax的测试按钮

**Comment by huilin-hub** [comment]
您好，我想应该不是Mathjax的问题。因为它在阅读模式，是可以正常显示公式的，所以markdown里的公式解析是没问题的。只是在编辑模式中，无法原地预览而已。 （图片的原地预览是正常的，就是公式的原地预览没有了）

因为咱们vnote，并不是双屏，所以这个原地预览对用户体验很重要。目前不知何原因，这个原地预览不见了，（我不记得是否由于我更新版本导致的），我只能暂时用第三方md编辑器来修改内容了。

**Comment by tamlok** [comment]
可以试试回退版本
