### ISSUE TITLE
编辑模式代码块中bash语言空行后#号显示小BUG

### ISSUE THREAD

**Issue by yisuixinq** [vnotex/vnote#1471]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
bash 语言，空一行后添加注释，注释行像标题一样加粗了，仅在编辑模式下有这个问题，阅读模式正常。
![Snipaste_2020-07-27_22-16-18](https://user-images.githubusercontent.com/40953718/88568322-64d54d00-d06b-11ea-89c5-047d95eceee6.png)

**Comment by tamlok** [comment]
代码块前多加一行
