### ISSUE TITLE
`/**/`这个标记在idea中是多行注释，在vnote中不支持，希望可以优化一下

### ISSUE THREAD

**Issue by One010101** [vnotex/vnote#1472]
`/**/`这个标记在idea中是多行注释，在vnote中不支持，希望可以优化一下

**Comment by tamlok** [comment]
注释markdown吗？

**Comment by One010101** [comment]
> 注释markdown吗？

是的，vnote可以单行注释`//`，多行注释`/**/`就不行了

**Comment by One010101** [comment]
![2020 07 28_11时25分15秒](https://user-images.githubusercontent.com/44254059/88615765-279da900-d0c5-11ea-9ea9-330bd2fd9a9e.png)

**Comment by tamlok** [comment]
你指的是在java代码块里面的多行注释，对吧？这个高亮问题，可能是上游highlight.js造成的。
