### ISSUE TITLE
为什么阅读状态下图片消失，而编辑状态下图片时存在的

### ISSUE THREAD

**Issue by liufeibio** [vnotex/vnote#1473]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2
Symptoms (表现):
我的Vnote文档在编辑状态下可以看到图片，当导出为html或者pdf时，图片消失，阅读状态下图片也不见了

How to Repro (如何复现):

**Comment by tamlok** [comment]
图片是自己写的路径吧？url里面得用/，空格得%20替代。vnote插入图片的时候会自动处理。

**Comment by liufeibio** [comment]
不是写的路径，是直接粘贴图片时vnote自动处理的

**Comment by tamlok** [comment]
直接贴原文看看，是不是在div里面？

**Comment by liufeibio** [comment]
所有的图片都可以在_v_images这个文件夹里找到的，但导出或者以阅读模式查看很多图片都不显示，只有很小一部分图片可以显示

**Comment by tamlok** [comment]
直接贴原文看看?

**Comment by liufeibio** [comment]
今天有学员问 MCScanX 安装问题，我试了下，果然有错误。
genek@GenekServer:~/software/MCScanX$ make
g++ struct.cc mcscan.cc read_data.cc out_utils.cc dagchainer.cc msa.cc permutation.cc -o MCScanX
msa.cc: In function ‘void msa_main(const char*)’:
msa.cc:289:22: error: ‘chdir’ was not declared in this scope
     if (chdir(html_fn)<0)
                      ^
makefile:2: recipe for target 'mcscanx' failed
make: *** [mcscanx] Error 1
这个错误的原因是，MCScanX 不支持64位系统。如果要在 64位上运行，需要修改下源代码。
只需要给 msa.h, dissect_multiple_alignment.h, and detect_collinear_tandem_arrays.h 这三个文件 前面添加
#include <unistd.h>
出现以下这个错误也是用这个方法解决的：
![image](https://user-images.githubusercontent.com/26890133/90256642-9ee47400-de0b-11ea-9b1e-a14f6e4ea073.png)
Make出现错误

g++ struct.cc mcscan.cc read_data.cc out_utils.cc dagchainer.cc msa.cc permutation.cc -o MCScanX
make: g++: Command not found
make: *** [makefile:2: mcscanx] Error 127

这是阅读模式下的，但我书写的时候并不是插入代码模式，阅读模式下怎么就变成了代码区域
![image](https://user-images.githubusercontent.com/26890133/90256866-f71b7600-de0b-11ea-830d-a0cdaad9bcae.png)

**Comment by tamlok** [comment]
hi，

md里面，像那段粘贴log输出的一大段，最好都放进代码块里面，因为各种特殊字符，很容易扰乱md的语法。

格式化后，图片应该就出来了。

**Comment by liufeibio** [comment]
好的，谢谢
