### ISSUE TITLE
外部编辑器打开的功能的改进建议

### ISSUE THREAD

**Issue by DaiJixiang** [vnotex/vnote#1476]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9

Symptoms (表现):目前大纲的结构已经很好了，但是使用外部编辑器（我使用的是Typora）编辑内部文档的时候，总是会弹出提醒，xxx文件已被修改，是否更新，我想说的是，我既然使用外部编辑器，其实这个外部编辑器的功能就等同于vnote里面的编辑器的功能，只不过实现的形式不同，所以，直接更新就可以了。今天也在群里面反映了这个问题，有人说可能会导致文件被篡改，我想建议一下，实在不行，给用户一个选择也是可以的，比如，使用外部编辑器的时候是否直接更新不询问，需要的用户就可以点击确定。之前使用的是joplin，他的这个外部编辑打开就挺好的，自动更新，但是他的图片处理和文件大纲不行。我只是提一下这个比较好的功能，希望开发者可以采纳。

How to Repro (如何复现):如上

**Comment by tamlok** [comment]
已支持
