### ISSUE TITLE
阅读模式不显示

### ISSUE THREAD

**Issue by lesuel** [vnotex/vnote#1483]
OS Version (操作系统): Windows10_2004

VNote Version (Help - About VNote - Version: )(VNote版本): 2.91

Symptoms (表现):
编辑完切换到阅读模式不显示，需要重启软件才可以阅读
![111](https://user-images.githubusercontent.com/23452687/89756968-8710a580-db16-11ea-8470-1244307d72ce.gif)

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

Check the pinned issue: https://github.com/tamlok/vnote/issues/853
