### ISSUE TITLE
功能需求：再次打开定位到最后一次阅读位置

### ISSUE THREAD

**Issue by uname2p** [vnotex/vnote#1486]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
【功能】：希望再次打开软件（文档）的时候能够自动恢复到上次阅读（编辑）的［大概］位置。
【场景】：我用Markdown做读书笔记，可能一个文档八千多行，在补充笔记内容的时候每次都要拉滚动条到最后面；日后温习文档的时候内容太多一次也看不完，而且有时候不是连续的天天都看，中间会间隔一两天，这样容易忘记看到哪个具体位置了。
【实现】：希望在关闭文档的时候记录一下文档的位置，如果可以最好能记录到具体行（【比如】阅读器区域最顶部当前显示到了哪一行），如果暂时不能到具体行，记录到大概的标题位置也可以。

最后，感谢您开发出这个精致的软件，让大众都收益颇丰。

**Comment by tamlok** [comment]
Fixed in VNote 3.0.
