### ISSUE TITLE
auto delete swap file

### ISSUE THREAD

**Issue by wutianjun5858** [vnotex/vnote#1489]
OS Version (操作系统): linux
VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现): 在编辑模式下修改后, 切换到阅读模式, 无法自动删除交换文件, 我觉得是否可以自动删除切换文件

How to Repro (如何复现):

**Comment by tamlok** [comment]
关闭文件后就会删除了吧？

**Comment by wutianjun5858** [comment]
我觉得在保存之后就可以自动删除, 虽然按照vim的做法确实是关闭文件的时候才能删除swap文件, 但是您这个vnote更多的是一种文件管理器, 写完保存之后, 就可以不需要swap文件, 进入阅读模式已经自动保存了, 这样对文件管理更有效

**Comment by tamlok** [comment]
频繁删除新建文件和频繁追加文件内容，不知道底层上会不会有区别。暂时先不改了。
