### ISSUE TITLE
Ctrl+T切换光标位置不同步

### ISSUE THREAD

**Issue by caixc-code** [vnotex/vnote#1491]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
在编辑模式下，按Ctrl+T可以跳到当前小节下预览，但再次Ctrl+T回到编辑模式时，光标总会跳到文档开头第一行，而不是跳到编辑位置。

建议，增加分栏界面实时预览，其他markdown编辑器转过来的新人用着不适应，建议增加该功能，提高入坑新人软件适应度

**Comment by tamlok** [comment]
fixed

**Comment by 1078249029** [comment]
最新版本依然出现了这个问题，只要连续切换3次视图就能稳定触发bug

OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 3.17.0
