### ISSUE TITLE
新建文章时粘贴标题文字的问题

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#1495]
OS Version (操作系统): Windows10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

新建文章时，需要填写文章标题，如果是从网上摘抄文章的时候，我通常喜欢把标题复制一下，然后粘贴到文章标题中，此时有个问题，如果粘贴的文本中有非法字符，比如斜杠`/`之类的，就不能粘贴，我想粘贴后修改一下都不行。希望修改一下，在保存的时候再检查这个标题字符串是否有效。

 Repro (如何复现):

1. 复制一个带`/`的字符串
2. 新建文章，把这个字符串粘贴到文章的标题中，应该是不能粘贴的

**Comment by tamlok** [comment]
下个版本会修复
