### ISSUE TITLE
【功能建议】 希望支持分屏预览功能🤣，不知道是不是只有我一个受不了原地预览🤦‍♂️

### ISSUE THREAD

**Issue by 17637462979** [vnotex/vnote#1496]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
已支持双边预览： https://github.com/vnotex/vnote/releases/tag/v3.10.0
