### ISSUE TITLE
双屏中有一个屏是高分屏时的缩放适配问题

### ISSUE THREAD

**Issue by zhyma** [vnotex/vnote#1499]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1
Symptoms (表现):
![WeChat Image_20200825102105](https://user-images.githubusercontent.com/2032749/91186368-f660ca80-e6bc-11ea-99a3-1eb629024ff1.jpg)

笔记本为高分屏（4k），外接屏幕为普屏（1080），外屏作为扩展桌面。当把vnote从笔记本屏幕拖到外接屏幕时，所有图标还有笔记内容的字体都会变得很大，其它字体（如菜单、笔记列表、片段列表、搜索）都正常。高分屏的默认缩放是250%，在高分屏上显示一切正常。

How to Repro (如何复现):
两个显示器分辨率不一样，其中一个设置了缩放

**Comment by tamlok** [comment]
qt通病，你想在那个屏幕用，就得在那个屏幕上启动。
