### ISSUE TITLE
最新版的vnote似乎不能使用输入法 

### ISSUE THREAD

**Issue by Orochi4268** [vnotex/vnote#1505]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by tamlok** [comment]
大哥，稍微有用的信息都没有呀：

![image](https://user-images.githubusercontent.com/5763157/92345563-6c712280-f0fc-11ea-8fcb-db30425696d4.png)

**Comment by Orochi4268** [comment]
> 大哥，稍微有用的信息都没有呀：
> 
> ![image](https://user-images.githubusercontent.com/5763157/92345563-6c712280-f0fc-11ea-8fcb-db30425696d4.png)

emmm就是我下载了最新的版本后是进入了使用搜索和新建文件都发现fcitx没有正常运行 更别提输入法了 但是我一旦切出其他位置就能正常使用输入法 这是我的信息 Linux mizuchi 5.7.0-kali3-amd64 #1 SMP Debian 5.7.17-1kali1 (2020-08-26) x86_64 GNU/Linux

**Comment by ihipop** [comment]
同样的问题,最新版本的appimage,使用的是fcitx4
估计那个fcitx支持vnote作者又忘记加上了

**Comment by ihipop** [comment]
这个问题可以甩给用户自己编译解决,也可以作者在打包的时候解决.

**Comment by roachsinai** [comment]
创建notebook的时候fcitx5同样无法切换到中文。

**Comment by zhyma** [comment]
OS Version (操作系统): Linux (Ubuntu 18.04)

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现): fcitx 4.2.96，谷歌拼音，无法在Vnote中切出中文

How to Repro (如何复现):

**Comment by yeahooii** [comment]
OS Version (操作系统): Linux (Ubuntu 18.04)

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现): fcitx 4.2.96，谷歌拼音，无法在Vnote中切出中文

How to Repro (如何复现):./VNote-2.10-x86_64.AppImage  --appimage-extract
 mv squashfs-root/ squashfs-root2.10
 ./VNote-2.9.1-x86_64.AppImage  --appimage-extract
 cp squashfs-root/usr/lib/libFcitxQt5DBusAddons.so.1 squashfs-root2.10/usr/lib/libFcitxQt5DBusAddons.so.1
 cp squashfs-root/usr/lib/libxkbcommon.so.0 squashfs-root2.10/usr/lib/libxkbcommon.so.0
 cp squashfs-root/usr/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so squashfs-root2.10/usr/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so

 wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
 chmod a+x appimagetool-x86_64.AppImage
 ./appimagetool-x86_64.AppImage squashfs-root2.10/
 rm -rf squashfs-root
 rm -rf squashfs-root2.10
 rm -f appimagetool-x86_64.AppImage

 ./VNote-x86_64.AppImage
