### ISSUE TITLE
2.8以后的版本公式渲染问题

### ISSUE THREAD

**Issue by hardjet** [vnotex/vnote#1506]
OS Version (操作系统):  Linux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9,2.10
Symptoms (表现):2.8以后的版本部分公式公式渲染不正常：
![image](https://user-images.githubusercontent.com/8086399/92435437-e2e15380-f1d4-11ea-9297-b994bb768b15.png)

How to Repro (如何复现):
$$
\begin{aligned}
\mathbf{F}(\mathbf{x})&=\sum_{k\in \mathcal{C}} \underbrace{\mathbf{e}_k(\mathbf{x}_k,\mathbf{z}_k)^\top \Omega_k\mathbf{e}_k(\mathbf{x}_k,\mathbf{z}_k)}_{\mathbf{F}_k}  \\
\mathbf{x}^* &= \underset{\mathbf{x}}{\operatorname{argmin}}\mathbf{F}(\mathbf{x})
\end{aligned} \tag{1}
$$

**Comment by zhyma** [comment]
![image](https://user-images.githubusercontent.com/2032749/93042669-a91dac00-f61d-11ea-898b-5324218d97f9.png)

配置：windows 10, Vnote 2.9.1
MathJax配置为3.0.1，本地，tex-svg.js，公式上点右键 math setting-> math renderer->SVG

**Comment by tamlok** [comment]
这个的预期效果是不是这样的：

![image](https://user-images.githubusercontent.com/5763157/102231326-d0d82500-3f28-11eb-9edb-5f2b1c611cb2.png)

需要`\\`来换行，转义一下。
