### ISSUE TITLE
UI customization help

### ISSUE THREAD

**Issue by randomgeek78** [vnotex/vnote#1508]
OS Version (Linux)

VNote Version (2.9.1)

Symptoms (UI tweaks):
I am new to VNote. I am a bit finicky about the UI and workflow and want to tweak things a bit. Overall, I really love the customization provided and I am sure there is a way to get what I want. I need your help.

Here is some summary info to set context- 
Theme: v_detorte
Mode: Vi
Theme modifications:
Copied ~/.config/vnote/themes/v_detorte/v_detorte.mdhl to ~/.config/vnote/styles/v_detorte.mdhl
Modified: vim-insert-background to match vim-normal-background (363636 -> 545454)
Copied ~/.config/vnote/themes/v_detorte/v_detorte.qss and ~/.config/vnote/themes/v_detorte/v_detorte.css to ~/.config/vnote/styles/ without changes
Changed vnote.init
[global]
css_style=v_detorte
editor_style=v_detorte

Need help with:
I find it annoying that the height of the cursor and height of the highlighted background gets reduced when in insert mode compared to normal mode. For example, see the animation below-

![vnote](https://user-images.githubusercontent.com/66195352/92693480-8f692580-f2fa-11ea-9b08-74e5c87f9aa1.gif)

I would like to have a uniform height irrespective of normal or insert mode. 

Given the level of customization, I am sure there is something that can be tweaked. Otherwise, I might have to go read the code :-(. Thanks!

**Comment by tamlok** [comment]
Hi,

Code change is needed here. Will refine it in next version.

Thanks!

**Comment by randomgeek78** [comment]
Thank you!

**Comment by tamlok** [comment]
Fixed in VNote 3.
