### ISSUE TITLE
VNote-2.10-x86_64.AppImage不能使用输入法

### ISSUE THREAD

**Issue by Aerotic** [vnotex/vnote#1509]
OS Version (操作系统): Ubuntu 18.04.4
VNote Version (Help - About VNote - Version: )(VNote版本): VNote-2.10-x86_64.AppImage

Symptoms (表现): 无法使用中文输入法输入（ibus-Sunpinyin），输入拼音直接显示英文字母

How to Repro (如何复现):

**Comment by FightingSu** [comment]
Same issue encountered here, my OS Version is Deepin 20

**Comment by tamlok** [comment]
please rollback to 2.9 for now

**Comment by Aerotic** [comment]
> please rollback to 2.9 for now

2.9 doesn't work, too.

**Comment by tamlok** [comment]
ibus应该没啥问题的呀，搜一下qt5和ibus的处理方法吧。或者其他qt5程序能用ibus不？感觉是少了某个库文件。

**Comment by chinggg** [comment]
OS Version (操作系统): Manjaro with KDE 5.7.0, Kernel 5.7.19
VNote Version (Help - About VNote - Version: )(VNote版本): (aur)vnote-bin 2.10
Symptoms (表现): 无法使用fcitx5输入
How to Repro (如何复现):按shift或ctrl+space 切换

本机Qt版本5.15.1，已经阅读过有关qt与fcitx冲突的很多issue，经过fcitx5-diagnose检测我已有libfcitx5platforminputcontextplugin.so在`/usr/lib/qt/plugins/platforminputcontexts`目录下，网上说应将其复制到Qt的“安装目录”下，但我用`qmake -query`也没找到这种路径，尝试直接将libfcitx5platforminputcontextplugin.so复制到`{VNOTE安装目录}/usr/plugins/platforminputcontexts`里，更改文件权限为644与原有文件相同，仍然不起作用。猜想因为VNote所使用的Qt版本停留在5.9.7而本机Qt版本过高导致无法使用。尝试按照[知乎上的一篇文章](https://zhuanlan.zhihu.com/p/150387095)手动编译

**Comment by tamlok** [comment]
@chinggg 先别折腾了，vnotex12月就发布了。
或者参考： https://github.com/vnotex/vnote/issues/1505#issuecomment-726603598

**Comment by pysense** [comment]
终于看到要发布的消息了

Le Tan <notifications@github.com>于2020年11月19日 周四14:59写道：
