### ISSUE TITLE
代码片段功能建议

### ISSUE THREAD

**Issue by xzlabs** [vnotex/vnote#1510]
OS Version (操作系统): Windows7X64

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现):

How to Repro (如何复现):

目前代码片段只能设置26个英文字母的快捷键，通过CTRL+E+S+快捷键输入片段，按下CTRL+E+S后，没有设置快捷键的片段不会在编辑器中弹窗提示。

这样片段多了快捷键不够用，而且快捷键也不能很好适配片段的功能含义，不方便记忆。

建议按下CTRL+E+S后，弹窗提示按照片段名排序提示，比如CTRL+E+S+A后，列出以A开头的片段名，这样方便记忆和选择。不知是否可行。

**Comment by tamlok** [comment]
Hi,

这样也可以,但这样子的话就有不确定性了,即目前我可以盲打一个快捷键后就直接插入我想要的片段,但如果是按照名字来列出来的话,那就有一个确认选择的过程了.

不过后面可以结合起来，一个是可以直接输入数字来选择某个片段，一个是搜索名字，这样的话就要求片段名字不能包含数字。

**Comment by tamlok** [comment]
已经支持按名字搜索
