### ISSUE TITLE
由托盘图标，打开软件，显示的问题

### ISSUE THREAD

**Issue by wuqiyin** [vnotex/vnote#1511]
OS Version (操作系统): Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,

Symptoms (表现):

![image](https://user-images.githubusercontent.com/26370779/93034545-f07f5900-f66c-11ea-9434-844e9ccec4a4.png)

How to Repro (如何复现):
先点击右上角x来关闭软件，然后从托盘打开软件，电脑有打开200%的缩放比

**Comment by tamlok** [comment]
https://github.com/tamlok/vnote/issues/853
