### ISSUE TITLE
Windows build fails with Qt BUG which caused by MS update VC to conform C++ standard

### ISSUE THREAD

**Issue by miurahr** [vnotex/vnote#1512]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 
   github master after 8f62f9902d5a038d23b061d02772f9e20a328d80

Symptoms (表现):

  Github actions failed in WIndows builds, it is because Microsoft changes their C++ STL implementation, to conform with ISO Standard(*1 see P0883), then it cause a Qt BUG.(*2) The BUG is fixed on 5.12.9 5.14.2 5.15.0, but not 5.9.

- (*1) https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019
- (*2) https://bugreports.qt.io/browse/QTBUG-81727

This problem seems affect also to qmake builds, when you update your MSVC version.

**Comment by tamlok** [comment]
Got it! I will release VNote 3.0 within next two months, which will use Qt 5.15. So let's just let it be for now.

Thank you!
