### ISSUE TITLE
启动后自动打开文档的问题

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#1515]
OS Version (操作系统): Windows 10
VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

有一次vnote没反应，然后把vnote强制退出了。之后每次重启后都会自动打开指定几个文档，即使上次关闭vnote时这几个文档没打开，而且发现现在vnote启动的速度慢了很多，加载文档也慢了很多，不知道怎么解决。

How to Repro (如何复现):

**Comment by tamlok** [comment]
每次关机前请手动退出vnote(文件菜单，退出)，或者干脆设置里面把自动打开上次未关闭页面去掉。

变慢可以看一下置顶issue，看看是否opengl的问题。

**Comment by jackydi** [comment]
> 每次关机前请手动退出vnote(文件菜单，退出)，或者干脆设置里面把自动打开上次未关闭页面去掉。
> 
> 变慢可以看一下置顶issue，看看是否opengl的问题。

好的多谢，我先看看
