### ISSUE TITLE
请问如何设置默认的行分隔符？

### ISSUE THREAD

**Issue by aomsweet** [vnotex/vnote#1516]
OS Version (操作系统): Windows, Linux, macOS

Windows 10 64bit build 2004

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

2.10

Symptoms (表现):

当新建笔记文档时，默认的行分隔符为windows风格的CR， 请问可以设置默认行风格符为unix风格LR吗？

How to Repro (如何复现):

**Comment by tamlok** [comment]
这个是qt默认处理的，应该是在linux下面是`LR`。

**Comment by aomsweet** [comment]
噢，原来如此。 不知道有没有方法解决噢， vscode和idea有自定义行分隔符的功能。

**Comment by aomsweet** [comment]
噢，原来如此。 不知道有没有方法解决噢？
我通常在idea和vscode中将新建文档的行分隔符设置成LR，以兼容不同操作系统。

感谢。

**Comment by tamlok** [comment]
后面我看一下

**Comment by tamlok** [comment]
Fixed.
