### ISSUE TITLE
左下「笔记」窗格 等列表最后一行文字显示不全

### ISSUE THREAD

**Issue by SYKoh** [vnotex/vnote#1517]
Version (操作系统):   macOS Catalina 10.15.6

VNote Version (VNote版本):    Github release VNote-2.10-x64.dmg

Symptoms (表现):  
在「笔记」窗格、「排序文件夹」窗格的最后一行中文显示不全，（未测试英文显示情况）
&nbsp;
&nbsp;

![image](https://user-images.githubusercontent.com/41710233/94014349-fc41ec80-fddd-11ea-81e8-29c61be94d82.png)

&nbsp;
![image](https://user-images.githubusercontent.com/41710233/94014761-8f7b2200-fdde-11ea-8506-40d356bb1772.png)

How to Repro (如何复现):
似乎在上个版本（2.9.1）就已出现此问题，无论何时都会出现

**Comment by tamlok** [comment]
Hi,

搜一下issue即可：

https://github.com/tamlok/vnote/search?q=mac+%E6%BB%9A%E5%8A%A8%E6%9D%A1&type=issues

**Comment by SYKoh** [comment]
谢谢！辛苦了！

**Comment by SYKoh** [comment]
谢谢！辛苦了！
