### ISSUE TITLE
Req, compile against ARM for Raspberry Pi?

### ISSUE THREAD

**Issue by BoVandenberg** [vnotex/vnote#1519]
Seems like a powerful, efficient, utility. Could it be compiled for Raspbian OS and run on the Raspberry Pi?

**Comment by tamlok** [comment]
it depends on whether qt 5.9 could be found on that platform.

**Comment by BoVandenberg** [comment]
There are certainly qt 5 versions available. Is qt 5.12 more recent than qt 5.9?

https://www.tal.org/tutorials/building-qt-512-raspberry-pi

The issue is that Arm is not an x86 instuction set...

**Comment by BoVandenberg** [comment]
QT ON THE RASPBERRY PI 4
July 2020

https://www.interelectronix.com/qt-on-the-raspberry-pi-4.html

**Comment by tamlok** [comment]
you could try it out. it would not require much code change i believe.
