### ISSUE TITLE
This AppImage does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [vnotex/vnote#152]
This AppImage does not run on Ubuntu 14.04:

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-7104/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by tamlok** [comment]
Hi, could you please tell me what is the solution? Use the patched one to generate the AppImage? Why it is not merged into the AppImageKit?

Thanks!

**Comment by probonopd** [comment]
In your case, removing 

https://github.com/tamlok/vnote/blob/28765bf4bbc15aac244285a4cade2e0973cec66f/.travis.yml#L20

should be the __best solution__, since this repository pulls in a newer libstdc++ version than what comes with Ubuntu 14.04 by default.

If you absolutely need this ppa because your application does not compile otherwise, check out https://github.com/darealshinji/AppImageKit-checkrt. It will search for `usr/optional/libstdc++/libstdc++.so.6` and `usr/optional/libgcc_s/libgcc_s.so.1` inside the AppImage or AppDir. If found it will compare their internal versions with the ones found on the system and prepend their paths to `LD_LIBRARY_PATH` if necessary.

**Comment by probonopd** [comment]
> Why it is not merged into the AppImageKit?

Because despite the name of the [checkrt](https://github.com/darealshinji/AppImageKit-checkrt) resporitory, it really has nothing to do with AppImage per se. AppImage is just a self-mounting filesystem that executes whatever the author has decided to put inside. So you need binaries that run on all target systems to begin with. [checkrt](https://github.com/darealshinji/AppImageKit-checkrt) can help in situations where you want to target Ubuntu 14.04 and newer as your target systems, and need to bundle a newer libstdc++ version than what comes with Ubuntu 14.04 by default.

**Comment by tamlok** [comment]
Thanks for your help! Will give it a try later. Packaging in Linux has been a nightmare to me for a long time. Thank you for your `linuxdeployqt`, really a great tool!

**Comment by tamlok** [comment]
It seems that VNote needs `ubuntu-toolchain-r/test` to pull in gcc6?

**Comment by probonopd** [comment]
I this case you may need to use something like https://github.com/darealshinji/AppImageKit-checkrt/issues/1#issuecomment-370134384
