### ISSUE TITLE
功能需求：使用外部程序编辑

### ISSUE THREAD

**Issue by ikaven1024** [vnotex/vnote#1520]
用惯了typora，不习惯写Markdown标记了。现在都是在vnote中点击打开文件位置，再使用typro来编辑。
可否在笔记的右键菜单上加上用外部程序打开的选型，毕竟，专业的事情要交给专业的来做。

**Comment by pysense** [comment]
> VNote支持使用外部程序来打开笔记。VNote将外部程序的配置信息保存在用户配置文件vnote.ini的[external_editors]小节中。

配置方法：
在 VNote 中右键选择某个笔记文件，选择“其他打开方式"-”添加外部程序“，根据提示操作即可。
