### ISSUE TITLE
公式预览在只有一个符号的时候失效

### ISSUE THREAD

**Issue by null-id** [vnotex/vnote#1521]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现): 比如$\epsilon$，就无法原地预览，但是$\epsilon-$就有原地预览了。可是我只想显示一个epsilon……

**Comment by tamlok** [comment]
Should be fixed. It works fine on Windows. Feel free to reopen if it was not.

![image](https://user-images.githubusercontent.com/5763157/102231138-98384b80-3f28-11eb-9076-c27a732531a8.png)
