### ISSUE TITLE
利用wkhtmltopdf导出pdf无法正常显示数学公式

### ISSUE THREAD

**Issue by AiresCCCC** [vnotex/vnote#1522]
OS Version (操作系统): Windows10
VNote Version(VNote版本): 2.9.1
Symptoms (表现):
**阅读模式**
![image](https://user-images.githubusercontent.com/49816895/94124451-9b6eee80-fe87-11ea-8d5e-cfeb9e11fbe3.png)

**编辑模式**
![image](https://user-images.githubusercontent.com/49816895/94124579-c2c5bb80-fe87-11ea-8a76-134dc3164e82.png)

**用wkhtmltopdf导出pdf后**
![image](https://user-images.githubusercontent.com/49816895/94124529-b3df0900-fe87-11ea-8e26-70319af081e7.png)

**Comment by tamlok** [comment]
Should be fixed in VNote 3 now.

![image](https://user-images.githubusercontent.com/5763157/130314889-55b3eb10-437a-42ac-a615-322b263d8d1f.png)
