### ISSUE TITLE
编辑模式下，公式发虚

### ISSUE THREAD

**Issue by ustchhy** [vnotex/vnote#1523]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现):
编辑模式下，公式发虚，阅读模式没问题
![image](https://user-images.githubusercontent.com/37625372/94264983-4d7ee700-ff6a-11ea-832b-4468f528bd92.png)

How to Repro (如何复现):
$$
J(\theta) = \frac 1 2 \sum_{i=1}^m (h_\theta(x^{(i)})-y^{(i)})^2
$$

**Comment by tamlok** [comment]
Please try VNote 3.0 to check. Thanks!
