### ISSUE TITLE
在Mac上没有找到git sync菜单。

### ISSUE THREAD

**Issue by xuedongliu** [vnotex/vnote#1524]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现):
在Mac上没有找到同步的菜单。在Windows上倒是找到了。

How to Repro (如何复现):
<img width="821" alt="Screen Shot 2020-09-25 at 20 34 30" src="https://user-images.githubusercontent.com/19763937/94267653-8faa2780-ff6e-11ea-9db5-1eb2b3d5055f.png">

请问Mac上现在有支持git sync同步么？

**Comment by mingming-cn** [comment]
同问，刚在mac上下载了vnote，也没找到。windows上正常。

**Comment by tamlok** [comment]
因为没测试过，所以暂时隐藏了。

**Comment by mingming-cn** [comment]
> 因为没测试过，所以暂时隐藏了。

可以通过修改配置把菜单显示出来吗？ 或者在下个版本可以使用吗？

**Comment by tamlok** [comment]
等下个版本吧
