### ISSUE TITLE
2.10 appimage格式在deepin v20无法输入中文

### ISSUE THREAD

**Issue by dong8yong8** [vnotex/vnote#1525]
OS Version (操作系统): Windows, Linux, macOS
linux deepin v20

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
VNote-2.10-x86_64.AppImage

Symptoms (表现):
使用讯飞输入法，无法切换讯飞输入法，无法输入中文

How to Repro (如何复现):
相同环境下，打开对应版即可

**Comment by jingle0927** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=202655

**Comment by tamlok** [comment]
回退一下2.9吧，编译环境发生变化，fcitx没有编译成功

**Comment by jingle0927** [comment]
> 回退一下2.9吧，编译环境发生变化，fcitx没有编译成功

欢迎去深度商店上架，这样就可以自己维护更新了

**Comment by tamlok** [comment]
上架了，可惜官方不维护，都是1.2版本

**Comment by NathanIceSea** [comment]
我这边用 Manjaro 安装 AUR vnote-git 编译安装后可以使用 fcitx，要不要考虑换下 Arch 邪教（手动滑稽

**Comment by plus-zhang** [comment]
> 我这边用 Manjaro 安装 AUR 的 vnote-git 编译安装后可以使用 fcitx，要不要考虑换下 Arch 邪教（手动滑稽

方便详细说一下步骤吗？我用的也是manjaro，2.9.1会有鼠标悬挂现象，2.10无法输入中文

**Comment by dong8yong8** [comment]
> anjaro 安装 AUR 的 vnote-git 编译安装后可以使用 fcitx，要不要考虑换下 Arch 邪教（手动滑稽

之前试着折腾过arch，折腾不动了，老实的用deepin省省心，deepin的本地化做的还是不错的
