### ISSUE TITLE
设置插入公式快捷键

### ISSUE THREAD

**Issue by xk005** [vnotex/vnote#1527]
我想自定义插入公式的快捷键如何自定义，或者建议作者在下一版本加入插入数学公式的快捷键，因为总是要中英文转换按两次`$`，感觉很麻烦。

**Comment by tamlok** [comment]
可以试试片段功能，分配一个快捷键即可，具体看一下文档。

新版会有专属快捷键

**Comment by xk005** [comment]
> 可以试试片段功能，分配一个快捷键即可，具体看一下文档。
> 
> 新版会有专属快捷键

有文档链接么？哪个文档？

**Comment by tamlok** [comment]
官网文档找一下

**Comment by tamlok** [comment]
- `Ctrl+,`  
Insert inline math. Press Ctrl+, again to exit. Current selected text will be changed to inline math if exists.
- `Ctrl+.`
Insert math block. Press Ctrl+. again to exit. Current selected text will be changed to math block if exists.
