### ISSUE TITLE
V2.10 UML 无法使用

### ISSUE THREAD

**Issue by ruleizhou** [vnotex/vnote#1529]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现): UML 无法使用， plantuml.jar 测试Error

How to Repro (如何复现): plantuml.jar 测试Error ExitCode：1

**Comment by Stivenke** [comment]
我的情况也一样，本地JAR，plantuml.jar 测试Error 无法渲染。
（2.7.2 至 2.9.1 版本的都正常）

操作系统：Windows 10 x64
VNote版本：2.10
表现：PlanUML 本地JAR，plantuml.jar 测试Error 无法渲染。
如何复现：plantuml.jar 测试Error ExitCode：1

**Comment by tenqaz** [comment]
同上

**Comment by gaoboyu** [comment]
我解决这个问题了，把plantUML放到C盘下，再进行配置。这里注意最多只能放在一层的文件夹内。
环境变量：
graphviz_dot=C:\\Program Files\\Graphviz\\bin\\dot.exe
vnote.ini
plantuml_jar=C:\\PlantUML\\plantuml.1.2020.26.jar
graphviz_dot=C:\\Program Files\\Graphviz\\bin\\dot.exe
plantuml_cmd=cmd.exe /c \"java -jar C:\\PlantUML\\plantuml.1.2020.26.jar -charset UTF-8 -nbthread 4 -pipe -t%0\"

**Comment by Tridu33** [comment]
![image](https://user-images.githubusercontent.com/31197010/108672147-8a043e00-751c-11eb-9816-c70ea4c70894.png)
同上问题，没能解决。

**Comment by Tridu33** [comment]
https://github.com/vnotex/vnote/issues/1539 这里说需要软件回滚到2.9版本。

**Comment by patricsun** [comment]
这个问题一直没有解决么？我在3.4.0版本里面也不能用PlantUML：
```
java -Djava.awt.headless=true -jar C:/plantuml.jar -charset UTF-8 -pipe -tsvg
Exitcode: -1
Output: 
Error: 
```

**Comment by tamlok** [comment]
> 这个问题一直没有解决么？我在3.4.0版本里面也不能用PlantUML：
> 
> ```
> java -Djava.awt.headless=true -jar C:/plantuml.jar -charset UTF-8 -pipe -tsvg
> Exitcode: -1
> Output: 
> Error: 
> ```

Hi,

指定路径的时候，请使用`C:\plantuml.jar`，斜杠。

另外，在命令行窗口，直接执行命令`java -Djava.awt.headless=true -jar C:/plantuml.jar -charset UTF-8 -pipe -tsvg`看看有什么提示？很有可能是java环境配置的问题。

**Comment by patricsun** [comment]
> 
> 
> > 这个问题一直没有解决么？我在3.4.0版本里面也不能用PlantUML：
> > ```
> > java -Djava.awt.headless=true -jar C:/plantuml.jar -charset UTF-8 -pipe -tsvg
> > Exitcode: -1
> > Output: 
> > Error: 
> > ```
> 
> Hi,
> 
> 指定路径的时候，请使用`C:\plantuml.jar`，斜杠。
> 
> 另外，在命令行窗口，直接执行命令`java -Djava.awt.headless=true -jar C:/plantuml.jar -charset UTF-8 -pipe -tsvg`看看有什么提示？很有可能是java环境配置的问题。

使用反斜线依然出错。

命令行窗口执行命令的结果：

> 错误: 找不到或无法加载主类 .awt.headless=true

**Comment by tamlok** [comment]
ok，那后面我改一下

**Comment by tamlok** [comment]
q奇怪，为什么要加引号呢？

**Comment by tamlok** [comment]
@patricsun 目前可以指定自定义命令来渲染：

打开用户配置文件，找到`plantuml_command`，如下指定命令，重启VNote：

```json
            "plantuml_command": "java -jar D:\\tamlok\\software\\plantuml.jar -charset UTF-8 -pipe -t%1",
```

**Comment by patricsun** [comment]
> 
> 
> @patricsun 目前可以指定自定义命令来渲染：
> 
> 打开用户配置文件，找到`plantuml_command`，如下指定命令，重启VNote：
> 
> ```json
>             "plantuml_command": "java -jar D:\\tamlok\\software\\plantuml.jar -charset UTF-8 -pipe -t%1",
> ```

我试了下修改配置文件，没有起作用。GUI设置里面需要更改么？

**Comment by tamlok** [comment]
gui不需要

**Comment by tamlok** [comment]
不会修改就等下一个版本吧
