### ISSUE TITLE
文件名带有空格的图片文件无法随笔记一起复制粘贴进行移动

### ISSUE THREAD

**Issue by cainb** [vnotex/vnote#1532]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

当图片文件的命名包含空格时，使用 VNote 的复制粘贴功能移动 .md 笔记，_v_images 文件夹里与笔记相关联的图片文件无法进行跟随移动！

How to Repro (如何复现):

[2020-10-05 15-27-58.zip](https://github.com/tamlok/vnote/files/5325926/2020-10-05.15-27-58.zip)

**Comment by tamlok** [comment]
图片url中需要将空格转义为20%

**Comment by cainb** [comment]
> 图片url中需要将空格转义为20%

您可以看一下我在复现选项中提交的压缩包里的复现视频，我图片 url 的格式转义 %20 了的 qaq

**Comment by cainb** [comment]
最新版本测试 该问题依然存在

版本号：3.8.1

**Comment by tamlok** [comment]
3.9.0应该修复了啦

**Comment by cainb** [comment]
实测 3.9.0 确实已修复 该问题关闭
