### ISSUE TITLE
windows gitee 上传图床失败

### ISSUE THREAD

**Issue by lsw9521** [vnotex/vnote#1536]
Windows 10
Vnote  2.10

上传图床失败，提示 - service replied: Not Found  请检查 Gitee 图床参数！

哎，感觉近半年不仅更新变慢了，而且出的新特性也不上心，一份一目了然的操作文档都不写，有时候遇到问题不知道是软件本身的缘故还是自己打开方式不对而反复尝试，又浪费时间又糟心，哎！

**Comment by tamlok** [comment]
Hi，

因为最近重心在重构vnotex，预计两个月左右会发布。

图床功能是后期用户PR的，所以维护上面可能不太及时。关于图床的文档，这里不知道看过没有： https://tamlok.gitee.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%9B%BE%E5%BA%8A.md

请耐心再等等哦。

![image](https://user-images.githubusercontent.com/5763157/95667831-13365c00-0b9e-11eb-96f0-d3bc22bfcaa1.png)

**Comment by lsw9521** [comment]
谢谢！ 【Github】 图床是一直可以的，但是实在太慢了，所以我才考虑换 【Gitee】 的，文档里是说大同小异的，但是反正我是正着来反着来都没搞定，【微信】听着就不靠谱，所以最后选择了【腾讯云】，当然也不是一帆风顺的，配置腾讯云的过程中至少遇到了三个不同的错误！心累啊！！！最后好歹是成了。。。先这样吧！VnoteX 加油！！！ 

有没有针对开发者的详细文档呀？ 就是解释整体功能模块和代码入口以及整个执行流程和事件入口的文档？ 之前下过Vnote 2.7 代码，而且成功编译并运行了，但是完全没接触过 qt 和 c++ 就会一点点 js ，感觉完全无法入手，不知道程序是从哪到哪的。其实一开始也就只是想要在每个笔记模板里加一小段能执行的 js 函数而已，因为发现直接在 vnote 笔记里加 script 标签，里边的 js 怎么都不会执行，所以才想着跑源码里去看看能不能改改的

**Comment by tamlok** [comment]
等vnotex吧，所有js都是配置文件配置的，可以自由添加或者修改
