### ISSUE TITLE
是否支持粘贴markdown后，将markdown内url形式的图片像粘贴html一样，下载图片并替换成本地图片

### ISSUE THREAD

**Issue by lowwor** [vnotex/vnote#1537]
想要的效果是想剪藏一些网页到vnote，如果直接手动复制页面的话，比较麻烦，所以想配合一些剪藏插件使用，但是没找到适配vnote的，像是https://github.com/webclipper/web-clipper 和 https://github.com/mika-cn/maoxian-web-clipper 都是导出markdown的，但是里面的图片都是url的，可否像粘贴html一样，也支持转本地图片？

**Comment by mika-cn** [comment]
@lowwor

如果把  MaoXian 裁剪下來的文件，以 Vnote 的存儲結構進行存儲，是 可以對接上的。我研究一下如何對接上 Vnote。

**Comment by tamlok** [comment]
> @lowwor
> 
> 如果把 MaoXian 裁剪下來的文件，以 Vnote 的存儲結構進行存儲，是 可以對接上的。我研究一下如何對接上 Vnote。

暂时不需要呀，等后面vnotex出来后，麻烦您帮适配一下就好了~~

**Comment by mika-cn** [comment]
@tamlok

抱歉，我有一段時間沒關注 Vnote 項目了，這個 vnotex 是一個全新的版本？

我之前一直想對接 Vnote 來着，就是軟件有點大，我用瀏覽器下了好幾次，都沒下載下來（被惡牆干擾了）。

**Comment by tamlok** [comment]
是一个全新重构的，预计两个月内会发布~

**Comment by mika-cn** [comment]
@lowwor

我对接上了目前的 Vnote，详情请看[这里](https://mika-cn.github.io/maoxian-web-clipper/native-app/vnote_v1-zh-CN.html)

**Comment by mika-cn** [comment]
@tamlok

我目前已经对接上现在的 Vnote，现在的 Vnote 文件存储结构 和 MaoXian Web Clipper 还是很像的，不同点是 Vnote 会在每一层都有个 `_vnote.json` ，而 MaoXian 则是每个 markdown 文件都存一个元信息文件。 所以我所做的是 markdown 文件存储成功后，向上遍历，修复 `_vnote.json` 里面的内容。目前对接上后，需要在 Vnote 那边刷新一下，才能看到文件。

等后面 vnotex 上线，我再对接 vnotex  :)
