### ISSUE TITLE
PlantUML Jar Invoke Error

### ISSUE THREAD

**Issue by DanielW10001** [vnotex/vnote#1539]
OS Version (操作系统): Windows

VNote Version (VNote版本): 2.10

Symptoms (表现):

Jar acts as expected in PowerShell:

```powershell
> java -D"java.awt.headless"="true" -jar C:\Users\daniel\bin\VNote\lib\plantuml.jar -charset UTF-8 -graphvizdot "C:\Program Files\Graphviz 2.44.1\bin\dot.exe" -pipe -tsvg
No diagram found
```

But does not work in VNote:

![ScreenShot](https://user-images.githubusercontent.com/44944011/95860493-afc14f80-0d92-11eb-8030-dfc023ed90f1.png)

PlantUML code blocks are also not rendered. It seems to be the invoke syscall that is misfunctioning.

**Comment by jimmyatgit** [comment]
Same problem. Roll back to 2.9.1, it works.
