### ISSUE TITLE
中英文切换 bug

### ISSUE THREAD

**Issue by lsw9521** [vnotex/vnote#1541]
windows 10
vnote 2.10

在vnote里使用 autohotkey 强制切换输入法为中文会卡死，在其它软件上都是不会的，不知道 vnote 是不是在键盘监控上有什么特殊的处理呀？

SwitchIME(00000804){
    HKL:=DllCall("LoadKeyboardLayout", Str, dwLayout, UInt, 1)
    ControlGetFocus,ctl,A
    SendMessage,0x50,0,HKL,%ctl%,A
}

**Comment by tamlok** [comment]
vi模式吗？vi模式正常模式下面会默认关闭输入法，其他倒没什么处理。
