### ISSUE TITLE
问一个开发问题

### ISSUE THREAD

**Issue by feloxx** [vnotex/vnote#1545]
作者你好
我特别喜欢这个项目
问一下,想为vnote做贡献提pr,语言和框架都该学习哪些呀. 然后学习到什么程度了了,就可以来提pr了呀.

**Comment by tamlok** [comment]
Hi,

1. 需要学习C++和Qt，掌握基本用法即可，能看懂Qt Creator自带的一些小demo；
2. 如果会Javascript或者CSS，也可以为VNote的阅读模式进行贡献的；
3. 其实，主要是多使用VNote，然后在使用的过程中，你觉得有什么是需要改进的，就可以向我提出，我指给你大概代码在哪里，你基本就可以修改了；
4. 其实VNote很多代码逻辑都是在搭积木一样，并没有什么技术难度；

谢谢！

**Comment by feloxx** [comment]
好的,谢谢作者

我已经安利了好多同事用vnote了,用过的都说好,完美的解决了对笔记的所有需求.

我到时候收集一波需求来试试找几个简单的功能实现.
