### ISSUE TITLE
VNotes首页404了

### ISSUE THREAD

**Issue by libra146** [vnotex/vnote#1546]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
不好意思给issues喜加一，不过我想问https://tamlok.github.io/vnote 为什么404了？是因为误删除了还是其他原因呢？

How to Repro (如何复现):

[https://tamlok.github.io/vnote](https://tamlok.github.io/vnote)

**Comment by tamlok** [comment]
因为仓库转移了

把tamlok换成vnotex即可

**Comment by libra146** [comment]
> 因为仓库转移了
> 
> 把tamlok换成vnotex即可

😂好的，了解，最好是把README更改一下吧，容易误导人

**Comment by tamlok** [comment]
后面会发布新版本，全部修改

**Comment by libra146** [comment]
> 后面会发布新版本，全部修改

期待ing😁
