### ISSUE TITLE
搜索出错

### ISSUE THREAD

**Issue by ice-doom** [vnotex/vnote#1551]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):
![image](https://user-images.githubusercontent.com/25363717/97254274-f8741080-1848-11eb-9ea4-e64d50c9685a.png)

How to Repro (如何复现):
不记得删掉了什么出现这个错误

**Comment by tamlok** [comment]
去看一下本地是否还存在这个文件夹就好了。应该是在vnote外删除了，但vnote的json索引里面没有删除。

**Comment by ice-doom** [comment]
索引的原因，删了就好了
