### ISSUE TITLE
macOS打开VNote屏幕黑屏2秒

### ISSUE THREAD

**Issue by yimtcode** [vnotex/vnote#1552]
OS Version (操作系统): Windows, Linux, macOS
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/33422693/97374589-9fad8200-18f3-11eb-8b41-e3eff8127598.png">

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
<img width="420" alt="图片" src="https://user-images.githubusercontent.com/33422693/97374639-b7850600-18f3-11eb-8f67-2bd20e19b266.png">

Symptoms (表现):
在没有外接显示器情况下打开VNote或整个屏幕黑屏2秒左右

How to Repro (如何复现):
正常打开VNote会出现黑屏2秒左右，将MacOS自动切换显卡关闭就不会出现，外接显示器也不会出现（可能也只会使用独立显卡），之前使用没有这个问题，突然出现的试过卸载重装还是不行，其他软件没有这个问题，猜测可能是触发macOS的双显卡切换了。

**Comment by yimtcode** [comment]
@tamlok

**Comment by tamlok** [comment]
Chrome有没有这个问题？macOS能否指定一个程序用集显？

**Comment by yimtcode** [comment]
> Chrome有没有这个问题？macOS能否指定一个程序用集显？

我测试下，Chrome没有问题，我之前也找了下指定程序使用指定显没有找到，只能关闭双显卡自动切换，强制全部使用独立显卡，但是这在移动办公下可能造成耗电过快。

**Comment by tamlok** [comment]
试试`--disable-gpu`：https://doc.qt.io/qt-5/qtwebengine-debugging.html

**Comment by yimtcode** [comment]
1. 这应该是添加启动参数吧？但是macOS上我没有找到添加启动参数的地方。

**Comment by yimtcode** [comment]
> 试试`--disable-gpu`：https://doc.qt.io/qt-5/qtwebengine-debugging.html

这应该是添加启动参数吧？但是macOS上我没有找到添加启动参数的地方。

**Comment by yimtcode** [comment]
> 试试`--disable-gpu`：https://doc.qt.io/qt-5/qtwebengine-debugging.html

1. 这应该是添加启动参数吧？但是macOS上我没有找到添加启动参数的地方。
2. 如果这个编译时添加的参数话，我对C++、QT都不是很熟悉还需要开发环境。

**Comment by tamlok** [comment]
可以添加启动参数或者环境变量：

![image](https://user-images.githubusercontent.com/5763157/97407236-5c740300-1935-11eb-9a77-72be0bea525d.png)

**Comment by yimtcode** [comment]
> 可以添加启动参数或者环境变量：
> 
> ![image](https://user-images.githubusercontent.com/5763157/97407236-5c740300-1935-11eb-9a77-72be0bea525d.png)

yimt@MacBook-Pro ~ % export QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu"         
yimt@MacBook-Pro ~ % open /Applications/VNote.app
这样配置也不确定对还是不对，还是会出现之前的情况。

**Comment by yimtcode** [comment]
> 可以添加启动参数或者环境变量：
> 
> ![image](https://user-images.githubusercontent.com/5763157/97407236-5c740300-1935-11eb-9a77-72be0bea525d.png)

yimt@MacBook-Pro ~ % export QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu"
yimt@MacBook-Pro ~ % open /Applications/VNote.app
这样配置也不确定对还是不对，还是会出现之前的情况。

**Comment by tamlok** [comment]
try this:

https://codereview.qt-project.org/c/qt-creator/qt-creator/+/75352/1/src/app/Info.plist.in

https://codereview.qt-project.org/c/qt/qtbase/+/73839/

**Comment by yimtcode** [comment]
> try this:
> 
> https://codereview.qt-project.org/c/qt-creator/qt-creator/+/75352/1/src/app/Info.plist.in
> 
> https://codereview.qt-project.org/c/qt/qtbase/+/73839/

参考：
https://codereview.qt-project.org/c/qt-creator/qt-creator/+/75352/1/src/app/Info.plist.in
操作：
修改/Applications/VNote.app/Contents/Info.plist文件，添加
```xml
<dict>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
</dict>
```
测试完成不会黑屏了，将添加的true修改为false在启动立马黑屏，猜测可能是这个问题了，如果后续在有问题我在和你反馈。
谢谢了，占用了你这么多时间。

**Comment by tamlok** [comment]
Confirmed that it is fixed after Qt 5.12.
