### ISSUE TITLE
如何显示或编辑笔记本根目录下的笔记

### ISSUE THREAD

**Issue by feloxx** [vnotex/vnote#1553]
作者你好,这是我学习vnote源码想尝试实现的第一个功能.

如何显示`笔记本`的`根目录`下的笔记.

如何在`笔记本`的`根目录`下新建笔记 等

(个人感觉应该就是把二级目录的笔记操作功能复制到根目录下)

---

这个功能的来由:

```
我们在创建了一个笔记工程,(想在github或者这类网站上进行同步),都会在根目录下放一些介绍内容或者其他内容比如README.md,如果想在vnote中进行此类的操作,目前是无法进行的.
```

**Comment by tamlok** [comment]
Hi,

目前这个功能已经在VNoteX中实现了，一两个月内VNoteX会发布，建议到时候基于该版本进行二次修改。VNote的代码会作古了。

**Comment by feloxx** [comment]
好的,那我先关闭这个is了.
