### ISSUE TITLE
Git Sync不支持路径中有空格的笔记本

### ISSUE THREAD

**Issue by Batianhu1108** [vnotex/vnote#1554]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现):
![捕获](https://user-images.githubusercontent.com/33864072/97452304-8ea25680-196f-11eb-89fb-d92701c70c76.PNG)

How to Repro (如何复现): 新建一个名字中带空格的笔记本，点击Gti Sync->upload

**Comment by Karonheaven** [comment]
奇怪，我这里可以上传
笔记本名：test notebook，笔记名：test note.md
Windows Git2.28.0 VNote2.10
可能是Git版本的问题？（我猜的，你可以试试

**Comment by Batianhu1108** [comment]
> 奇怪，我这里可以上传
> 笔记本名：test notebook，笔记名：test note.md
> Windows Git2.28.0 VNote2.10
> 可能是Git版本的问题？（我猜的，你可以试试
