### ISSUE TITLE
Security Vulnerability Disclosure

### ISSUE THREAD

**Issue by indianamoreau** [vnotex/vnote#1555]
Hi,

I have found a high-risk security vulnerability which may result in remote code injection in this project. Who can I contact to responsibly disclose it?

Thanks,
Indiana Moreau

**Comment by tamlok** [comment]
Hi,

Do you mean this: https://github.com/vnotex/vnote/issues/564 ?

You could send email to `tamlokveer at gmail.com`.

Thanks!
