### ISSUE TITLE
预览界面文字模糊

### ISSUE THREAD

**Issue by sparrowyang** [vnotex/vnote#1556]
OS Version (操作系统): Kubuntu 20.10
(VNote版本): 2.10
Symptoms (表现):预览界面文字不清晰

你好，我在自己的kubuntu 20.10 上构建并安装了Vnote，经过重重困难我成功安装上了vnote。但是我在打开markdown时，预览显得非常的不清晰，如下：
![Screenshot_20201029_110444](https://user-images.githubusercontent.com/53291577/97521158-ed031f80-19d7-11eb-96ea-80adf40f8c47.png)
编辑界面是非常清晰的：
![Screenshot_20201029_110502](https://user-images.githubusercontent.com/53291577/97521202-0310e000-19d8-11eb-813d-699588c810f7.png)
我不知道是什么原因导致的，如果能得到帮助，那真是感激不尽！

**Comment by sparrowyang** [comment]
我找到问题了，似乎是分辨率缩放导致的问题。我的配置分辨率配置的是1920*1080 125%缩放。
我把缩放调成100%，问题就解决了，但是这样的缩放让我不是很舒服。
不知道有其他方法没有。

**Comment by tamlok** [comment]
Hi,

Chrome有这个问题吗？

KDE的缩放是不是可以调节字体大小来进行缩放的？试试这个？

是独立显卡吗？

系统125%缩放，vnote里面设置中调节一下缩放，缩小看看？

谢谢！
