### ISSUE TITLE
代码块不能高亮显示

### ISSUE THREAD

**Issue by netcm** [vnotex/vnote#1558]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现):
 #代码块不能高亮显示

How to Repro (如何复现):
安装版本 x64 2.10

**Comment by tamlok** [comment]
hi，代码块前面空一行看看

**Comment by netcm** [comment]
> hi，代码块前面空一行看看

是代码块里的语法关键字不能高亮显示,如c# 、js等

**Comment by netcm** [comment]
> hi，代码块前面空一行看看

搞懂了,是我不会用.  没加代码类型标识.所以就没有语法提示
