### ISSUE TITLE
包裹类标记的建议

### ISSUE THREAD

**Issue by tzraeq** [vnotex/vnote#1559]
在vscode中，只需要选中一部分文字，然后按下 ` 或者 ” 或者 ' 按键，编辑器会自动使用这个符号，成对的包裹选中的这部分文字，非常方便，希望vnote也可能增加这个特性。当然我说的都是英文半角的标记，中文全角的字符不在考虑之内。

非常感谢作者的辛勤付出！！！

**Comment by tamlok** [comment]
hi，

vnote3本来支持的，但用户说比较烦人，想想也是，类似于I'm之类的，如果补全那就有点傻了。所以后面去掉了。目前只会自动补全括号。

**Comment by tzraeq** [comment]
你好，我可能没说清楚，我说的不是自动补全，而是，选中一段文字，注意，是选中之后，这时候直接输入一个可以成对的符号，比如输入一个单引号，这个时候不是用单引号替换这段选中的文字，而是将这段选中的文字包裹起来。

**Comment by tamlok** [comment]
哦哦，这个可以有，我看看。

**Comment by tamlok** [comment]
Supported 1601fe84c5c193e227af416487ba4a354e8d9b6b
