### ISSUE TITLE
想实现在表格中一栏放入多个公式和伪代码，另一栏放入图片

### ISSUE THREAD

**Issue by zhyma** [vnotex/vnote#1561]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.9.1

Symptoms (表现):

想写一个表格，其中一格放入
```
> Initialize: $V(s)\leftarrow 0$
> Loop for each $k\in N$
> If $k=N$, then:
> 　　Loop for each $\langle x_N,w_N\rangle\in \langle X,W\rangle$:
> 　　　　$V(\langle N,x,w\rangle)\leftarrow J(x,w)$ (terminal cost)
> Else:
>        Do sth
```
其中$引出的部分解释为公式
另一格中插入图片。

请问有什么比较好的实现方法么？
1. 如果用markdown的话，markdown表格只支持单行，我需要引用的伪代码行数很多，看起来非常混乱。若通过插入&lt;br />进行换行后，'> '不会被解析。
2. 如果用html的表格标签，插入图片可以直接用&lt;a>，但是无法解析mathjax。我对vnote的理解是它每个预览实际是解析成了html然后通过浏览器渲染的，那么实际上应该是在&lt;head>或者某个部分已经载入过mathjax.js，那么我应该使用一个已经定义好的自定html标签包裹公式内容从而实现公式的渲染，但是这块没有头绪，希望能得到一些相关信息。谢谢！

How to Repro (如何复现):

**Comment by mlkey** [comment]
|    code    |    img    |
| ---------  | -------- |
| Initialize: $V(s)\leftarrow 0$<br>Loop for each $k\in N$<br>If $k=N$, then:<br>　　Loop for each $\langle x_N,w_N\rangle\in \langle X,W\rangle$:<br>　　　　$V(\langle N,x,w\rangle)\leftarrow J(x,w)$ (terminal cost)<br>Else:<br>　　Do sth | ![](https://github.githubassets.com/favicons/favicon.png) |

**Comment by zhyma** [comment]
> code	img
> Initialize: $V(s)\leftarrow 0$
> Loop for each $k\in N$
> If $k=N$, then:
> 　　Loop for each $\langle x_N,w_N\rangle\in \langle X,W\rangle$:
> 　　　　$V(\langle N,x,w\rangle)\leftarrow J(x,w)$ (terminal cost)
> Else:
> 　　Do sth	![](https://camo.githubusercontent.com/fcd0c844439dfcdaa7e451ab9c6cc4ed4f95ac81f1e801c7858ffaaf6fcba58f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e706e67)

请问你的代码是如何实现的？Initialize: $V(s)\leftarrow 0$和Loop for each $k\in N$之间是如何实现换行的？谢谢

**Comment by mlkey** [comment]
```
|    code    |    img    |
| ---------  | --------- |
| Initialize: $V(s)\leftarrow 0$<br>Loop for each $k\in N$<br>If $k=N$, then:<br>　　Loop for each $\langle x_N,w_N\rangle\in \langle X,W\rangle$:<br>　　　　$V(\langle N,x,w\rangle)\leftarrow J(x,w)$ (terminal cost)<br>Else:<br>　　Do sth | ![](https://github.githubassets.com/favicons/favicon.png) |
```
`<br>`换行，全角空格缩进，在VNote里公式也可以正常解析。

**Comment by zhyma** [comment]
> ```
> |    code    |    img    |
> | ---------  | --------- |
> | Initialize: $V(s)\leftarrow 0$<br>Loop for each $k\in N$<br>If $k=N$, then:<br>　　Loop for each $\langle x_N,w_N\rangle\in \langle X,W\rangle$:<br>　　　　$V(\langle N,x,w\rangle)\leftarrow J(x,w)$ (terminal cost)<br>Else:<br>　　Do sth | ![](https://github.githubassets.com/favicons/favicon.png) |
> ```
> 
> `<br>`换行，全角空格缩进，在VNote里公式也可以正常解析。

对，我知道可以插入&lt;br />进行换行，但是我想在markdown里应用"> "的引用模式，因为是引用了部分伪代码和一些不在代码里的注解混排的。而且内容非常长，因此不想通过markdown自带的表格实现。可能一开始没有解释得很清楚
