### ISSUE TITLE
手动重构笔记本之后无法识别笔记本

### ISSUE THREAD

**Issue by rguo97** [vnotex/vnote#1563]
OS Version (操作系统): Windows, Linux, macOS
Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.10
Symptoms (表现):
手动重构笔记本目录下面的文件或者文件夹之后，无法识别，我看到VNote的工作是依赖每个目录下面的vnote.json，是不是有点不科学，希望增加重构选项或者在每次重启之后重新扫描一下当前的目录，完成重构

How to Repro (如何复现):
通过Windows的资源管理器修改一下目录，笔记本不可用。

**Comment by tamlok** [comment]
因为是笔记软件，所以就弄了一个索引文件，可以通过vnote里面的右键菜单进行复制粘贴。

如果需要频繁在vnote之外变动文件，可以考虑使用左上角第三个按钮浏览器功能，将vnote单纯作为一个编辑器使用。

**Comment by rguo97** [comment]
> 因为是笔记软件，所以就弄了一个索引文件，可以通过vnote里面的右键菜单进行复制粘贴。
> 
> 如果需要频繁在vnote之外变动文件，可以考虑使用左上角第三个按钮浏览器功能，将vnote单纯作为一个编辑器使用。

好的，明白了，我觉得添加一个在重启之后自动重构笔记本的功能会方便很多。

**Comment by tamlok** [comment]
自动重构就很玄学了~~vnote很难知道哪些文件要索引，哪些文件不用索引的~不过可以手动修改json索引。

**Comment by cxwind** [comment]
我觉得确实可以增加一个重构功能,因为我可以直接使用我喜欢的编辑器如emacs/vim增加或者修改MD文件,使用vnote可视化.

可以 vnote 启动的时候检查哪些文件被删除或者增加了哪些 md 文件,然后询问是否删除或者增加对应 jason条目.

**Comment by tamlok** [comment]
3.0后面会有新的解决方案。

**Comment by l00c00l** [comment]
刚开始接触。
在建立根文件夹以后复制进来一个vnote1.md，也在VNote中打开编辑过两次，但是，在vnote里一直看不到这个文件！
这个问题，大概跟题主说的是同一个问题？
还有，vnote里看不到最近打开文件？有点点不适应。

**Comment by tamlok** [comment]
@l00c00l 先用2.10吧，里面有历史文件面板，也有浏览器面板来浏览编辑外部文件，如果需要频繁绕过vnote来管理文件，建议把vnote当做一个编辑器使用即可。

**Comment by l00c00l** [comment]
> @l00c00l 先用2.10吧，里面有历史文件面板，也有浏览器面板来浏览编辑外部文件，如果需要频繁绕过vnote来管理文件，建议把vnote当做一个编辑器使用即可。

收到，这两天实验了表格、插图、图片、公式等功能
好用！
非常感谢~~
