### ISSUE TITLE
Feature Request: Shift indent left, and shift indent right

### ISSUE THREAD

**Issue by Bizzaro** [vnotex/vnote#1564]
Hi, 

I don't think this feature exists in vnote, but it would be useful for me.
I copy paste a lot of things into vnote, and 99% of the time, the indents are all whacky 

Like in sublime and vscode, I select the text then hit `ctrl + [` or `ctrl + ]` to indent left and right. 

Thanks!

**Comment by tamlok** [comment]
hi

try tab and shift-tab?

**Comment by Bizzaro** [comment]
thanks, `tab` worked. 
can you make this an option in the keyboard shortcut file? that would be awesome

**Comment by tamlok** [comment]
Do you mean the `Shortcuts Help` in the help menu? It is already there.

![image](https://user-images.githubusercontent.com/5763157/99013646-e81f9d80-258b-11eb-903c-a3179130e111.png)

**Comment by Bizzaro** [comment]
> Ohh, maybe you mean make this an option in the config file to let user customize it? I think that is too trivial to be a configurable shortcut. Anyway, I will try to support VSCode shortcuts, just like Vi mode.

yes in the config file. ok thanks :)
