### ISSUE TITLE
[Feature Request] Marked and inserted text in markdown-it

### ISSUE THREAD

**Issue by roshiajin-kunai** [vnotex/vnote#1568]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Hello. 
I would really like to see the marked text `<mark>` with shortcut and markup `==Marked text==`
and even more so the <ins>inserted</ins> text `<ins>` as `++Inserted text++` 
in markdown-it.

Thank you.

**Comment by tamlok** [comment]
Hi,

You could use Snippet in VNote to insert `<mark>` via a shortcut.

For other extensions in Markdown-It, you could add them to VNote in the following release of VNote.

Thanks!

**Comment by roshiajin-kunai** [comment]
Yes, I'm aware about snippets, however in that case I'd need to define two shortcuts `<mark>` and  `</mark>`, and if I'd want to use `<ins>` it will be two more shortcuts.

When  if it would work as `<del>` - `~~`, all I'd need to do is select wanted text and press `Ctrl+something`.

**Comment by tamlok** [comment]
Try this `<mark>$$@@</mark>`. Since Vi-mode will occupy most of the shortcuts, I will make `<mark>` an action like bold and italic, and leave the shortcut blank for user to fill in.

**Comment by roshiajin-kunai** [comment]
Ah, that's right... Omigosh.. 
Thank you very much.

**Comment by roshiajin-kunai** [comment]
I wonder if now I don't need this feature and this issue can be closed...
Still, it would be good to visualise `<ins>` in edit mode.
