### ISSUE TITLE
[Feature Request] Improve auto-completion

### ISSUE THREAD

**Issue by sakkamade** [vnotex/vnote#1569]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Hello, 
I would like to see the option to turn on/off constant auto-completion.
Like, I just started to write a word, but menu with completed ones would be already present if similar word exists in the document. And all I need to do is with arrow keys select one(or ignore it). Such as in `Notepad++`.

And/or allow user to define custom shortcuts for already present function.

Thank you.

**Comment by tamlok** [comment]
Did you try `Ctrl+N` and `Ctrl+P`. I am a fan of Vim instead of Notepad++, and VNote is a Vim-inspired note-taking app, so most of the logics in VNote are similar to Vim.

**Comment by roshiajin-kunai** [comment]
Yes, I tried, however default shortcut is truly inconvenient for me. And I haven't seen an option to change it.

**Comment by tamlok** [comment]
What is your preferred shortcut then?

**Comment by roshiajin-kunai** [comment]
Something like `Ctrl+Arrow Up` `Ctrl+Arrow Down`, but it would be better to make it possible to config in `.ini`, since I've never used auto-completion this way, I can't be sure.
However, the distance between `N` and `P` is too large for me.

**Comment by tamlok** [comment]
After ctrl-n triggering the completion, you could just use simply the arrow keys to navigate up and down. Or ctrl-j and ctrl-k if you are a fan of vim.

**Comment by roshiajin-kunai** [comment]
Yes, however after i would press `Ctrl+N` and navigate through pop-up window with `Arrows` for desired word, it doesn't change the word in text, just remaining on first example. Even after I hit `Space` or `Enter`, it remains on first word.

**Comment by tamlok** [comment]
`Enter` (at the main area instead of the num keyboard) should work.

**Comment by roshiajin-kunai** [comment]
@tamlok Well, it doesn't work. Either of them.

And even it would work, `Space` would be more comfortable.

**Comment by tamlok** [comment]
This is the Vi way! :)
Will tune it in future release.

**Comment by roshiajin-kunai** [comment]
I wonder, how can it be comfortable *wink*

Thank you very much.

**Comment by sakkamade** [comment]
I would like to append some clarification/variation of my request.

Using `npp` for quite a time now, I truly come to believe the `vim`-way of auto-completion being much more preferable.
However, a sole tweak of allowing user to change a shortcuts for `Ctrl+N/P`  I still would like to see.
With such difference, I believe, 'non-vim' and 'non-programmers' people, such as myself, shall find the auto-completeion even more convenient.

**Comment by sakkamade** [comment]
I don't think that this issue is (and was) actually relevant. 
For version 2 used to have slightly another completeion behaviour than version 3 now.

I rather open another issue addressing it, when VNote3 will finalise/stabilise its new appearance.

Thank you.
