### ISSUE TITLE
关于从notion导出的本地md文件，导入后图片不显示问题

### ISSUE THREAD

**Issue by Palvehelmed** [vnotex/vnote#1570]
OS Version (操作系统):  macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现):
从notion导出的.md文件，在其他md编辑器（如typora）中可见图片，在Vnote中偶尔可见，并且之后依然看不到

导入的图片显示如下：
<img width="521" alt="image" src="https://user-images.githubusercontent.com/36530040/99755182-11f53900-2b25-11eb-96b0-e2c5dacd6df9.png">

How to Repro (如何复现):
基本都无法显示，暂不清楚如何能看到图片，新导入的有时可以看到图片

**Comment by Palvehelmed** [comment]
已解决 把导出的图片文件放在笔记目录下， 并且把图片路径下的中文替换成英文即可在md中显示图片

**Comment by Palvehelmed** [comment]
但是这个方法不支持上传到图床， 只能手动再复制粘贴进文档， 不知道这个算不算bug

**Comment by tamlok** [comment]
我这边试了一下没有问题，可能我导出的图片名称里面没有中文（但我不知道怎么让图片名称有中文）。你可以把导出有问题的笔记zip发到我邮箱，我看看能不能复现。一般来说没啥问题。

**Comment by Palvehelmed** [comment]
> 我这边试了一下没有问题，可能我导出的图片名称里面没有中文（但我不知道怎么让图片名称有中文）。你可以把导出有问题的笔记zip发到我邮箱，我看看能不能复现。一般来说没啥问题。

感谢回复， 
不好意思是我没有表达清楚，是笔记下导出的图片所在的文件夹有中文，导出在桌面之后，在vnote选择从文件新建笔记，就无法显示图片了
<img width="505" alt="image" src="https://user-images.githubusercontent.com/36530040/99925090-a8209d80-2d77-11eb-9af9-2cfc7d219c08.png">

我的解决方法是将上图图片里的符号部分（即原路径的中文部分）改为英文，图片即可在vnote中显示
但是这种方法无法上传图片， 只能手动复制再粘贴进笔记中才能上传，而且由于是手动把图片复制到笔记目录，如果笔记有移动，图片文件夹爱就得手动移动到相应笔记目录，比较麻烦

请问这个目前有解决方案吗？

**Comment by Palvehelmed** [comment]
另外还想问一下， 用f. f, df. 之类命令的时候不支持中文标点，除了批量替换成英文的标点， 还有其他办法吗

**Comment by tamlok** [comment]
VNote的`从文件新建笔记`功能只是会简单复制md文件到当前文件夹，不会拷贝图片文件夹。所以你可以手动把md文件和图片文件夹到拷贝到vnote的目标文件夹中，然后再导入，这时候vnote不会复制文件，只是添加一下索引。

马上会发新版，后面会解决这个问题。

现在的Vim好像对中文标点的支持也不太好吧？这个我一般都是用选择来替换了。

**Comment by Palvehelmed** [comment]
好的 

ps Vnote我见过最好的app之一， 感谢作者♥️
