### ISSUE TITLE
vnote上传图片至gitee报创建SSL上下文错误

### ISSUE THREAD

**Issue by yisuixinq** [vnotex/vnote#1571]
OS Version (操作系统): Windows 10 1903 HOME 

VNote Version (Help - About VNote - Version: )(VNote版本):  2.10

Symptoms (表现):

起先上传图片至gitee，vnote报创建SSL上下文错误，试了github也一样，我用的vnote是portable版本，又将软件重装了好几次，也没有解决。接着我又安装好了openssl，并没有解决问题，vnote检查更新也一直失败 。前面看见有类似问题的closed issue，但是并没有最终解决方案。 (我的另一台电脑图片上传一直正常，用的账户都是一样的) 

![image](https://user-images.githubusercontent.com/40953718/99876193-2540fb00-2c30-11eb-84b3-a5166f5765a5.png)

![image](https://user-images.githubusercontent.com/40953718/99876217-59b4b700-2c30-11eb-9c24-6ab890999154.png)

![image](https://user-images.githubusercontent.com/40953718/99876228-6a652d00-2c30-11eb-9382-ab4c56ee12cc.png)

**Comment by tamlok** [comment]
回退一个版本吧，openssl的版本变了

**Comment by yisuixinq** [comment]
是回退VNOTE 还是回退OpenSSL，事实上Vnote已经回退到 V2.9.1试过了，还是一样现象

**Comment by yisuixinq** [comment]
![image](https://user-images.githubusercontent.com/40953718/99878383-f29efe80-2c3f-11eb-9ccb-f0127279b4a2.png)

**Comment by tamlok** [comment]
就是qt版本升级了，导致openssl的版本不兼容。openssl升级一下看看，或者看一下最新qt 5.9的openssl的版本号

**Comment by yisuixinq** [comment]
从前面的图片可以看出，我目前安装的OpenSSL已经比较新了，2020-09-22 发布的，更新的就是3.0.0的beta版本了。
跟qt 5.9 版本匹配的话，我搜了一下，openssl-1.1.1h 应该够了。
![image](https://user-images.githubusercontent.com/40953718/99879967-60045c80-2c4b-11eb-86cf-804545eaffe9.png)
![image](https://user-images.githubusercontent.com/40953718/99879982-832f0c00-2c4b-11eb-8ad7-1b2034e477e1.png)

**Comment by tamlok** [comment]
试试这个版本？现在VNoteX会在启动的时候输出build版本，这个是5.12的输出：

```
OpenSSL build version: "OpenSSL 1.1.1d  10 Sep 2019" link version: 0
```

**Comment by yisuixinq** [comment]
一大早起来就折腾这个OpenSSL，装好了这个版本还是不行

![image](https://user-images.githubusercontent.com/40953718/99893004-4ea46a00-2cb6-11eb-97e6-1cc39d1b756d.png)

**Comment by tamlok** [comment]
刚看了代码，发现VNote启动的时候会打印出openssl的版本：

```
Info:(main.cpp:211) VNote started "2.10" "Sun Nov 22 12:34:55 2020"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
```

再试试这个吧。如果还不行，那就暂时等一下即将发布的VNoteX吧。

**Comment by yisuixinq** [comment]
可以传图了，差点没把我整崩溃，感谢指点。
