### ISSUE TITLE
关于Vnote中的文档链接404应该由tamlok.github.io变为vnotex.github.io

### ISSUE THREAD

**Issue by baiguantao** [vnotex/vnote#1573]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10,  d78e892d5cc  etc..

Symptoms (表现):
Vnote2.10版本，关于Vnote中的文档链接错误应该由tamlok.github.io变为vnotex.github.io

How to Repro (如何复现):
从"帮助"选择“关于VNote”，在弹窗中点击访问"Vnote" 链接404

**Comment by tamlok** [comment]
是的，为了迎接vnoex的到来，仓库迁移到vnotex组织下面了，去个人化~vnote后面会发布3.0，目前的就不修复了。

**Comment by aomsweet** [comment]
@tamlok 貌似有大动作呀！😄
