### ISSUE TITLE
表格编辑问题

### ISSUE THREAD

**Issue by RogerYoungh** [vnotex/vnote#1574]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.10

Symptoms (表现): 当我使用 markdown 格式的表格时，每过固定的时间就会自动将表格格式化，文本变化造成了光标的移动，使得不能在输入时等待太长的时间。选择文字也是一样，固定时间光标就会移动。

而且在我选择的等宽字体下，格式化也并不整齐，不知道格式化遵循的时什么格式。

希望这个格式化功能成为能可选的。

How to Repro (如何复现): 使用 markdown 表格输入和选中会遇到。

**Comment by tamlok** [comment]
编辑菜单下面应该有开关？

**Comment by tamlok** [comment]
Should be fixed in beta.5.
