### ISSUE TITLE
是否可以设置从阅读模式切换为编辑模式时，光标不回到文档顶部

### ISSUE THREAD

**Issue by JadeQi** [vnotex/vnote#1575]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
是否可以设置从阅读模式切换为编辑模式时，光标不回到文档顶部

How to Repro (如何复现):
使用快捷键Ctrl + T ，从阅读模式切换到编辑模式时，光标总会回到文档顶部，导致还得重新下滑才能编辑。

**Comment by tamlok** [comment]
目前是根据标题来定位的。后面会直接定位到行，其实VNoteX内测版已经实现了。12月份会发布。

**Comment by JadeQi** [comment]
> 目前是根据标题来定位的。后面会直接定位到行，其实VNoteX内测版已经实现了。12月份会发布。

好的，谢谢
