### ISSUE TITLE
Fail to open folder notes

### ISSUE THREAD

**Issue by mikeyyyzhao** [vnotex/vnote#1577]
OS Version (操作系统): Windows, Linux, macOS
MacOS (Big sur 11.0.1)

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
2.1.0

Symptoms (表现):
When I opened Vnote, it says that the source folder does not exist. However, the folder is definitely there since it's in my dropbox and it's working fine on my other laptop.

I've tried to restart, uninstall and reinstall the app but nothing seems to work

How to Repro (如何复现):
I think I tried to open vnote before _vnote.json was synced through dropbox

**Comment by tamlok** [comment]
So after all the files have been synced, does it work fine?

**Comment by mikeyyyzhao** [comment]
closing this as I think it was an issue with my dropbox sync and the file might have been corrupted
