### ISSUE TITLE
Help with GitHub Actions

### ISSUE THREAD

**Issue by tamlok** [vnotex/vnote#1579]
Hi @miurahr ,

VNote comes back now. And I am referencing your previous GitHub Actions to add CI for it. I encountered an error with `linuxdeploy` action.

https://github.com/vnotex/vnote/runs/1471314919?check_suite_focus=true

Could you please help to take a look?

Many thanks!

**Comment by tamlok** [comment]
It seems that the linuxdeploy action needs a fix?

https://github.com/mojolicious/mojo/pull/1612

**Comment by miurahr** [comment]
Problematic "add-path" seems to be generated with github-actions toolkit.
May it be solved by releasing new one without any change?

**Comment by tamlok** [comment]
is it related to the `core.addpath` call in your action?

**Comment by miurahr** [comment]
It seems to be. Now I found a solution. pls wait a moment.

**Comment by miurahr** [comment]
You are running miurahr/install-linuxdeploy-action@v1.2.0 and  v1.2.1 use the updated `action/core` toolkit that work around it.

**Comment by tamlok** [comment]
> You are running miurahr/install-linuxdeploy-action@v1.2.0, and v1.2.1 (11, Oct) use the updated `action/core` toolkit that work around it.

Oh, thanks! let me try.

**Comment by tamlok** [comment]
changed to v1.2.1, and it complains file missing.

https://github.com/vnotex/vnote/actions/runs/391104388

**Comment by miurahr** [comment]
I made a mistake on release process...
Now v1.3.2 is out and  `miurahr/install-linuxdeploy-action@v1` works.

**Comment by miurahr** [comment]
https://github.com/miurahr/install-linuxdeploy-action-test/actions/runs/392820499
