### ISSUE TITLE
关于markdown-it下部分公式无法渲染的问题

### ISSUE THREAD

**Issue by LTzunan** [vnotex/vnote#1581]
OS Version (操作系统): Windows

VNote Version (VNote版本): 2.10

Symptoms (表现):
部分公式在markdown-it下死活无法渲染，如下
$$
f(t)\to f(at)\begin{cases}a>1,压缩,保持信号的时间缩短\\
\\
0<a<1,扩展,保持信号的时间增长
\end{cases}
$$
结果：
![image](https://user-images.githubusercontent.com/60066337/100861100-5345fb00-34cc-11eb-8ace-b720f8aba51b.png)
其在Hoedown等其它几种模式下都能正常显示（但Hoedown又有必须关闭该笔记重开才会刷新等情况），如：
![image](https://user-images.githubusercontent.com/60066337/100861278-9011f200-34cc-11eb-957a-2eeb7d566418.png)
希望能尽快解决该问题

**Comment by tamlok** [comment]
Hi, vnote 2.x已经不再维护，新版VNote 3.0已经公测发布，可以使用3.0测试一下。windows的二进制文件可以在github actions下面下载。

欢迎在合适的时机升级到3.0~

**Comment by LTzunan** [comment]
> Hi, vnote 2.x已经不再维护，新版VNote 3.0已经公测发布，可以使用3.0测试一下。windows的二进制文件可以在github actions下面下载。
> 
> 欢迎在合适的时机升级到3.0~

那么vnote3的release大概什么时候发布呢？

**Comment by roshiajin-kunai** [comment]
You can download it from here. 你可以在这里下载
https://github.com/vnotex/vnote/actions

For windows - https://github.com/vnotex/vnote/actions/runs/394006392

**Comment by tamlok** [comment]
刚试了一下，好像也不行，后面会修复。

**Comment by tamlok** [comment]
Should be fixed in 3.0 e55434965b5509220f8182fb8b31f9689e7bf4b6

**Comment by LTzunan** [comment]
> Should be fixed in 3.0 [e554349](https://github.com/vnotex/vnote/commit/e55434965b5509220f8182fb8b31f9689e7bf4b6)
> 
> BTW, please use `\\` to new a line:
> 
> ```
> $$
> f(t)\to f(at)\begin{cases}a>1,压缩,保持信号的时间缩短\\
> \\
> 0<a<1,扩展,保持信号的时间增长
> \end{cases}
> $$
> ```

有'\\'的，只是没复制上
![image](https://user-images.githubusercontent.com/60066337/102287812-30105680-3f76-11eb-876e-0533ba62154b.png)
![image](https://user-images.githubusercontent.com/60066337/102287834-3999be80-3f76-11eb-8ceb-47ad7cf62e07.png)

**Comment by tamlok** [comment]
@LTzunan 这是还没换新版吧？

**Comment by tamlok** [comment]
如果旧版，有一个临时解决方案，在大于号小于号左右都插入一个空格即可。
