### ISSUE TITLE
标头显示不全

### ISSUE THREAD

**Issue by rawbin-** [vnotex/vnote#1586]
![image](https://user-images.githubusercontent.com/8169783/101336007-e1e3bf00-38b4-11eb-98c0-59ef664dd7c9.png)

![image](https://user-images.githubusercontent.com/8169783/101336026-e9a36380-38b4-11eb-93e9-26081178d907.png)

**Comment by tamlok** [comment]
请使用markdown-it渲染引擎

**Comment by rawbin-** [comment]
本身用的markdown-it，发现在第五行后加一个空行就行~
