### ISSUE TITLE
添加高亮的语法

### ISSUE THREAD

**Issue by Batianhu1108** [vnotex/vnote#1587]
能否添加高亮的语法，这可能不是Markdown规定的语法，但是Typora支持==Text==这种方式来高亮（这个功能还是挺有用的，用一块特殊背景颜色和字体来突出显示）。尽管已经有`Text`能实现类似的效果，但是两者的用法还是有区别的，`Text`通常用来标记较小范围的名词（或者其他词），而==Text==用来标记大范围的句子。我个人认为这个语法还是很有必要存在并且很有用的。

**Comment by tamlok** [comment]
试试mark

**Comment by Batianhu1108** [comment]
Vnote如何给<mark></mark>添加快捷键？

**Comment by tamlok** [comment]
看一下文档里面的片段的说明，支配一个快捷键（如`a`），然后`Ctrl+E S a`即可。

**Comment by Batianhu1108** [comment]
片段的功能是个亮点，给你点赞
