### ISSUE TITLE
复制粘贴时崩溃

### ISSUE THREAD

**Issue by satnosun** [vnotex/vnote#1595]
如果一个md文件，有一行很长自动折行了，紧挨着的第二行和第三行都有数据时，在第一行处三击选中整行，原位ctrl+v就会崩溃。

**Comment by satnosun** [comment]
例如简单的：

ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
d
d

**Comment by tamlok** [comment]
Hi,

`Ctrl+V`是粘贴，当时候系统剪切板中的内容是什么呢？尝试复制一段纯文本，然后`Ctrl+V`试试？

目前Win下面暂时无法复现。

**Comment by satnosun** [comment]
> Hi,
> 
> `Ctrl+V`是粘贴，当时候系统剪切板中的内容是什么呢？尝试复制一段纯文本，然后`Ctrl+V`试试？
> 
> 目前Win下面暂时无法复现。

说漏了一步，三击选中后先ctrl c，再ctrl v会崩溃

**Comment by tamlok** [comment]
无法复现呀，你哪个操作系统？是VNote 3.0吗？

**Comment by satnosun** [comment]
win10 版本2.10，我试试3.0发自我的华为手机-------- 原始邮件 --------发件人： Le Tan <notifications@github.com>日期： 2020年12月17日周四 20:23收件人： vnotex/vnote <vnote@noreply.github.com>抄送： satnosun <satnosun@163.com>, Author <author@noreply.github.com>主    题： Re: [vnotex/vnote] 复制粘贴时崩溃 (#1595)

无法复现呀，你哪个操作系统？是VNote 3.0吗？

**Comment by satnosun** [comment]
3.0没问题，改用3.0了。多谢指导。

Sent from YoMail

**Comment by jackydi** [comment]
我这里，在2.x下，这个问题偶尔也会出现，通常都是在往代码标签中粘贴的时候出现。比如下面这种：

\```
D:\test1\test2\test3\test3\...这是很深的目录                //粘贴这一行的时候会出现问题
int test()
{
......
}
\```

**Comment by tamlok** [comment]
> 我这里，在2.x下，这个问题偶尔也会出现，通常都是在往代码标签中粘贴的时候出现。比如下面这种：
> 
> ```
> D:\test1\test2\test3\test3...这是很深的目录 //粘贴这一行的时候会出现问题
> int test()
> {
> ......
> }
> ```

2.0的bug就不修了啦。
