### ISSUE TITLE
Missing version information in macOS download 3.0.0.beta.1

### ISSUE THREAD

**Issue by suschizu** [vnotex/vnote#1596]
I noticed that the download doesn't contain a version information
(https://github.com/vnotex/vnote/releases/download/v3.0.0-beta.1/vnote-mac-x64_v3.0.0-beta.1.zip)

<img width="329" alt="Screenshot 2020-12-14 at 11 58 26" src="https://user-images.githubusercontent.com/16004333/102073640-e6076380-3e03-11eb-9320-48b53efbb492.png">

**Comment by tamlok** [comment]
Will try to add the version into the `plist` file. Thank you!

**Comment by suschizu** [comment]
great thanks - the info.plist should contain: 
```
…
<key>CFBundleShortVersionString</key>
<string>x.x.x.x</string>
…
<key>CFBundleVersion</key>
<string>x.x.x.x</string>
…
```

**Comment by tamlok** [comment]
Fixed in beta.3. Thanks!
