### ISSUE TITLE
macos 无法打开 

### ISSUE THREAD

**Issue by oouyezi** [vnotex/vnote#1597]
电脑：mbp 2019 
系统：macos big sur 11.0.1
问题：在任务栏点击后程序不启动

**Comment by tamlok** [comment]
能否在终端输入`./vnote.app/Contents/MacOS/vnote`启动看看有什么信息？

**Comment by oouyezi** [comment]
一直卡着没有输出




| |
胡建清
|
|
immender@163.com
|
签名由网易邮箱大师定制


在2020年12月14日 21:14，Le Tan<notifications@github.com> 写道：

能否在终端输入./vnote.app/Contents/MacOS/vnote启动看看有什么信息？

**Comment by tamlok** [comment]
vnote旧版有问题吗？

有空我找个新版macos确认一下。

**Comment by tamlok** [comment]
Should be fixed. Please try 3.0.0-beta.4.

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/1619
