### ISSUE TITLE
是否可以增加网页内容复制自动转换markdown格式

### ISSUE THREAD

**Issue by Superkeyv** [vnotex/vnote#1598]
经常做笔记需要复制网页内容，包括各个标题、代码块、 列表项、图片。
现在只能剪切纯文字内容，能不能增加一个自动转化网页内容到markdown格式的功能，方便做笔记

**Comment by tamlok** [comment]
hi，这个功能一直在那里，编辑器上右键，解析为markdown并粘贴，即可。

**Comment by Superkeyv** [comment]
> hi，这个功能一直在那里，编辑器上右键，解析为markdown并粘贴，即可。

好的，谢谢
