### ISSUE TITLE
[Feature] Search and jump to  in READ MODE?

### ISSUE THREAD

**Issue by seaspeak** [vnotex/vnote#1599]
Version 2.9.1

Double clicking the search result jumps to the document in EDIT mode. Is that possible to open the document in READ mode?

**Comment by tamlok** [comment]
In vnotw 2.0, the regular expression is not supported in read mode, so it is hard to pass through the full-text search result to read mode. However now in VNote 3.0, the regular expression is supported in read mode, so it is possible to do it. Will do this when mograting full-text search in the near future.

Thanks!
