### ISSUE TITLE
Linux AppImage restart 导致内存中存在多个实例

### ISSUE THREAD

**Issue by ygcaicn** [vnotex/vnote#1612]
**Describe the bug**
Linux下使用AppImage打包的应用， 在restart时导致内存中存在多个实例，（旧的实例没有正常释放）

**To Reproduce**
1. open AppImage
2. Click on Settings->Restart

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/17684070/102691258-1b69e200-4246-11eb-9910-de16d245e853.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: AppImage package

**Comment by tamlok** [comment]
这个很难搞呀，应该怎么重启呢？

**Comment by ygcaicn** [comment]
Creator下编译，debug模式运行没有这个问题。不了解AppImage，不知是否是打包导致的该问题

**Comment by ygcaicn** [comment]
> 这个很难搞呀，应该怎么重启呢？

我尝试在本地编译后按照ci-linux.yml内的流程打包，发现并没有这个问题，很奇怪。。。

不同的是Qt版本不一样，难道是Qt的问题？


```
Qt5_Dir=/opt/Qt/5.15.2/gcc_64
mv AppDir/usr/lib ./
export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH
# copy translations
mkdir -p AppDir/usr/translations
cp $Qt5_Dir/translations/qt_zh_CN.qm AppDir/usr/translations
# package qt5ct (EXTRA_QT_PLUGINS seems not work)
# EXTRA_QT_PLUGINS="platformthemes/libqt5ct.so;styles/libqt5ct-style.so"
mkdir -p AppDir/usr/plugins/platformthemes
mkdir -p AppDir/usr/plugins/styles
cp $Qt5_Dir/plugins/platformthemes/* AppDir/usr/plugins/platformthemes/
cp $Qt5_Dir/plugins/styles/* AppDir/usr/plugins/styles/
# package libssl.so and libcrypto.so
Qt5_Tools=$Qt5_Dir/../../Tools

linuxdeploy-x86_64.AppImage --appdir ./AppDir --plugin qt --output appimage -l $Qt5_Tools/OpenSSL/binary/lib/libcrypto.so.1.1 -l $Qt5_Tools/OpenSSL/binary/lib/libssl.so.1.1
```

**Comment by tamlok** [comment]
You have resolved this issue by yourself! Thank you so much!
