### ISSUE TITLE
Mac版无法正常启动

### ISSUE THREAD

**Issue by selfly** [vnotex/vnote#1619]
3.0版mac上无法启动，现象为图标在Dock上不停的跳，只能强制退出
使用命令行 ./vnote.app/Contents/MacOS/vnote 无任何输出
2.0版可以正常使用
系统：macos high sierra     10.13.6

**Comment by tamlok** [comment]
可能还是共享内存问题，晚点我尝试修一下

**Comment by tamlok** [comment]
Should be fixed. Please try 3.0.0-beta.4.
