### ISSUE TITLE
自适应屏幕

### ISSUE THREAD

**Issue by xk005** [vnotex/vnote#1621]
不能鼠标拖到边框自适应屏幕变大或拖下来变小

**Comment by tamlok** [comment]
设置里面，外观，系统标题栏，勾上重启即可。或者用快捷键win-方向键。

要美观还是要实在，得做个选择了

**Comment by XiaofengdiZhu** [comment]
> 设置里面，外观，系统标题栏，勾上重启即可。或者用快捷键win-方向键。
> 
> 要美观还是要实在，得做个选择了

应该是QT的锅，我的WPF程序不用系统标题栏仍然有此功能
