### ISSUE TITLE
小节序号功能问题

### ISSUE THREAD

**Issue by simaodangan** [vnotex/vnote#1623]
版本：v3.0.0-beta.3
操作系统：Windows 10
问题描述：设置选项`编辑器`->`Markdown`->`小节序号`选中后，使用`#`或`##`等定义的大纲标题并没有自动添加序号。

**Comment by tamlok** [comment]
阅读模式下会添加，不强行修改文件了。

**Comment by pysense** [comment]
> 阅读模式下会添加，不强行修改文件了。

好像已经习惯自动添加序号了，能不能考虑做个选项？

**Comment by tamlok** [comment]
ok

**Comment by jackydi** [comment]
这个功能很实用，希望能做成选项。

**Comment by tamlok** [comment]
Supported in 3.0.0-beta.4.
