### ISSUE TITLE
3.2打开原有的mdwenjian会多几行格式符

### ISSUE THREAD

**Issue by cuijianzhe** [vnotex/vnote#1624]
**Describe the bug**

**To Reproduce**
引用原有的md文件夹
打开md文件

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.0.0]

**Additional context**
![image](https://user-images.githubusercontent.com/48144475/102950210-1f775780-4505-11eb-85bf-ef3c6dbeb76a.png)

**Comment by tamlok** [comment]
不懂，啥意思？具体一点？

**Comment by cuijianzhe** [comment]
> 不懂，啥意思？具体一点？

就是我用3.0的vnote打开之前2.0的笔记之后，笔记显示出来的话就变了，而且每个文件都会有 “{: id="20200917181038-dmwxqwx"}”这种信息。
![image](https://user-images.githubusercontent.com/48144475/102951034-dc1de880-4506-11eb-92cd-3fc08b57aa20.png)

**Comment by tamlok** [comment]
`{id}`的这种做法绝对不是vnote添加的，应该是思源笔记其他笔记什么的吧？你是不是有用过其他笔记软件编辑过该文件？找一个最近没有打开编辑过的试试。

**Comment by cuijianzhe** [comment]
> `{id}`的这种做法绝对不是vnote添加的，应该是思源笔记什么的用于支持双向链接的吧？你是不是有用过其他笔记软件编辑过该文件？找一个最近没有打开编辑过的试试。

对的，看来是这样……，应该是我用过思源的打开过就成这样了，谢谢
