### ISSUE TITLE
关于部分快捷键无法使用

### ISSUE THREAD

**Issue by yyy33** [vnotex/vnote#1625]
**Describe the bug**
按control+数字键插入不了标题，没反映

**To Reproduce**
就是正常的编辑markdown文件，刚刚下载的时候可以用，用了几十分钟就不能用了

**Expected behavior**
希望可以正常插入标题

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]windows10
 - Version [e.g. 3.0.0]

**Additional context**

**Comment by tamlok** [comment]
看一下是不是输入法或者其他软件快捷键冲突了

**Comment by yyy33** [comment]
> 看一下是不是输入法或者其他软件快捷键冲突了

谢谢，是和我的输入法冲突了。
