### ISSUE TITLE
A few questions about v3

### ISSUE THREAD

**Issue by mkpaz** [vnotex/vnote#1627]
Hey, I'm using VNote for 2 years. I think it's highly underrated by community and actually one of the best note taking apps, esp because of how it handles images. I make a huge amount of screenshots for my notes, so it's just wow. Much thanks for your work! I've tried v3 recently and it's obvious how much has been changed, but some v2 features haven't been implemented (yet?), so could you be so kind to clarify some questions:

1. You've mentioned that VNoteX will support some premium features. Could you please be more specific, what features do you mean? 
2. I use VNote on Linux desktop. Sadly, AppImage doesn't pick default QT theme, so native theme looks real ugly on GTK based systems. v2 does support custom themes (and I made my own one). In v3 I can't even change default font family :-) Is something changed about UI customization? I mean an ability to customize both QSS and CSS is essential.
3. Full text search support?

**Comment by tamlok** [comment]
Hi,

All features of 2.0 will be migrated to 3.0 eventually. Here is the progress check of the migration (https://github.com/vnotex/vnote/projects/1).

About the premium features, currently I do not have concrete ideas. All features of 2.0 will surely be open source.

VNote is 4 years old now. But the community has not growed much yet. There is still only one person doing the whole work. To help making it advance further and longer, I need some power. :) So it comes the VNoteX.

Thank you for your attention and love about VNote!

**Comment by mkpaz** [comment]
> VNote is 4 years old now. But the community has not growed much yet. There is still only one person doing the whole work.

It's because of lack of promotion I suppose. It's hard to find VNote even if you're know what you're searching for. It's almost not advertised in English-speaking community. You could try to post some news on Reddit (`/r/kde`, `/r/NoteTaking`) or even create your own one (like BoostNote and Notable devs did). Update README - ask people to vote for VNote on Github and Slant.co. Create `CONTRIBUTING.md` if you're searching for contributors. There's also a lot of Chinese in issue tracker. Many people tend to avoid such projects, because it's somewhat frustrating. If you can't read any issue, how you will be to commit to that project...

I would be glad to make a contribution to VNote since it's one of my everyday apps, and considering top notch image support it has zero alternatives, but I'm a Java coder. So I can only come with ideas, but I'm sure you have plenty of them :-) and not much time for actual implementation.
