### ISSUE TITLE
文件隐藏

### ISSUE THREAD

**Issue by chenjiazhi1014** [vnotex/vnote#1630]
对于软件生成的文件及文件夹  能做成隐藏文件及文件夹吗？

**Comment by tamlok** [comment]
隐藏了的话，一些同步软件默认是不会同步隐藏文件的，会造成大量用户不知所措。

**Comment by chenjiazhi1014** [comment]
如果是采用同一个软件应该是会重新生成这个隐藏软件，而使用不同个软件应该不会出现加载不出来的吧？

**Comment by l1422586361** [comment]
能改成可配置的吗？软件生成的文件及文件夹，我试着改源码里的配置常量，发现编译后没有生效（不太懂c）

**Comment by l1422586361** [comment]
换了一个机器编译可以了，估计是编译有缓存的问题o(╥﹏╥)o
