### ISSUE TITLE
关于旧版本在linux上fcitx输入法的支持问题

### ISSUE THREAD

**Issue by ZuoAnZoom** [vnotex/vnote#1640]
**fcitx在2.9.1版本上就可以正常输入文字，但是在2.10上不行**，试了好多遍都是一样的结果，都是直接用 Appimage 打开的，对2.10尝试过检查qt的库等等一系列问题，都是正常的。
虽然知道2.xx的版本已经停止维护了，但是真的挺好用的。有点想不明白为什么2.9.1上就正常，换到2.10就不行了。

 - OS: ubuntu18.04

**Comment by tamlok** [comment]
Hi,

AppImage是可以解压缩出来的，里面应该是少了`libfcitx*.so`的文件，复制回去即可。

参考： https://github.com/vnotex/vnote/issues/1505#issuecomment-726603598

**Comment by ZuoAnZoom** [comment]
好的，非常感谢
