### ISSUE TITLE
plantuml支持 ASCII Art，请问如何在vnote中开启

### ISSUE THREAD

**Issue by jimorsm** [vnotex/vnote#1642]
vnote支持plantuml，默认生成图片。我注意到plantuml支持ASCII Art，请问如何在vonte中开启？
https://plantuml.com/zh/ascii-art

**Comment by tamlok** [comment]
Hi，

由于这个场景普适性不强，所以vnote里面就不支持了。或者后面可以提供这样一个插件，允许用户粘贴一段puml的代码，然后生成ASCII Art，用户再复制走。

谢谢！
