### ISSUE TITLE
windows下3版本，vim模式，不支持:wq 这种命令？可输入，但不生效

### ISSUE THREAD

**Issue by hyperwd** [vnotex/vnote#1643]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.0.0]

**Additional context**

**Comment by tamlok** [comment]
还没实现

**Comment by ooing** [comment]
@tamlok   目前编辑支持vim模式吗

**Comment by tamlok** [comment]
支持

**Comment by ooing** [comment]
@tamlok  我在设置里面 没有找到  我的版本是3.1.0

**Comment by tamlok** [comment]
> @tamlok 我在设置里面 没有找到 我的版本是3.1.0

文本编辑器，输入模式，vi
