### ISSUE TITLE
3.0.0-beta.4 功能缺失

### ISSUE THREAD

**Issue by Linjj** [vnotex/vnote#1652]
1、导出pdf/html功能看不到了
2、编辑markdown的时候，表格按钮点击没反应，日志如下
![image](https://user-images.githubusercontent.com/10056177/104141669-da9f5c00-53f2-11eb-8cdc-f91577cf4a21.png)

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/104142334-1982e100-53f6-11eb-9acd-6ee1d2f74e45.png)

beta就是还没正式发布的版本，都在慢慢迁移，具体看GitHub Projects。表格在beta.5支持了。
