### ISSUE TITLE
关于启动后恢复上次退出时的工作状态

### ISSUE THREAD

**Issue by Vandalizegod** [vnotex/vnote#1653]
新版本的VNote下载后，我在设置找了一下，没找到老版本里“继续上次退出时的页面”选项。
我个人很重视这个选项，因为它可以让我迅速恢复头一天的工作状态。但老版本这个选项问题很多，实际上没效果，希望在新版本得到改进。
1. 老版本必须在退出软件的时候才能保存退出时的页面，这在实际工作中几乎不可能，因为我开机自启动VNote，关机的时候也不会关闭，但关机的时候并不会保存该设置。**建议新版本每次打开或关闭文件时实时保存相应状态。**
2. VNote允许切割多个窗口，我一般会将窗口分成三个，左右窗口用于放参考资料，中间窗口是主要工作区。但重启后并不会保存这个状态，所以每次开机后还要专门调整窗口，很麻烦。**建议新版本实时保存该状态，包括工作空间，窗口切割，每个切割出来的窗口上打开的文件，切割的窗口调整后的大小等等。**

**Comment by tamlok** [comment]
3.1.0 已经可以完全恢复整个会话状态。发现漏了打开或关闭文件时保存状态，后面加上。你有空可以验证一下。谢谢！
