### ISSUE TITLE
阅读模式的小节序号起始层级和大纲中的小节序号

### ISSUE THREAD

**Issue by simaodangan** [vnotex/vnote#1655]
版本：v3.0.0-beta.6
环境：Windows 10 x64

功能建议1：实现阅读模式设置小节序号起始层级。
原因：目前阅读模式从二级标题(`##`)开始设置小节序号，这样如果笔记以一级标题(`#`)作为大纲，则不会被设置序号

功能建议2：实现大纲显示中的小节序号
原因：对于较长的笔记，那么从大纲中直接点击跳转是个方便的方法。但是如果标题较多，或者层级较多，寻找大纲标题也需花费功夫，如果此时大纲中也显示序号，则会方便很多。

感谢作者的工作！

**Comment by tamlok** [comment]
* [x] 阅读模式已经支持指定小节序号起始层级了（1、2、3）；
* [ ] 大纲这个后面再添加。
