### ISSUE TITLE
文件夹链接无法打开

### ISSUE THREAD

**Issue by ngvjai** [vnotex/vnote#1656]
deepin 20.1 操作系统，源码编译 v3.0.0-beta.4 版本，发现之前用的文件夹链接点击没有反应。文件夹的链接是通过链接功能生成，指定文字，然后在给出文件夹路径。
![截图录屏_选择区域_20210112151600](https://user-images.githubusercontent.com/17464867/104281870-20d6e700-54e9-11eb-9c8b-abc6a64f3832.png)

**Comment by tamlok** [comment]
beta.7修复了。
