### ISSUE TITLE
工具栏建议

### ISSUE THREAD

**Issue by xxxmailk** [vnotex/vnote#1657]
**Is your feature request related to a problem? Please describe.**
我在ubuntu下使用vnote的时候，按ctrl+alt+F无法唤出高级查找功能，具体是什么原因不清楚，也许是快捷键冲突

**Describe the solution you'd like**
是否可以在顶部增加一个工具下拉列表或者工具栏位，当快捷键无法使用的时候依然可以通过下拉列表唤出工具。

**Comment by tamlok** [comment]
如果是3.0，全文搜索还没实现。

**Comment by xxxmailk** [comment]
好的，感谢，编辑器很不错
