### ISSUE TITLE
特殊字符显示异常

### ISSUE THREAD

**Issue by l1422586361** [vnotex/vnote#1658]
版本：beta-6

以下是编辑模式的显示
![image](https://user-images.githubusercontent.com/32669129/104469307-58ca5100-55f3-11eb-810a-4fedd7b431b7.png)
以下是阅读模式的显示
![image](https://user-images.githubusercontent.com/32669129/104469386-6c75b780-55f3-11eb-9995-99c93ce3445d.png)

以下是原vnote的显示
![image](https://user-images.githubusercontent.com/32669129/104469433-7992a680-55f3-11eb-81e3-8d8bf82e8bd9.png)

**Comment by l1422586361** [comment]
- **可以输入含有^%&',;=?$\"等字符：**`[^%&',;=?$\x22]+`

**Comment by tamlok** [comment]
$是公式标记，旧版默认不打开，所以没有渲染，新版默认打开了，\转义一下即可
