### ISSUE TITLE
vnote 3.0 beta5文件管理方面的几个bug

### ISSUE THREAD

**Issue by Superkeyv** [vnotex/vnote#1659]
**Describe the bug**
1. 从'导航‘页面重命名笔记时，如果笔记名从首字母小写改为大写，程序认为该笔记名字和已有笔记冲突，修改失败。
2. 'vx.json'中’file'部分的文件项重复。如何复现我不太记得了，应该是拷贝、删除、或者移动文件位置出现的这个问题
3. 在Linux系统下默认使用本程序打开'markdown'文件，使用文件管理器dolphin，双击打开‘markdown'文件会启动vnote，但是并没有打开该’markdown'文件

**Comment by tamlok** [comment]
Should be fixed.
