### ISSUE TITLE
New Notes from File导入外部笔记不能显示图片

### ISSUE THREAD

**Issue by Tridu33** [vnotex/vnote#1660]
New Notes from File导入外部笔记不能显示图片

我有一个外部笔记+图片文件夹images.然后我把笔记和文件夹都复制到一个文件目录中，接着我“New Notes from File”导入：
```
![v8-LLVM-IR-WebAssembly](.\images\v8-LLVM-IR-WebAssembly.png)
```
编辑状态能正确看图片，预览状态ctrl +T后显示不了图片

**Comment by tamlok** [comment]
url的路径里面应该使用/

这是2. x版本吧，不维护了。3.0导入外部文件会自动复制图片。
