### ISSUE TITLE
非笔记本下的文件无法正常打开

### ISSUE THREAD

**Issue by qtxiaofei** [vnotex/vnote#1661]
**Describe the bug**
非笔记本下的的md文件双击后，只可以启动VNote，但内容无法显示

**To Reproduce**
1. 比如，我在笔记本建在D盘，而E盘有其他的md文件。现在需要打开E盘文件预览
![image](https://user-images.githubusercontent.com/53969204/104591447-ab654500-56a7-11eb-91a3-844e49349789.png)
![image](https://user-images.githubusercontent.com/53969204/104591605-e6677880-56a7-11eb-836d-fe49d0deaa33.png)
2. 从上图图标可以看到，系统的md文件已经默认使用VNote方式打开。
3. 双击打开README.md文件，VNote软件会打开，但无法显示内容。

**Expected behavior**
希望在非笔记本路径下的md文件可以直接打开，预览修改。不用把所有的md文件都放在现有的笔记本下面

**Desktop (please complete the following information):**
 -  Windows 10 家庭版
 - Version  3.0.0

**Comment by tamlok** [comment]
先拖进去，还没迁移

**Comment by tamlok** [comment]
Fixed.
