### ISSUE TITLE
3.x能否恢复2.x版本的笔记排序功能

### ISSUE THREAD

**Issue by gueeisgrim** [vnotex/vnote#1662]
笔记排序功能非常重要，这样我不用每次都是把文章加在末尾，能否在3.x中恢复谢谢。

**Comment by luhua2018** [comment]
同求

**Comment by tamlok** [comment]
能。我现在是忙不过来，还在逐步迁移，可以看准时机再入坑3.0

**Comment by gueeisgrim** [comment]
其实还有个建议，最好支持csv格式的表格，这样子功能就全了。
比如可以插入一堆csv内容，显示为表格
