### ISSUE TITLE
怎么感觉最新的3.0不如2.*系列好用了呢 界面上少了几个窗口也没有导出功能了？

### ISSUE THREAD

**Issue by windoversnow** [vnotex/vnote#1663]
怎么感觉最新的3.0不如2.*系列好用了呢 界面上少了几个窗口  也没有导出功能了？

**Comment by tamlok** [comment]
功能还在迁移中呢，大哥！https://github.com/vnotex/vnote/projects/1

就是beta公测版而已，自己决定啥时候从2到3迁移即可。

**Comment by windoversnow** [comment]
好的 大佬
