### ISSUE TITLE
简书网页解析Markdown Bug

### ISSUE THREAD

**Issue by jluliuchao** [vnotex/vnote#1664]
描述：
复制简书网页上的内容，粘贴到VNote(2.x或3.x版本)后，文字格式显示错误，不显示图片。

复现方法：
复制此网页(https://www.jianshu.com/p/8dfb5b7c020f) 中文字和图片内容，在Vnote中新建笔记，右键选择“解析为Markdown并粘贴”，进入阅读模式后显示如下：

![image](https://user-images.githubusercontent.com/35259060/104810761-d5e30980-5831-11eb-9180-e0f6a5df7103.png)
进入编辑模式后，发现其图片链接前确少https:，文字前多了很多空格，导致显示错误，如下：

![截屏2021-01-16 下午7 33 56](https://user-images.githubusercontent.com/35259060/104810846-67eb1200-5832-11eb-95ae-48d62824e388.png)

**Comment by jluliuchao** [comment]
另外，在3.0Beta6上发现，在网页上复制图片链接，到VNote笔记中右键"多功能粘贴"->"插入为图片"后，在编辑模式下看不到图片，在阅读模式下能看到图片。2.9版本没有这个问题。

**Comment by tamlok** [comment]
1. 第一个问题已经解决了，空格是因为原来的文章就有首行缩进空格；
2. 这是因为这些下载下来的图片虽然是PNG后缀，但是是`webp`格式，Qt官方好像默认暂时不支持这种格式；
