### ISSUE TITLE
Debian下无法正常运行软件提示--no-sandbox

### ISSUE THREAD

**Issue by ciscochao** [vnotex/vnote#1665]
**Describe the bug**
Debian下无法通过root账户正常运行软件提示--no-sandbox
⚡  Soft  ./vnote-linux-x64.AppImage 
[308547:308547:0119/173502.414196:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by tamlok** [comment]
所以应该是QtWebEngineProcess (Chrome) 的bug了？有啥解决办法？

**Comment by ciscochao** [comment]
> 所以应该是QtWebEngineProcess (Chrome) 的bug了？有啥解决办法？

`./vnote-linux-x64.AppImage --no-sandbox`可以正常运行，但是在创建新笔记时会提示无法在root目录下创建等字样~准备回退到2.8.1版本

**Comment by tamlok** [comment]
能新建新建一个用户组给vnote运行吗？然后把笔记本文件夹的权限给这个用户组，应该没问题？一定要用root？
