### ISSUE TITLE
Hi,could you perfect the Vim?

### ISSUE THREAD

**Issue by wyhhh** [vnotex/vnote#167]
Recent days,I learn Vim a a lot,it can improve efficiencies yet.But I can't use such `.` command(repeat command) in Vim mode,so can you add more features of Vim?

**Comment by tamlok** [comment]
Vim mode in VNote is implemented from scratch. Currently I have no idea how to support the dot command. Will look back to it in the future.

**Comment by tamlok** [comment]
VNote 3.0 uses `KateVi` which is more complete.
