### ISSUE TITLE
选择“从文件夹新建笔记本”的时候可能会卡到失去响应

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#1671]
**描述**
简单来说就是选择“从文件夹新建笔记本”的时候，如果该文件夹又内容，会导致vnotex

卡到失去响应。剩下的看图释义

![Snipaste_2021-01-25_13-06-17](https://user-images.githubusercontent.com/40653617/105663811-26cbbf80-5f0e-11eb-98c0-749d2338e6a2.png)

**Comment by tamlok** [comment]
应该是正在导入文件吧，晾它一段时间就好了？
