### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by wanghao931212** [vnotex/vnote#1674]
**Describe the bug**
我在执行源码编译的时候出现了报错，就在执行make的时候
      /home/***/Vnote/vnote-3.0.0-beta.6/libs/vtextedit/src/editor/textedit/vtextedit.cpp: In member function ‘void vte::VTextEdit::setTabStopWidthInSpaces(int)’:
/home/***/Vnote/vnote-3.0.0-beta.6/libs/vtextedit/src/editor/textedit/vtextedit.cpp:507:5: error: ‘setTabStopDistance’ was not declared in this scope
     setTabStopDistance(QFontMetrics(font()).width(QLatin1Char(' ')) * m_tabStopWidthInSpaces);
     ^~~~~~~~~~~~~~~~~~
/home/***/Vnote/vnote-3.0.0-beta.6/libs/vtextedit/src/editor/textedit/vtextedit.cpp:507:5: note: suggested alternative: ‘setTabStopWidth’
     setTabStopDistance(QFontMetrics(font()).width(QLatin1Char(' ')) * m_tabStopWidthInSpaces);
     ^~~~~~~~~~~~~~~~~~
     setTabStopWidth

**To Reproduce**
cd vnote.git
mkdir build
cd build
qmake ../VNote.pro
make    //执行到这一步的时候出现了报错
sudo make install

我的系统是Ubuntu18.04.5 LTS

**Comment by tamlok** [comment]
qt版本？

**Comment by wanghao931212** [comment]
你好，qt版本：5.9.9

**Comment by tamlok** [comment]
邮件里不是说了要5.12吗？那个文档是旧版的。

**Comment by wanghao931212** [comment]
你好，我重新安装了5,12的qt，但是执行make的时候还是报错，显示vnote.git/libs/vtextedit/src/editor/textedit/vtextedit.cpp    error‘setTabStopDistance’ was not declared in this scope，我感觉这个应该个QT这个工具没关系，是这个源码里这个方法的问题，我在vnote.git目录下搜索，只在这个类里面找到这一个，没找到申明这个方法的地方！

**Comment by tamlok** [comment]
https://doc.qt.io/qt-5/qplaintextedit.html#tabStopDistance-prop

`qmake -v`

确认你用的qt是你安装的那个qt

**Comment by wanghao931212** [comment]
虽然我安装了qt5.12.9，但是qmake -v显示还是用的5.9.9的，这个该怎么切换呀

**Comment by tamlok** [comment]
用绝对路径吧，不懂就网上多搜一下吧

**Comment by wanghao931212** [comment]
我切换到使用5.12.9了，现在qmake -v显示如下，但是make还是报错
QMake version 3.1
Using Qt version 5.12.9 in /home/wanghao/snap/Qt5.12.9/5.12.9/gcc_64/lib

**Comment by wanghao931212** [comment]
你能把你那使用的打包一份发我吗？我总感觉我从Github上下载的文件有缺失

**Comment by tamlok** [comment]
我的也是GitHub下载的，和源码无关，就是编译器的问题吧。自己对比一下CI的log吧。

https://github.com/vnotex/vnote/runs/1695322179?check_suite_focus=true
