### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Linjj** [vnotex/vnote#1679]
- 支持使用浏览器打开笔记，类似 Markdown Pad 的预览功能
- 支持导出为HTML/PDF，自动生成大纲或目录
- 支持剪切板图片或图片路径自动转base64，这个对于导出html比较友好，不需要图床和图片附录，方便笔记共享
- 支持区域批量编辑（ALT+鼠标选中），比如批量删除连续几行前面的空格，这对笔记排版比较友好
- 支持快速表格，2.0是有该功能的，3.0的表格按钮用不了

**Comment by tamlok** [comment]
1. 是指双边预览吧？
2. 旧版支持
3. 旧版支持导出为单个html文件，导出html的时候，各种选项看看
4. 还没支持
5. 最新版已经支持

**Comment by Linjj** [comment]
1指的是类似导出html后到浏览器打开，html是个临时文件的效果。主要用于预览导出效果。

嗯，目前已经升级到3.0-beta6了，3.0的从文件夹创建笔记本功能很好用，这点2.0没有，就比较难搞。

期待最新稳定版本的发布，感谢你的答复
