### ISSUE TITLE
C#代码高亮问题

### ISSUE THREAD

**Issue by myaircastle** [vnotex/vnote#1680]
**C#** 代码在编辑状态下都是统一的颜色,，不能实时预览关键字高亮（Windows系统）。

“编辑模式”和“阅读模式”的代码高亮截图：
![1](https://user-images.githubusercontent.com/60167528/106358461-60099280-6347-11eb-88f7-9b0974280ba0.png)
![2](https://user-images.githubusercontent.com/60167528/106358465-63048300-6347-11eb-884d-f6b3856f5043.png)

**Comment by tamlok** [comment]
cs或者c#看看那个吧

**Comment by myaircastle** [comment]
> cs或者c#看看那个吧

感谢回复，使用“cs”成功解决。
