### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by kukuxiahuni** [vnotex/vnote#1682]
# 背景
电脑外接显示器场景
# 描述
电脑外接显示器时，由于两个显示器的分辨率并不一致。导致笔记本在两个显示器之间拖动的时候，工作区、文字的大小等都没有进行自适应。
# 期望
虽然属于体验方面的优化，但还是请考虑有空支持一下

**Comment by tamlok** [comment]
hi，这是qt的问题，基本做不到，只能哪个显示器启动就在哪个显示器上面使用了。官方的qtcreator也处理不好不同dpi的适配问题。

或者，看看exe右键属性，调节一下windows里面dpi的情况？比如使用独立dpi或者不跟随系统变化之类，尝试一下吧。

**Comment by cxheny** [comment]
这一点我也遇到了，V3.0好像无法解决这个问题，但是使用V2.10就没这个问题，完全可以自适应界面大小。
