### ISSUE TITLE
3.0 关于使用 Ctrl+Shift+V 粘贴时点击取消的问题

### ISSUE THREAD

**Issue by LightAPIs** [vnotex/vnote#1684]
**Describe the bug**
在 3.0.0-beta.6 中使用快捷键 Ctrl+Shift+V 进行粘贴弹出"从剪贴板插入"对话框的过程中，点击取消按钮会经常无响应，很多时候需要点多次对话框才会关闭，直接点击右上角的关闭按钮则无此问题。

**To Reproduce**
1. 打开笔记
2. 按下 Ctrl+Shift+V 进行粘贴
3. 点击取消按钮
_多试几次，很容易复现。_

**Expected behavior**
点击取消按钮后如同点击右上角关闭按钮一下正常关闭对话框

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.0-beta.6

**Comment by tamlok** [comment]
这是要双击的呢，试试。

**Comment by LightAPIs** [comment]
原来如此，了解了。
