### ISSUE TITLE
笔记本怎样退回到2版

### ISSUE THREAD

**Issue by zoubei** [vnotex/vnote#1685]
中午好，很棒的软件。就是升级到3版，发现还不是完全体，有没有办法可以倒回到2版，谢谢！

**Comment by supengchuan** [comment]
记得在升级的时候作者有提醒，但是我还是义无反顾的升级，最后才发现是半成品，最近用的比较难受。好像是退不回去的

**Comment by tamlok** [comment]
退不回去了，除非自己写脚本。

可以暂时用旧版本的 浏览器  面板打开新的笔记本，作为外部文件编辑。

**Comment by gaospecial** [comment]
朋友们，我刚刚完成了一个转换器，可以将 3.x 版本的笔记本转换为 2.x 的笔记本。虽然不是完美转换，但是自己测试还能用。

软件使用 `R` 语言写成，地址在 https://github.com/gaospecial/vnoteTransformer 

VNote 这么好用的工具，希望早日完善 3.x 版本的功能！

**Comment by LiuYang-1997** [comment]
我记得不是有2.x的安装包么

**Comment by gaospecial** [comment]
> 我记得不是有2.x的安装包么

https://github.com/vnotex/vnote/releases/tag/v2.10

**Comment by tamlok** [comment]
@LiuYang-1997 应该是指笔记本数据格式的回退

**Comment by LiuYang-1997** [comment]
@tamlok 哦哦哦

**Comment by juzijun233** [comment]
> 朋友们，我刚刚完成了一个转换器，可以将 3.x 版本的笔记本转换为 2.x 的笔记本。虽然不是完美转换，但是自己测试还能用。
> 
> 软件使用 `R` 语言写成，地址在 https://github.com/gaospecial/vnoteTransformer
> 
> VNote 这么好用的工具，希望早日完善 3.x 版本的功能！

这个工具应该没法恢复比2.0里的标签吧？

**Comment by gaospecial** [comment]
> > 朋友们，我刚刚完成了一个转换器，可以将 3.x 版本的笔记本转换为 2.x 的笔记本。虽然不是完美转换，但是自己测试还能用。
> > 软件使用 `R` 语言写成，地址在 https://github.com/gaospecial/vnoteTransformer
> > VNote 这么好用的工具，希望早日完善 3.x 版本的功能！
> 
> 这个工具应该没法恢复比2.0里的标签吧？

我自己的笔记都没有打标签，所以也没有测试过。目前应该是不支持的。

**Comment by my36z** [comment]
好像把配置文件删掉就好了，只是文档 排序丢了
