### ISSUE TITLE
建议优先添加的功能

### ISSUE THREAD

**Issue by coder163** [vnotex/vnote#169]
- 表格加强
   - 最近在编写API接口说明,大量用到了表格,真的很苦逼
- Git同步
   - 无论自己笔记还是项目说明文档都需要提交到GitHub上,每次写完切换出去有点蛋疼,如果能接入本地的Git Bash更好
  - 推送博客,这个不知道怎么表达,每次都是写好复制粘贴过去,但是没有发现一个比较好的编辑器,大部分都不支持,不清楚原因,如果能加上更好
- **最后:自从知道这个软件,一直爱不释手,加油**

**Comment by tamlok** [comment]
Hi,

- 表格主要是我用得少，暂时没什么设计上的想法，得想想。VNote里面的大部分功能基本都是按照自己的日常心得来设计的。目前表格有两个想法，一个是完全原地维护纯文本，一个是弹出一个电子表格。
- 写Github上的文档，可以把VNote当前一个编辑器来打开需要编辑的文件，比如可以把VNote设置为md格式的默认打开方式，双击即可编辑。VNote所有相关的文档都是通过这种方式来使用VNote编写的，图片也能支持。后面会添加一个文件导航栏，方便编辑外部文件。Git的同步会在2.0之后考虑。
- 不知道您用的是什么博客呢？VNote提供一个个性复制功能，比如复制到微信公众号，复制到OneNote等等，可以右键菜单试试。

谢谢！

**Comment by coder163** [comment]
1. 表格个人建议，能够设置快捷键，当按下快捷键弹出对话框类似typora的这种，但是选择完最好还是原地展示效果，保持现在的风格
2. 个人建议最好是能将控制台或者git bash中的内容展示在笔记中，类似Editplus的那个输出窗口一样
3. 我用的是博客园,干净
非常感谢您能回复我





 
发件人： Le Tan
发送时间： 2018-03-22 21:39
收件人： tamlok/vnote
抄送： 舞动的代码; Author
主题： Re: [tamlok/vnote] 建议优先添加的功能 (#169)
Hi,
表格主要是我用得少，暂时没什么设计上的想法，得想想。VNote里面的大部分功能基本都是按照自己的日常心得来设计的。目前表格有两个想法，一个是完全原地维护纯文本，一个是弹出一个电子表格。
写Github上的文档，可以把VNote当前一个编辑器来打开需要编辑的文件，比如可以把VNote设置为md格式的默认打开方式，双击即可编辑。VNote所有相关的文档都是通过这种方式来使用VNote编写的，图片也能支持。后面会添加一个文件导航栏，方便编辑外部文件。Git的同步会在2.0之后考虑。
不知道您用的是什么博客呢？VNote提供一个个性复制功能，比如复制到微信公众号，复制到OneNote等等，可以右键菜单试试。
谢谢！

**Comment by tamlok** [comment]
It is supported already in VNote 2.0 and will be migrated to 3.0 soon.
