### ISSUE TITLE
能否添加按时间展示的视图？

### ISSUE THREAD

**Issue by empty-id** [vnotex/vnote#1692]
有时候笔记太多按照树结构组织的笔记也不足以检索，希望能添加按照时间顺序展示最近自己修改（或者创建）的笔记，类似博客一样。

**Comment by empty-id** [comment]
看到最新版更新说支持多种顺序，试了一下没弄懂在哪里设置、怎么使用……

**Comment by tamlok** [comment]
https://b23.tv/K4gGgx

**Comment by empty-id** [comment]
哦……我知道为什么了，在暗黑主题下那个按钮不显示……浮动上去才能看到那个调整顺序的按钮

**Comment by tamlok** [comment]
都是浮动才显示的

**Comment by empty-id** [comment]
哦，好的，谢谢！
