### ISSUE TITLE
2.10 Linux AppImage包诸多问题

### ISSUE THREAD

**Issue by EL-File4138** [vnotex/vnote#1695]
**Describe the bug**
1. 「持续触发」Rime输入法无法使用（不弹出选词框直接输入了字母）
2. 「随机触发」有些弹出窗口会变成黑框但里面的输入控件等等还能用
3. 「随机触发」会无故弹出无响应弹窗但应用没有锁死
4. 「持续触发」基本上只要一打开笔记文件就会锁死，~~有时候~~还会锁住整个GNOME桌面，只能重启恢复
5. 「持续触发」4崩溃/强停后再次打开依然会闪退（不弹出界面），需要打开两次才能显示界面

**To Reproduce**
1. 使用2.10版本的AppImage打包版
2. 启动后随意打开一个文件
3. 在渲染过程中/渲染完成后首次交互时界面锁死
4. GNOME弹出无响应弹窗
5. GNOME时间控件锁死，鼠标锁死，键盘灯锁死

**Expected behavior**

**Screenshots**
Bug 1
![图片](https://user-images.githubusercontent.com/28867264/108619751-c9218900-7461-11eb-9563-1fbac1fad608.png)

Bug 2
![图片](https://user-images.githubusercontent.com/28867264/108619710-88c20b00-7461-11eb-86e0-8d8b0e40144e.png)

Bug 3
![图片](https://user-images.githubusercontent.com/28867264/108619768-ef472900-7461-11eb-8091-ec83f91d1a2d.png)

4/5无法截图

**Desktop (please complete the following information):**
 - OS: Fedora release 33 (Thirty Three) Linux <hostname> 5.10.15-200.fc33.x86_64 #1 SMP <install_time> x86_64 x86_64 x86_64 GNU/Linux
 - Version: 2.10

**Additional context**

**Comment by tamlok** [comment]
不维护了啦，试试3.0吧
