### ISSUE TITLE
vim 模式复制问题

### ISSUE THREAD

**Issue by supengchuan** [vnotex/vnote#1704]
**Describe the bug**
使用 vim 模式编辑时, ctl+c 无法复制内容, 而在阅读模式下是能够复制的

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - Version [ 3.0.0-beta8]

**Comment by tamlok** [comment]
`Ctrl+C`是终止命令或者回到正常模式，后面会加配置容许设置是否按照Vi的映射来处理`Ctrl+C`。

**Comment by tamlok** [comment]
经过再三考虑，目前还是不会将`Ctrl+C`变为复制，因为`Ctrl+V`是不可能变成粘贴的（后面会支持块模式），所以为了一致，就都统一按照Vi来处理了。

要复制到系统剪切板，请使用`“+y`，后面会配置leader按键，允许`<space>+y`复制。
