### ISSUE TITLE
支持Window的窗口最大最小化快捷键

### ISSUE THREAD

**Issue by llzywhy** [vnotex/vnote#1705]
- 支持Window的最大最小化快捷键，例如：

> Windows+M：最小化所有窗口
> Windows+Shift+M：还原最小化的窗口
> 
> Alt+Space+N：最小化当前窗口
> Alt+Space+X：最大化当前窗口

- 点击状态栏图标最大最小化窗口

**Comment by tamlok** [comment]
把系统标题栏勾上：

![image](https://user-images.githubusercontent.com/5763157/109442191-743dce00-7a72-11eb-83a0-94357121681e.png)

**Comment by llzywhy** [comment]
系统标题栏勾上之后确实可以了，不过多了个标题栏，影响了美观，哈哈哈
