### ISSUE TITLE
3.x版本啥时候弄出来以前2.x版本有的那些功能？

### ISSUE THREAD

**Issue by littleheary** [vnotex/vnote#1709]
现在升级上去，笔记我也给转换了。
不知道该咋办了。。。。。

**Comment by tamlok** [comment]
在赶了。

如果急的话，可以: https://github.com/vnotex/vnote/issues/1685#issuecomment-784820052

或者用2.0编辑外部文件的方式来编辑3.0的笔记。

**Comment by littleheary** [comment]
可以开发出来协作的功能么？就是团队协作编辑文档的那种。

**Comment by tamlok** [comment]
协作开发就不是一个人业余时间能做的好的了。
