### ISSUE TITLE
It seems memory consumption is a bit large

### ISSUE THREAD

**Issue by Honghe** [vnotex/vnote#171]
- When reporting problems, elaborate it as detailed as possible like:
    - Version of VNote, which operating system;  vnote 1.13 x64, Windows 10.
    - What is the symptoms; memory used 250M+
    - What action triggered it; do nothing, only open an empty note file.

Is this normal?
Thanks!

**Comment by tamlok** [comment]
Yes, it surely needs optimization. I will dive into it after implementing some critical features. For now, just bear it.

Thanks! :)
