### ISSUE TITLE
导出html问题

### ISSUE THREAD

**Issue by Linjj** [vnotex/vnote#1710]
1、不支持导出单个文件
2、导出文件夹时，只会将该文件夹下的第一个md转换为html，其他md文件输出的html是空的
3、导出文件夹时，子目录下的文件不会被扫描

以上bug是使用默认导出选项时出现的问题，具体见下图：
![image](https://user-images.githubusercontent.com/10056177/110300742-34f31c80-8032-11eb-8b48-550df57c126b.png)
![image](https://user-images.githubusercontent.com/10056177/110300827-5a802600-8032-11eb-86fe-229dabf98542.png)

**Comment by tamlok** [comment]
说一下vnote版本吧

**Comment by tamlok** [comment]
Fixed already.
