### ISSUE TITLE
自己调试的font-family

### ISSUE THREAD

**Issue by heartnn** [vnotex/vnote#1711]
**body**

    font-family: -apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji';

**code, pre code**

    font-family: "iA Writer Mono V", "Fira Code", "Lucida Console", Monaco, Consolas, "Ubuntu Mono", "DejaVu Sans Mono", Menlo, "Courier New", "Hiragino Sans GB", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, monospace, sans-serif;

code中插入的中文字体是防止中文显示不正常。

此代码是我以前在editor.md中使用的。

**Comment by tamlok** [comment]
谢谢！后面融合到默认样式中。

**Comment by tamlok** [comment]
Merged part of it: https://github.com/vnotex/vnote/commit/6cd666552db7194772b2002e6ae84d6f78601e64
