### ISSUE TITLE
V3.0 B.7 操作过程中误删除根目录问题

### ISSUE THREAD

**Issue by ELE-Clouds** [vnotex/vnote#1712]
**Describe the bug（问题描述）**
我在将我的一个子目录剪切到根目录的时候，弹出无法复制的错误提示，关闭对话框后，文件夹目录已经出现在了根目录，其下子目录和文件只有一个，未全部复制过来，原目录下的文件已经消失，再次使用复制命令将其复制到根目录后，目录名已被自动加“1”，但目录中多了一个和根目录同名的子目录，在删除这个目录后，根目录（笔记本）消失，提示无法加载笔记。

> 当前笔记所有文件及目录名基本上都是中文名称。

**To Reproduce（问题重现）**
不容易复现，但仍会出现。

**Expected behavior（期望结果）**

**Screenshots（截图）**

**Desktop (please complete the following information):（桌面信息）**
 - OS: Windows 10 x64
 - Vnote Version 3.0 Bata.7

**Additional context（其它）**
在操作过程中经常出现崩溃的现象，程序突然关闭，得重新运行程序打开。    
右键删除时，经常会出现删除失败的提示，有时关闭提示框后文件仍在，有时会消失。

**Comment by tamlok** [comment]
建议你新建一个笔记本，然后看能不能复现，感觉你原来那个笔记本的索引已经全乱了。
