### ISSUE TITLE
[BUG] 在删除目录或文件时，程序经常崩溃

### ISSUE THREAD

**Issue by ELE-Clouds** [vnotex/vnote#1713]
**Describe the bug**
在左侧栏，右键点击目录或文件，点击删除，程序崩溃，自动关闭。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.0.0]

**Additional context**

**Comment by eccstartup** [comment]
+1

**Comment by tamlok** [comment]
最新版10还会吗？

**Comment by tamlok** [comment]
更新后还会吗？

**Comment by eccstartup** [comment]
界面不能重命名，文件夹里手动重命名之后就有崩溃。

**Comment by tamlok** [comment]
肯定不能绕开vnote重命名的。类似于编辑器打开一个文件，然后你外面把文件改名了，编辑器哪知道谁是谁。

界面右键菜单属性能重命名。
