### ISSUE TITLE
[BUG] 清空回收站经常出错

### ISSUE THREAD

**Issue by ELE-Clouds** [vnotex/vnote#1715]
**Describe the bug**
右击当前笔记回收站图标，点击清空回收站，此时，弹出无法清空的提示（详细信息见截图）。且出现概率较高。

**To Reproduce**

**Expected behavior**

**Screenshots**
![无法清空回收站](https://user-images.githubusercontent.com/20043036/110730865-32740b00-825c-11eb-941a-17191e4f86af.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Vnote Version 3.0.0 B.7/B.8

**Additional context**

**Comment by tamlok** [comment]
`E:/gitee`这个目录是会被第三方管理吗？是不是读写权限有什么问题？
