### ISSUE TITLE
vnote使用上的一些建议

### ISSUE THREAD

**Issue by llzywhy** [vnotex/vnote#1720]
OS: Windows 10
version： VNote 3.0.0-beta.9

- 建议重启vnote之后，能保存窗口布局（包括位置，大小等），打开的note窗口，已经展开的note层级，阅读/编辑的位置，甚至是编辑的历史记录等。
  类似的issue如： #1653 
- 建议鼠标单击目录就可以展开目录内容，而不是双击目录才能展开。
- 建议note目录能一键全部展开和折叠。
- 建议`ESC键`退到阅读模式的快捷键也能加回来

**Comment by tamlok** [comment]
目前右键可以一键展开目录。

**Comment by Mojicode** [comment]
其他的一些建议：
1. 能够像其他编辑器一样对打开文件分为临时和永久，即双击为保持永久打开，单机只是临时打开。
2. 保存上次关闭时的页面布局和打开文件真的非常有用！！！

**Comment by tamlok** [comment]
已支持会话恢复。

**Comment by llzywhy** [comment]
> 目前右键可以一键展开目录。

另外希望是单击即可展开，这样操作起来感觉会好一些。
![image](https://user-images.githubusercontent.com/23399862/119223372-9e5fd300-bb2b-11eb-8b7e-46daa10f0264.png)

**Comment by tamlok** [comment]
这不是基本操作，暂时不会支持。
