### ISSUE TITLE
windows下源码编译Vnote遇到“Cannot find file:syntax-highlighting\syntax-highlighting.pro”问题

### ISSUE THREAD

**Issue by Tridu33** [vnotex/vnote#1721]
**Describe the bug**
windows下源码编译Vnote遇到“Cannot find file:syntax-highlighting\syntax-highlighting.pro”问题

**To Reproduce**
安装windows下Qt 15
双击.pro锤子🔨配置安装编译源码安装vnote

**Expected behavior**
报错：
```bash
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.
	cd syntax-highlighting\ && D:\Qt\Qt5.12.10\5.12.10\msvc2017\bin\qmake.exe -o Makefile D:\tridu33\QtVnote\vnote.git\libs\vtextedit\src\libs\syntax-highlighting\syntax-highlighting.pro -spec win32-msvc "CONFIG+=debug"
Cannot find file: D:\tridu33\QtVnote\vnote.git\libs\vtextedit\src\libs\syntax-highlighting\syntax-highlighting.pro.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
09:09:54: 进程"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"退出，退出代码 2 。
Error while building/deploying project vnote (kit: Replacement for "Desktop Qt 5.9.9 MSVC2017 64bit")
When executing step "qmake"
09:09:54: Elapsed time: 00:01.
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.0.0]

**Additional context**
本地编译生成的文件目录中·`D:\tridu33\QtVnote\vnote.git\libs\vtextedit\src\libs\syntax-highlighting\`是空白，的确没有`syntax-highlighting.pro`文件生成。不知道应该怎么办，没google到类似解决方案。

**Comment by Tridu33** [comment]
然后`vnote.git\src\data\extra\syntax-highlighting`我看到有syntax-highlighting相关文件，但是Everything.exe也没搜到`syntax-highlighting.pro`

**Comment by tamlok** [comment]
大概参考一下，执行一下git submodule： https://vnotex.github.io/vnote/zh_cn/#!docs/%E5%BC%80%E5%8F%91%E8%80%85/%E6%9E%84%E5%BB%BAVNote.md

https://www.bilibili.com/video/BV1u54y1s7gj?from=search&seid=11367725940825604924

**Comment by Tridu33** [comment]
```
$git submodule update --init --recursive
Submodule 'src/libs/syntax-highlighting' (https://github.com/vnotex/syntax-highlighting.git) registered for path 'libs/vtextedit/src/libs/syntax-highlighting'
Cloning into 'D:/tridu33/QtVnote/vnote.git/libs/vtextedit/src/libs/syntax-highlighting'...
Submodule path 'libs/vtextedit/src/libs/syntax-highlighting': checked out '0f63ff8ce3f7135ffafd62bc464c355960f56cfd'
```
666文档没写递归--recursive这个，视频写了，发现加了这个命令好像就是另外的报错```Visual Studio can't build due to rc.exe```。
r然后我找到解答“https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe”
