### ISSUE TITLE
Inline math with $$...$$

### ISSUE THREAD

**Issue by irosyadi** [vnotex/vnote#1724]
VNote strictly uses single dollar $...$ for math equation, while in [https://github.com/vnotex/markdown-it-texmath](https://github.com/vnotex/markdown-it-texmath) it is possible to use double dollars $$...$$.

Since single dollar delimiter $...$ will make problem for currency-related text and for compatibility with other mathjax parsers (for example in Github Pages), can double dollar delimiter be used also for inline math?

**Comment by tamlok** [comment]
How to differentiate inline and block equation if we use `$$` for the inline math? https://github.com/vnotex/markdown-it-texmath#faq

**Comment by irosyadi** [comment]
Understandable, thanks
