### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by 5rKB5bPlusD** [vnotex/vnote#1728]
已加星。先赞美一下，这就是我想要的软件。编辑和阅读分开太棒了，在阅读的时候不会冒出markdown语法来打扰你。而且上面的工具栏也对刚接触markdown的新手十分友好。然后就是图片能不能支持上传，能够使用picgo-core就可以（像typora那样）。目前虽然也能使用picgo的客户端，但毕竟多了一个步骤。期待更新。

**Comment by tamlok** [comment]
hi,

2.0支持图床，3.0还没迁移。后面会迁移。

**Comment by 5rKB5bPlusD** [comment]
希望3.0的版本可以支持设置path，目前是放在外部有一点乱。另外再粘贴的时候希望能勾选上传。辛苦。
ps：如果可以支持picgo相册功能看到之前上传了什么可以删掉就更好了。
ps：一键切换笔记挺好的，3.0双击有点累

**Comment by JeroGC** [comment]
> hi,
> 
> 2.0支持图床，3.0还没迁移。后面会迁移。
感谢提供这么好用的笔记软件，在这里顺便提出一下另一个好用的feature，能否仿照 Typora 开放一下`自定义命令`(Custom Command)图片上传的功能？

**Comment by 5rKB5bPlusD** [comment]
> hi,
> 
> 2.0支持图床，3.0还没迁移。后面会迁移。

使用了一段时间的2.0，文件夹内目录、文件一键切换非常方便好用，图片上传仍有不便之处。希望考虑一下约定大于配置的方式，如果用户配置了图床，应该默认用户会使用图床上传文件。另外图片的粘贴我希望不要让用户去判断从什么地方导入（参考typora）。此外2.0的图片粘贴有时没有后缀，上传时出现不支持格式的字样。
ps：如果2.0不再进行维护，希望能够在3.0得到支持

**Comment by tamlok** [comment]
Fixed already.
