### ISSUE TITLE
[BUG]加粗字体在预览模式下不能正常显示

### ISSUE THREAD

**Issue by wpx1997-stack** [vnotex/vnote#1729]
如下：编辑模式
![image](https://user-images.githubusercontent.com/80240320/113299551-96579400-932f-11eb-9fd2-8d94cbd4bfdb.png)
预览模式：
![image](https://user-images.githubusercontent.com/80240320/113299621-a8393700-932f-11eb-81bf-a261696e8ff2.png)

**Comment by wpx1997-stack** [comment]
VNote 3.0.0-beta.10 Windows x64

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/490

**Comment by shepherdwind** [comment]
这个问题好多人都在提，我最近也遇到了，修复了一下，需要可以拿去试试 https://github.com/shepherdwind/match-pairs
