### ISSUE TITLE
Ordered and Unordered list

### ISSUE THREAD

**Issue by arvindsridharan** [vnotex/vnote#1730]
When I typed 1.  List1 and pressed enter I was expecting an ordered list to be automatically created with 2. List 2. However this does not seem to be the case. 

The same is with unordered list.

**Comment by tamlok** [comment]
Not migrated to 3.0 yet. Stay tuned.

**Comment by arvindsridharan** [comment]
It works well in Linux but not in windows. Will wait for 3.0.  Is there a provision to include the following features

1. Backlinks
2. Diagramming tool like mermaid.js

Thanks

**Comment by tamlok** [comment]
Backlink is in plan. mermaid.js is already supported in both versions.

**Comment by arvindsridharan** [comment]
Thank you. Vnote is really awesome and works like a charm.  
Appreciate the efforts you and your team have put. 

You can also feature your product on product hunt. 

Waiting for backlink features eagerly.

**Comment by tamlok** [comment]
https://www.producthunt.com/posts/vnote

**Comment by arvindsridharan** [comment]
Awesome.  Can we have provision for underlining text, highlighting and spell check.  Plus check box.  Also I see when I press Ctr+T I have to scroll down every time to see how the content got rendered. Is there an option/feature to avoid this.

**Comment by tamlok** [comment]
1. Use `<u></u>` for underline text since it is not within Markdown standards;
2. Use `<mark></mark>` for highlihgting;
3. Spell check will be coming sone;
4. Checkbox is already supported, check the Markdown syntax guide (`[x] zbc`);
5. 3.0 already sync the read and edit mode in a finer grain. Try it out.

**Comment by arvindsridharan** [comment]
Okay. Thank you for your valuable inputs and taking your time to write. Appreciate your efforts.

**Comment by arvindsridharan** [comment]
![image](https://user-images.githubusercontent.com/34650531/114274597-df4cce00-9a3c-11eb-9280-3c73e5677902.png)

When I click on about VNote, I see the current version is 2.10.  But in my Linux terminal (please see attached screen print) it says +3.0.00 installed.  Please guide.

**Comment by arvindsridharan** [comment]
In my linux terminal it shows vNote version 3.0. But when I check in about Vnote it displays 2.10. You know why?

**Comment by tamlok** [comment]
just download the appimage from girhub

**Comment by arvindsridharan** [comment]
Ok. Thank's a lot.

**Comment by arvindsridharan** [comment]
I installed the app image version 3.0, but the menu bar is not visible.

**Comment by tamlok** [comment]
@arvindsridharan  No menu bar any more.

**Comment by arvindsridharan** [comment]
@tamlok thanks Tam. I will check the features. Vnote is Awesome!!!
