### ISSUE TITLE
粘贴解析的MarkDown文本情况下，图片无法下载到本地，依然是网络链接

### ISSUE THREAD

**Issue by txdonefu** [vnotex/vnote#1731]
新机器上安装vnote便携版，出现无法本地化图片情况：

例如，复制网页图片后粘贴解析的MarkDown文本
依然是：

`![](https://nimg.ws.126.net/?url=http%3A%2F%2Fcms-bucket.ws.126.net%2F2021%2F0410%2F5dd9a45bj00qrcjma001jc000rs00ijc.jpg&thumbnail=660x2147483647&quality=80&type=jpg)`

环境win10专业版 20h2  Ver2.7.2 或者 2.10

以前未曾出现过此问题。从以前机器上复制配置文件vnote.ini替换，不能解决问题。重启vnote或系统不能解决问题。

**Comment by tamlok** [comment]
Hi,

有网页源地址吗？看这图片的地址，比较复杂，感觉是又是发送一个请求去下载图片，不是直接的图片地址。

**Comment by txdonefu** [comment]
举例来说，复制https://mp.weixin.qq.com/s/Q33NVcoMAW3w95qkzynfrQ网页的内容，结果如下：

（原文太长，部分内容）

**“延长春节、延长产假、延长节假日……”。**

  

![](https://mmbiz.qpic.cn/mmbiz_jpg/EAp1pibzPzzia6c221BKuNM9O8RjP1KTt6yIFI1NsRpO2ZzHTOwWpT2xYoyzHqHK8TwQN6Vp7Ab2pIWicRf6KEMicA/640?wx_fmt=jpeg)

  

消息一出，网友们集体叫好，**工作压力大，节假日确实不够用**。****

  

「中国人工作时间长，工资却超低」，这一度被发达国家当成笑柄。

  

**“吃的比猪少，干得比牛多，睡得比狗晚，起得比鸡早”。**

  

这就是我们这代人的真实写照。

  

这次我给大家介绍一位朋友，却改变了自己的人生。

  

![](https://mmbiz.qpic.cn/mmbiz_jpg/EAp1pibzPzzjKoQtJ4ACSnhuHqxXpoIINs3TglCMAwsk9nfJGiakl9FFN2vicqZSpZvQo20lsrxkDkBJBHbNBKkYw/640?wx_fmt=jpeg)

**Comment by tamlok** [comment]
文章被删除了~再来一篇？

**Comment by tamlok** [comment]
VNote 3.0 能正确处理，请先尝试3.0能否复现。

![image](https://user-images.githubusercontent.com/5763157/118655563-4029ac00-b81c-11eb-95ad-17756aa8169b.png)
