### ISSUE TITLE
Automatic list numbering

### ISSUE THREAD

**Issue by arvindsridharan** [vnotex/vnote#1732]
Using v 3.0. I see that the list is not getting automatically numbered on pressing enter. This is the case with ordered and unordered list. 

Also there is no menu bar getting displayed

**Comment by arvindsridharan** [comment]
Hope the team is looking into it

**Comment by arvindsridharan** [comment]
@tamlok please check the above issue. Automatic list numbering is not enabled in your latest version. Like on pressing enter the list should get automatically numbered. Also while indention.

**Comment by tamlok** [comment]
Hi,

There is no menu bar any more. They are now embedded in the top toolbar buttons.

For the list numbering and auto indentation, please be patient and stay tuned. Will be migrated in next two or three versions.

**Comment by tamlok** [comment]
Supported now in 3.3.0
