### ISSUE TITLE
After upgrading to v3.0.0-beta.11, full text search is still useless?

### ISSUE THREAD

**Issue by wwwxxxttt1** [vnotex/vnote#1735]
After upgrading to v3.0.0-beta.11, press Ctrl + Alt + F, unable to call out global search, thank you!

**Comment by tamlok** [comment]
The shortcut is `Ctrl-G 3`. Or just simply click on the left side panel. Will add this extra shortcut to it.

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/115097712-71356900-9f5e-11eb-8370-7541a0fc4ded.png)

**Comment by wwwxxxttt1** [comment]
Yes, thank you very much!

**Comment by wwwxxxttt1** [comment]
Yes, thank you very much!
