### ISSUE TITLE
直接导入Markdown

### ISSUE THREAD

**Issue by youlxiao** [vnotex/vnote#1739]
希望增加直接导入markdown的功能，我有好多markdown笔记，但是却只能一项一项粘贴到vnote中，这太难了

**Comment by tamlok** [comment]
VNote 3.0支持：

1. 基于现有文件夹建立一个新的笔记本：  
    ![image](https://user-images.githubusercontent.com/5763157/115315790-a209de00-a1aa-11eb-892d-db85f6353a0e.png)
2. 导入文件或者文件夹到现有笔记本：  
    ![image](https://user-images.githubusercontent.com/5763157/115315770-94545880-a1aa-11eb-8418-2ec4b0f90e2b.png)
