### ISSUE TITLE
使用ctrl+滚动缩放时过于灵敏

### ISSUE THREAD

**Issue by pingplug** [vnotex/vnote#1741]
**Is your feature request related to a problem? Please describe.**
在使用 ctrl+触摸板滚动 缩放时过于灵敏，导致无法缩放到合适的大小

**Describe the solution you'd like**
降低 ctrl+触摸板滚动 的灵敏度

**Describe alternatives you've considered**
在界面处提供一个缩放选择

**Additional context**

**Comment by tamlok** [comment]
1. `ctrl+-`或者`ctrl+=`就是缩放；
2. 设置里面有缩放设置：
![image](https://user-images.githubusercontent.com/5763157/115718952-35f7c780-a3ae-11eb-95e6-07b961bf31c4.png)
