### ISSUE TITLE
编辑模式 增加隐藏图片

### ISSUE THREAD

**Issue by BeyondXinXin** [vnotex/vnote#1747]
编辑模式下图片显示有时感谢很碍眼，希望编辑模式下 有快捷键可以隐藏图片

**Comment by tamlok** [comment]
后面会暴露对应配置。

**Comment by BeyondXinXin** [comment]
@tamlok  作者大大，您空闲的时候帮忙删掉这个issue，而不是关闭。我发现只要在别人项目issues下发言，自己的Repositories里就会保留对方的仓库。有点强迫症
