### ISSUE TITLE
网文中.webp图片，无法解析出后缀名

### ISSUE THREAD

**Issue by SanTTang** [vnotex/vnote#1748]
https://mp.weixin.qq.com/s/oGZVf6k3qBJl0aDQO9XYbQ
比如，作者微信公众号文章。
复制粘贴解析成Markdown，到vnote中，
网文中的.webp格式得图片，保存到本地后，都没有后缀名
`![Image](_v_images/20210427005203892_2945)`

无后缀图片在vnote是能正常预览。
但是对笔记导出时，这些无后缀的图片，都不能正常的导出。
VNote2和VNote3中都存在这样情况。

**Comment by tamlok** [comment]
Fixed 58a7745b0e458dd6b5bc19a3b4b0527e9d181e70
