### ISSUE TITLE
add support for custom swap file location

### ISSUE THREAD

**Issue by sylph520** [vnotex/vnote#1750]
**Is your feature request related to a problem? Please describe.**
I'm using VIM mode, and I use Onedrive to sync files, it's something annoying that the notification of addtion and delete of a swap file. I know it's a problem of Onedrive by not providing an ignore setting
**Describe the solution you'd like**
But i'm wondering whether it's possible and easy to add a setting of swap file location to store the swap file out of onedrive sync path. Thanks in advance!

**Comment by tamlok** [comment]
vnote3 or vnote2?

**Comment by sylph520** [comment]
vnote 2.10

**Comment by tamlok** [comment]
Add this config to `vnote.ini` to specify your location to hold SWAP files:

https://github.com/vnotex/vnote/blob/de753706d17bac7e9c1d0224609e85741cbddf2c/src/resources/vnote.ini#L202

**Comment by sylph520** [comment]
Thanks, it works after I created vnote.ini under the program root folder and set the backup_directory.

**Comment by tamlok** [comment]
dont do this. open the config folder in the app menu, and change that vnote.ini.
