### ISSUE TITLE
可否支持base64编码方式插入图片

### ISSUE THREAD

**Issue by husx** [vnotex/vnote#1755]
可否在vnote设置中增加将插入图片转换成base64编码，转移Markdown文件的时候就很方便

**Comment by wsrf16** [comment]
个人观点，这种方式对于纯文本的支持虽然比较友好，但是渲染非常慢，而且排版看上去就是一大堆乱码

**Comment by tamlok** [comment]
鉴于精力有限，暂时不会实现。VNote里面导出为Markdown格式的话，会把相关的资源都导出到一个文件夹中，打包该文件夹即可。
