### ISSUE TITLE
Allow switching tabs via Alt+<digit>

### ISSUE THREAD

**Issue by laur89** [vnotex/vnote#1759]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Application could allow switching opened tabs via `Alt + <digit>` keycombos. Eg given 3 tabs are open and first on is active, `Alt + 2` would activate the second tab, `Alt + 3` would activate the 3rd one.

**Additional context**
This is in-line with how it's implemented for most web browsers and number of other programs.

Note I'm talking specifically about Linux; on Windows `Alt` modifier is generally replaced by `Ctrl`, unsure how macOS behaves.

**Comment by tamlok** [comment]
Hi,

`Alt` should be a shortcut to trigger menu action. Now VNote supports `Ctrl+G, <n>` to activate tabs or `Ctrl+G, N/P` to jump forward/backward.

Regards,
Le
