### ISSUE TITLE
建议想法

### ISSUE THREAD

**Issue by dong8yong8** [vnotex/vnote#1760]
已经开始用3了，相比2来说简洁了很多

有一个小小建议，就是能不能不显示层级编号，比如0.0.1,0.0.0.1 或者可以提供设置可隐藏

还是喜欢通过标题的字体大小来区分

**Comment by tamlok** [comment]
Hi,

多看看设置：

![image](https://user-images.githubusercontent.com/5763157/118068660-52978600-b3d5-11eb-8ff9-167174d1bd68.png)

**Comment by dong8yong8** [comment]
看到了，还有一个问题，plantuml不用自己配置jar包选择了吗

**Comment by tamlok** [comment]
本地jar模式还没迁移，目前是使用线上服务器。
