### ISSUE TITLE
单行代码块内含有反引号时，会被丢弃，渲染结果会出现异常

### ISSUE THREAD

**Issue by Gongkaikai** [vnotex/vnote#1761]
OS: macOS 10.14.6
version： VNote v3.0.1

**Describe the bug**
单行代码块内含有反引号时，渲染结果会出现异常，代码中的反引号丢失
![image](https://user-images.githubusercontent.com/19772826/118103921-0c5e1900-b40d-11eb-8d92-cc464fcd47b7.png)

**Comment by tamlok** [comment]
看一下软件的帮助菜单：

![image](https://user-images.githubusercontent.com/5763157/118105403-ed608680-b40e-11eb-88c2-c91bc68c0261.png)
