### ISSUE TITLE
Do not close Find menu w/ Ctrl+F if editor is active

### ISSUE THREAD

**Issue by laur89** [vnotex/vnote#1765]
**Is your feature request related to a problem? Please describe.**
No/Maybe

**Describe the solution you'd like**
Currently, when `Find And Replace` menu is opened (Ctrl+f by default), and then editor is activated again (eg for post-search editing), then subsequent `Ctrl+f` closes the search menu. Better UX would be to activate the `Find` field in the already-opened search menu instead. 
On the other hand, if search menu is active (eg `Find` field), then `Ctrl+f` closing the menu would be appropriate.

**Additional context**
Running on Linux, vnote v3.0.1

**Comment by tamlok** [comment]
Should be fixed in f80fe2629af152ee4e463aa8d5800468d70679b2

Thank you!
