### ISSUE TITLE
3.0.1设置界面操作很大几率卡死

### ISSUE THREAD

**Issue by JimmyZou92** [vnotex/vnote#1766]
**Describe the bug**
设置界面操作很大几率卡死

**To Reproduce**
设置界面多点击几次选项

**Expected behavior**
解决卡死

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [3.0.1]

**Additional context**

**Comment by tamlok** [comment]
opengl设置一下？参考置顶issue

**Comment by JimmyZou92** [comment]
> opengl设置一下？参考置顶issue

设置成opengl就不卡死了，谢谢，是我没留意置顶，不好意思
