### ISSUE TITLE
快捷键无法使用

### ISSUE THREAD

**Issue by l1422586361** [vnotex/vnote#1768]
在一些场景下，选词后无法使用快捷键（比如加粗）

**Comment by tamlok** [comment]
开了vi吧？

**Comment by Gone4long** [comment]
> 开了vi吧？

没开也会无法使用，比如Ctrl+B，右下角显示RICKMARKDOWN插入
v3.3.0

**Comment by tamlok** [comment]
查看一下是不是有其他软件有快捷键冲突，或者把中文输入法换成英文输入法看看行不行。应该是环境的问题。实在不行，可以自行修改配置，换一个快捷键。

**Comment by Gone4long** [comment]
> @Gone4long
> 查看一下是不是有其他软件有快捷键冲突，或者把中文输入法换成英文输入法看看行不行。应该是环境的问题。实在不行，可以自行修改配置，换一个快捷键。

应该不是快捷键冲突、中英输入法，就很奇怪，打开的3个笔记，其中1个可以用快捷键，另外2个就不行……
删了配置文件，重新下载解压运行，还是只有1个能用。就这一个能用的里边，也很奇怪，选中某些内容能用，另外一些内容又不能用（中间不包含嵌套加粗、换行），搞不明白了

**Comment by tamlok** [comment]
如果方便的话，可以把不能用快捷键的那个笔记发给我邮箱，我看看这边是不是这样能复现。

**Comment by Gone4long** [comment]
> 如果方便的话，可以把不能用快捷键的那个笔记发给我邮箱，我看看这边是不是这样能复现。

已发送，请查收~

**Comment by tamlok** [comment]
我这边没法重现。你是win吗？如果是的话，尝试一下设置opengl的值，然后重启vnote测试一下？

**Comment by Gone4long** [comment]
> 我这边没法重现。你是win吗？如果是的话，尝试一下设置opengl的值，然后重启vnote测试一下？

现在OpenGL设置是无，列表可选项是Desktop、OpenGL ES、software，需要设置成哪个？

**Comment by tamlok** [comment]
每个都试一下，每改一个值都重启vnote

**Comment by Gone4long** [comment]
> 每个都试一下，每改一个值都重启vnote

-_-||都试了，还是不行。既然你新建笔记都不能复现，那也不是笔记创建时间、软件版本的问题。
先就这样吧，后面软件更新的时候我再删除配置文件重装，无法复现的问题也许就莫名其妙的解决了……退役码农的痴心妄想哈哈，3Q

**Comment by tamlok** [comment]
后面我加一些log，你关注一下日志，看能不能清楚是啥问题

**Comment by Gone4long** [comment]
> 后面我加一些log，你关注一下日志，看能不能清楚是啥问题

好的，能定位问题的话再反馈给你。

**Comment by tamlok** [comment]
我这边测试了一下，ctrl-b没问题，ctrl-,有问题。而且，当首次启动vnote的时候，快捷键都没问题，一旦鼠标点击一下其他地方，然后让vnote重新获取焦点，这时候ctrl-,就不会触发了。结论是qt本身的问题！你可以修改配置文件换一个快捷键。

**Comment by Gone4long** [comment]
> 我这边测试了一下，ctrl-b没问题，ctrl-,有问题。而且，当首次启动vnote的时候，快捷键都没问题，一旦鼠标点击一下其他地方，然后让vnote重新获取焦点，这时候ctrl-,就不会触发了。结论是qt本身的问题！你可以修改配置文件换一个快捷键。

改了下快捷键，可以了。多谢~qt的问题就留给你反馈吧

**Comment by tamlok** [comment]
我们这种白嫖用户，qt一般不管这些issue了
