### ISSUE TITLE
v3.1.0 无序列表自定义快捷键失效

### ISSUE THREAD

**Issue by Karonheaven** [vnotex/vnote#1771]
**Describe the bug**
更新到v3.1.0后，用户自定义的无序列表快捷键失效（默认的Ctrl+8仍有效）
旧版v3.0.1无此问题

**To Reproduce**
1. 将“用户配置” vnotex.json 中的["TypeUnorderedList": "Ctrl+8"]修改为其他快捷键（我修改为Ctrl+Q）
2. 重启VnoteX（v3.1.0）后按Ctrl+Q未生效
3. 已确认未开启vim模式，测试的VnoteX为从GitHub中下载的原始Release，不包含其余可能干扰的配置

**Expected behavior**
自动输入无序列表符号[* ]

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSC 1809
 - Version v3.1.0

**Comment by tamlok** [comment]
冲突了吧，新版ctrl-q刚好用来作为退出的快捷键了，你把那个删掉或者换掉。
