### ISSUE TITLE
关于与其他软件应用快捷键冲突的一个小建议

### ISSUE THREAD

**Issue by cainb** [vnotex/vnote#1772]
如果当焦点处于 VNote 界面时，能否锁定快捷键操作，使其只能触发生效 VNote 提供的快捷键或者加上系统默认的一些快捷键，屏蔽其它软件应用的快捷键触发响应（~

**Comment by tamlok** [comment]
这是其他软件监听操作系统的按键事件了，所以vnote应该是无能为力。
