### ISSUE TITLE
v3.1.0 不支持plant uml本地jar了？

### ISSUE THREAD

**Issue by Yealove** [vnotex/vnote#1773]
v2.x 能配置plant uml本地jar，能加载本地uml的样式，v3.x beta版没有找到就一直观望，v3.1.0还是没有...

**Comment by Yealove** [comment]
![image](https://user-images.githubusercontent.com/20787109/119777025-41cc3180-bef8-11eb-9ec8-06fc8e394e5d.png)

**Comment by tamlok** [comment]
3.2.0支持了

**Comment by Yealove** [comment]
> 3.2.0支持了

👍
