### ISSUE TITLE
3.1.0 Mac下标题的渲染不受缩放设置控制

### ISSUE THREAD

**Issue by dmahacker** [vnotex/vnote#1775]
**Describe the bug**
在设置中设置缩放过后，在编辑模式下标题的渲染大小不变

**To Reproduce**
1. 设置中修改缩放
2. 新建测试.md
3. 输入截图内容

**Expected behavior**
预期渲染标题应该会随缩放改变

**Screenshots**
未调整缩放前
![image](https://user-images.githubusercontent.com/8119999/119923230-e8b9d780-bfa3-11eb-9dbf-964f08550abb.png)

调整缩放为14
![image](https://user-images.githubusercontent.com/8119999/119923132-c2943780-bfa3-11eb-909e-a6cf5849fb35.png)

**Desktop (please complete the following information):**
 - OS: [Mac 10.15.7]
 - Version [3.1.0]

**Additional context**
显示器为2K分辨率，hidpi到1080p
![image](https://user-images.githubusercontent.com/8119999/119923378-2c144600-bfa4-11eb-9715-f9bf95aed5e4.png)

**Comment by tamlok** [comment]
Should be fixed in next release. https://github.com/vnotex/vnote/commit/c13d1803ce10999dc1e29c65d6b1af4ad284e851
