### ISSUE TITLE
vi模式下，加粗(ctrl+b)快捷键有bug，生成的星号无法包裹选中的区域

### ISSUE THREAD

**Issue by mudssky** [vnotex/vnote#1780]
**Describe the bug**

**To Reproduce**

 首先用vw选中下面的单词
```
title
```
选中后，执行ctrl+b快捷键,结果如下
```
**titl**e
```

**Expected behavior**
```
**title**
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - Version 3.1.0

**Additional context**

**Comment by tamlok** [comment]
已经修复。
