### ISSUE TITLE
vi模式，编辑模式下ctrl+，（插入数学公式）不生效

### ISSUE THREAD

**Issue by mudssky** [vnotex/vnote#1781]
**Describe the bug**
vi模式，在vim的命令模式下ctrl+,是生效的，但是你按i进入编辑模式以后，ctrl+,快捷键就失效了。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:win10
 - Version 3.1.0

**Additional context**

**Comment by tamlok** [comment]
好像是win的输入法发生冲突了，没办法，只能换一个了，下一版本会更改默认按键。
