### ISSUE TITLE
可以考虑加入自动生成目录功能吗？

### ISSUE THREAD

**Issue by PengfeiM** [vnotex/vnote#1783]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
笔记在自动保存时可以自动生成目录，目录生成在笔记题目下面，然后目录内容包含笔记中后续的各个章节标题

**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
不就是 toc 吗？ 百度一下吧
