### ISSUE TITLE
避免绘图时频繁闪烁

### ISSUE THREAD

**Issue by Aloxaf** [vnotex/vnote#1788]
**Is your feature request related to a problem? Please describe.**

当前使用本地 graphviz 时，每次修改内容时都会重新绘制图片，造成严重的闪烁

**Describe the solution you'd like**

在新的图片绘制完成以前，不删除旧图片

**Describe alternatives you've considered**

在用户完成输入若干秒后再进行绘图

**Additional context**

![Peek 2021-06-09 13-58](https://user-images.githubusercontent.com/17017672/121301473-d7b98080-c92a-11eb-9d8c-d67dd11b0357.gif)

**Comment by tamlok** [comment]
Fixed:  https://github.com/vnotex/vnote/commit/c50f76c40a1c704c46b6933c6be1ff0a927d3b90
