### ISSUE TITLE
目前设置小节序号为阅读模式，仅文本中显示序号，希望大纲中也可以显示

### ISSUE THREAD

**Issue by moehz** [vnotex/vnote#1790]
希望小节序号能在大纲中也生效

**Comment by tamlok** [comment]
Fixed: 6109737b9d44cbe2a0c85bd27ceb416580b5461d

![image](https://user-images.githubusercontent.com/5763157/129730233-9be48ed3-861e-49d3-ada2-1ff4e22ccdf8.png)
