### ISSUE TITLE
编辑区的UI太小了，希望能调大或者出调节功能

### ISSUE THREAD

**Issue by moehz** [vnotex/vnote#1791]
[![2cEai4.png](https://z3.ax1x.com/2021/06/09/2cEai4.png)](https://imgtu.com/i/2cEai4)
如图，编辑区的图标和上面的tab都太小了还无法调节，希望调大或者增加可以调节大小的功能

**Comment by moehz** [comment]
不知道为啥，截图看上去变大了好多，实际非常小

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/121357449-68608280-c964-11eb-8bfc-8ad4f4545756.png)

**Comment by moehz** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/5763157/121357449-68608280-c964-11eb-8bfc-8ad4f4545756.png)

这里调节后没有效果，你可以看上面的灯泡快速访问等，已经很大了，就是靠这个选项调节的。  
只有编辑区不受这个选项的影响，系统是win10 ltsc 1809 系统内部版本17763.1971

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/121467741-38f55880-c9ec-11eb-9778-bfe11008bc04.png)

有两个类似选项的，仔细一点
