### ISSUE TITLE
单个文件夹下面支持按照修改时间排序

### ISSUE THREAD

**Issue by senday** [vnotex/vnote#1793]

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/122563234-8ae65000-d076-11eb-82e4-d463a7f2a2c9.png)

**Comment by ooing** [comment]
@tamlok   可否拖放排序（自定义排序）

**Comment by tamlok** [comment]
@ooing 自定义排序的话，右键菜单排序即可。拖放只是gui的行为，这个优先级低一点，后面会考虑。

**Comment by ooing** [comment]
@tamlok   好的 ，拖放排序 比较直观操作
