### ISSUE TITLE
同一个目录，其他编辑器创建的文件和目录不显示，只能到vnote里面来创建

### ISSUE THREAD

**Issue by rawbin-** [vnotex/vnote#1797]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.0.0]

**Additional context**

**Comment by tamlok** [comment]
Hi, 请使用VNote3最新版本，VNote2已经不维护了。

**Comment by rawbin-** [comment]
> 版本

一直用brew 更新，以为是最新呢，刚更新3了，确实能自动加载了，但貌似不能删除
![image](https://user-images.githubusercontent.com/8169783/123593321-f2439300-d820-11eb-91a9-1f575da9076a.png)

**Comment by tamlok** [comment]
vnote3 是会以外部文件的形式展示外部的文件，对外部文件就不能删除了，双击打开会自动导入到索引中，转换成内部笔记，这时候vnote就能管理这个文件了。大概就是这样的逻辑。
