### ISSUE TITLE
Disable autocompletion of the double apostrophes

### ISSUE THREAD

**Issue by Primokorn** [vnotex/vnote#1798]
Hello,

I didn't want to create a bug report for that but I didn't find the solution.

When I types ' then VNote automatically writes '' with the cursor in the middle. How to disable that?
VNote 3.2.0 - Windows 10

Thank you.

![image](https://user-images.githubusercontent.com/5938828/123617604-b819c780-d807-11eb-9ba1-018513f1b2d9.png)

**Comment by tamlok** [comment]
ok~ someone likes it while others hate it. Will add a config for this.

**Comment by Primokorn** [comment]
Yes, it's very irritating when writing with languages where apostrophes are often used.

**Comment by tamlok** [comment]
Removed the `'` and `"` from auto bracket.

https://github.com/vnotex/vtextedit/commit/2eee68d02b6a48b5064dc76df2b5c7fe94bd8f0c
