### ISSUE TITLE
vi模式下删除行操作的问题

### ISSUE THREAD

**Issue by chndzcl** [vnotex/vnote#1799]
**Describe the bug**

在以前 `2.x` 版本的时候，`vi` 编辑模式下在 `Normal` 模式按 `dd` 以及按 `.` 重复 `dd` 操作时，当前行被删除后光标会保持行号不变，结果就是现在光标停在原来的下一行（下一行上移的效果）。

而现在 `3.3.0` 版本这个操作变成了光标到上一行的效果，相当于上一行下移。

这个和多数软件以及 `vi` 、`vim` 都不相同，不知道是有意这样设计还是 `BUG`？

**To Reproduce**

1. 设置编辑器为 `vi` 输入模式；
2. 编辑文件，比如移到第 `3` 行；
3. 在 `normal` 模式按 `dd`，第 `3` 行被删除，但现在光标往上移了一行，变成了第 `2` 行。

**Expected behavior**

和一般 `vi` 编辑器的行为一致，删除当前行以后把下面的行上移，光标当前行号不变。

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Version 3.3.0

**Comment by tamlok** [comment]
是bug，下个版本会修复。谢谢反馈！

**Comment by tamlok** [comment]
Fixed.
