### ISSUE TITLE
Flowcharts in mermaid can't show text

### ISSUE THREAD

**Issue by 9chu** [vnotex/vnote#1800]
**Describe the bug**
Even a simple FlowChart can't show text.
However, the ClassDiagram chart works well.

**To Reproduce**
Input any FlowChart in the mermaid format.

**Expected behavior**
The text should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4137042/123748943-76604e00-d8e7-11eb-9bf2-e65f8d140cc1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.3.0

**Additional context**
No other context.

**Comment by tamlok** [comment]
Hi，

This is an issue with the Mermaid.js library itself. It will use many external object in SVG while Qt's SVG rendering does not support it well.

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/pull/2334
