### ISSUE TITLE
win下文件管理器拖动图片或文件到vnote 3.3未能生成图片或附件

### ISSUE THREAD

**Issue by MarsLiao88** [vnotex/vnote#1801]
**拖动图片或文件到正在编辑的vnote笔记中，未能生成vnote v2.1的markdown连接，只生成文件文件路径文本。**

**Comment by tamlok** [comment]
因为很多人喜欢直接粘贴纯文本，所以vnote3之后都是默认纯文本粘贴，需要你右键选择 `多功能粘贴` ，或者`Ctrl+Shift+V`。

对于拖放，目前只能先复制文件，然后再多功能粘贴。后面支持按住`Shift`拖放启用多功能粘贴。

**Comment by tamlok** [comment]
下个版本会支持按住Shift默认激活多功能粘贴。
