### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by x3rz** [vnotex/vnote#1802]
**Describe the bug**
Stored XSS vulnerability on the latest release of Windows version as other arent tested yet.
**To Reproduce**
1. Download the windows application.
2. Enter the payload and preview the page

**Expected behavior**
No execution of javascript 

**Screenshots**
https://drive.google.com/file/d/12AvtsWPrwaUYQXZ9rMecrkO4tmWy9Mrd/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.3.0

**Additional context**
Use of DOMpurify or user input sanitization could resolve this issue

Please visit and validate this finding that I reported on huntr.dev https://www.huntr.dev/bounties/1624643393435-vnotex/vnote/

**Comment by tamlok** [comment]
Hi,

The XSS protection is turned of by defautl since it is a personal note-taking app instead of a web browser.

https://github.com/vnotex/vnote/issues/564

You could turn it on in the config.
