### ISSUE TITLE
windows下mathjax插件用不了

### ISSUE THREAD

**Issue by fulong** [vnotex/vnote#1804]
**Describe the bug**
有mathjax块，但不显示成公式，只显示文本

**To Reproduce**
把帮助文档的mathjax模板填到测试md文件下，不显示公式

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.3.0

日志文件显示：
```
Critical:(markdownviewer.js:107) failed to render MathJax
Critical:(markdownviewer.js:200) Uncaught TypeError: Cannot read property 'querySelectorAll' of null
```

**Comment by tamlok** [comment]
Is your network working fine to access `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js`?

**Comment by tamlok** [comment]
如果是网络问题，可以参考文档下载MathJax到本地：https://tamlok.gitee.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#toc_1
