### ISSUE TITLE
希望能够在U盘中运行的porket版本

### ISSUE THREAD

**Issue by mshdyh** [vnotex/vnote#1807]
使用云同步的方式虽然挺好，但是仍然有需要一个U盘运行的porket模式的需求。现在的软件可以再U盘中直接启动，但是因为配置数据保存在appdata中，所以换一台电脑，加载的笔记本就需要重新加载。希望可提供porket模式的选项。软件越做越好了，从2.0到3.0，一直很喜欢。

**Comment by tamlok** [comment]
https://tamlok.gitee.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E9%85%8D%E7%BD%AE.md#toc_2
