### ISSUE TITLE
GUI text appears very small on my HiDPI machine.

### ISSUE THREAD

**Issue by 5uttercan3** [vnotex/vnote#1808]
Hi, the text in the gui is scaling very small. I can alter the size of the icons but not the text outside of the editor, e.g the menus text.
I've added some 16px text in the note for comparrison. Is there a way to alter it? I've tried finding it in themes and config files but to no avail.
Much appreciared!
![vnote-scaling](https://user-images.githubusercontent.com/87071719/124751091-26ecd400-df1e-11eb-93d0-496a115a04d9.png)

**Comment by tamlok** [comment]
OS version?

**Comment by 5uttercan3** [comment]
Sorry!! Linux Mint 20.1 Ulyssa

**Comment by tamlok** [comment]
I will try to install a Linux Mint and repro it.

For a temp solution, you could open the default configuration folder and find the theme folder. Then add font size to the QSS style sheet file.

https://github.com/vnotex/vnote/blob/c13d1803ce10999dc1e29c65d6b1af4ad284e851/src/data/extra/themes/pure/interface.qss#L14
