### ISSUE TITLE
请问有原生m1支持的计划吗

### ISSUE THREAD

**Issue by mofaxiaoyuan** [vnotex/vnote#1810]
希望可以增加原生m1运行支持

**Comment by tamlok** [comment]
我连mac都没有~

这个运行支持主要是看Qt，Qt能支持，VNote就支持。听说Qt 6.2会支持吧，等它稳定了就迁移过去就行了。

**Comment by mofaxiaoyuan** [comment]
> 我连mac都没有~
> 
> 这个运行支持主要是看Qt，Qt能支持，VNote就支持。听说Qt 6.2会支持吧，等它稳定了就迁移过去就行了。

明白了，谢谢

**Comment by WenboSheng** [comment]
请问目前是否有支持的计划？
