### ISSUE TITLE
我原来是 3.0 bat版本，但是用 3.4打开笔就闪退

### ISSUE THREAD

**Issue by anyunpu** [vnotex/vnote#1811]
![image](https://user-images.githubusercontent.com/44797254/125830147-48f5c41a-5865-4ca0-ab58-65c50a2bfe45.png)

**Comment by tamlok** [comment]
右上角打开用户配置文件夹，把这个文件夹清空，重启vnote新版本，重新导入笔记。

**Comment by anyunpu** [comment]
> 右上角打开用户配置文件夹，删掉`vnotex.json`，重启vnote新版本。

很好，解决了。  谢谢
