### ISSUE TITLE
小键盘回车键无法使用

### ISSUE THREAD

**Issue by canflyx** [vnotex/vnote#1816]
3.3版本之前使用正常，换了新版本后就用不了了。
在非vnote下小键盘回车键使用正常
习惯了小键盘回车，无法使用挺麻烦

**Comment by tamlok** [comment]
什么情况下无法使用？

**Comment by canflyx** [comment]
编辑状态下不能使用。
不能用的时候切到其它编辑器中完全正常

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vtextedit/commit/47902164b0e11f5debfb40deb649d451d650660f
