### ISSUE TITLE
什么时候更新支持markdown的流程图语法？

### ISSUE THREAD

**Issue by winterstay** [vnotex/vnote#1817]
突然发现markdown的流程图、时序图语法很好用，啥时候vnote可以更新下嘛

**Comment by tamlok** [comment]
1. https://github.com/vnotex/vnote/blob/master/src/data/extra/docs/zh_CN/markdown_guide.md#%E5%9B%BE%E8%A1%A8
2. https://github.com/vnotex/vnote/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by winterstay** [comment]
啊这，原来是我写错了，尴尬了，谢谢作者的付出
