### ISSUE TITLE
最新版本 阅读模式下不能自动换行

### ISSUE THREAD

**Issue by szylmzs** [vnotex/vnote#1819]
编辑模式下可以自动换行 切换成阅读模式就不能自动换行了

**Comment by tamlok** [comment]
具体一点？是代码块里面不能自动换行吗？这个可以通过自定义CSS样式控制。

**Comment by szylmzs** [comment]
> 具体一点？是代码块里面不能自动换行吗？这个可以通过自定义CSS样式控制。

是的 代码块显示的时候不能自动换行 但是编辑代码块的时候可以

**Comment by szylmzs** [comment]
是highlight.css么

**Comment by tamlok** [comment]
https://vnotex.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E4%B8%BB%E9%A2%98%E5%92%8C%E6%A0%B7%E5%BC%8F.md#toc_3

可以都试一下

**Comment by szylmzs** [comment]
好的 解决了 谢谢
