### ISSUE TITLE
mac dmg cannot open 

### ISSUE THREAD

**Issue by leaderli** [vnotex/vnote#1820]
安装vnote-mac-x64_v3.5.0.zip式，提示 no mountable file systems，是不是打包出问题了。

**Comment by tamlok** [comment]
Could you download it again from GitHub? Please make sure the MD5 of the downloaded zip file is `2FC3C9CD046EE4032E17391F4BD24BE7`.

**Comment by leaderli** [comment]
> Could you download it again from GitHub? Please make sure the MD5 of the downloaded zip file is `2FC3C9CD046EE4032E17391F4BD24BE7`.

yes, i use command  
$ md5 vnote-mac-x64_v3.5.0.zip
MD5 (vnote-mac-x64_v3.5.0.zip) = 2fc3c9cd046ee4032e17391f4bd24be7

my OSX version is  EI CAPITAN.

**Comment by tamlok** [comment]
这个是旧版的系统？之前哪个版本是可以正常使用的？

**Comment by leaderli** [comment]
> 这个是旧版的系统？之前哪个版本是可以正常使用的？

我是才用的，我下载了一个3.4的版本的，也是同样的错误。

我使用命令行安装dmg时提示如下

hdiutil attach -verbose vnote-mac-x64_v3.4.0.dmg
Initializing…
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score      100, CCarbonBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CMacBinaryEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CAppleSingleEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CEncryptedEncoding
DIFileEncodingInstantiatorProbe: interface  0, score      900, CUDIFEncoding
DIFileEncodingNewWithBackingStore: CUDIFEncoding
DIFileEncodingNewWithBackingStore: instantiator returned 0
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CSegmentedNDIFEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CSegmentedUDIFEncoding
DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CSegmentedUDIFRawEncoding
DIDiskImageInstantiatorProbe: interface  0, score     1000, CUDIFDiskImage
DIDiskImageInstantiatorProbe: interface  1, score        0, CSparseBundleDiskImage
DIDiskImageInstantiatorProbe: interface  2, score        0, CSparseDiskImage
CRawDiskImage: data fork length 0x000000000819888F (135891087) not a multiple of 512.
DIDiskImageInstantiatorProbe: interface  3, score     -100, CRawDiskImage
DIDiskImageInstantiatorProbe: interface  4, score        0, CDARTDiskImage
DIDiskImageInstantiatorProbe: interface  5, score        0, CDiskCopy42DiskImage
DIDiskImageInstantiatorProbe: interface  6, score    -1000, CNDIFDiskImage
DIDiskImageInstantiatorProbe: interface  8, score     -100, CShadowedDiskImage
DIDiskImageInstantiatorProbe: interface  9, score    -1000, CCFPlugInDiskImage
DIDiskImageInstantiatorProbe: interface 10, score     -100, CWrappedDiskImage
DIDiskImageNewWithBackingStore: CUDIFDiskImage
DIDiskImageNewWithBackingStore: instantiator returned 0
Verifying…
Verification completed…
Error 0 (Undefined error: 0).
expected   CRC32 $D4A0558F
Attaching…
DI_kextWaitQuiet: about to call IOServiceWaitQuiet...
DI_kextWaitQuiet: IOServiceWaitQuiet took 0.000004 seconds
2021-07-27 13:23:04.496 diskimages-helper[3034:69715] DIHelperHDID serveImage: attaching drive
{
    autodiskmount = 1;
    "hdiagent-drive-identifier" = "F307C51C-C66D-4D3E-A595-E5E9048B48D3";
    "unmount-timeout" = 0;
}
2021-07-27 13:23:04.498 diskimages-helper[3034:69715] DIHelperHDID serveImage: connecting to myDrive 0x4E0B
2021-07-27 13:23:04.498 diskimages-helper[3034:69715] DIHelperHDID serveImage: register _readBuffer 0x11328d000
2021-07-27 13:23:04.498 diskimages-helper[3034:69715] DIHelperHDID serveImage: activating drive port 19467
2021-07-27 13:23:04.498 diskimages-helper[3034:69715] DIHelperHDID serveImage: set cache enabled=TRUE returned SUCCESS.
2021-07-27 13:23:04.498 diskimages-helper[3034:69715] DIHelperHDID serveImage: set on IO thread=TRUE returned SUCCESS.
2021-07-27 13:23:04.498 diskimages-helper[3034:69715] -processKernelRequest: will sleep received
Volume check completed…
Mounting…
2021-07-27 13:23:04.535 diskimages-helper[3034:69711] -remountReturningDictionary: detaching because no mountable filesystems.
Attaching…
Error 112 (no mountable file systems).
Finishing…
DIHLDiskImageAttach() returned 112
2021-07-27 13:23:05.550 diskimages-helper[3034:69707] *** -[NSMachPort handlePortMessage:]: dropping incoming DO message because the connection is invalid
hdiutil: attach failed - no mountable file systems

**Comment by leaderli** [comment]
dmg的文件的md5是多少呀，是不是
MD5 (vnote-mac-x64_v3.5.0.dmg) = 3d8f50e29c7f4a689ed857fed74f6f2a

**Comment by tamlok** [comment]
Hi,

文件是没有错的。原因是你的系统太旧了，VNote 打包的时候默认使用了 APFS 格式。参考 （https://apple.stackexchange.com/questions/344414/create-dmg-file-on-macos-10-14-that-can-be-opened-on-macos-10-11）

解决办法应该就是打包的时候，命令里面多加一个参数指定格式即可。

如果是程序员，可以自行解决。下面是VNote CI里面用于打包的命令，你可以一个PR，然后里面修改该命令成兼容旧版本的参数。PR会触发CI，等构建完毕就可以下载自己构建的DMG文件了。

https://github.com/vnotex/vnote/blob/5ba425ae9520fb5b5011e874833da9053a291799/.github/workflows/ci-macos.yml#L112

如果不是程序员，我今晚尝试帮你弄一下。

**Comment by leaderli** [comment]
> Hi,
> 
> 文件是没有错的。原因是你的系统太旧了，VNote 打包的时候默认使用了 APFS 格式。参考 （[https://apple.stackexchange.com/questions/344414/create-dmg-file-on-macos-10-14-that-can-be-opened-on-macos-10-11）](https://apple.stackexchange.com/questions/344414/create-dmg-file-on-macos-10-14-that-can-be-opened-on-macos-10-11%EF%BC%89)
> 
> 解决办法应该就是打包的时候，命令里面多加一个参数指定格式即可。
> 
> 如果是程序员，可以自行解决。下面是VNote CI里面用于打包的命令，你可以一个PR，然后里面修改该命令成兼容旧版本的参数。PR会触发CI，等构建完毕就可以下载自己构建的DMG文件了。
> 
> https://github.com/vnotex/vnote/blob/5ba425ae9520fb5b5011e874833da9053a291799/.github/workflows/ci-macos.yml#L112
> 
> 如果不是程序员，我今晚尝试帮你弄一下。

提了一个PR，加了一个参数 -fs ExFAT ，是不是这样就可以了

**Comment by tamlok** [comment]
根据那个StackOverflow的链接是 ` -fs JHFS+`，不过都可以试一下。

可以等一下这个build完成：

https://github.com/vnotex/vnote/actions/runs/1070369752

**Comment by tamlok** [comment]
好了，可以测试一下： https://github.com/vnotex/vnote/suites/3338595077/artifacts/78339999

**Comment by leaderli** [comment]
> 好了，可以测试一下： https://github.com/vnotex/vnote/suites/3338595077/artifacts/78339999

明天上班试一下！

**Comment by leaderli** [comment]
可以使用，谢谢

**Comment by leaderli** [comment]
可以打开，但是软件不支持这个版本的了。
