### ISSUE TITLE
大佬作者，能不能整个边写边预览的功能呀

### ISSUE THREAD

**Issue by winterstay** [vnotex/vnote#1824]
感觉还需要个边写边预览的功能

**Comment by winterstay** [comment]
还有那个，一般英文会出现红色下划线，是什么情况呀？

**Comment by tamlok** [comment]
双边预览优先级会低一点，预期两个月左右吧。

红色是拼写检查，右下角可以关闭，或者设置里面永久关闭。额。。。那我还是把这个设为默认关闭吧。

**Comment by pysense** [comment]
边写边预览的功能在真正支持之前其实也可以这样实现：

1. 选中需要实时预览的标签页
2. 右上角三点图标选择垂直拆分（快捷键 `Ctrl+G, \`）

这样右侧面板默认就是阅读模式，左侧面版可以进入编辑模式，更改会实时更新到右侧面板。

**Comment by winterstay** [comment]
了解了，十分感谢

**Comment by tamlok** [comment]
已支持双边预览： https://github.com/vnotex/vnote/releases/tag/v3.10.0

**Comment by winterstay** [comment]
好的，感谢作者的付出
