### ISSUE TITLE
管理外部文件夹时误删 vx.json 不能重新生成（且导致使用搜索功能后程序崩溃）

### ISSUE THREAD

**Issue by pysense** [vnotex/vnote#1826]
**Describe the bug**
管理外部文件夹时误删 vx.json 不能重新生成（且导致使用搜索功能后程序崩溃）

**To Reproduce**
1. 【笔记本】-【从文件夹新建笔记本】后目录下生成多个 vx.json 文件，操作过程中删除了某个目录下的 vx.json 文件
2. 在【导航】中点击右键选择【重新加载】、【从磁盘重新加载索引】均无法重新生成 vx.json 文件
![image](https://user-images.githubusercontent.com/2695913/127797926-c165996b-08a1-4523-b538-affdf4eb3ac6.png)

3. 使用搜索功能时程序崩溃，日志如下：

```
Critical:(exception.h:39) "FailToReadFile" "failed to read file: P:/Personal/Data/VNote/xxxxxxxxxx/images/vx.json"
```
4. 目前是手动编辑父文件夹下 vx.json 删除相应的配置，在【导航】中双击 images 文件夹重新导入

**Expected behavior**
提供重新生成 vx.json 的操作，修复 vx.json 缺失情况下搜索功能导致程序崩溃的问题。

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.5.0

**Additional context**

**Comment by je45** [comment]
【重新加载】、【从磁盘重新加载索引】这两个有什么用啊？感觉没啥用，右键点击了还是没有更新vx.json。例如我通过文件管理器移动了文件，VNote是没有办法识别的，这不能通过简单的删除索引来解决吧？
还有，删除了笔记本根目录下的vx.json会直接报错，能否更加灵活点，重新创建索引？

**Comment by tamlok** [comment]
* 重新加载： 根据索引重新生成节点树
* 从磁盘重新加载索引： 读取磁盘的vx.json文件生成索引，并重新生成节点树
* 如果通过文件管理器移动了文件，vnote能识别出来是一个外部文件，并灰色显示，双击即可导入到索引中；对于原来失效的节点，会显示红色节点，右键删除即可
* vx.json是vnote管理文件的基础，没事就别删除
* 后面会提供另一种类型的笔记本，没有索引，就是浏览整个文件夹的所有文件，但会缺失附件以及标签功能。用户自己选择了，是想要一个笔记软件，还是要一个编辑器。

**Comment by je45** [comment]
> @je45
> 
> * 重新加载： 根据索引重新生成节点树
> * 从磁盘重新加载索引： 读取磁盘的vx.json文件生成索引，并重新生成节点树
> * 如果通过文件管理器移动了文件，vnote能识别出来是一个外部文件，并灰色显示，双击即可导入到索引中；对于原来失效的节点，会显示红色节点，右键删除即可
> * vx.json是vnote管理文件的基础，没事就别删除
> * 后面会提供另一种类型的笔记本，没有索引，就是浏览整个文件夹的所有文件，但会缺失附件以及标签功能。用户自己选择了，是想要一个笔记软件，还是要一个编辑器。

感谢回复！
笔记本内部，通过文件管理器移动文件/文件夹。确实会如你所说的那样，移动的文件/文件夹会显示为外部文件，不过原来的位置仍然会显示出来，点击会提示失效。虽然说可以删除失效索引，引入外部文件到索引，不过操作还是过于繁琐。如果文件夹内有多个文件，双击文件夹并不能引入文件夹内的文件，需要一个一个点击，很麻烦。
我的需求是能够重新生成索引（即重新创建vx.json，替换原来的），这样一步到位比较方便。
如果能监控文件变化，自动删除失效索引，自动导入新的文件那就更好了。
至于上面的两个功能，我理解有误。
目前我的解决方案是：笔记本管理-关掉当前笔记本，然后重新通过文件夹创建该笔记本。
个人建议：关于管理笔记本管理按钮，不是应该放到左上角的笔记本子菜单中更加方便吗？一看到笔记本就会想到笔记本相关的功能吧，之前找笔记本管理按钮找了半天。
关于vx.json被删除，个人觉得既然软件检测到了应该更加人性化一点，引导用户重新构建索引，而不是奔溃。当然删除vx.json文件是不太对。其实说到底就是希望能够有重建索引这个功能。

**Comment by tamlok** [comment]
VNote 可能会管理很多类型的文件，然后加上附件文件夹什么的，所以很难检测到哪些的确是用户需要的笔记文件，比较难自动化追踪。后面会添加一个扫描并索引的功能，按一下就能递归扫一遍了，然后如果有错漏就是用户自己去处理了。
