### ISSUE TITLE
能否在vnote内增加直接更新vnote版本的功能

### ISSUE THREAD

**Issue by zhajianting** [vnotex/vnote#1827]
如题，每当vnote发布新版本时，我都需要来github手动下载最新版的压缩包。

然后整体替换，再导入笔记本，这样太麻烦了。

请问后期版本中能否支持在vnote内直接更新，以避免这些繁琐的操作。

**Comment by tamlok** [comment]
替换后不用重新导入笔记本呀？配置是在用户文件夹的，和exe分开的。
