### ISSUE TITLE
垂直拆分后，编辑模式和预览模式，位置不同步

### ISSUE THREAD

**Issue by zt449569708** [vnotex/vnote#1828]
问题：
markdown编辑时，当用锤直拆分后，左边是编辑模式，右边是预览。当编辑模式写完一页后，滚动条都会会往下滚动，但是右边的预览模式，滚动条不会自动滚动，也就是预览不会同步到最新的编辑位置，这样导致在写文档的时候，就不能实时看到右边的预览效果。

环境：
OS：win7
vnote版本：3.5.1

**Comment by tamlok** [comment]
那个拆分不是这样用的。双边预览还没做

**Comment by tamlok** [comment]
已支持双边预览： https://github.com/vnotex/vnote/releases/tag/v3.10.0
