### ISSUE TITLE
a syntax highlighter

### ISSUE THREAD

**Issue by xp44mm** [vnotex/vnote#1831]
`lex-highlight` is a syntax highlighter written according to the lexical analyzer. So it can correctly analyze all kinds of tokens. and It supports advanced features such as string interpolation and language nesting. 

the open source of `lex-highlight` is [here](https://github.com/xp44mm/lex-highlight)

A demo is [here](https://github.com/xp44mm/colorful-language), to test rendered result, you can open the `/dist/index.html` file with a browser.

如果您有兴趣，是否采纳我的语法高亮器到你的markdown编辑器。

目前编写了F#语言，fslex，fsyacc的高亮。高亮测试比较正常。是否能帮我补充你擅长的语言。各个语言高亮的框架是共享的，补充语言只需要提供一系列的正则表达式即可。

**Comment by tamlok** [comment]
Currently I do not have extra energy to try out new things in VNote. Thanks!
