### ISSUE TITLE
新建笔记存在选择模板未生效的情况

### ISSUE THREAD

**Issue by pysense** [vnotex/vnote#1832]
**Describe the bug**
新建笔记存在选择模板未生效的情况，当第一次选择模板时选择项从【无】切换到任一模板时可应用模板内容，当模板已经在其中一个选择状态时直接新建则无法应用模板内容。

**To Reproduce**
1. 导航面板右键【新建笔记】打开新建笔记对话框
2. 模板处先选择【无】再选择任一模板，此时将以选择模板新建笔记
3. 重复【新建笔记】操作，此时模板处将显示上一次记住的模板，直接点击确定，此时新建的笔记未应用当前选择的模板

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2695913/128282253-07f001d5-64f6-4e47-a55e-91e9aea799fd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.5.0

**Additional context**

**Comment by tamlok** [comment]
Will be fixed in next version. Thanks!
