### ISSUE TITLE
位置列表快捷键 `Ctrl+G, C` 无效

### ISSUE THREAD

**Issue by pysense** [vnotex/vnote#1833]
**Describe the bug**
位置列表快捷键 `Ctrl+G, C` 无效

**To Reproduce**
1. 按快捷键 `Ctrl+G, C` 无法切换位置列表面板状态

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.5.0

**Additional context**

**Comment by tamlok** [comment]
`Ctrl+G, C` 是先按住`Ctrl`和`G`，然后松开，然后按`C`。

其实已经激活到位置面板了，按一下上下箭头才开始选中项目，后面会默认选择第一个。

如果不是这样的问题，希望能具体像一点好让我复现，不然我也不知道发生什么事情。

**Comment by pysense** [comment]
VNote 正常按快捷键的表现应该是这样的：

1. 按下 `Ctrl+G, A` ，面板切换到导航窗口
2. 接着按下 `Ctrl+G, U` ，面板将切换到大纲窗口
3. 但如果我按下 `Ctrl+G, C` ，面板并没有切换到位置列表窗口（不是没选择项目的问题）

另外，如果当前大纲窗口是关闭的：
![image](https://user-images.githubusercontent.com/2695913/128584460-4c6cf81b-ed7e-4f08-a096-404c5dc8467a.png)

那么按下 `Ctrl+G, U`  将打开大纲窗口面板

但按下 `Ctrl+G, C` 同样并不会打开位置列表窗口。

**Comment by tamlok** [comment]
我这边没有问题，你看一下用户配置文件夹里面是怎么写的配置？

**Comment by pysense** [comment]
配置文件里是 `Ctrl+G, B`，不知道自己什么时候改动到了。

乌龙了，不好意思~
