### ISSUE TITLE
希望在文本编辑器处增加换行符风格选择

### ISSUE THREAD

**Issue by istarmeow** [vnotex/vnote#1837]
![image](https://user-images.githubusercontent.com/26065919/128653500-95fb5063-3d09-4250-9620-24f24c41c097.png)

目前在VNote编辑shell脚本后，在VSCode中看到行尾序列会变更为CRLF，导致在Linux中运行报错
希望能增加自定义功能，对不同脚本的后缀识别，设置不同的风格。

- CRLF->Windows-style
- LF->Unix Style
- CR->Mac Style
CRLF表示句尾使用回车换行两个字符(即我们常在Windows编程时使用”\r\n”换行)

> VNote牛逼，感谢大佬

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/releases/tag/v3.7.0
