### ISSUE TITLE
舰长模式在输入法为中文的情况下无效

### ISSUE THREAD

**Issue by pysense** [vnotex/vnote#1839]
**Describe the bug**
编辑模式下，当前输入法为中文的情况下，按下 `Ctrl+G` 后按下第二个字符如 `A`，不会触发舰长模式的快捷键，而是触发中文输入法。对比了 VNote 2.x 是没有这个问题的。

**To Reproduce**
1. 按 `Ctrl+T` 切换到编辑模式（如果是 Vi 模式，需要进入 Vi 的编辑模式）
2. 确保当前切换到中文输入法
3. 按 `Ctrl+G` 再按 `A`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2695913/128680290-2a0b0307-78ea-47ff-9c9d-54d582590cc0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.5.0

**Additional context**

**Comment by tamlok** [comment]
目前看来这是Qt的问题，输入法会优先于它的快捷键解析。对文本编辑的确会有影响，后面看看怎么能hack一下。

**Comment by tamlok** [comment]
已经通过一些hack修复了：https://github.com/vnotex/vnote/commit/5da6a81d4b5031e8debc717368dfc0a0b4020c39

可以下载最新构建版使用。

**Comment by pysense** [comment]
> 已经通过一些hack修复了：[5da6a81](https://github.com/vnotex/vnote/commit/5da6a81d4b5031e8debc717368dfc0a0b4020c39)
> 
> 可以下载最新构建版使用。

感谢修复，目前测试正常。
