### ISSUE TITLE
能否增加带前导 0 的星期数字的对应片段

### ISSUE THREAD

**Issue by pysense** [vnotex/vnote#1840]
**Is your feature request related to a problem? Please describe.**
作为一个强迫症患者，有些东西能对齐就尽量对齐……

**Describe the solution you'd like**
日期（dd）、月份（MM）等都有带前导 0 的对应片段，星期数字（w）能不能也增加一个~

**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
Added 0cf0da06f83e158a61a8fc780be99aa2b30ead42
