### ISSUE TITLE
与Deepin20的任务栏插件冲突

### ISSUE THREAD

**Issue by czcn** [vnotex/vnote#1841]
最新：
就Deeping应用商店安装的3.1版有冲突。
用github上的vnote-linux-x64_v3.5.1.appimage，正常可用，没有冲突。

---

**Describe the bug**
与Deepin20的任务栏插件冲突，当安装VNote后，Deepin20的任务栏插件全部消失。

**To Reproduce**
1. Install VNote
2. See Deepin TaskBar ....

**Expected behavior**

**Screenshots**
https://storage.deepin.org/thread/202108071549202984_%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20210807154052.png

**Desktop (please complete the following information):**
 - OS: Deepin
 - Version 20.2.2

**Additional context**

**Comment by tamlok** [comment]
虚拟机装了个Deepin测试了一下，没法复现。估计是Deepin自身的不稳定吧，VNote的代码里面完全没有干预到任务栏。
