### ISSUE TITLE
按f9用外部软件打开，vnote能不能关闭当前md文件，避免两个软件同时修改md文件，导致vnote缓存冲突

### ISSUE THREAD

**Issue by ppxiaodi** [vnotex/vnote#1846]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ppxiaodi** [comment]
我一直在使用vnote，从vnote1上一个版本就开始使用，我记得在vnote1内按f9，使用typora打开md文件，vnote会关闭当前的md文件，我希望vnote2也加上这个功能。

**Comment by tamlok** [comment]
Fixed: 6109737b9d44cbe2a0c85bd27ceb416580b5461d

![image](https://user-images.githubusercontent.com/5763157/129730376-c0cfdb4c-bafd-4795-8e47-839bfa0c5def.png)
