### ISSUE TITLE
[Question] Tag field position

### ISSUE THREAD

**Issue by petertom51** [vnotex/vnote#1849]
OS Version: Windows and Mac
VNote Version: [3.6.0](https://github.com/vnotex/vnote/commit/0530422a9b9a374974ac6af229f218f1778a4af4)

Hi!
I am looking forward a tag to be inserted. I read #1204 and #1029 but still can't find the field to insert tags. One said at the right bottom corner and the other said left bottom corner. Could you kindly to tell me where the field is? Many thanks.

![image](https://user-images.githubusercontent.com/6023242/130001120-35937278-13ef-44d2-9073-e798eec60ee5.png)

**Comment by tamlok** [comment]
Hi,

VNote 3 is a refactor of VNote 2. VNote 3 does not have the **tag** funcationality for now. Will migrate it wihtin next 2 versions. Please stay tuned.

Thanks!

**Comment by petertom51** [comment]
Good to know. 
Looking forward the **tag** functionality. 

Thanks for the quickly reply 👍

**Comment by tamlok** [comment]
Supported now.
