### ISSUE TITLE
不能自适应屏幕分辨率

### ISSUE THREAD

**Issue by hdaojin** [vnotex/vnote#1852]
笔记本电脑外接了一块扩展屏幕。
笔记本本身分辨率是4K屏幕，扩展屏幕是2K。
在两个屏幕之间拖动时，会出现工具栏及其他软件本身的字体变得非常大或非常小，不能自适应分辨率。
其他软件如浏览器可以自适应。

系统：Windows 10 专业版21H1
vnotex：3.6.0

？3.5.1的时候好像没有这个问题。

**Comment by tamlok** [comment]
Qt的应用程序好像都有这样的问题，如果不是同样的DPI的话，两个屏幕之间移动并不能自适应。改变DPI后，需要在你希望的屏幕上启动VNote进行初始化。

**Comment by hdaojin** [comment]
> Qt的应用程序好像都有这样的问题，如果不是同样的DPI的话，两个屏幕之间移动并不能自适应。改变DPI后，需要在你希望的屏幕上启动VNote进行初始化。目前的办法是移动VNote到指定屏幕，然后右上角重启一下。

收到。谢谢解答。
