### ISSUE TITLE
期望增加设置关闭历史记录或者把历史记录从 vx_notebook/vx_notebook.json 移除

### ISSUE THREAD

**Issue by L-sizhong** [vnotex/vnote#1855]
原因：使用 git 同步笔记，多端使用时，只是查看笔记就会导致 vx_notebook/vx_notebook.json 的 history 节点发生变更，需要频繁提交变更，查看笔记容易忘记同步，导致下次同步时需要解决冲突。

建议方案：
1、增加开关，允许用户手动关闭历史记录
2、增加开关，允许用户手动选择历史记录的存放位置

目的：尽量减少单纯查看笔记带来的变更

**Comment by tamlok** [comment]
重启了吗？我这边改为了0就不会再改动历史条目了。

**Comment by tamlok** [comment]
54a71ae9772c4587b8dd08e7fb81f0f66e332591

增加了一个开关了。

![image](https://user-images.githubusercontent.com/5763157/131236311-4efe1686-39ab-4e38-9b89-39c307365a69.png)

**Comment by L-sizhong** [comment]
> 重启了吗？我这边改为了0就不会再改动历史条目了。

非常感谢，重启后就可以了
