### ISSUE TITLE
阅读模式时展示图表的时候也展示源码

### ISSUE THREAD

**Issue by L-sizhong** [vnotex/vnote#1863]
这是一个比较小众的需求：能否在代码块增加一个标志，控制这段代码在阅读模式下，渲染为 PlantUML、Flowchart.js、Mermaid、WaveDrom 等图表时，同时也能展示这段源代码，例如下面的（|showSource）：

    ```puml|showSource
    @startuml
    @enduml
    ```

原因：最近在学习这些图表的语法，有些示例，想同时能看到源码和渲染后的结果，现在是同时写两份代码实现的，一份指定为 text/plain，一份指定为 puml。

这个功能很小众，使用场景也很少，也有替代的解决方法，要是实现起来太麻烦的话，作者请忽略这个需求吧。

**Comment by tamlok** [comment]
鉴于还有500个issues，最近需求也是肝到内牛满面，这种边角需求就没精力顾及了。

自己动手实现思路：VNote的阅读模式是使用JS来渲染的，所以完全可以通过JS来添加一个DOM来展示源码。这个也不用重新编译VNote，改动`web/js`下面的对应文件即可。

**Comment by L-sizhong** [comment]
> 鉴于还有500个issues，最近需求也是肝到内牛满面，这种边角需求就没精力顾及了。
> 
> 自己动手实现思路：VNote的阅读模式是使用JS来渲染的，所以完全可以通过JS来添加一个DOM来展示源码。这个也不用重新编译VNote，改动`web/js`下面的对应文件即可。

好嘞，我试试，非常感谢
