### ISSUE TITLE
笔记名称中有空格，插入图片，链接未自动处理空格

### ISSUE THREAD

**Issue by yf-9186** [vnotex/vnote#1868]
笔记名称中有空格，插入图片，链接未自动处理空格（默认 gitee 图床）

VNote 3.7.0

版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎1/‎13
操作系统内部版本	19043.1165
体验	Windows Feature Experience Pack 120.2212.3530.0

**Comment by tamlok** [comment]
应该是Gitee的Bug，vnote是直接使用返回的URL的。

已经修复： 606dcef16f882350cc2be2fd108625894d13143b
