### ISSUE TITLE
工具栏图标可能出现重叠现象

### ISSUE THREAD

**Issue by pysense** [vnotex/vnote#1869]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2695913/131981192-2b5498b2-6b41-457a-b09f-78ac0e6e82d5.png)

**To Reproduce**
复现的步骤不一定全，我尝试了以下一种情况可以复现：
1. 关闭所有笔记，关闭 VNote
2. 打开 VNote，打开两篇笔记（默认处于阅读模式）
3. 新建工作空间并打开一篇笔记
4. 切换到第一个工作空间，再点击第一篇打开的笔记
5. 按两次 `Ctrl+T` 切换编辑、阅读模式
6. 切换到第二个工作空间，再切换到第一个工作空间
7. 按 `Ctrl+T` 切换到编辑模式，此时可以看到工具栏图标重叠

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10
 - Version 3.7.0

**Comment by tamlok** [comment]
置顶issue : https://github.com/vnotex/vnote/issues/853

**Comment by pysense** [comment]
> 置顶issue : #853

刚试了也不行，OpenGL问题就忽略了，影响也不大
