### ISSUE TITLE
Theme太少，能否复用VS Code的theme？

### ISSUE THREAD

**Issue by ygcaicn** [vnotex/vnote#1871]

**Comment by tamlok** [comment]
主题是肯定不能复用的。主题数量靠我一个人来做，做来做去也就那几款了。用户可以参考文档自定义。后面会添加在线主题功能，方便用户分享主题。

**Comment by gueeisgrim** [comment]
不能复用是不是版权的问题？

**Comment by tamlok** [comment]
> 不能复用是不是版权的问题？

是文件格式不通用问题，只能人工迁移
