### ISSUE TITLE
mermaid 绘图没有立即渲染

### ISSUE THREAD

**Issue by YeomanYe** [vnotex/vnote#1872]
**Describe the bug**
编写mermaid代码，没有被立即渲染

**To Reproduce**

**Expected behavior**
mermaid 绘图立即渲染出来

**Screenshots**

![image](https://user-images.githubusercontent.com/18027354/132289845-ce38dc90-d4e5-49ad-bf77-c3974a4af441.png)

**Desktop (please complete the following information):**
 - OS: [Mac 10.15.7]
 - Version [2.10]

**Additional context**

**Comment by tamlok** [comment]
2.10 已经不再维护，请更新到3。

Mermaid的原地预览会有些已知问题。

**Comment by YeomanYe** [comment]
> 2.10 已经不再维护，请更新到3。
> 
> Mermaid的原地预览会有些已知问题。

3.7版本确实可以，但是原地渲染会有问题，这些能解决吗？

**Comment by tamlok** [comment]
> > 2.10 已经不再维护，请更新到3。
> > Mermaid的原地预览会有些已知问题。
> 
> 3.7版本确实可以，但是原地渲染会有问题，这些能解决吗？

解决不了，要不mermaid哪天支持png格式渲染，现在svg里面有foreign object，qt的渲染支持不是很好。js转svg为png的话，也因为跨域转不了。
