### ISSUE TITLE
"上传图片到图床":建议优化下目录的取值范围

### ISSUE THREAD

**Issue by kunlunsiqu** [vnotex/vnote#1876]
**Describe the bug**
上传后的图片 uri 无法获取

**To Reproduce**
1. 编辑
2. 上传图片到图床

**Screenshots**
Uri: https://gitee.com/analysis-of-river-snow/drawing-bed/raw/master/20210911113403.gif

**Desktop (please complete the following information):**
 - OS: Linux kunlun 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
 - Version [e.g. 3.6.0]

**Additional context**

**Comment by tamlok** [comment]
这是Gitee的bug，它返回的downloadurl居然是包含空格的，你手动把url里面的空格替换为`20%`即可。已经修复。

**Comment by kunlunsiqu** [comment]
> 这是Gitee的bug，它返回的downloadurl居然是包含空格的，你手动把url里面的空格替换为`20%`即可。已经修复。

感谢
