### ISSUE TITLE
搜索功能输入问题

### ISSUE THREAD

**Issue by limouren-soul** [vnotex/vnote#1879]
每次全文搜索时，中文输入还没点确定自己就变成英文提前到输入框中去了，window10，自带输入法

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/133864196-c346181b-33b5-4fc2-9d90-ab7eb3762074.png)

![image](https://user-images.githubusercontent.com/5763157/133864211-aa7ac56a-6338-45d0-9018-7b601069547c.png)

ESC能撤销，Enter能上英文，空格能上中文。

我认知中一直都是这样的，这个叫pre-edit text.
