### ISSUE TITLE
VNote打开.sql文件，软件无响应

### ISSUE THREAD

**Issue by istarmeow** [vnotex/vnote#1882]
VNote3.7.0
Windows11
打开笔记中的**.sql文件，必现软件无响应

**Comment by tamlok** [comment]
先看一下是不是这个问题：https://github.com/vnotex/vnote/issues/853

方便的话，可以把文件发我邮箱，我这里无法复现。

无响应后，重启vnote，右上角问号那里有日志，可以看一下。

**Comment by istarmeow** [comment]
大概知道了，我认为是sql文件过大导致的，80M+，新创建的sql文件比较小可以正常打开
