### ISSUE TITLE
关于字数统计

### ISSUE THREAD

**Issue by zhangbw17** [vnotex/vnote#1884]
我看到2018年6月发布的版本中是存在右下角的字数统计的，但是在最新的一版中似乎在正中间替换成了行数的范围和当前光标在每一段中的位置。
请问是出于什么原因将字数统计取消了呢？感觉这是一个很实用的功能，有没有将其重新加回来的计划呢。
最后感谢作者和这个很棒的项目，Thanks!

**Comment by tamlok** [comment]
因为还没迁移

**Comment by zhangbw17** [comment]
好的谢谢
