### ISSUE TITLE
关于文件加密

### ISSUE THREAD

**Issue by zhangbw17** [vnotex/vnote#1885]
之前在使用有道云笔记的时候，有些笔记本可以设置加密，这个功能是否有计划实现呀？
还有一个问题，作为github小白想尝试一下并且pr一下会有什么需要注意的吗？
如能解惑，不胜感激~

**Comment by tamlok** [comment]
vnote是开放数据，有道云是封闭数据，所以后者很方便加密。PR随便提就好了。

**Comment by zhangbw17** [comment]
好的谢谢
