### ISSUE TITLE
windows 10 系统下 3.7 版本的 斜体 预览字体发虚

### ISSUE THREAD

**Issue by hhycqu** [vnotex/vnote#1889]
刚从2.9版本升级过来，现在用的3.7.

在windows 10 系统下 
斜体预览时字体发虚 （图中上部）
![图片](https://user-images.githubusercontent.com/91321830/134837457-63695108-76c6-4b0e-bd2c-0eab51afd870.png)

在ubuntu 20.04 下 正常（图中下部）

**Comment by tamlok** [comment]
这个我也不知道怎么处理，可以试试编辑样式里面得`text-editor.theme`更换一个字体看看。具体参考官网文档。

**Comment by hhycqu** [comment]
> 这个我也不知道怎么处理，可以试试编辑样式里面得`text-editor.theme`更换一个字体看看。具体参考官网文档。

谢谢您！ 经过反复测试，确实应该是默认字体的问题。我在windows 10 下在“设置”-“编辑器”-“Markdown 编辑器”把“覆盖字体”选择为“微软雅黑” 则恢复了正常！  那么是否可以在下一个版本默认修改为微软雅黑字体呢？ 谢谢！
