### ISSUE TITLE
编辑模式下代码块中的中文字体始终是宋体，无法通过配置改变

### ISSUE THREAD

**Issue by zhangwinston** [vnotex/vnote#1892]
**Describe the bug**
编辑模式下，代码块中的中文字体始终是宋体，尝试修改text-editor.theme文件中的相关字段，无法改变。
比如：markdown-editor-styles下面的各个字段CODE、COMMENT、FENCEDCODEBLOCK，将font-family修改为Microsoft YaHei，不是生效，只保留Microsoft YaHei，中文字体仍然是宋体。

**To Reproduce**
修改text-editor.theme保存后，退出Vnote并重启。

**Expected behavior**
期望编辑模式下，代码块中的中文字体是雅黑。

**Screenshots**
![image](https://user-images.githubusercontent.com/13915542/135051223-4dddc92c-cf25-43fd-8e0b-eab5194774a1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.7.0

**Comment by hhycqu** [comment]
在“设置”-“编辑器”-“Markdown 编辑器”把“覆盖字体”选择为“微软雅黑” 试试吧。

**Comment by tamlok** [comment]
无法复现，这个应该就是yahei了？如果是中文系统，是不是可以写`微软雅黑`试试？

![image](https://user-images.githubusercontent.com/5763157/140237512-79808ab0-b815-496f-a37e-684aa7b1ad0c.png)

**Comment by zhangwinston** [comment]
最新的3.8.1版本已经是OK的了，多谢！！！
