### ISSUE TITLE
Display problems in edit mode

### ISSUE THREAD

**Issue by ygcaicn** [vnotex/vnote#1893]
**Describe the bug**

When editing a line that is too long, the rightmost words are obscured.

**Screenshots**

![image](https://user-images.githubusercontent.com/17684070/135217627-5570ea9d-378d-4206-86c1-ce7afe850e87.png)

**Desktop (please complete the following information):**
 - OS: macOS  11.6
 - Version 3.7.0

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/576
