### ISSUE TITLE
希望vnote的latex(mathjax)功能可以支持加载更多宏包

### ISSUE THREAD

**Issue by Roseleaves** [vnotex/vnote#1894]
**Is your feature request related to a problem? Please describe.**
现在在代码中写```\dv{x}```仍然报错

**Describe the solution you'd like**
physics宏包有```\dv{x}```，它可以直接写出导数符号

**Describe alternatives you've considered**
当前规范的导数符号只能使用```\frac{\mathrm{d}}{\mathrm{d}x}```来实现，十分繁琐。

**Additional context**
问题已经解决了。要在 `\dv{x}` 使用前使用 `\require{physics}`。目前能正常运行。

**Comment by tamlok** [comment]
我对这方面不了解，具体是应该怎么操作呢？是加载MathJax脚本的时候提供额外的参数？
