### ISSUE TITLE
对于微信公众号文章复制内容粘贴为Markdown解析不正常

### ISSUE THREAD

**Issue by Storm0** [vnotex/vnote#1896]
**Describe the bug**
在对微信公众号的文章内容进行复制时，如果所复制的内容包含有代码块。那么在进行`解析为 Markdown 并粘贴`之后，会出现代码块内容只粘贴了一行或部分内容的情况。

**To Reproduce**
[示例文章](https://mp.weixin.qq.com/s/H9omH8ir5dYSnZJVq8b3Nw)

1. 复制一部分带有代码块的文章内容
2. 在VNote中进行 `解析为 Markdown 并粘贴`

**Expected behavior**
应完整的粘贴为复制的内容

**Screenshots**
下面分别是被复制的内容和粘贴之后显示的效果：

![image](https://user-images.githubusercontent.com/45959316/136661237-548a0f6d-18e6-4fa9-85b4-d33b44ab5949.png)

![image](https://user-images.githubusercontent.com/45959316/136661248-dae170bc-6909-4c49-9877-915b5368bfd0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.7.0

**Comment by tamlok** [comment]
Hi,

看了一下，这个公众号的代码块并不是标准的代码块，而是一行一个`<code>`。对于这种非标准的网页，暂时不考虑兼容了。可以单独复制代码块内容，然后作为纯文本粘贴即可。

![image](https://user-images.githubusercontent.com/5763157/140295201-67844f59-6d05-4b33-aa90-c2a084b53888.png)
