### ISSUE TITLE
文件夹和文件无法升降级，不知道能够增加这项功能

### ISSUE THREAD

**Issue by gueeisgrim** [vnotex/vnote#1899]
作者的辛苦和努力我都能看到。比如支持csv和新文件导入
不知道能够增加文件夹和文件升降级别，谢谢。

**Comment by tamlok** [comment]
> 作者的辛苦和努力我都能看到。比如支持csv和新文件导入 不知道能够增加文件夹和文件升降级别，谢谢。

右键菜单剪切粘贴就是了呀
