### ISSUE TITLE
windows平台打开笔记本中的目录直接卡死

### ISSUE THREAD

**Issue by xiaoxinbioinfo** [vnotex/vnote#1902]
**问题描述**：
打开软件进入笔记本，双击打开里边的目录时，软件直接卡死，没有响应；
问题的情况和#853类似。
已经尝试了里边的几种方法，指定集成显卡、更新显卡驱动、声明新的环境变量、在vnote中设置openGL值，不论哪种方法，设置后重启vnote，依旧会卡死。

目前使用的电脑系统是win10 20H2，
使用的vnote在3.7.0和3.6.0中都遇到了同样的问题，暂时无法解决。

大佬们求助！！

**Comment by xiaoxinbioinfo** [comment]
当时应该是试用了3.6.0和3.7.0都没有解决，考虑用个最新的试试，后来也没有解决就没有再动了。
目前电脑可能不太方便远程，可以调取其他日志来检查吗？

**Comment by tamlok** [comment]
把新建笔记本操作后崩溃的log发给看看？

**Comment by xiaoxinbioinfo** [comment]
> Info:(main.cpp:133) "VNote (v3.7.0) started at 周三 10月 20 11:26:20 2021 (windows)"
> Info:(main.cpp:138) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1g  21 Apr 2020"
> Info:(main.cpp:194) locale: "zh_CN"
> Info:(thememgr.cpp:91) using theme "pure"
> Warning:(notebooktagmgr.cpp:26) ignore invalid <parent, child> tag pair ""
> Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default

和上边描述的语言信息有关联吗？

**Comment by tamlok** [comment]
没关系，啊，真的是没什么相关信息呀。要不你通过命令行 vnote.exe -d 启动vnote，然后操作卡死，再把log看一下？

**Comment by xiaoxinbioinfo** [comment]
我安装vnote应该早一些，最早安装到现在有快半年，但是中间基本没有使用；
最近才刚开始用起来，所以，可以算是第一次使用吧

**Comment by leichn** [comment]
我也遇到同样的问题，一打开很快就卡死，更新到最新版本3.10.1，删除旧的配置文件都没用。关掉有道词典就好了。

**Comment by tamlok** [comment]
已经修复了，下个版本应该好了
