### ISSUE TITLE
希望能实现2.8版本中的“钉到历史中”的功能

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#1907]
如题，期待大佬不忙的时候能够实现上述功能，现在笔记比较多（198篇笔记，293个文件夹），有的比较常用的笔记在层级较深的位置，“钉到历史中”的功能可以很方便的打开这类笔记。嘿嘿

昨天开始尝试从2.8迁移到3.8.1，目前已经调整出了一套自己的主题了（多行代码限制最大高度、图片加边框、单行代码加阴影、引用样式修改等等）。

还有个小小的个人愚见：能否优先实现老版本中的功能，将新功能作为第二优先级的任务。这样可以方便深度实用的老用户迁移过来，这样的话可以帮忙测试出来一些比较严重的bug

十分谢谢大佬的努力！vnote 对我来说简直太好用了

**Comment by tamlok** [comment]
3.9.0可以方便删除了。
