### ISSUE TITLE
Add a toggle to force rendering plain text as markdown

### ISSUE THREAD

**Issue by a224515a** [vnotex/vnote#1908]
I've wrote a markdown and saved as a file with extension '.txt'.
It's OK that VNote recognize this file as plain text rather markdown.
It would be helpful if there is a toggle (e.g., a shortcut, like `Ctrl+T`) to control *force rendering as markdown*.

Thank you for this great work !

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/b3a385693c46b957c62aa1bbe10549ca944ac496
