### ISSUE TITLE
建议：关于图片的一些个人建议

### ISSUE THREAD

**Issue by MooNkirA** [vnotex/vnote#1910]
你好。对于使用软件操作上一些建议，希望作者可以采纳

1. 是否可以增加自定义设置保存图片的本地文件夹名称？
2. 是否可以增加手动拖动图片文件到编辑区，直接插入图片？

**Comment by tamlok** [comment]
Hi,

1. 名称的话，可以在`vx_notebook`下面的json文件里面设置一下`image_folder`；
2. 按住`shift`再拖动就可以插入图片了。以前直接拖动就可以的，但用户说希望直接拖动是粘贴纯文本，所以必须要按shift才能触发多功能粘贴。

**Comment by MooNkirA** [comment]
明白。感谢大佬百忙中抽空回复。谢谢
