### ISSUE TITLE
编辑模式下mermaid预览问题

### ISSUE THREAD

**Issue by wuscloud** [vnotex/vnote#1912]
![image](https://user-images.githubusercontent.com/12063279/139796417-d3d00dbb-d281-4ac9-ae8d-87ebc4ade9f1.png)

**Comment by tamlok** [comment]
这是mermaid的问题，暂时无能为力。前端大神如果能帮一下忙也好，看怎么绕开跨域的限制把svg转换成png。我实在折腾不了了。

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/pull/2334
