### ISSUE TITLE
功能需求：对特定后缀的文件自动使用外部程序编辑

### ISSUE THREAD

**Issue by jasongwq** [vnotex/vnote#1913]
**Is your feature request related to a problem? Please describe.**
docx，pdf等后缀的文件双击的时候会自动调用外部程序打开，针对*.drawio文件（后缀）我的期望也是能自动调用外部程序打开，当前会自动在vnote内置阅读器中打卡，呈现结果是类似如下的人类几乎无法阅读的字符
`<diagram id="vPbhk3nIlcIQmpf27ohs" name="第 1 页">7V1bc9rIEv41qso+xKW7NI+SgCR14qxrSbw+T6cwyMBZjFwgx/b59Wd6LkJoGiGDYMRmU6myNJJGo57ury/TPRhO8vj6aTV6ml1nk3Rh2Obk1XB6hm1blmnTP9Dyxlv80OcN09V8Im7aNAzn/0tFoylan+eTdL11Y55li3z+tN04zpbLdJxvtY1Wq+xl+7aHbLH91q`

**Describe the solution you'd like**
新增一个配置项，将特定后缀的文件排除外，不让vnote使用内置阅读器打卡
**Describe alternatives you've considered**
使用快捷键F9打开
**Additional context**
我在github中搜索docx，pdf等关键词没看到代码中有对其特殊处理的地方。不知vnote当前对于docx，pdf等是如何处理的，如果有可能的话请帮忙增加下这个需求，如果开发者有其他优先级更高的事情，请求能给予我一些帮助，让我能自行尝试修改代码

**Comment by tamlok** [comment]
Hi,

默认是纯文本都会在VNote里面当作文本打开。可以尝试修改这个函数： https://github.com/vnotex/vnote/blob/d7bfb956ec0f635c97518e5dda162077b3cedcde/src/core/buffer/filetypehelper.cpp#L62

**Comment by jasongwq** [comment]
看起来似乎可以在
https://github.com/vnotex/vnote/blob/d7bfb956ec0f635c97518e5dda162077b3cedcde/src/core/buffer/filetypehelper.cpp#L58
前面加一行 `type.m_suffixes << QStringLiteral("drawio");` 即可
```
    {
        FileType type;
        type.m_type = FileType::Others;
        type.m_typeName = QStringLiteral("Others");
        type.m_displayName = Buffer::tr("Others");
        type.m_suffixes << QStringLiteral("drawio");
        m_fileTypes.push_back(type);
    }
```
但理想的应该是完成以下TODO，后缀从配置文件中读取
https://github.com/vnotex/vnote/blob/d7bfb956ec0f635c97518e5dda162077b3cedcde/src/core/buffer/filetypehelper.cpp#L25

**Comment by tamlok** [comment]
是的，从配置文件读取这个后面再做了，优先级较低。

**Comment by jasongwq** [comment]
> 是的，从配置文件读取这个后面再做了，优先级较低。

我这边通过加了一行type.m_suffixes << QStringLiteral("drawio")实现了对特定后缀使用外部编辑器，是否可以pr合入？还是等实现可自定义配置之后再合入？

**Comment by tamlok** [comment]
等后面实现从配置文件里面读取吧，这样通用一点。

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/b3a385693c46b957c62aa1bbe10549ca944ac496

**Comment by jasongwq** [comment]
补充下摸索出来的配置方式：
需要先[添加外部程序](https://github.com/vnotex/vnote/blob/14c54ab2759ad16cdfbc5fad3aa7a4eca3c69ac3/src/data/extra/docs/zh_CN/external_programs.md)，然后再在设置->文件关联->外部程序里添加对应的后缀，实现特定后缀使用特定程序打开的效果（支持直接双击打开）
