### ISSUE TITLE
vnote-win-x64_v3.9.0.zip 解压失败

### ISSUE THREAD

**Issue by BeyondXinXin** [vnotex/vnote#1914]
vnote-win-x64_v3.9.0.zip 解压失败
vnote-win-x86_v3.9.0.zip 解压正常

系统 win11
软件 7-zip

![SharedScreenshot](https://user-images.githubusercontent.com/78600221/140614684-b826cb44-b00e-4251-86cf-416d44ddd9dd.jpg)

**Comment by tamlok** [comment]
已经修复，谢谢！
