### ISSUE TITLE
编辑模式下代码段中tab显示问题

### ISSUE THREAD

**Issue by ygcaicn** [vnotex/vnote#1915]
![image](https://user-images.githubusercontent.com/17684070/140618813-7f0e9996-5649-4ea9-a1a7-c3c25114f4f5.png)

强迫症无法接受，请问如何修改tab显示样式

**Comment by tamlok** [comment]
`text-editor.theme` 里面：

![image](https://user-images.githubusercontent.com/5763157/140629098-270b1aac-a31d-42fb-af57-db74570ce588.png)

**Comment by ygcaicn** [comment]
多谢
