### ISSUE TITLE
组合快捷键&点击按钮收起侧边栏

### ISSUE THREAD

**Issue by Karonheaven** [vnotex/vnote#1916]
**Is your feature request related to a problem? Please describe.**
组合快捷键会被中文输入法捕获。例如“CTRL+G, E”收起侧边栏，中文输入状态下按完CTRL+G后按下E会出现输入法框，需要切换到英文输入才能正常实现快捷键功能

**Describe the solution you'd like**
类似于VSCODE或者IntelliJ的UI逻辑，点击按钮能够展开相应侧边栏，再点击相同按钮能收起侧边栏

**Comment by tamlok** [comment]
组合键问题已经修复了，可以等下一个版本。

Qt不支持自动隐藏的dock，所以暂时不做这个功能了。
