### ISSUE TITLE
与有道词典软件冲突，vnote卡死

### ISSUE THREAD

**Issue by senweiliang** [vnotex/vnote#1918]
**Describe the bug**
与有道划词翻译冲突导致vnote卡死
**To Reproduce**
打开有道词典（8.10.3.0），打开划词翻译，点击设置->取词划词->直接展示结果，双击任意笔记或右键笔记，软件卡死无响应。
**Expected behavior**
不应卡死

**Comment by Star-air** [comment]
这个我也碰到了，所以我把有道卸载了

**Comment by tamlok** [comment]
可以换欧路词典，我有空再看看能不能解决吧

**Comment by senweiliang** [comment]
> 可以换欧路词典，我有空再看看能不能解决吧

好的，谢谢！

**Comment by senweiliang** [comment]
> 这个我也碰到了，所以我把有道卸载了
如果取词划词设置的不是“直接展示结果”就没问题

**Comment by tamlok** [comment]
Fixed https://github.com/vnotex/vnote/commit/301dace730279d3b3ac199764f72ded39c03c93c
