### ISSUE TITLE
求导出功能的用法

### ISSUE THREAD

**Issue by iktcao** [vnotex/vnote#1921]
能否介绍一下借助pandoc导出的使用方法，软件导出的高级选项不太会用

**Comment by tamlok** [comment]
https://vnotex.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%AF%BC%E5%87%BA.md#toc_5

这里看一下？

**Comment by iktcao** [comment]
多谢多谢
