### ISSUE TITLE
The width of TAB char in markdown editor is 3, but in read mode is 4

### ISSUE THREAD

**Issue by shengkui** [vnotex/vnote#1925]
**Describe the bug**
I found if paste some code from other editor to the markdown editor, the width of TAB char is 3. But I've set the TAB size to 4. And its size is 4 when display in read mode.

**To Reproduce**
1. Edit a markdown note
2. Copy some code using TAB chars for indent from other editor.

**Expected behavior**
The size of TAB in markdown editor should be the same with config of text editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/17078500/141251529-de7faca2-09d1-4f19-9b23-c264011feb2c.png)

![image](https://user-images.githubusercontent.com/17078500/141251979-35bb30af-05e0-44c7-8157-ef5a14a93944.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.9.0

**Additional context**
None

**Comment by tamlok** [comment]
Fixed in https://github.com/vnotex/vtextedit/commit/08b440d3045c944a8a6d7f8945a197ff56dcec82

Thank you!
