### ISSUE TITLE
快捷键改进建议

### ISSUE THREAD

**Issue by ircc** [vnotex/vnote#1933]
新的VNote3跟VNote2相比，改进很大，很多方面都有增强，比如：标签、搜索
但快捷键跟VNote2相比还少了很多，建议改进完善，

1. 增加支持修改快捷键能力，跟其他程序有快捷键冲突的时间都没办法修改
2. 增加更多快捷键，比如：
	- 支持快捷键切换显隐停靠部件; 
	- 支持快捷键（ctrl+c,ctrl+v）、插入链接等

**Comment by tamlok** [comment]
1. 右上角设置那里，编辑用户配置文件，里面都是所有的快捷键设置，随便改即可。
2. 完整的快捷键列表请看上述配置文件。应该是有快捷键扩展内容区以及选定某个面板的。
3. ctrl-v默认插入的是纯文本，这是以前有用户要求改的，想要多功能粘贴，请按ctrl-shift-v，右键菜单那里应该都有提示的。
