### ISSUE TITLE
Version number wrong in latest MacOS download

### ISSUE THREAD

**Issue by suschizu** [vnotex/vnote#1934]
The version number wasn't updated to 3.10.1 - it still shows 3.10.0
MacOS download: 
https://github.com/vnotex/vnote/releases/download/v3.10.1/vnote-mac-x64_v3.10.1.zip

<img width="409" alt="Screenshot 2021-11-18 at 21 13 37" src="https://user-images.githubusercontent.com/16004333/142490196-2970eb48-bfed-4c0a-b850-1e523dfd89a3.png">

**Comment by tamlok** [comment]
Thanks! Fixed: https://github.com/vnotex/vnote/commit/54576543e9d34899d03735f2edffc118956b02f0

You could continue to use it. The binary is the latest one without the version updated.
