### ISSUE TITLE
编辑模式和阅读模式代码段语言标记问题

### ISSUE THREAD

**Issue by ygcaicn** [vnotex/vnote#1939]
**Describe the bug**
编辑模式和阅读模式代码段语言标记不一致，例如汇编代码，在编辑模式下标记asm可以高亮，而在阅读模式下需要标记为nasm，类似的还有shell脚本等。

**Expected behavior**
编辑模式和阅读模式语言标记保持一致。

**Screenshots**

![image](https://user-images.githubusercontent.com/17684070/142757330-6f94bc33-e4ac-43fa-89ac-b50059268edd.png)

**Desktop (please complete the following information):**
 - OS: [macOS 12.0.1]
 - Version 3.10.1

**Comment by tamlok** [comment]
编辑模式添加了`nasm`语言，shell的有具体例子吗？其他的也可以报告，我逐一看看。

https://github.com/vnotex/vnote/commit/2d4d4609da1a93b37c9ef10099dc600fd62b7e6d

**Comment by ygcaicn** [comment]
shell的问题是编辑模式下sh，shell，bash标记均可，习惯了简单直接写sh，但是阅读模式下只认bash

**Comment by tamlok** [comment]
那就写bash吧

**Comment by ygcaicn** [comment]
那是否编辑模式也只保留bash

**Comment by tamlok** [comment]
编辑模式是按照文件名后缀的,例如CPP的可能是*.c或者*.cc或者*.cpp

**Comment by tamlok** [comment]
想了一下，还是让编辑模式只保留bash吧。
