### ISSUE TITLE
在Metadata中自定义图片目录

### ISSUE THREAD

**Issue by Jie-Qiao** [vnotex/vnote#1940]
如果要实现每个md文件有不同的image目录，在typora中的解决方法是在metadata中创建两条：
```
---
typora-root-url: my_custom_image_folder
typora-copy-images-to: my_custom_image_folder
---
```
标记自定义的目录位置，以及图片保存位置。不知道这里能否实现呢？

**Comment by tamlok** [comment]
Typora是编辑器，所以可能比较注重每个文件的metadata的定义。VNote是笔记本软件，所以比较注重整个笔记本的统一设置。目前还没有读取每个文件的metadta的能力。
