### ISSUE TITLE
Read mode does not work in latest Fedora

### ISSUE THREAD

**Issue by henices** [vnotex/vnote#1942]
vnote：   3.10.1
OS   ：   Fedora Linux 35
QT   ：   5.15.2

When exporting a large markdown file to a html file, vnote cpu 100%, but for a small markdown file vnote works properly. 

![image](https://user-images.githubusercontent.com/929715/142802013-c4984271-f7af-4c21-8980-962d1393f5dc.png)

**Comment by tamlok** [comment]
It eventually finished the export, right?

I tested one file with 10K lines and it consumed some CPU but eventually finished.

**Comment by henices** [comment]
![image](https://user-images.githubusercontent.com/929715/142957709-7819c351-42bd-4583-af21-160887e7e511.png)

almost every markdown file except very small one export to html failed.

**Comment by tamlok** [comment]
Do you compile it yourself? Try AppImage file from GitHub. VNote is not tested in qt 5.15.

**Comment by henices** [comment]
I did test the vnote AppImage download from Github, but in Fedora 35 the view mode display nothing, so I have to compile vnote myself. 

![image](https://user-images.githubusercontent.com/929715/142962059-dc99ccc4-f9fb-46b3-8f95-b1ac4dfd2d97.png)

I also try to use Qt 5.12 to compile vnote,  but the view mode display nothing neither.

**Comment by henices** [comment]
BTW  in QT 5.12   F12 doesn't works   :)

![image](https://user-images.githubusercontent.com/929715/142962824-e3fddb90-9837-45d0-a100-8fce47c45d56.png)

**Comment by tamlok** [comment]
It looks like that qtwebengineprocess does not work as expexted. Do you install qtwebview
when compiling it? I will test it on fedora later sometime

**Comment by tamlok** [comment]
Are you using nvidia video card?

**Comment by henices** [comment]
Yes, I use nvidia video card.  Everything works properly in previous Fedora editions, I'm a vnote user since vnote 2.

**Comment by henices** [comment]
> 

![image](https://user-images.githubusercontent.com/929715/142964092-bca1e540-0358-4d94-9fb2-cab637f996b0.png)

I didn't install qtwebview when compiling vnote,  I will install it and try to compile vnote again.

**Comment by tamlok** [comment]
To compile it using 5.12, you could download the qt installer from qt and install it you home dir. Then use it to compile vnote,.without polluting your system env.

**Comment by henices** [comment]
![image](https://user-images.githubusercontent.com/929715/142964782-1b950e3a-102c-435e-bf77-080ba4359430.png)
![image](https://user-images.githubusercontent.com/929715/142964819-51d34b75-6386-4c97-b538-84739652cd86.png)

Yes, I tried it several times, after compiling vnote,  the view mode display nothing.  In Fedora 34,  vnote works properly.

**Comment by henices** [comment]
using fedora system's qt 5.15.2 to compile vnote, the vnote view mode works properly, but exprot html or pdf failed.

**Comment by tamlok** [comment]
do you install qtwebview in 5.12 qt?

**Comment by henices** [comment]
Fedora 35 only provide qtwebview in 5.15.2 qt,  so I have to install it qtwebview 5.12 manualy ?

**Comment by tamlok** [comment]
from qt online installer

**Comment by henices** [comment]
I selected every from the installer

![image](https://user-images.githubusercontent.com/929715/142967022-3b554d56-373b-40b4-a84e-fb47582f93b8.png)

**Comment by tamlok** [comment]
can you try extracting the appimage and execute the script to run vnote directly and check if there is any error hints?

**Comment by henices** [comment]
```
./vnote-linux-x64_v3.10.1.AppImage --appimage-extract
cd squashfs-root
./AppRun
```

![image](https://user-images.githubusercontent.com/929715/142969488-08a37406-0411-432c-911d-9a58e628794b.png)

export md to html, cpu 100%

![image](https://user-images.githubusercontent.com/929715/142969408-520bb392-b6c0-4e4a-953d-96aa888a11ff.png)

view mode display nothing
![image](https://user-images.githubusercontent.com/929715/142969443-c10ff20b-6378-4d90-86f1-0595459aaed6.png)

**Comment by tamlok** [comment]
ok, i will try fedora latest version later.

**Comment by henices** [comment]
> ok, i will try fedora latest version later.

thanks a lot, vnote is quite good,  thank you for your hard work.

**Comment by tamlok** [comment]
It is not VNote's bug. It is a Qt's issue.

Try adding `--no-sandbox` as start up argument. It should work.

https://github.com/microsoft/vscode/issues/132455

**Comment by henices** [comment]
QTWEBENGINE_DISABLE_SANDBOX=1 ./vnote

**Comment by henices** [comment]
@tamlok There is a bug in edit mode's preview (two panel),  preview panel will refresh automaticly when typing text and then the text in preview panel disappear, press ctrl T return to vnote's view mode the text in it disappear too.

Close the markdown file which we opened and reopen it again, I can see content of the markdown in view mode.

**Comment by tamlok** [comment]
I could not repro this on Fedora VM. It is an env-related issue for Qt aplications with QtWebEngine. VNote seems could do nothing here.

You could try `sudo` with `--no-sandbox` to run VNote.

**Comment by henices** [comment]
> I could not repro this on Fedora VM. It is an env-related issue for Qt aplications with QtWebEngine. VNote seems could do nothing here.
> 
> You could try `sudo` with `--no-sandbox` to run VNote.

AppImage ？

**Comment by tamlok** [comment]
> > I could not repro this on Fedora VM. It is an env-related issue for Qt aplications with QtWebEngine. VNote seems could do nothing here.
> > You could try `sudo` with `--no-sandbox` to run VNote.
> 
> AppImage works properly ？

Yes, I tested the AppImage.

**Comment by henices** [comment]
Note AppImage lack of fcitx5 library，I can't use it to type chinese  :(   @tamlok

**Comment by henices** [comment]
> I could not repro this on Fedora VM. It is an env-related issue for Qt aplications with QtWebEngine. VNote seems could do nothing here.
> 
> You could try `sudo` with `--no-sandbox` to run VNote.

sudo command may cause some security related problems

**Comment by tamlok** [comment]
I also tried self-built version with 5.12. It works fine, too.

You could first try to use AppImage to verify if the issue is gone. Then we could focus on the fcitx5 issue.

**Comment by henices** [comment]
> I also tried self-built version with 5.12. It works fine, too.
> 
> You could first try to use AppImage to verify if the issue is gone. Then we could focus on the fcitx5 issue.

The problem exits in self-built edit mode's two panel preview,  for read mode in self-built version with qt 5.12 works fine.

Vnote AppImage edit mode's two panel preview feature works fine when typing english.

BTW could you please share the vnote build script with me.

**Comment by henices** [comment]
self-built vnote with qt 5.12,  vnote edit mode's two panel preview feature works fine in the first two minutes. After that the preview panel refresh frequently and the text in it disappear.

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/blob/master/.github/workflows/ci-linux.yml

**Comment by tamlok** [comment]
Does selft-built vnote with qt 5.15 work?

**Comment by henices** [comment]
> Does selft-built vnote with qt 5.15 work?

self-built vnote with qt 5.15, edit mode's two panel preview feature works fine, but export markdown to pdf cause cpu 100%

BTW self-built vnote with system provided qt 5.15, vnote works fine without `--no-sandbox` commdline parameter

**Comment by tamlok** [comment]
Do you try install Qt 5.15 to your home folder from Qt's installer?

I tried AppImage/5.12 and 5.15 from Qt installer/5.15 from fedora. All of them work fine with `--no-sandbox`. However, 5.15 from fedora version will make the look of VNote weird.

AppImage has the fcitx5 library, but that may not the version you are using on Fedora. I think you could fork VNote repo and modify the built script to use a new version of Fcitx5 or use Fedora instead of Ubuntu to build the AppImage.

**Comment by henices** [comment]
Thanks again my brother, I will try it and report the result back.

**Comment by henices** [comment]
Use Qt online installer https://download.qt.io/archive/online_installers/4.0/qt-unified-linux-x64-4.0.1-1-online.run to install Qt 5.15.2 and compile vnote again, finally everything work again.

Maybe there are something diffirent between online installer and offline installer,  I used qt-opensource-linux-x64-5.12.11.run to install Qt 5.12 and compiled vnote these days.

Thanks @tamlok for answering lots of my naive questions

**Comment by henices** [comment]
https://www.usmacd.com/2021/11/29/vnote/
