### ISSUE TITLE
发现了个冲突，只要开着有道词典的划词功能，就一直崩溃

### ISSUE THREAD

**Issue by littleheary** [vnotex/vnote#1943]
用3.10的时候，开着有道词典的划词功能，只要再一操作vnote，vnote就崩溃了。

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/1918

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/301dace730279d3b3ac199764f72ded39c03c93c
