### ISSUE TITLE
复制代码到代码块中，后面出现大段空行标志，虽然退出编辑模式就消失了，但是很难受，，，，

### ISSUE THREAD

**Issue by ahuxjz** [vnotex/vnote#1944]

**Comment by tamlok** [comment]
在代码编辑器里面，这个叫做trailing spaces，一般对代码格式要求严格的都会去掉。所以VNote里面会高亮提醒用户。

设置里面把`高亮空白字符`去掉即可：

![image](https://user-images.githubusercontent.com/5763157/143447721-57e0b3d6-dd3f-4af5-98a9-2b7861ee6384.png)
