### ISSUE TITLE
编辑模式mermaid渲染问题

### ISSUE THREAD

**Issue by ygcaicn** [vnotex/vnote#1945]
**Describe the bug**
编辑模式，mermaid流程图无法正常显示。

**Screenshots**
![image](https://user-images.githubusercontent.com/17684070/143521203-cec8f155-cf81-446b-b440-3b87d0fb4f9f.png)

**Desktop (please complete the following information):**
 - OS: [macOS 12.0.1]
 - Version [3.10.1]

**Comment by tamlok** [comment]
先提前搜一下issue。

这个问题我能力解决不了。

**Comment by haigear** [comment]
@tamlok 这个是不是可以试试更新mermaid的版本来解决呢？我看他们在网页的预览和渲染都很正常啊，vnote貌似也是html的构架，应可以正常预览吧
