### ISSUE TITLE
外接显示器打开vnote字体过小，不能自适应

### ISSUE THREAD

**Issue by notorious-eric** [vnotex/vnote#1946]
在电脑屏幕上正常，外接显示器打开vnote字体过小，不能自适应，字体和图标大小感觉比电脑原屏幕还要小

 - OS: [e.g. Windows 10]
 - Version [e.g. 3.10.1]

![1](https://user-images.githubusercontent.com/44058627/143616241-396cbbea-582e-4a67-90f9-8418d987f840.png)
![2](https://user-images.githubusercontent.com/44058627/143616242-4a26613b-28e1-4f12-89ab-bd1fcc7521e7.png)
调整缩放会过大,而且默认缩放125%，调成150，175，200都是一样的过大，调成125就过小
![3](https://user-images.githubusercontent.com/44058627/143617634-4e90af07-7caf-455f-8446-de0576ce6a90.png)

**Comment by tamlok** [comment]
你要直接在外接显示器上面启动vnote，dpi发生变化的话，vnote需要重启。qt的程序都这样。

**Comment by notorious-eric** [comment]
> 你要直接在外接显示器上面启动vnote，dpi发生变化的话，vnote需要重启。qt的程序都这样。

好像只有把外接显示器设置成主要屏幕才行，单纯从外接屏幕打开vnote还是一样的问题

**Comment by tamlok** [comment]
那可能是检测屏幕放面有点问题，后面有条件看看
