### ISSUE TITLE
无效的自包含笔记本根文件夹

### ISSUE THREAD

**Issue by Jeff0083** [vnotex/vnote#1952]
```
无效的自包含笔记本根文件夹 (C:/xxxxx/Documents/sync_dir/vnote_notebooks/vnotebook)。
```
windows 10 ,v3版本，这个打开已有笔记到底有什么规律啊，快被搞死了

**Comment by tamlok** [comment]
请问进行了什么操作，有什么提示？能否具体一点，然后最好截图。

“打开其他笔记本”，然后根文件夹选择VNote建立的笔记本根文件夹（该文件夹目录下面会有一个`vx_notebook`，然后这个文件夹下面有`vx_notebook.json`）。如果不存在这些文件，VNote就不会认为这是一个以前建立的笔记本。

你选择的是VNote2的笔记本吗？

最好能具体一点，有利于快速定位问题，谢谢！

**Comment by Jeff0083** [comment]
我修改了主题，然后不生效，我就通过Vnote自带的重启按钮可以生效，但是会有一个问题就是我已经导入的笔记全部丢失，需要再次手动导入，但是导入的方式有很多入口，有打开其他笔记、打开遗留V2笔记，我选择了其他笔记，第一次可以，我再次重启又出现上次说的情况，再利用上面的方法发现好像不行了（这里可能我的问题，不保证两次是一样的途径，但是确实不知道规律），再你回答我的时候，我使用了打开V2遗留的方式导致，现在是可以的

这个软件很好用，用了很久，感谢楼主，刚才提问题不太科学，抱歉，不过确实再笔记导入这一块非常难用且没有统一入口，我再不同的电脑打开同样的笔记均没有很流畅的一次成功。

最后再次感谢，是我的问题，问题没有描述清楚，目前没有问题了。
