### ISSUE TITLE
字体设置后，表格字体没有相应调整

### ISSUE THREAD

**Issue by gueeisgrim** [vnotex/vnote#1956]
vnote作者大神好。
为了表格对齐，我设置了noto等宽字体，但是表格上仍然是宋体，无法实现等宽
请大神关注，谢谢

**Comment by tamlok** [comment]
Hi,

表格的字体需要设置`text-editor.theme`里面的TABLE。

https://tamlok.gitee.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E4%B8%BB%E9%A2%98%E5%92%8C%E6%A0%B7%E5%BC%8F.md
