### ISSUE TITLE
MacOs11.6.1_vnote3.10.1_内存占用过大

### ISSUE THREAD

**Issue by kam1uSEC** [vnotex/vnote#1957]
**Describe the bug**
打开一个文件后内存占用过大

**Screenshots**
![image](https://user-images.githubusercontent.com/46443718/144194039-8b9d2642-7b90-43ab-8a79-d04039a3e041.png)
![image](https://user-images.githubusercontent.com/46443718/144194321-018408e9-91fd-431f-ae5d-f962d9aa2b90.png)

**Desktop (please complete the following information):**
 - OS: MacOs11.6.1
 - Version vnote3.10.1

**Additional context**
开了三个md文件

**Comment by tamlok** [comment]
因为要显示网页，所以嵌套了一个Chromium内核，这内存好像无能为力。
