### ISSUE TITLE
outline显示问题

### ISSUE THREAD

**Issue by ygcaicn** [vnotex/vnote#1958]
开启section number后，outline的显示能否优化一下，不再显示序号

![image](https://user-images.githubusercontent.com/17684070/144552156-733d4415-2242-4880-aeda-ba54d9818b64.png)

**Comment by tamlok** [comment]
暂时手动关掉吧，这种“智能化”还没有时间做。

**Comment by ygcaicn** [comment]
好的outline可以单独控制，没问题啦。大佬辛苦了！
