### ISSUE TITLE
外接显示器后，菜单图标太大了

### ISSUE THREAD

**Issue by k2easy** [vnotex/vnote#1959]
![image](https://user-images.githubusercontent.com/20715282/144693432-00cb5d80-33c0-4a10-b45a-77af4544bab8.png)

**Comment by tamlok** [comment]
从外接显示器启动vnote看看？

**Comment by k2easy** [comment]
![image](https://user-images.githubusercontent.com/20715282/144734621-c5eac202-d308-447f-93f1-6248e1b8cbd0.png)
系统是 Linux Mint 20.2 Cinnamon Edition ，重新启动图标还是那么大，要怎么配置修改下？

**Comment by tamlok** [comment]
应该是默认显示器那里的逻辑有问题，我修一下。

**Comment by k2easy** [comment]
![image](https://user-images.githubusercontent.com/20715282/145578384-4dc56108-6170-4ba4-b562-22aa0e01d7fd.png)
不好意思，是我的系统设置的字体放大了1.2倍造成的，调整成1倍后菜单图片字体都显示正常了。
感谢。
