### ISSUE TITLE
目录折叠

### ISSUE THREAD

**Issue by mengzairanshao** [vnotex/vnote#1960]
希望vnote目录能够添加一个折叠/展开折叠选项。

**Comment by tamlok** [comment]
详细一点？

**Comment by mengzairanshao** [comment]
> 详细一点？

如果目录中有二级标题，大纲中的目录现在默认是展开的，我希望增加一个按钮啥的，让大纲中的目录能够折叠起来。
![image](https://user-images.githubusercontent.com/12567588/144796591-30e59556-a9c2-4d2a-ab56-f76fd9f89053.png)
![image](https://user-images.githubusercontent.com/12567588/144796621-8c21e64f-086f-437c-91fd-e2a2f544d81a.png)

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/144801290-dc7404d0-9bb5-4cff-90cd-c2ce5aa4654f.png)

那里有两个按钮

**Comment by mengzairanshao** [comment]
> ![image](https://user-images.githubusercontent.com/5763157/144801290-dc7404d0-9bb5-4cff-90cd-c2ce5aa4654f.png)
> 
> 那里有两个按钮

OK，多谢
