### ISSUE TITLE
编辑大文件出现明显卡顿

### ISSUE THREAD

**Issue by mengzairanshao** [vnotex/vnote#1961]
编辑大文件出现明显卡顿。大文件编辑时出现删除、增加文字时，一顿一顿的。

**Comment by tamlok** [comment]
没开竖直分隔吧？vnote测试过能扛10k行文字。

**Comment by mengzairanshao** [comment]
> 没开竖直分隔吧？vnote测试过能扛10k行文字。

确实没开竖直分割，我是在编辑模式下测试的，也没有打开实时预览。我看了下代码，debug了一下，感觉像是单线程造成的页面卡顿。具体的表现如下：
我的文件有16000+行，在3000行左右做的测试。
1. 如果是快速的换行，好像不会出现卡顿问题。
2. 如果是先换一行，然后顿一下，继续换行，就会出现第二个换行出现卡顿，
![image](https://user-images.githubusercontent.com/12567588/144792537-406cae3f-c67f-4d6a-ba38-c46da10672af.png)
我观察到上面这个函数是在rehighlightBlockRange函数执行完成之后才触发的，而从触发上面这个函数到真正渲染耗时又特别长，且这两个函数都是同一个线程在调用，所以第二次回车就会卡顿，不知道是不是问题所在。

**Comment by mengzairanshao** [comment]
![image](https://user-images.githubusercontent.com/12567588/147804019-959e0c69-0a03-46c8-9a2a-5b9550fe53bc.png)
我在记笔记的时候发现，vnote在修改大文件时会有卡顿的问题，经过排查我发现卡顿情况是在调用这个函数的时候，用户在编辑文档时，触发contentsChanged，然后调用handleContentsChange，然后在handleContentsChange有一个highLightWhiteSpace函数，该函数应该是扫描整个文档，比较耗时，导致主界面短时间卡顿。希望作者能够修改一下这个逻辑，优化一下。

**Comment by tamlok** [comment]
设置里面把高亮空白字符关闭试试？

**Comment by mengzairanshao** [comment]
> 设置里面把高亮空白字符关闭试试？

好用，感谢！！
