### ISSUE TITLE
如何自定义代码块在编辑模式下的高亮模式？

### ISSUE THREAD

**Issue by ryanzx82** [vnotex/vnote#1965]
在编辑模式下 插入C++代码段
```cpp
...........
```

语法会高亮显示，这个高亮显示的尝试修改highlight.css 没有效果。请教下具体修改的配置文件和方法

**Comment by tamlok** [comment]
首先参考这里熟悉一下vnote的主题：https://vnotex.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E4%B8%BB%E9%A2%98%E5%92%8C%E6%A0%B7%E5%BC%8F.md

然后修改：

C:\Users\xxx\AppData\Roaming\VNote\VNote\syntax-highlighting\themes

下面的某个主题即可。

可以拷贝到用户配置文件夹下面的同级别目录再进行修改。

**Comment by tamlok** [comment]
晚点我更新一下文档。

**Comment by tamlok** [comment]
下一版本会统一是用`highlight.css`来进行阅读模式和编辑模式的高亮。
