### ISSUE TITLE
希望能简化一下mathjax本地化的配置

### ISSUE THREAD

**Issue by uFcvT** [vnotex/vnote#1967]
比起plantuml和Graphviz，mathjax算是markdown的基本功能了。
但是新版的vnote中，mathjax的本地化却比前两个更难配置，真的不合理。
毕竟vnote的特色是本地化（联网的markdown编辑器不要太多，不乏优化做得非常好的）

建议把mathjax本地化的配置放回gui里，或者把配置教程写详细一些，方便更多人使用

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/a4a5dea3d74f086e3b90696dfeab7fd14e4cdc12

**Comment by haigear** [comment]
how to fix the issu?

**Comment by tamlok** [comment]
设置里面有选项了

**Comment by haigear** [comment]
vnote3.13最新版里面的确有一个配置文本框，但填写text-chtml.js仍然无效

**Comment by tamlok** [comment]
> vnote3.13最新版里面的确有一个配置文本框，但填写text-chtml.js仍然无效

        this.mathJaxScript = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js';

使用类似的svg
