### ISSUE TITLE
文档预览，github图床图片加载失败

### ISSUE THREAD

**Issue by k2easy** [vnotex/vnote#1970]
您好：
    复制图片插入时能够成功上传到配置好的github图床，
    但是文档预览时github图片加载失败，像是网络不通，好像并没有走系统vpn代理。
    测试使用其他md编辑器打开，图片能够正常显示的。
   
![image](https://user-images.githubusercontent.com/20715282/145715053-6949cbfa-26e2-4f6e-a451-c6086006b457.png)

**Comment by tamlok** [comment]
网络就是普通的程序网络设置，应该是走代理的。这个仓库是私有的吗？可以把链接贴出来，我这边试一下。

**Comment by k2easy** [comment]
可以使用下面这个测试连接，https://raw.githubusercontent.com/k2easy/imageBase/main/aa/%E7%AC%94%E8%AE%B0.md/418485503606113.png
![image](https://user-images.githubusercontent.com/20715282/147435338-801cd983-6afb-4112-9403-b7afa5b6f573.png)

我好像发现问题了，当点击几次 纯编辑/预览编辑，预览窗口的图片就加载出来了。 难道是我的网络比较慢？
![image](https://user-images.githubusercontent.com/20715282/147435468-b0da3672-e3f2-447f-9f2e-537aca7ab1d2.png)

**Comment by tamlok** [comment]
有可能的，你看一下日志有什么错误吗？
不过你阅读模式也加载不出来，估计就是加载超时了。
