### ISSUE TITLE
一整块的公式编辑模式不支持吗？

### ISSUE THREAD

**Issue by RachelWealth** [vnotex/vnote#1973]
这种:
\```math

\```
格式的公式编辑是不支持吗？我的代码在别的编辑器都是没问题的，在vnote中就没法使用？
![image](https://user-images.githubusercontent.com/74123687/146118028-16812545-ccfd-414f-958d-4febe996f4e7.png)

**Comment by tamlok** [comment]
mathjax或者$$

右上角帮助那里有语法指南
