### ISSUE TITLE
文件夹不支持通过右键添加到快速访问中

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#1977]
**版本：** 当前（2021年12月21日最新版本）
**描述：** 只能对文件进行右键执行“固定到快速访问”，而文件夹点击之后，实际上是没有添加过去的。虽然通过“设置”可以手填文件夹过去，但如果您有时间的话，期待还是能修复一下这个小瑕疵
![Snipaste_2021-12-21_12-41-22](https://user-images.githubusercontent.com/40653617/146872245-f7f84281-9fba-4f8b-9c64-6391a57f8624.png)

**Comment by tamlok** [comment]
这不是瑕疵，你可以看到左下角状态栏那里会提示快速访问不支持文件夹。当初是想着文件夹目前没有编辑器打开，所以没有支持。后面对于文件夹的话，就在目录树定位吧。

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/ef7b28b6b3974588d82f379fbb50c1bb9cf082c3
