### ISSUE TITLE
Latest stable release does not match app version

### ISSUE THREAD

**Issue by vitorgalvao** [vnotex/vnote#1980]
**Describe the bug**
[The `3.10.1` tag/release](https://github.com/vnotex/vnote/releases/tag/v3.10.1) contains a macOS app with version `3.10.0`, despite that being [the previous release](https://github.com/vnotex/vnote/releases/tag/v3.10.0) (and a different build).

**To Reproduce**
1. [Download the stable macOS version](https://github.com/vnotex/vnote/releases/download/v3.10.1/vnote-mac-x64_v3.10.1.zip) `3.10.1` (according to the URL and GitHub tag).
2. Do a Get Info (<kbd>⌘</kbd><kbd>I</kbd>) on the app.
3. Note the version is `3.10.0`.

**Expected behavior**
App should have same version as tag.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - macOS (any version).
 - vnote `3.10.1`.

**Additional context**
N/A.

**Comment by tamlok** [comment]
Should have been fixed: https://github.com/vnotex/vnote/commit/54576543e9d34899d03735f2edffc118956b02f0

Will do a new release soon.

Thanks!
