### ISSUE TITLE
建议增加txt文件直接当做markdown编辑

### ISSUE THREAD

**Issue by gueeisgrim** [vnotex/vnote#1986]
我平时喜欢整理大段文字和撰写小说，一般我喜欢用markdown设置标题或者加粗，这样码子的时候非常方便。但是如果直接用md文件发布后，因为很多读者是不装markdown软件的，他们直接说打不开markdown文件，因此我每次都需要转成txt才能发布，非常繁琐。

希望vnote能够自动设置语言模式，让txt也能使用markdown，谢谢。

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/b3a385693c46b957c62aa1bbe10549ca944ac496
