### ISSUE TITLE
建议作者，能否将预览的界面与编辑界面位置时时同步

### ISSUE THREAD

**Issue by winterstay** [vnotex/vnote#1987]
在使用过程中，我经常开着那个预览的界面，但是当我打满一面的时候，接着向下打的时候，预览界面总会更新并跳到最上面，希望作者大大能让预览界面更新后同步到编辑的地方，方便继续对照，而不需要拖拽了。

**Comment by tamlok** [comment]
例子截图？

**Comment by tamlok** [comment]
升级到最新版看看

**Comment by winterstay** [comment]
![image](https://user-images.githubusercontent.com/73685462/147423117-8fa29229-0a06-4dff-8abd-d90597a0c848.png)
就是这样，在左边写，右边更新的时候会自动跳到最上面
现在时3.10，应该是最新的了

**Comment by tamlok** [comment]
同步时以顶行的位置进行同步的。

**Comment by winterstay** [comment]
这样的话，有一丢丢小麻烦，每次都要下拉看，作者大大看能不能弄个按钮，让自己选择是顶行同步，还是同步完再自己移动到左侧对应的位置

**Comment by tamlok** [comment]
设置里面有一个光标居中的选项，你选择底部那个选项，看看效果会不会好一点。

因为这个双边不是vnote的主要方式，所以优先级比较低。等后面有时间了可以再优化一下。

这次版本作为默认的差看嘛模式，是为了提醒那些以前用屏幕分割来预览的用户。后面默认配置会设为原地预览的方式。

**Comment by winterstay** [comment]
好的，感谢作者的付出了
