### ISSUE TITLE
希望增加『目录索引』自动更新功能

### ISSUE THREAD

**Issue by cnshegg** [vnotex/vnote#1988]
需求：
在md文档最上面增加了目录索引后，希望能像VSCode里面的插件实现的那样，当内容变化后，可以自动更新目录索引。
应用场景：
虽然vnote自带的大纲目录很好用，但是生成的md文档可能会发给其他人，这些人不一定使用vnote查看md。此时，需要开头有个目录索引。

**Comment by tamlok** [comment]
啊！！！

`[toc]`试过了吗？
