### ISSUE TITLE
图片不能紧邻左侧，始终居中

### ISSUE THREAD

**Issue by QingCaigjm** [vnotex/vnote#1989]
**Describe the bug**
插入图片的位置自动居中，而不是处于紧靠左侧。
多次重启，粘贴、键入后，图片位置依旧，还是处于中央，
拉动右侧大纲页面宽度，随之移动，始终在左侧阅读窗口居中。

**To Reproduce**
1. 编辑ctrl+T，粘贴图片
2. 阅读ctrl+T

**Expected behavior**
图片像上面的图片一样，紧靠左侧

**Screenshots**
![image](https://user-images.githubusercontent.com/94917420/147462630-8634d0bb-e503-4ae0-8c14-d1ff86248020.png)

**Desktop (please complete the following information):**
 - OS[Windows 10]
 - Version [3.10.1]

**Additional context**
发现一个怪事，编辑栏给图片后面或前面加一个字符/图片，图片就能紧靠左侧。
把它单独放着，哎，就是居中，你说气不气人。
真是奇怪了
![image](https://user-images.githubusercontent.com/94917420/147466772-8fb65d2f-8464-45c2-a08e-cf641e4a236d.png)
![image](https://user-images.githubusercontent.com/94917420/147466929-8c1a0393-2b67-4e77-800c-900ec252bfc1.png)

初步解决办法在编辑栏后面加个标记，就可以解决了。但只是治标，希望能彻底解决。
![image](https://user-images.githubusercontent.com/94917420/147467793-9050bfca-31b2-49be-80fb-934d454ea276.png)

[JAVA编程.md.zip](https://github.com/vnotex/vnote/files/7779787/JAVA.md.zip)

**Comment by tamlok** [comment]
设置里面把图片居中取消就行了：

![image](https://user-images.githubusercontent.com/5763157/147474512-4819b610-704a-432b-be38-e11c02609940.png)
