### ISSUE TITLE
编辑稍大的文件会闪退

### ISSUE THREAD

**Issue by moyu0** [vnotex/vnote#1992]
vnote 版本： 3.11.0

问题描述：
查看文件的话并不会闪退，但是转成编辑模式就会直接闪退。
之前也遇到过编辑大一点的文件直接闪退的情况，更新到最新也还是会。

编辑文件大小：227KB

操作流程：打开对应md文件 -> 点击编辑按钮 -> 闪退

对应日志：
Info:(main.cpp:139) "VNote (v3.11.0) started at 周二 12月 28 10:31:08 2021 (windows)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1g  21 Apr 2020"
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:91) using theme "pure"
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default

**Comment by tamlok** [comment]
方便把文件发我邮箱不？

**Comment by moyu0** [comment]
> 方便把文件发我邮箱不？

@tamlok 

链接: https://pan.baidu.com/s/1nxZPTwhMbFtDCiw5R4E_hw?pwd=n73i 提取码: n73i 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by tamlok** [comment]
好像复现不了，你等下一个版本看看，或者设置里面把高亮空白字符关掉。
