### ISSUE TITLE
什么时候搞M1版本的啊 现在M1运行占内存太大了

### ISSUE THREAD

**Issue by Judong0x0** [vnotex/vnote#1995]
M1什么时候原生支持啊

**Comment by tamlok** [comment]
再等两三个版本吧，把通用入口迁移过来了再考虑升级qt版本

**Comment by skyhiter** [comment]
> 
什么时候可以适配Apple Silicon芯片(M1, M2等)？

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/releases/download/continuous-build/VNote-3.17.0-mac-universal.dmg 求帮忙测试一下

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/2115
