### ISSUE TITLE
BUG: 正则表达式之替换功能

### ISSUE THREAD

**Issue by HRS2049** [vnotex/vnote#1996]
在环视条件下的正则表达式，无法完成替换，但是可以查找。
期待改进。谢谢！

**Comment by tamlok** [comment]
给个例子呀

**Comment by HRS2049** [comment]
![VNote下的正则替换](https://user-images.githubusercontent.com/96814608/147710574-f74cd853-acd1-4eac-b6d2-a589d89a0ce7.png)

**Comment by tamlok** [comment]
Should be fixed in https://github.com/vnotex/vnote/commit/969db5c3db17996bbc777ec7b36f33e4a12aa67a
