### ISSUE TITLE
统一存放自动生成的文件

### ISSUE THREAD

**Issue by auxiling** [vnotex/vnote#1997]
在使用VNote的过程中会生成一些如：vx_notebook、vx.json 之类的目录或文件，建议把这些文件统一放在笔记本根目录下的 .vnote 目录下，就像 .vs 和 .git 那样。

**Comment by Fxiao1** [comment]
感觉现在这样挺好的，每个文件夹下的所有文件都几乎一样（配置文件、附件、图片、文件夹、markdown文档），这样在任何目录都可以查看它的描述文件 vx.json 确定哪里有问题。逻辑比较简单，每个描述文件只描述当前目录，而不是整个树，方便离开vnote也能理解文档结构信息。
