### ISSUE TITLE
有没有办法去掉右边markdown的实时预览，就是那个占用一般编辑器空间的

### ISSUE THREAD

**Issue by Jontyshaw** [vnotex/vnote#1998]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.0.0]

**Additional context**

**Comment by tamlok** [comment]
工具栏有个查看模式开关
