### ISSUE TITLE
在win11 下使用 Qt5.12.5编译出错

### ISSUE THREAD

**Issue by yougoup** [vnotex/vnote#1999]
编译后，提示如下错误：
“ 无法解析的外部符号 "__declspec(dllimport) public: __cdecl QLinkedListData::QLinkedListData(void) ... ... ”
![image](https://user-images.githubusercontent.com/11360401/147760679-2febd7ce-353a-4045-910f-605b44fb612d.png)

**Comment by tamlok** [comment]
暂时不清楚是什么错误。具体编译步骤可以参考CI脚本：https://github.com/vnotex/vnote/blob/master/.github/workflows/ci-win.yml
