### ISSUE TITLE
【需求】增加WebDAV支持和Mathjax公式支持

### ISSUE THREAD

**Issue by JamesMackerel** [vnotex/vnote#20]
WebDAV支持可以配合许多同步网盘使用。
Mathjax不用多说，写公式非常好用。

**Comment by tamlok** [comment]
Hi，MathJax和Mermaid目前都是已经支持了的呢，需要在`Markdown`菜单下勾选启用，默认是关闭的。`WebDAV`后面会看看，谢谢建议！2.0版本后开始考虑对接和同步的事情，目前先集中精力把编辑弄好！谢谢使用！
