### ISSUE TITLE
代码高亮无法识别大写的C++

### ISSUE THREAD

**Issue by mengzairanshao** [vnotex/vnote#2000]
![image](https://user-images.githubusercontent.com/12567588/147807921-2966f278-a2af-4321-9b05-f12e101d9e5a.png)
大写的```C++无法正确的识别
![image](https://user-images.githubusercontent.com/12567588/147807965-1d5ddf3d-c375-42a9-913f-81957baddc38.png)
小写的正常识别

**Comment by tamlok** [comment]
下一版本会统一用阅读模式来渲染，使用`cpp`。

https://prismjs.com/#supported-languages
