### ISSUE TITLE
希望迁移笔记栏

### ISSUE THREAD

**Issue by Shiina18** [vnotex/vnote#2002]
VNote 2 左侧文件管理系统中分为两栏, 上面是目录 (directory), 下面 **笔记栏** 是选中的目录中的所有 .md 文件. 层次清楚.

VNote 3 文件管理系统只有一栏, 把文件逐层缩进展开在对应目录下, 当目录层次多的时候, 缩进太多, 很难看文件.

因此希望迁移 2 的笔记栏.

**Comment by jackydi** [comment]
有的人喜欢3的这种风格，有的人喜欢2的那种风格，两种各有利弊，如果做成选项最好了

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/2630999acf7dac37dbd27fae411cf5c995ea3ecd
