### ISSUE TITLE
Separate snippets to every notebook

### ISSUE THREAD

**Issue by ANAT01** [vnotex/vnote#201]
Feature request
Now all snippets storage in ~/.config/vnote/snippets/ (under linux)

If snippets are used in notebooks to really different fields, than it may be problem for find needful.
I think, that have a reasons to separate snippets for every notebooks and move snippets to every main notebook's folders.

**Comment by tamlok** [comment]
I am afraid it will make VNote more complicated to use. You could type some keys in the snippet list to search for their names.

**Comment by ANAT01** [comment]
It may be optional if _vbote.json of notebook have that opportunity (like _v_recycle_bin or else).

Some snippets are common for everything (like table template or article structure) It may storage in `~/.config/vnote/snippets/`
Some snippets are very specific only for some notebook (I write many mails to government and often use citations from law, but I don't want watch that snippets when I write article in another notebook.)

That may be actual for ~/.config/vnote/templates too.

Every Notebook may be more independent from another.
It's just an idea to the future.

**Comment by tamlok** [comment]
Maybe folders for snippets and templates is a better solution. You just need a method to manage and classify them. I think they are not part of a notebook (neither the metadata nor data). It is strange to couple them with notebook.

**Comment by tamlok** [comment]
In VNote 3, there is a handy search method when applying a snippet. Hence I think we do not need to classify snippets like notes. *Search is better than go through*.
