### ISSUE TITLE
linux环境下Ctrl+G快捷键失效

### ISSUE THREAD

**Issue by w454196785** [vnotex/vnote#2010]
![image](https://user-images.githubusercontent.com/31468811/147895949-7141e06c-e5e6-4a1b-ad7e-2812a2139a99.png)

**Comment by tamlok** [comment]
关闭输入法看看？

**Comment by w454196785** [comment]
不行，我远程的一个win10版本的也不行。 
但是2.0版本的这个快捷键都是好用的

**Comment by tamlok** [comment]
日志看一下？

**Comment by w454196785** [comment]
按了Ctrl+G没有看到vnote的日志有变化

Info:(main.cpp:133) "VNote (v3.10.0) started at 周一 1月 3 10:21:18 2022 (newstartos)"
Info:(main.cpp:138) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1d  10 Sep 2019"
Warning:(main.cpp:142) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:194) locale: "zh_CN"
Info:(thememgr.cpp:91) using theme "pure"
Warning:(:0) QXcbConnection: XCB error: 3 (BadWindow), sequence: 701, resource id: 13397463, major code: 40 (TranslateCoords), minor code: 0
Info:(main.cpp:139) "VNote (v3.11.0) started at 周二 1月 4 14:09:20 2022 (newstartos)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1d  10 Sep 2019"
Warning:(main.cpp:148) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:91) using theme "pure"
Warning:(:0) QXcbConnection: XCB error: 3 (BadWindow), sequence: 801, resource id: 13567230, major code: 40 (TranslateCoords), minor code: 0
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default
Warning:(:0) QXcbConnection: XCB error: 3 (BadWindow), sequence: 2883, resource id: 13568731, major code: 40 (TranslateCoords), minor code: 0
Warning:(:0) QXcbConnection: XCB error: 3 (BadWindow), sequence: 3060, resource id: 13569319, major code: 40 (TranslateCoords), minor code: 0

**Comment by tamlok** [comment]
是所有ctrl-g的快捷键都不能用吗？具体是哪个快捷键？

**Comment by tamlok** [comment]
是所有ctrl-g的快捷键都不能用吗？具体是哪个快捷键？

**Comment by tamlok** [comment]
3以后目前还没有通用入口，所以目前ctrl-g并不是任何完整功能的快捷键。其他快捷键请参考右上角帮助的快捷键说明。
