### ISSUE TITLE
请问怎么设置编辑时右边的实时预览栏不再显示

### ISSUE THREAD

**Issue by lynn0977** [vnotex/vnote#2013]
希望配置为不需要左边编辑，右边预览双栏显示的设置，仅留编辑栏即可。要如何设置，我用的版本是3.11.0

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/148212366-f2eaf033-cff0-4e87-8fa3-51ae3a3ae42d.png)

**Comment by lynn0977** [comment]
谢谢
