### ISSUE TITLE
3.0 能不能像 2.0 一样分开显示目录和里面的文件？

### ISSUE THREAD

**Issue by skywind3000** [vnotex/vnote#2014]
你好，vnote 我一直在用，最新版3.0 能不能像2.0一样的把目录和文件分开窗口显示啊？现在 3.0 全部挤在一个目录树上，文件多了很难操作，几次升级不习惯又退了回去。

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/2630999acf7dac37dbd27fae411cf5c995ea3ecd
