### ISSUE TITLE
后续是否支持jupyter notebook

### ISSUE THREAD

**Issue by hotbaby** [vnotex/vnote#2015]

**Comment by tamlok** [comment]
这个能怎么支持呢？

**Comment by Howard-Zhou-77** [comment]
或许可以像处理笔记一样处理markdown块，处理代码一样处理代码块，然后调用本地的python解释器调试代码

但是这么做工作量看起来就很大

**Comment by ibn-xu** [comment]
。。。这是记笔记的，不是给你运行代码的

要调试用专门的软件不行嘛
