### ISSUE TITLE
外接显示器界面缩放问题

### ISSUE THREAD

**Issue by mxyq** [vnotex/vnote#2016]
**Expected behavior**
笔记本电脑外接显示器，大显示器会出现缩放的情况

**Screenshots**
<img width="454" alt="Snipaste_2022-01-12_09-58-31" src="https://user-images.githubusercontent.com/42633205/149050692-55e1f954-100e-44a9-aa8c-2d4d8b343794.png">
<img width="440" alt="微信图片_20220112095958" src="https://user-images.githubusercontent.com/42633205/149050723-2511bfaf-84c1-4397-8128-4626d059f75e.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.11.0

**Comment by tamlok** [comment]
你不能直接拖过去，你想在哪个显示器用，你就在哪个显示器上面重启一下vnote
