### ISSUE TITLE
插入图片居中居左问题

### ISSUE THREAD

**Issue by baorant** [vnotex/vnote#2018]
**Describe the bug**
插入图片时随机居左和居中对齐，页面不一致，怎么控制图片是居左还是居中对齐呢？

**Comment by tamlok** [comment]
这是因为有些图片被按照行内图片插入了，行内的图片就没有居中的说法了。一般插入图片，是要独立作为一行的，然后前面最好空一行，这样这个图片就是一个块元素，不是行内的了。

下面这种就是行内图片了。你也可以在第一行的后面加两个空格强制换行，这样应该也是块图片。

```
abccjkdjfkjdkjf
![ad](jdkjfd.jpg)
```

**Comment by baorant** [comment]
> 最近开始切换使用的vnote，刚重复试了下，如果![ad](jdkjfd.jpg)插入图片，如果插入文件的上下都是标题，这个图片就会居中，图片路径[]中的内容会出现在图片的下面，如果在图片的上方写一句正文，图片就会靠左对齐了

**Comment by tamlok** [comment]
因为md里面要分段换行，只能插入一个空行或者末尾空两格。
