### ISSUE TITLE
正则搜索有卡死的bug

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2020]
# 基础信息
* vnote_version: 3.11.0
* 操作系统： win10 专业版（21H2）

# 重现步骤
1. 随意打开一篇markdown笔记
2. 进入编辑模式
3. 开始搜索。搜索模式： 大小写敏感（false）、匹配完整词（false）、正则表达式（true）、增量查找（false）
4. 键入`$`，点击搜索
5. 卡死，失去响应

# 重现概率： 100%

**Comment by tamlok** [comment]
请问你搜这个$行尾是为了进行什么操作呢？

**Comment by tamlok** [comment]
Should be fixed in https://github.com/vnotex/vnote/commit/969db5c3db17996bbc777ec7b36f33e4a12aa67a

**Comment by Fxiao1** [comment]
实在不好意思，我没有看到你的邮件，想进行的是找到所有的空行，然后就在尝试，发现一旦正则表达式里面含有结尾匹配符“$”搜索后就会卡死




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Le ***@***.***&gt;; 
发送时间: 2022年1月24日(星期一) 中午12:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vnotex/vnote] 正则搜索有卡死的bug (Issue #2020)





 
请问你搜这个$行尾是为了进行什么操作呢？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
