### ISSUE TITLE
AppImage of VNoteX 3.12 don't start with Linux Mint 18.3 Cinnamon

### ISSUE THREAD

**Issue by ribezzz** [vnotex/vnote#2028]
**Describe the bug**
Since today i've used VNote 2.10 without problem. Then i've tried to open vnote-linux-x64_v3.12.0.AppImage, but i've this error messages in the shell:

> /tmp/.mount_vnote-xeiuo7/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_vnote-xeiuo7/usr/bin/../lib/libsystemd.so.0)
> /tmp/.mount_vnote-xeiuo7/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_vnote-xeiuo7/usr/bin/../lib/libsystemd.so.0)

**To Reproduce**
1. Open shell
2. go to dir where is vnote-linux-x64_v3.12.0.AppImage
3. digit and launch ./vnote-linux-x64_v3.12.0.AppImage

**Expected behavior**
vnote-linux-x64_v3.12.0.AppImage should open VNoteX

**Desktop (please complete the following information):**
 - Linux Mint 
 - 18.3 Cinnamon

**Comment by tamlok** [comment]
please google GLIBC_2.27 not found to find the way to install the dependents.

**Comment by ribezzz** [comment]
ok, thank you.
I've think that the appimage format contains all the dependences needed.

**Comment by tamlok** [comment]
For some basic libs, such as glibc, it won't pack them. I guess Linux Mint 18.3 is using an older glibc than the CI environment building the AppImage.
