### ISSUE TITLE
建议停靠部件支持自动隐藏

### ISSUE THREAD

**Issue by ircc** [vnotex/vnote#2029]
![1B869C95-A5C3-4d4f-B8C2-D94FB3396E17](https://user-images.githubusercontent.com/6668905/150898758-b5ab3d40-6c42-4eb1-bcdf-7eeee57ae5a9.png)
建议内容区旁边的停靠部件支持自动隐藏，
1. 有些停靠部件不需要一直展示（但在界面上需要有相应的入口），只需要在点击或者hover上去时展示出来就行（比如标签、历史、搜索）
2. 在笔记本屏幕较小的情况下，如果停靠部件一直展示会压挤内容区域，导致内容区过小
3. 在投屏时，通常只需要展示内容区，但停靠部件没法隐藏，只能关闭

**Comment by tamlok** [comment]
`Ctrl+G, E`可以扩展内容区。

Qt自带的部件不支持自动隐藏，暂时不会花费太多精力在这些锦上添花的图形界面细节上面。
