### ISSUE TITLE
怎么快速覆盖缓冲区

### ISSUE THREAD

**Issue by cqh-sy** [vnotex/vnote#2030]
在我使用git pull之后，就会弹出一个框提示我是否覆盖缓冲区
![image](https://user-images.githubusercontent.com/73568694/151129358-cd4c6824-77cd-4ce6-ba10-1ea53046debb.png)

我想在任务里面直接写一个命令自动覆盖缓冲区(推荐)，或在配置里配置也可以，，这功能目前可以实现吗？我该怎么做？3.12.0版本

**Comment by tamlok** [comment]
目前还不行，你只能全部文件关闭了再pull了。

**Comment by cqh-sy** [comment]
> 目前还不行，你只能全部文件关闭了再pull了。

嗯嗯，，希望后续能出个配置，支持自动从放弃缓冲区
