### ISSUE TITLE
大佬能优化下打印嘛

### ISSUE THREAD

**Issue by fyljp** [vnotex/vnote#2032]
默认主题黑色背景，看着相当舒服，但是打印也是黑底，简直吓死了。

能提供一个选项在打印的时候打印白底嘛，谢谢！

**Comment by Fxiao1** [comment]
设置不出来让多行代码里面超长自动换行，先不搞了，抱歉

**Comment by fyljp** [comment]
> 设置不出来让多行代码里面超长自动换行，先不搞了，抱歉

没事没事，依然十分感谢！

**Comment by Fxiao1** [comment]
> > 设置不出来让多行代码里面超长自动换行，先不搞了，抱歉
> 
> 没事没事，依然十分感谢！

# 放弃了代码块换行
你好，我成功设置代码块里面代码过长自动换行了，但是换行之后不知道怎么让左边的行号也跟着追踪如下图vscode里面的这种模式
![Snipaste_2022-03-03_13-09-57](https://user-images.githubusercontent.com/40653617/156500425-2a90df2f-1a5e-4bc6-9dea-45e8637c7adf.png)
最后还是放弃代码换行了，所以你打印的时候要注意，代码别过宽了，否则打印不上。

# 现有修改版效果
现有的打印修改版，是基于vnote自带的主题“纯净”修改的，将现有找到的文字变成了纯黑色，找到的背景改成了纯白色，效果如下图所示
![暗黑1](https://user-images.githubusercontent.com/40653617/156501149-d36c5ad9-6bc5-494e-9ae9-4c0c958a7c40.png)
![亮色1](https://user-images.githubusercontent.com/40653617/156501157-2cce77fd-fc52-4908-a1d2-4d61e67da3ed.png)
![暗黑2](https://user-images.githubusercontent.com/40653617/156501172-8a3e03f7-957b-4be9-b6e4-22f8402bedfc.png)
![亮色2](https://user-images.githubusercontent.com/40653617/156501181-cfe65f8d-134d-4440-89be-2a65ba9d8b8c.png)

# 修改版主题文件

[pure-print.zip](https://github.com/vnotex/vnote/files/8175166/pure-print.zip)

# 如何使用？

1. 将上述主题文件解压后的文件夹，放置在`设置`-`主题`-`添减\删除`打开后的文件夹里
2. 打开要打印的文档
3. 选择导出
4. 导出选项，设置透明背景色，渲染的两个文件分别选择我那个修改版里面的`web.css`和`highlight.css`。如下图所示
![打印选项](https://user-images.githubusercontent.com/40653617/156501460-496fbc5d-a1eb-4125-8f61-b9b92960572a.png)

**Comment by fyljp** [comment]
太感谢了！
