### ISSUE TITLE
I want to set a default for the file type for new notes

### ISSUE THREAD

**Issue by sinh927** [vnotex/vnote#2033]
**Is your feature request related to a problem? Please describe.**
I mainly create text files, but in vnote, the default setting is markdown, which is problematic because it needs to be changed every time.

**Describe the solution you'd like**
I would like to be able to set a default value for the file type in the Create New Note dialog.
I would like to see the item added to the VNote settings screen.

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/6ea5995c12e82996a3f0dbad1d368f25708d31b2
