### ISSUE TITLE
可以增加导航和大纲关闭的快捷键吗？

### ISSUE THREAD

**Issue by dbcoffee** [vnotex/vnote#2035]
目前可以通过快捷键（包括自定义）快速打开导航和大纲，但是再次使用快捷键并不能关闭，需要手动关闭。是否可以用同一个快捷键关闭或打开（在关闭的状态下打开，在打开的状态下关闭）？

**Comment by tamlok** [comment]
那个快捷键的意思是聚焦到某个面板，然后可以通过ctrl+j/k来上下移动操作。

要隐藏的话，可以尝试一下`ctrl+g, e`，扩展内容区域。
