### ISSUE TITLE
配置文件及theme是否默认可以放置到软件安装的目录？

### ISSUE THREAD

**Issue by dbcoffee** [vnotex/vnote#2038]
配置文件及theme是否默认可以放置到软件安装的目录？

目前vnote配置文件及theme默认在c盘，但是在重新安装windows或者将vnote放到NAS同步盘（其他电脑同步NAS上的vnote，绿色运行），所有配置及样式需要重新设置，比较麻烦，而将配置文件和theme放在安装目录下则只需一次部署即可。

**Comment by pysense** [comment]
用户配置文件夹会覆盖默认配置，参考文档操作即可：https://vnotex.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E9%85%8D%E7%BD%AE.md#toc_2

**Comment by tamlok** [comment]
https://vnotex.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E9%85%8D%E7%BD%AE.md#toc_2
