### ISSUE TITLE
Cannot get preview

### ISSUE THREAD

**Issue by raffaem** [vnotex/vnote#2039]
**Describe the bug**

I cannot get a preview of my document. The preview windows is empty

**To Reproduce**
1. Download VNote 3.12.888 from [here](https://github.com/vnotex/vnote/releases/tag/v3.12.888)
2. Open VNote and write a note
3. Switch to Preview panel
4. See nothing

**Expected behavior**
A preview of the rendered document

**Screenshots**

![image](https://user-images.githubusercontent.com/54762742/151789992-42b630a7-3b15-4c16-980d-4dd795b9f0ac.png)

**Desktop (please complete the following information):**
 - OS: Fedora Workstation
 - Version 35

**Comment by tamlok** [comment]
i donnot know why either. linux desktop is still a toy in 2022...

**Comment by tamlok** [comment]
i will try ci on fedora in the future.

**Comment by tamlok** [comment]
Fedora is not provided by GitHub actions. Maybe we could use docker to build VNote on Fedora. PullRequest is welcome for this since I don't have time for it.
