### ISSUE TITLE
请求添加删除索引后自动删除vx.json文件的功能

### ISSUE THREAD

**Issue by ccsugar** [vnotex/vnote#2040]
如题，索引删除后文件夹下仍残留了vx.json

**Comment by tamlok** [comment]
是不是因为文件夹没有删除，文件夹还需要节点？如果提问有例子有截图能具体一点就好了！

**Comment by tamlok** [comment]
从文件夹新建笔记本的时候，应该可以选择需要导入的文件的后缀名，从而可以跳过只包含图片的文件夹。

从索引中移除是指从父级目录中移除该文件夹，每个文件夹是一个自包含的结构，所以对该文件夹内部的内容不会进行更改。
