### ISSUE TITLE
正则引用问题

### ISSUE THREAD

**Issue by HRS2049** [vnotex/vnote#2043]
OS: Win10 64位
VNote： 3.12.888

正则表达式反向引用无法返回期望的结果，如下截图：
![正则引用问题](https://user-images.githubusercontent.com/96814608/152665988-847c2186-72b6-4ed6-93b0-1b94cf074641.png)

**Comment by Fxiao1** [comment]
你替换写错了，但是问题好像确实存在

应该查找`<mark>(.{1,})</mark>`替换成`<u>$1</u>`，经测试，vnote替换后的结果是: `<u>$1</u>`，好像并没有识别到`$1`这个占位符。实测在vscode里面是正常开可以替换的
![GIF 2022-3-2 18-20-54](https://user-images.githubusercontent.com/40653617/156343096-5d8f6ba8-5772-48d2-959a-c96050d514ba.gif)

**Comment by HRS2049** [comment]
.+和.{1,}是一个意思吧？就是匹配至少一个任意字符。反向引用\1或者$1只是正则派系不一样，有的必须用$1（PCRE的好像必须用$1,我记得是这个样子？），我手上常用的软件，这两种格式都可以。如下视频来自emeditor（editpad也一样，视频此处略过）：

https://user-images.githubusercontent.com/96814608/156357227-ea7027cb-443a-4a10-ab4f-58a67eb6439e.mp4

**Comment by tamlok** [comment]
it is a regression introduced recently. Fixed: https://github.com/vnotex/vnote/commit/f9767bf7f72c84701799a04598633df04c21244e

**Comment by HRS2049** [comment]
@tamlok, nice to see it is fixed. Thanks a lot.
