### ISSUE TITLE
If you create a new folder in Navigation, it will move into that folder.

### ISSUE THREAD

**Issue by sinh927** [vnotex/vnote#2049]
**Describe the bug**
When you create a new folder in Navigation, the location of Navigation will be moved to the contents of that folder.

**To Reproduce**
1. Click "New Folder" on Navigation.
2. In the New Folder dialog, enter a name and click the OK button.
3. Navigation will reappear, and the location of Navigation will be changed to New Folder.

**Expected behavior**
I would like only the folder to be created and the navigation location to remain the same.
I think that's how it used to work.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.12.888

**Comment by tamlok** [comment]
Example? Do not understand the question.

When a new folder is created, VNote will navigate to that folder and show the contents of it. That is how it is desinged.
