### ISSUE TITLE
Fold Text not working

### ISSUE THREAD

**Issue by reregaga** [vnotex/vnote#2050]
**Describe the bug**
Settings > Editor > Text Editor > [ ] Fold Text  
After activating this item, I do not see any changes in the program.

**Expected behavior**
What is this feature supposed to do and how can I see the result?

**Desktop:**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.12.888]

**Comment by tamlok** [comment]
Hi,

It should work in editing script files in VNote. It is not supported in Markdown file for now.
