### ISSUE TITLE
markdowny阅读界面下，右键鼠标，选择刷新后什么都不显示，但是编辑模式下正常。

### ISSUE THREAD

**Issue by dbcoffee** [vnotex/vnote#2056]
markdowny阅读界面下，右键鼠标，选择刷新后什么都不显示，但是编辑模式下正常。关闭vnote重启后一切正常，但是再次刷新后问题依然出现。

**Comment by tamlok** [comment]
这是由于更新Qt版本后把这些项目暴露出来了，后面会隐藏掉。
