### ISSUE TITLE
vnote不展示gitee图床的图片

### ISSUE THREAD

**Issue by dong8yong8** [vnotex/vnote#2057]
你好，很抱歉没有按格式反馈问题，
现在就是我用gitee做图床，都配置好了，图片可以传到gitee
但是在vnote里边不展示图片，可以展示图片标题
是需要什么特别的设置么？

系统Deepin 20.4 
vnote版本 "恭喜发财" 版本

**Comment by tamlok** [comment]
详细一点？给点能复现的信息？看一下日志？

**Comment by dong8yong8** [comment]
日志
Warning:(:0) request reply error QNetworkReply::ContentAccessDenied QUrl(地址)

图片的地址我通过浏览器是可以直接访问的

**Comment by tamlok** [comment]
这个是私有仓库吗？

**Comment by dong8yong8** [comment]
> 这个是私有仓库吗？

对，是的，需要弄成公有的么

**Comment by dong8yong8** [comment]
> 

设置成共有后可以了，谢谢

**Comment by dong8yong8** [comment]
但是仓库在**私有**状态下，有办法访问么

**Comment by tamlok** [comment]
图床是为了分享的，私有仓库就没意思了。私有仓库的话，你把整个笔记本用一个仓库管理起来即可
