### ISSUE TITLE
[需求]Ctrl+X, 剪切

### ISSUE THREAD

**Issue by enoche** [vnotex/vnote#2058]
Ctrl+C/V 功能部分实现了（_V其实在编写模式下有效，但vi模式下粘贴不上_），X在Mac上没有用。

**Comment by tamlok** [comment]
详细一点？

**Comment by enoche** [comment]
> 

嗯，谢谢回复！ 就是期待在setting里面Vi那边的卡片页 加入：
“ctrl_x_to_cut”: True,

不知道，我这样表达是不是更精确一些。

**Comment by enoche** [comment]
当然了，这个优先级可能非常低，因为我翻了下 论坛，之前没有人提到，所以大家应该都是用Vi的命令来实现 剪切的。

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/8be34ade30d541082b23ef1567965b7d0937f350
