### ISSUE TITLE
git的配置应该在哪里配置

### ISSUE THREAD

**Issue by winterstay** [vnotex/vnote#2064]
请问作者大大，界面里的git的用户配置应该在哪里配置啊？

**Comment by winterstay** [comment]
还有一个问题就是，最新版的无法换主题，不知道是什么原因

**Comment by tamlok** [comment]
git需要你先用命令行配置好各种设置，然后通过任务来执行git命令。

我这里还是可以更换主题，需要重启vnote的，方便的话可以录屏看看。

**Comment by winterstay** [comment]
git命令是在哪里配置的呀，是在vnote里配置，还是在自己下的git里配置
录像 的话他显示文件过大，上传不了

**Comment by tamlok** [comment]
重启电脑看看

**Comment by winterstay** [comment]
这样点了没反
<img width="854" alt="Snipaste_2022-03-07_22-08-35" src="https://user-images.githubusercontent.com/73685462/157049804-00c50aa1-fc19-4a8e-9d45-d4a4ede2fff5.png">
应

**Comment by winterstay** [comment]
就是在cmd里设置是吧

**Comment by tamlok** [comment]
都说了要重启vnote呀

**Comment by winterstay** [comment]
我试了，我的只有重启电脑才能生效，重启vnote没有用

**Comment by tamlok** [comment]
vnote估计被驻留系统托盘，需要退出再打开，关闭没用。
