### ISSUE TITLE
db文件在同步时会显示冲突

### ISSUE THREAD

**Issue by notorious-eric** [vnotex/vnote#2065]
**问题描述**
db文件在同步时会显示冲突，想请问一下它的作用是什么，如果冲突了有影响吗？我使用onedrive同步，会在两个电脑上都编辑文件，一般不会同时编辑一个文件，是分开编辑的。

**Screenshots**
![image](https://user-images.githubusercontent.com/44058627/157152630-7df6eb32-de89-4063-8526-48633d27ce74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.11.0

**Comment by tamlok** [comment]
同步前请关闭vnote

**Comment by tamlok** [comment]
我一般不会同时在两台电脑上使用vnote，一般在一台电脑上工作完就退出vnote，另一台电脑同步好再打开vnote

**Comment by notorious-eric** [comment]
> 我一般不会同时在两台电脑上使用vnote，一般在一台电脑上工作完就退出vnote，另一台电脑同步好再打开vnote

谢谢解答，我之后也这么使用吧。不过每次出现冲突的时候，我都直接把冲突生成的额外的db文件删掉，好像也没有对其他文件有大影响。

**Comment by tamlok** [comment]
没影响，只是辅助，会根据json索引实时更新的

**Comment by bricle** [comment]
用git同步可不可以直接把这个db文件ignore了

**Comment by tamlok** [comment]
> 用git同步可不可以直接把这个db文件ignore了

可以。后面会把这个db文件放在本地缓存，挪出notebook之外。
