### ISSUE TITLE
功能需求：支持自定义配置plantuml server的地址

### ISSUE THREAD

**Issue by jasongwq** [vnotex/vnote#2066]
**Is your feature request related to a problem? Please describe.**
由于无法联网以及信息安全考虑无法使用默认plantuml server服务
当前只能使用本地jar包，但本地jar相对并发较差，生成图片延迟较高

**Describe the solution you'd like**
支持自定义配置plantuml server的地址

**Describe alternatives you've considered**
通过手动修改plantuml.js文件中this.serverUrl的方式进行配置

**Additional context**
测试数据如下：
使用本地jar包每次刷新耗时3s
使用在线服务（配置为自部署的plantuml server），每次刷新耗时1.5s
另外使用在线服务的好处在于图片空白时间短，使用本地jar包的方式每次刷新期间图片为空白。

**Comment by tamlok** [comment]
Fxied
