### ISSUE TITLE
图片复制出来，背景黑色

### ISSUE THREAD

**Issue by taptao** [vnotex/vnote#2067]
Describe the bug:
复制自己用mermaid写的流程图的图片到word里面，图片背景显示黑色。
To Reproduce
1. 编写一个流程图
2. 退出编辑模式
3. 双击流程图，弹出流程图的图片
4. 右键图片，选择复制图片
5. 复制到任意地方，比如word
Expected behavior
正常显示图片，原先背景为白色，复制后的也应该是白色
Screenshots
![image](https://user-images.githubusercontent.com/33219531/157575457-2cc9b432-f0ab-40cd-8db4-7756e79efe78.png)
![image](https://user-images.githubusercontent.com/33219531/157575923-c5cd6836-8461-405a-aff0-367e6da66d74.png)
Desktop (please complete the following information):

OS: [Windows 10]
Version [e.g. 3.12.888]
Additional context
无

**Comment by tamlok** [comment]
这是Word不能处理SVG的问题。你尝试粘贴回vnote里面。

这个图片是透明背景色的。

**Comment by taptao** [comment]
是的，粘贴会vnote后正常的，并且保存下来的图片，其它地方也可以正常使用，暂时也可以用这种方式。thx~
只是直接复制word、画图和typora好像都不太行。
