### ISSUE TITLE
Macbook Fn键异常

### ISSUE THREAD

**Issue by champagneo** [vnotex/vnote#2068]
我用的系统是 Big Sur 11.6.3 (20G415)

有人和我一样，使用Fn+左右，会直接跳到文章最开头与最结尾，而不是跳到本行开头与结尾么？

Vscode和JetBrain全家桶中则正常

**Comment by tamlok** [comment]
VNote does not modify the default behavior of Qt's edit widget for `FN+Left/Right`.

![image](https://user-images.githubusercontent.com/5763157/157790885-d6d6e838-75b2-46fc-9342-4c919639404a.png)

**Comment by champagneo** [comment]
> VNote does not modify the default behavior of Qt's edit widget for `FN+Left/Right`.
> 
> ![image](https://user-images.githubusercontent.com/5763157/157790885-d6d6e838-75b2-46fc-9342-4c919639404a.png)

So where can I change the bindings of those shortcut buddy ?

**Comment by tamlok** [comment]
For built-in bindings, no.

**Comment by champagneo** [comment]
So sad...

Hope the next version will support.
