### ISSUE TITLE
全局搜索的高亮不能消失

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2069]
# 版本：
* vnote-3.12.888
* windows-10，版本号：21H2

# 重现步骤

1. 全局搜索
2. 点击搜索结果
3. 关闭搜索，高亮依然在
![Snipaste_2022-03-11_11-11-49](https://user-images.githubusercontent.com/40653617/157794992-930ebb62-4d39-477e-a3e6-5e32e4236afa.png)

**Comment by tamlok** [comment]
`Ctrl+G, Space` in version 3.13.0
