### ISSUE TITLE
导航栏能够整个拉出来，拉出来后却不是一个独立的窗口，双击它的标题栏，它就会自动组合回去了，也无法最大化，难以拉到第二个显示器上

### ISSUE THREAD

**Issue by hgyhgyhgyhgyhgy** [vnotex/vnote#2071]
而且那个显示.md文件的工作空间。它似乎无法被拉出去。

这个问题，对于高分辨的大屏幕问题可能不大。但对于1080的中小显示器问题就比较大。
无法让导航栏和工作空间同时尺寸足够大。

还有导航栏空间与工作空间（md编辑器）都有一个最小尺寸限制。无法把它调到很小。

希望可以把工作空间或者导航栏能够拉出去成为一个独立的窗口，且具有一般窗口的功能，比如能够最大化，能够在第二个显示器显示。调整位置时，不会自动吸收回到主窗口里。

**Comment by tamlok** [comment]
这是qt的标准控件，不会做过多文章。应该是能够拉出来的，右上角有一个悬浮的按钮。

**Comment by hgyhgyhgyhgyhgy** [comment]
导航窗口是有悬浮的按钮，也能拉出来。但那个快速开始的窗口，没有悬浮的按钮，也不能拉出来呀。

**Comment by tamlok** [comment]
那个是主窗口。后面会有分离模式。
