### ISSUE TITLE
如果能方便地给笔记添加超连接（快捷方式文件），那应该十分有用。

### ISSUE THREAD

**Issue by hgyhgyhgyhgyhgy** [vnotex/vnote#2072]
目前，有新建笔记与新建文件夹的功能。笔记文件作为文件夹下的内容，会在文件夹树的右侧显示。

既然文件夹名字本身就是一个笔记内容，那么支持这个笔记内容的网页或者pdf文件或者图片或路径等等可以通过一个超链接文件（快捷方式）来访问。这样就不必把文件，图片拷贝进去了。

这样就不必新建一个md文件，再在md文件中加超链接了。这样要跳转好多次，比较麻烦。

能新建快捷方式，可以用于启动软件，直接打开网页，直接打开用于参考的文件，打开某一个文件夹。

这个快捷方式文件与笔记文件.md一起作为文件夹下面的文件，一起显示在文件夹树的右侧。

**Comment by tamlok** [comment]
看不懂。。。

可以考虑一下标签。

**Comment by hgyhgyhgyhgyhgy** [comment]
![image](https://user-images.githubusercontent.com/101418318/158055877-a1dddc75-90a7-42ee-b8a6-9d05cf306fcc.png)
内容窗口右键有4个，建议加一个新建链接的选项。
这样就能新建网址的快捷方式，其他文件夹的快捷方式，其他文件的快捷方式。

目前，即使手动粘贴一个快捷方式在文件夹底下，vnote也不会加载它的。不会显示在内容窗口里。

**Comment by tamlok** [comment]
这个超出vnote的功能定义了，人手有限，暂时不会实现。
