### ISSUE TITLE
粘贴内容到文本编辑器后，头部会多出6个字节的数据。

### ISSUE THREAD

**Issue by D0ngsec** [vnotex/vnote#2073]
比如：将文本test复制粘贴至burp中，头部会多出6个字节（0aefbb）的数据。
复制：
<img width="117" alt="image" src="https://user-images.githubusercontent.com/26764349/158520303-3788e188-9b05-4e7e-92eb-951f50c9eaec.png">
粘贴：
<img width="552" alt="image" src="https://user-images.githubusercontent.com/26764349/158520252-ae95a1a6-34e7-417b-a715-308a7d7a3496.png">

**Comment by tamlok** [comment]
但粘贴到其他编辑器是正常的。不知道是不是Qt自己的处理问题。

**Comment by D0ngsec** [comment]
> 但粘贴到其他编辑器是正常的。不知道是不是Qt自己的处理问题。

目前发现的有burp、finashell粘贴出现异常，每次都要把首字符删除后，手动添加才正常。emm

**Comment by D0ngsec** [comment]
----更新至最新版本，该问题已解决
