### ISSUE TITLE
窗口列表显示

### ISSUE THREAD

**Issue by qifeng-git** [vnotex/vnote#2075]
当切换笔记本时，希望能够将之前笔记本中打开过的窗口列表清除掉

**Comment by tamlok** [comment]
Hi,

你可以新建一个工作空间来容纳新的笔记本的标签页。可能有场景是需要两个笔记本之间的笔记之间互相切换的，所以不能清除掉。

![image](https://user-images.githubusercontent.com/5763157/159439743-180fbaef-f646-4da6-a3e3-7d36b93ed62a.png)

**Comment by qifeng-git** [comment]
那么可以做出一个选项或按钮，一键清除之前打开过的窗口列表吗？

**Comment by tamlok** [comment]
右键菜单里面的关闭其他窗口？

**Comment by qifeng-git** [comment]
我发现 remove workspace  可以一键移除所有的窗口，感谢
