### ISSUE TITLE
Vnote 源代码编译问题

### ISSUE THREAD

**Issue by qifeng-git** [vnotex/vnote#2076]
#### 获取VNote的源代码
git clone https://github.com/vnotex/vnote.git vnote.git
cd vnote.git
git submodule update --init --recursive

#### 从 PPA 获得 Qt 5.12
sudo add-apt-repository ppa:beineri/opt-qt-5.12.10-focal -y    #for（20.04）
sudo apt-get update -qq
sudo apt-get -y install qt512base qt512webengine
sudo apt-get -y install qt512webchannel qt512svg qt512location qt512tools qt512translations
source /opt/qt*/bin/qt*-env.sh

#### Fcitx
sudo cp /lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so /opt/qt512/plugins/platforminputcontexts/

#### OpenSSL
sudo apt install openssl
sudo apt install libssl-dev
安装openSSL后，并没有找到两个库文件：
/usr/lib/libcrypto.so.1.0.0
/usr/lib/libssl.so.1.0.0
于是通过如下方式安装这两个库文件：
sudo dpkg -i multiarch-support_2.27-3ubuntu1.5_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb
将这两个文件复制到Qt的库目录中：
sudo cp /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /opt/qt512/lib/
sudo cp /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /opt/qt512/lib/
在Qt的库目录中，为这两个文件创建符号链接：
sudo ln -s libcrypto.so.1.0.0 libcrypto.so
sudo ln -s libssl.so.1.0.0 libssl.so

#### 编译和安装VNote
cd vnote.git
mkdir build
cd build
qmake ../vnote.pro
make
sudo make install

编译过程中出错：
![图片](https://user-images.githubusercontent.com/61483526/159655280-45bfd27f-0e25-4bcc-9748-5b75aa3451ca.png)

**Comment by tamlok** [comment]
新版升级到5.15了

**Comment by qifeng-git** [comment]
麻烦给一个环境配置步骤，在ubuntu 能正确编译，或者更新一下
https://vnotex.github.io/vnote/zh_cn/#!docs/vx.json

**Comment by tamlok** [comment]
和文档差不多，就是qt版本升级成5.15了，其他命令不变
