### ISSUE TITLE
如何打开通用入口的？

### ISSUE THREAD

**Issue by imchj** [vnotex/vnote#2079]
window10，Vnote3.12
![image](https://user-images.githubusercontent.com/18289628/160226614-e4ac2e38-2c8c-4e0d-a1f1-6d73540c24fe.png)

我尝试使用Ctrl+G键，没有弹出任何输入框。效果如下图。
![image](https://user-images.githubusercontent.com/18289628/160226551-4d37dedb-88ce-4e34-8be7-02f07cfd4896.png)

我网上搜索通用入口效果如下的，想要使用
![image](https://user-images.githubusercontent.com/18289628/160226579-f1bca8d7-944f-4f8a-87a3-0763c5e180bc.png)

**Comment by tamlok** [comment]
下一个版本才会迁移呢。

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/commit/dba9fb30e8450dce99a01d7061a346ee86f3219d
