### ISSUE TITLE
希望v3版本增加编辑模式下，手动拖拽添加附件会像v2.10版本一样提示多种选择

### ISSUE THREAD

**Issue by D0ngsec** [vnotex/vnote#2080]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

版本：v3.12.888 
系统：macos/win10
1、希望v3版本增加编辑模式下，手动拖拽添加附件会像v2.10版本一样提示多种选择（如下图），例如：添加附件并插入链接等多种功能。目前v3版本应该只是默认作为文本插入，添加至附件还需要额外操作；
<img width="240" alt="image" src="https://user-images.githubusercontent.com/26764349/160247229-58a03547-3334-4ac7-a4a7-84682ee2931f.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
你得按着shift还是ctrl拖进去

**Comment by D0ngsec** [comment]
真的可以！谢谢🙏
