### ISSUE TITLE
双击附件时，如何用默认浏览器打开附件中的html文件，而不是用vnote新标签页打开

### ISSUE THREAD

**Issue by D0ngsec** [vnotex/vnote#2081]
**Is your feature request related to a problem? Please describe.**
版本：v3.12.888
系统：macos
1、当我双击打开附件中的html文件时，v3版本会在vnote中新建标签页打开html文件（而且mac卡顿严重），而我之前使用的v2.10会使用默认浏览器打开；
2、请问双击附件时，如何用默认浏览器打开附件中的html文件，而不是用vnote新标签页打开
双击：
<img width="320" alt="image" src="https://user-images.githubusercontent.com/26764349/160248024-6ec0af36-e967-404e-aa2f-3ba2e39dd436.png">
打开：
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/26764349/160248045-95a0b6aa-9eb3-444c-afed-9241409a1a3f.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
Should fixed: https://github.com/vnotex/vnote/commit/cadbab25bb790b9cfba15c4d8c4ae8c66880142b

Should add associaton in the Settings page.

**Comment by D0ngsec** [comment]
How should I add file associations to the settings？
I have added html to the markdown options associated with the file, but vnote still opens the html file?
<img width="958" alt="image" src="https://user-images.githubusercontent.com/26764349/161432862-a392668c-e6e9-4e40-8cc5-2157cd1a2c5e.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/26764349/161433031-1580713a-62c1-48a2-9386-60106d4f2c68.png">

**Comment by tamlok** [comment]
拉下来，有个system的选项，把html加在那里面
