### ISSUE TITLE
剪切粘贴功能有bug

### ISSUE THREAD

**Issue by hgyhgyhgyhgyhgy** [vnotex/vnote#2085]
bug出现在这种情况下面：

假设文件夹里含有文件，比如pdf文件，同时这个pdf文件未被导入到索引中。
当这个文件夹被剪切走时，会出现这样的现象：这个文件夹并不能被剪切走，文件夹依然存在，只是未被加入到索引中，而被粘贴出现的新文件夹一切正常。

这个bug能够根据上面所说复现。

如果那个pdf文件已经被导入了索引中，剪切粘贴功能似乎就一切正常。

解决办法：
在剪切前，把文件夹底下的内容自动导入到索引中？

我进一步测试了，如果文件夹里含有未被导入索引的文件，删除文件夹功能也失效。

**Comment by tamlok** [comment]
那是因为检测到文件夹非空，所以不敢乱删除。

**Comment by hgyhgyhgyhgyhgy** [comment]
但这样显然是bug呀。

你想删除一个文件夹，你也无法删除。
你想移动一个文件夹，也无法移动。这不是bug?

文件被删除或者被移动，又不是自动进行的，是用户想移动或者想删除，才去删除的。

比如移动，文件夹内的内容能移动，但原来的文件夹却没有被删除，这样不是bug吗？

**Comment by tamlok** [comment]
如果文件夹内没有非索引的文件，删除后，文件夹会是一个空文件夹，从而该文件夹也会被删除。但如果有其他vnote不知道的文件(非索引文件)，那为了数据，vnote不会继续删除该文件夹本身。

所以，解决办法就是全部文件归vnote索引。

不过后面可以改一下，如果是非空，那就移动到回收站算了。
