### ISSUE TITLE
通用入口中文输入法不显示候选框

### ISSUE THREAD

**Issue by D0ngsec** [vnotex/vnote#2087]
**Describe the bug**
版本：3.13.0
系统：macos 12
<img width="420" alt="image" src="https://user-images.githubusercontent.com/26764349/161432063-7e40d410-fbdb-4d92-af77-4b28d78045d8.png">
通用入口中文输入法不显示候选框，是不是被挡住了？
<img width="728" alt="image" src="https://user-images.githubusercontent.com/26764349/161432033-959f7ce2-ae29-416c-9965-57760547bf66.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.0.0]

**Additional context**

**Comment by tamlok** [comment]
需要简单修一下

**Comment by tamlok** [comment]
是能输入中文，但候选框不显示？

**Comment by D0ngsec** [comment]
> 是能输入中文，但候选框不显示？

是的

**Comment by tamlok** [comment]
应该已经修复了
