### ISSUE TITLE
源码编译出错

### ISSUE THREAD

**Issue by qifeng-git** [vnotex/vnote#2092]
### 原来的3.12.888 版本源码编译正常，qt的库使用的是5.15.2，更新到3.13.0 后，编译出现error：

cd src/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/keefer/project/vnote/src/src.pro ) && make -f Makefile 
Project MESSAGE: VNote will be installed in prefix /usr
Project ERROR: Unknown module(s) in QT: webenginewidgets webchannel
make: *** [Makefile:74：sub-src-make_first] 错误 3

**Comment by tamlok** [comment]
搜一下这个：Project ERROR: Unknown module(s) in QT: webenginewidgets webchannel

应该是qt安装的问题

**Comment by qifeng-git** [comment]
ok, 已通过 安装 qtwebengine5-dev qtpositioning5-dev搞定
