### ISSUE TITLE
md 预览是空白的，急需紧急修复

### ISSUE THREAD

**Issue by hyperwd** [vnotex/vnote#2093]
![image](https://user-images.githubusercontent.com/5171317/161921572-fbb6c6ea-97e7-41d5-abca-1daa8b502991.png)
![image](https://user-images.githubusercontent.com/5171317/161921599-d7d53c12-d588-4784-a835-e0bf9c9c0600.png)

![image](https://user-images.githubusercontent.com/5171317/161921637-bb1df5f9-9588-40b4-ac95-a54dd2740c44.png)
![image](https://user-images.githubusercontent.com/5171317/161921655-ff1de705-219b-44d1-8d02-484c8ca3e656.png)

**Comment by tamlok** [comment]
操作系统？

如果是win，设置里面改一下oepngl，官方文档的faq里面写有相关操作。

**Comment by hyperwd** [comment]
arch linux

**Comment by hyperwd** [comment]
![image](https://user-images.githubusercontent.com/5171317/161958179-e5b72fcf-b2c7-45a8-9b6b-72de219b3502.png)

启动没有这个参数

**Comment by hyperwd** [comment]
--no-sandbox  这个参数有效
