### ISSUE TITLE
昨晚强行关闭win系统，导致vnote里的笔记本全部丢失了，vnote似乎没把笔记本的信息保存下来？

### ISSUE THREAD

**Issue by hgyhgyhgyhgyhgy** [vnotex/vnote#2095]
笔记本全部丢失了，而且快速访问的内容也全部丢失了！
vnote似乎没有把这些信息保存在vnote的程序目录之中，也没保存在笔记本文件夹底下。

笔记本当然是可以重新打开，但我是把一个笔记本底下的许多子文件夹建成许多个小笔记本。这样就无法恢复其他笔记本了，因为难以记清楚还有多少个子笔记本！

快速访问的内容，也全部丢失。也无法恢复。

如果这些信息没有保存下来，即使不发生强行关闭win系统的事情，从一个电脑转到另一个电脑，也无法重建这个快速访问以及许多子笔记本吧？

**Comment by tamlok** [comment]
应该会保存的。如果强行关闭操作系统，而这时候vnote正在保存这些信息，那么中途关闭的话，可能会导致信息不完整或者出错。这种情况下的数据完整性，一般应用软件都无法保证的。你可以具体检查一下session.json里面的信息。

**Comment by hgyhgyhgyhgyhgy** [comment]
查看了session.json, 只有新打开的笔记本的信息，旧的信息全部都没有了。

你是说vnote恰巧保存这些信息，强行关闭电脑，导致这个文件的信息损坏了？

我是因为电脑休眠后无法唤醒显示器（好像与显示器有点兼容问题），强行关闭电脑，当时并无操作vnote, 当然vnote也未关闭。

这个session.json, 应该放在vnote的目录底下，或者每一个笔记本底下都拷贝一个副本，以免不测。

**Comment by tamlok** [comment]
这个是会话信息，现在放在一个全局位置是合适的。

**Comment by hgyhgyhgyhgyhgy** [comment]
我通过everything 查找session.json，只能找到新·的了。我查看了session.json,发现没有旧的信息。

由于我打开vnote之后发现没有任何一个笔记本后使用打开其他笔记本的选项去重新打开根目录的笔记本了，这样就覆盖了旧的session.json文件？

你是说碰巧vnote在写session.json, 造成了它的损坏？导致其内容丢失了？

如果这个session.json文件是保存已打开的所有笔记本的根目录信息，以及所有快速访问入口的信息，那么它是否应该放在vnote目录底下，或者放到每一个笔记本底下？
它占不了多少空间的。

昨晚，电脑休眠了，显示器无法唤醒，我就只能强行关闭电脑，重启。也不清楚发生了什么事情。不是在操作vnote时强行关机的。

从 Windows 版邮件发送

发件人: Le Tan
发送时间: 2022年4月8日 9:09
收件人: vnotex/vnote
抄送: hgyhgyhgyhgyhgy; Author
主题: Re: [vnotex/vnote]=?UTF-8?Q?_=E6=98=A8=E6=99=9A=E5=BC=BA=E8=A1=8C=E5=85=B3=E9=97=ADwin=E7=B3=BB=E7=BB=9F=EF=BC=8C=E5=AF=BC=E8=87=B4vnote=E9=87=8C=E7=9A=84=E7=AC=94=E8=AE=B0=E6=9C=AC=E5=85=A8=E9=83=A8=E4=B8=A2=E5=A4=B1=E4=BA=86=EF=BC=8Cvnote=E4=BC=BC=E4=B9=8E=E6=B2=A1=E6=8A=8A=E7=AC=94=E8=AE=B0=E6=9C=AC=E7=9A=84=E4=BF=A1=E6=81=AF=E4=BF=9D=E5=AD=98=E4=B8=8B=E6=9D=A5=EF=BC=9F?==?UTF-8?Q?_=28Issue_#2095=29?=

应该会保存的。如果强行关闭操作系统，而这时候vnote正在保存这些信息，那么中途关闭的话，可能会导致信息不完整或者出错。这种情况下的数据完整性，一般应用软件都无法保证的。你可以具体检查一下session.json里面的信息。

**Comment by tamlok** [comment]
你是一个笔记本下面建立多个笔记本？这种语法是不推荐的，我不知道有没有什么坑。

Session.json文件一般不会丢失和损坏的。放在目录底下和放在用户文件夹下面都差不多。你要放在vnote目录底下，可以参考文档的配置文件里面说的便携化的设置。

**Comment by hgyhgyhgyhgyhgy** [comment]
也不仅仅是vnote的设置丢失了，另一个软件的设置也奇怪地丢失了。不清楚是什么原因导致的。可能不是vnote的原因。

可以把便携化设置作为默认设置，这样不容易丢失设置。
