### ISSUE TITLE
标签页右键菜单添加文件属性查看

### ISSUE THREAD

**Issue by cainb** [vnotex/vnote#2111]
![image](https://user-images.githubusercontent.com/48700331/164157465-978219ca-9122-48cb-94c4-559ed2fdef0f.png)

这个文件属性能重新加回到标签页右键菜单嘛，之前 2.x 版本就有

3.x 每次想快速查看文件属性或者重命名都得先定位节点，然后再右键笔记选择属性，有点绕，当焦点不在当前笔记目录树时。

**Comment by feloxx** [comment]
现在的持续集成版本已经迁移了该功能，或者等下一个新版本发布。

**Comment by cainb** [comment]
> 现在的持续集成版本已经迁移了该功能，或者等下一个新版本发布。

好的，收到！
