### ISSUE TITLE
奇怪的bug, 目录下只有一个文件夹，却会显示有两个文件夹

### ISSUE THREAD

**Issue by hgyhgyhgyhgyhgy** [vnotex/vnote#2114]
![image](https://user-images.githubusercontent.com/101418318/164355724-6b39fd51-b003-42e4-9661-5fc53b579b09.png)
![image](https://user-images.githubusercontent.com/101418318/164355744-f3a31786-a6d3-4d7a-a30f-6c24b0dadb68.png)

vx.json的内容如下：
{
    "created_time": "2022-04-09T22:26:13Z",
    "files": [
        {
            "attachment_folder": "",
            "created_time": "2022-04-09T22:26:13Z",
            "id": "4323",
            "modified_time": "2022-04-09T22:26:13Z",
            "name": "H in bcc W.md",
            "signature": "102393669879813",
            "tags": [
            ]
        },
        {
            "attachment_folder": "",
            "created_time": "2022-04-10T03:00:48Z",
            "id": "0",
            "modified_time": "2022-04-10T03:00:48Z",
            "name": "H in bcc W.md",
            "signature": "33270466234465",
            "tags": [
            ]
        }
    ],
    "folders": [
        {
            "name": "Solution energy of H in bcc W"
        },
        {
            "name": "Solution energy of H in bcc W"
        }
    ],
    "id": "4322",
    "modified_time": "2022-04-09T22:26:13Z",
    "signature": "53400977934341",
    "version": 3
}
产生原因不明。
有可能是因为复制粘贴操作造成的。
解决方法，去掉索引，去掉.vx.json文件，或者让复制粘贴剪切的功能更加稳定可靠？

**Comment by tamlok** [comment]
后面会加一个加载去重的逻辑
