### ISSUE TITLE
文档位置定位功能

### ISSUE THREAD

**Issue by ppxiaodi** [vnotex/vnote#2116]
**Is your feature request related to a problem? Please describe.**
vnote同时打开了很多的文档，我想找到其中一个文档的文件夹，因为当文件夹分了很多层，需要花费很多时间才能找到文档的位置
**Describe the solution you'd like**
希望Vnote能提供一个按钮，点击后，能跳转到文档所在的文件夹。因为我经常使用idea,idea就提供了这个功能，希望Vnote也能加上这个功能。
![image](https://user-images.githubusercontent.com/27324380/164976846-d6994e4b-e912-457e-8954-c6582deecc6b.png)

**Comment by feloxx** [comment]
![image](https://user-images.githubusercontent.com/8359848/164983498-021e7377-e4c1-4fd0-b21d-139bb0539348.png)

如果看不到该功能，请使用持续集成版本，或者等下一个版本。

**Comment by tamlok** [comment]
😓😓😓

**Comment by ppxiaodi** [comment]
找到了这个功能了，非常感谢

**Comment by ppxiaodi** [comment]
原来这个功能早就有了
