### ISSUE TITLE
VNote怎么实现为已有的段落自动编号？

### ISSUE THREAD

**Issue by ZhiboWong** [vnotex/vnote#2129]
我发现自动编号，是每次敲击回车后，会自动编号，这不是我想要的。

**Comment by Fxiao1** [comment]
描述的不清楚，标题的意思和描述是两种不同的意思。麻烦能详细描述，方便作者理解你的意图

**Comment by ZhiboWong** [comment]
> 

vnote的自动编号是敲击回车，自动加上编号，这不是我想要的效果。我的需求是：现有多个段落。我要在每个段落前实现自动编号。点击”自动编号“，只会在首段编号，其他自然段没反应。

**Comment by feloxx** [comment]
设置 -> 编辑器 -> MarkDown编辑器 -> 通用 -> 小节序号

**Comment by tamlok** [comment]
选中所有段落，然后按有序列表即可
