### ISSUE TITLE
未选择笔记目录时展示该笔记本下全部笔记,点击父目录时展示父目录下包含子目录全部的记笔

### ISSUE THREAD

**Issue by guyuexue** [vnotex/vnote#2132]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guyuexue** [comment]
建议增加笔记展示的排序方式设置.

**Comment by tamlok** [comment]
> 建议增加笔记展示的排序方式设置.

有呀，面板那里随便点点看看

**Comment by guyuexue** [comment]
1,未选择笔记目录时展示该笔记本下全部笔记(或者在文件目录树增加全部笔记按钮)
2,点击父目录时展示父目录下包含子目录全部的记笔(可以加配置)
3,单击笔记时建议立即在临时标签页中打开,双击在固定标签页打开.临时标签页只保留一个,且保持在第一
4,增加设置:隐藏笔记的文件后缀名
5,增加设置:是否展示笔记目录和笔记本的图标

**Comment by guyuexue** [comment]
编辑模式下,高亮的连接,可以直接点击跳转,或者按ctrl+鼠标左键点击跳转

**Comment by tamlok** [comment]
> 编辑模式下,高亮的连接,可以直接点击跳转,或者按ctrl+鼠标左键点击跳转

右键可以访问链接
