### ISSUE TITLE
mathJaxScript今天莫名就失效了，公式都渲染不出来

### ISSUE THREAD

**Issue by fangxy926** [vnotex/vnote#2133]
如图，默认配置文件这个脚本好像打不开了，我自己换成了这个 https://cdn.bootcdn.net/ajax/libs/mathjax/3.1.2/es5/tex-svg.js
![图片](https://user-images.githubusercontent.com/23739775/169677561-8745eeb9-ca10-4f83-854c-661a30472a81.png)

![图片](https://user-images.githubusercontent.com/23739775/169677622-1a8f68f6-aa30-4e02-879f-3db2cc1c451d.png)

**Comment by tamlok** [comment]
那可能是cdn挂了？

**Comment by rhczz** [comment]
我也遇到了同样的问题

**Comment by hardjet** [comment]
+1

**Comment by hhycqu** [comment]
> 最好是配置到本地，经常会因为访问外网不稳定导致公式渲染不成功的。我在@tamlok的帮助下已经配置了本地的mathjax，很顺畅了。

我这里经常不能渲染公式了，请问一下怎么配置为本地mathjax？

**Comment by hhycqu** [comment]
> > 最好是配置到本地，经常会因为访问外网不稳定导致公式渲染不成功的。我在@tamlok的帮助下已经配置了本地的mathjax，很顺畅了。
> 
> 我这里经常不能渲染公式了，请问一下怎么配置为本地mathjax？

@tamlok 请问一下是否可以发布一下如何配置本地mathjax，以及是否可以在以后更新的版本里集成本地化的？因为最近不能显示公式，确实给我带来了很大的困扰。谢谢！

**Comment by tamlok** [comment]
> > > 最好是配置到本地，经常会因为访问外网不稳定导致公式渲染不成功的。我在@tamlok的帮助下已经配置了本地的mathjax，很顺畅了。
> > 
> > 
> > 我这里经常不能渲染公式了，请问一下怎么配置为本地mathjax？
> 
> @tamlok 请问一下是否可以发布一下如何配置本地mathjax，以及是否可以在以后更新的版本里集成本地化的？因为最近不能显示公式，确实给我带来了很大的困扰。谢谢！

https://github.com/vnotex/vnote/discussions/2127#discussioncomment-2842634
