### ISSUE TITLE
正则不支持"$n"的引用

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2135]
# 环境
电脑：win10
vnote 版本： 3.12.888
# 示例

* 待处理文本： `abcd123efg`
* 正则： `(\d+)`
* 替换内容： `_$1_`
* 替换效果： `abcd_$1_efg`
* 预期效果： `abcd_123_efg`

**Comment by tamlok** [comment]
请使用`\n`: 
![image](https://user-images.githubusercontent.com/5763157/169749197-2c4254a0-2c55-490d-854e-afa97decee4c.png)

**Comment by Fxiao1** [comment]
原来是这样，怪我没有认真看到提示，直接按照历史习惯使用了

**Comment by Fxiao1** [comment]
今天发现即使是`\n`也不能引用

![image](https://user-images.githubusercontent.com/40653617/171327395-83a0976d-29bb-4a39-bc31-cdf9a72a2bf6.png)


![image](https://user-images.githubusercontent.com/40653617/171327333-e729f5e8-aebc-44e2-842e-d01d04bf4c4e.png)

**Comment by Fxiao1** [comment]
发现最新版本（3.13.0）中修复了替换一次和替换并查找，这两个按钮的功能，但替换全部的功能好像漏了，依然会被替换成“\1”这个字符串。

发现这个问题在 #2043 这里也有提到过了，所以就不在这里讨论了，如果那边解决了，这边就会同步关闭
