### ISSUE TITLE
在vnote3以后的版本中增加可行的mathjax配置方法（give  a convenient way to config mathjax）

### ISSUE THREAD

**Issue by haigear** [vnotex/vnote#2136]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I try to config a new version mathjax in vnote (3.0 or later version)
**Describe the solution you'd like**
I want a convenient way to config mathjax in new version of vnote.
**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
最新版设置里面不是有吗？
