### ISSUE TITLE
系统快捷键唤醒速度慢的问题。

### ISSUE THREAD

**Issue by zhouchuanfu** [vnotex/vnote#2139]
环境是deepin，我在系统上设置一个快捷键，专门用于打开vnote，目的是在vnote打开的情况下，能够迅速在其他界面切换到vnote，但是当前并不理想，我每次用快捷键再次打开的时候，都会等1S左右，能否优化一下，如果判断已经运行了的话就尽快切过去，我也怀疑是不是因为程序过大，而且是单个文件，导致的加载速度慢导致的。还望能考虑一下。

谢谢！祝越来越好！

**Comment by feloxx** [comment]
持续集成版本，或者下一个rel版本，已经内置 `快速唤醒` 了。请升级使用

**Comment by zhouchuanfu** [comment]
> 持续集成版本，或者下一个rel版本，已经内置 `快速唤醒` 了。请升级使用
新的build版本测试好像强了一丢丢,感谢!

**Comment by zhouchuanfu** [comment]
> 持续集成版本，或者下一个rel版本，已经内置 `快速唤醒` 了。请升级使用

我没太明白你的意思,**快速唤醒**是一个设置么?

**Comment by feloxx** [comment]
是一个 `设置`，默认 `Ctrl + Alt + U`，可以在在 `vnote.json` 配置文件里手动修改

**Comment by zhouchuanfu** [comment]
> 是一个 `设置`，默认 `Ctrl + Alt + U`，可以在 `vnote.json` 配置文件里手动修改

我试了，快捷键没反应，我又将之前的vnotes.json删除了，重新打开，还是没有。

**Comment by feloxx** [comment]
![image](https://user-images.githubusercontent.com/8359848/170903040-10b4d7a2-6cec-4c74-ae27-e98cb60515d2.png)

把这2个目录里的 `vnotex.json` ，任意一个删除了重启后都会自动生成

![image](https://user-images.githubusercontent.com/8359848/170903264-e6f889cc-e156-46b5-8738-4f7cb82a00b8.png)

如果没有sheng'c生成，请给出详细的复现步骤

**Comment by zhouchuanfu** [comment]
可以了，我删除了`.local`目录下的`vnotex.json`才行，之前只删除了`.config`目录下的，推测是版本号没更新，导致默认的`.local`的没有改，所以必须删除`.local`目录下的才可以。

我还有一个疑问，快捷键是否支持win键，我设置成`Win+V`但是没有反应。

谢谢！
