### ISSUE TITLE
通过外部程序打开文件或目录的问题。

### ISSUE THREAD

**Issue by zhouchuanfu** [vnotex/vnote#2140]
环境是deepin，版本3.13.0，用外部程序打开已经在vnote中打开的文件，或者当前文件是在用外部程序打开的目录时，都会关闭掉内部的，因为我是用列编辑的时候打开外部，写完之后还是希望回到vnote继续写，所以感觉关掉不合理，或者有一个选项用于配置是否关掉。

谢谢。祝顺！

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/blob/09776f07cd74cc7b646de3316676eae81dc8265f/src/data/core/vnotex.json#L488

**Comment by zhouchuanfu** [comment]
OK，谢谢楼上！解决了。
