### ISSUE TITLE
markdown文件间跳转问题

### ISSUE THREAD

**Issue by hsopen** [vnotex/vnote#2143]
![serve20220531235357](https://user-images.githubusercontent.com/61812401/171217339-87e22e5f-dd76-481f-a90e-ce3e8f015f23.gif)
无法在文件名含有空格的文件中跳转

**Comment by hsopen** [comment]
奇怪的问题出现了,就算有空格在vnote中又可以用另一种模式成功
![serve20220601001750](https://user-images.githubusercontent.com/61812401/171222847-4fdffdf2-ccd5-469e-bfb4-179d95dec206.gif)

**Comment by Fxiao1** [comment]
好像是url中不能有空格，可以用`%20`来代替空格，就比如你在搜索引擎里搜索“1 1”，实际地址栏里的地址是这样的： 
`https://www.baidu.com/s?ie=UTF-8&wd=1%201`

**Comment by hsopen** [comment]
> 好像是url中不能有空格，可以用`%20`来代替空格，就比如你在搜索引擎里搜索“1 1”，实际地址栏里的地址是这样的： `https://www.baidu.com/s?ie=UTF-8&wd=1%201`

的确是的，但第二张动图里使用软甲自带的复制路径——插入为相对路径就没有问题出现
![图片](https://user-images.githubusercontent.com/61812401/171452376-3a2e1339-de7a-415a-9788-6eab1aa9a3a3.png)

**Comment by Fxiao1** [comment]
> > 好像是url中不能有空格，可以用`%20`来代替空格，就比如你在搜索引擎里搜索“1 1”，实际地址栏里的地址是这样的： `https://www.baidu.com/s?ie=UTF-8&wd=1%201`
> 
> 的确是的，但第二张动图里使用软甲自带的复制路径——插入为相对路径就没有问题出现 ![图片](https://user-images.githubusercontent.com/61812401/171452376-3a2e1339-de7a-415a-9788-6eab1aa9a3a3.png)

你没发现vnote帮你把空格转成`%20`了吗？
