### ISSUE TITLE
可以提供一下plantuml服务器地址吗？

### ISSUE THREAD

**Issue by SONTON01** [vnotex/vnote#2147]
本地安装plantuml，测试报错，想换下网络服务，哪位大佬可以提供下吗

**Comment by tamlok** [comment]
设置里面不填写就用默认的了呀

**Comment by Fxiao1** [comment]
> 本地安装plantuml，测试报错，想换下网络服务，哪位大佬可以提供下吗

要啥网络服务，本地为王！

1. 建议在vnote根目录下创建个文件夹叫”lib“（当然，你放在本地任何位置都行，前面只是建议）
2. 将
[plantuml-1.2022.2.zip](https://github.com/vnotex/vnote/files/9248675/plantuml-1.2022.2.zip) 解压，得到 ”plantuml-1.2022.2.jar“文件，将其放置到刚才那个lib里面
3. 在vnote里面引入上述jar文件，如下图
![image](https://user-images.githubusercontent.com/40653617/182541791-a2109b65-e357-4a61-82ec-c5f888c77278.png)
