### ISSUE TITLE
vnote没有vue主题风格吗？

### ISSUE THREAD

**Issue by SONTON01** [vnotex/vnote#2148]
我在早期用vnote的时候是有的，现在好像改了3.0版本上

**Comment by dbkuaizi** [comment]
你说的是这款主题吗？官方好像没有vue主题
![](https://user-images.githubusercontent.com/44014601/182031027-85f14300-705e-4146-bccd-4e62568fcf28.png)

**Comment by tamlok** [comment]
3.15支持了
