### ISSUE TITLE
在md文件内链接跳转到另一个md文档是不是新建标签页，而是直接覆盖原有标签页

### ISSUE THREAD

**Issue by hsopen** [vnotex/vnote#2150]
在md文件内链接跳转到另一个md文档是不是新建标签页，而是直接覆盖原有标签页
![serve20220605220457](https://user-images.githubusercontent.com/61812401/172054570-c7f32427-cfe1-472e-9259-a4fa449e671b.gif)

**Comment by feloxx** [comment]
目前是这样设计的。如果点击是一个新的连接则`新建一个笔记页`，如果点击的连接已存在则`跳转到对应的笔记页`。

这样的目的是为了，你在打开阅读的同时，也能方便编辑。且不会影响到其他。

如果点击的跳转都在同一个笔记页中，当多次跳转后会造成编辑与阅读的混乱。

**Comment by hsopen** [comment]
> 目前是这样设计的。如果点击是一个新的连接则`新建一个笔记页`，如果点击的连接已存在则`跳转到对应的笔记页`。
> 
> 这样的目的是为了，你在打开阅读的同时，也能方便编辑。且不会影响到其他。
> 
> 如果点击的跳转都在同一个笔记页中，当多次跳转后会造成编辑与阅读的混乱。

可以设置一个新的快捷键吗？比如说按住ctrl然后点击链接就在原标签打开
