### ISSUE TITLE
位置列表中的列表名长度无法拖拽

### ISSUE THREAD

**Issue by laycher** [vnotex/vnote#2151]
目前在笔记中搜索后，展示出来的位置列表的列名的宽度无法拖拽，导致右边的文本看不到。麻烦优化下。
![QQ图片20220606105013](https://user-images.githubusercontent.com/1949584/172086381-9bbdb0f0-5641-4e1c-a0d1-b59acb9f49df.jpg)

**Comment by tamlok** [comment]
Fixed.
