### ISSUE TITLE
How do I enable UML chart viewing?

### ISSUE THREAD

**Issue by it19862** [vnotex/vnote#2152]
How do I enable UML diagram viewing?
`@startuml
     Bob -> Alice : hello
     Alice -> Bob : ok
@enduml
`
![07 06 2022_01-42-09](https://user-images.githubusercontent.com/18245828/172261070-95e5e29d-4681-40bf-a780-bf9da43b4f74.png)

**Comment by tamlok** [comment]
check the markdown guide at the top right corner help menu please.

**Comment by it19862** [comment]
@tamlok 
I misunderstood the Readme...
The `Readme` in the picture shows a `UML diagram`.
I looked at the `Readme` carefully. This turns out to be a picture inserted into a `Note`.

**Question:** `VNote` does not allow viewing diagrams based on the `uml` code?

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/172331228-de9293a0-2180-485c-8676-7731bd25db75.png)

![image](https://user-images.githubusercontent.com/5763157/172331264-0cdee28e-be00-44c5-be6d-56b02ad341c4.png)
