### ISSUE TITLE
markdown_editor中的auto_break参数无效

### ISSUE THREAD

**Issue by qidanges** [vnotex/vnote#2154]
**Describe the bug**
md在浏览模式下无法自动换行

设置
![image](https://user-images.githubusercontent.com/54615337/172523596-4954a20f-025c-47a4-9ed2-6925de66f1a5.png)

效果
![image](https://user-images.githubusercontent.com/54615337/172523718-c2b0828e-3bc7-4172-91e9-5e7f63328fd9.png)

期望
![image](https://user-images.githubusercontent.com/54615337/172523823-c41b2202-a8ed-4131-9ed5-163fda74eea4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
![image](https://user-images.githubusercontent.com/54615337/172523936-848066b0-89c2-4744-bdfd-5ad0a7aa528e.png)

**Comment by tamlok** [comment]
1. 为什么要弄一个md的代码块呀？
2. AutoBreak的意思是渲染的时候，自动为每一行加一个换行，因为在markdown里面如果两行文本连着写，是不会换行的。
3. 你想要的是AutoWrap，需要通过CSS来定义，你可以右上角打开自定义样式，然后输入你的样式即可。
![image](https://user-images.githubusercontent.com/5763157/172538229-3e30caef-297a-41b5-9664-6601f7a2167e.png)

**Comment by qidanges** [comment]
你好，我所表达的意思是在markdown浏览时单行内容过多，如何自动换行呢。


我使用AutoBreak并不能在markdown浏览的时候，实现单行内容过多，自动换行的功能。


1.现在我在markdown编译时，单行内容过多会自动换行
2.我现在想要markdown在浏览时，实现单行内容过多自动换行的效果





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vnotex/vnote"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 中午1:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vnotex/vnote] markdown_editor中的auto_break参数无效 (Issue #2154)





  
为什么要弄一个md的代码块呀？
 
AutoBreak的意思是渲染的时候，自动为每一行加一个换行，因为在markdown里面如果两行文本连着写，是不会换行的。
 
你想要的是AutoWrap，需要通过CSS来定义，你可以右上角打开自定义样式，然后输入你的样式即可。

**Comment by tamlok** [comment]
![image](https://user-images.githubusercontent.com/5763157/172587453-5a6b9919-2a0c-48fd-ab83-a1a9f5cb35d2.png)

**Comment by D0ngsec** [comment]
编辑 Markdown用户样式，修改user.css文件
```css
code{
    white-space: pre-wrap !important;
    word-wrap: break-word !important;
    word-break: break-all !important;
}
```

**Comment by qidanges** [comment]
多谢，已经通过修改white-space参数实现。
pre[class*="language-"].line-numbers &gt; code {
&nbsp; &nbsp; position: relative;
&nbsp; &nbsp; white-space: pre-wrap;
}



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vnotex/vnote"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 晚上10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vnotex/vnote] markdown_editor中的auto_break参数无效 (Issue #2154)





 
编辑 Markdown用户样式，修改user.css文件
 code{     white-space: pre-wrap !important;     word-wrap: break-word !important;     word-break: break-all !important; }
