### ISSUE TITLE
请求增加“在当前目录打开作为笔记本(open cur-dir as NoteBook)”

### ISSUE THREAD

**Issue by Schips-Wong** [vnotex/vnote#2155]
在Vnote里面打开一个现有的笔记本时，总需要浏览目录再点击确定。

请问是否能够快速将资源管理器的目录作为笔记本路径并打开？

例如，关联一个*.vnote后缀的文件a，执行它就便能够以a所在路径的目录打开对应的路径。

**Comment by hgyhgyhgyhgyhgy** [comment]
现在的从文件夹可以新建笔记本。

我反映过这个功能会导致奇怪的问题，会出现丢失的问题。

作者说，这个不是vnote的用法。

这个如果太多目录，是会让人分心的。
又没有只显示某个目录的功能。
从子目录新建笔记本的功能，又有bug。

**Comment by Schips-Wong** [comment]
谢谢您的回复~我理解啦
