### ISSUE TITLE
请求增加“本地图床功能：将网络图片保存为本地图片”

### ISSUE THREAD

**Issue by Schips-Wong** [vnotex/vnote#2156]
像我在内的一些笔记爱好者，在写Markdown时总喜欢把图片保存在本地里面。

Vnote下载图片的功能确实很好，但如果遇到“一些事先通过网络图床保存文件”的情况，只能够手动下载图片。请问是否可以在图片的右键菜单里，添加“保存到本地图床(Upload image to image host -> local)”的功能。

效果为：

```bash
# before
![](http..../xx/xyz123456.png)
# after
![](vx_images/xyz123456.png)
```

**Comment by feloxx** [comment]
你可以在 阅读模式里，复制图片，然后在笔记粘贴，就自动下载了，虽然稍微有点麻烦，但是可以解决现在的问题。

**Comment by Schips-Wong** [comment]
谢谢您的回复，我咋没想到这种方法。
