### ISSUE TITLE
Windows界面 Task字符重叠

### ISSUE THREAD

**Issue by cemon-liu** [vnotex/vnote#2158]
**Describe the bug**
设置task menu后字符重叠
**To Reproduce**
1. Create a task
2. it will show on the menu

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [3.13.0]

![image](https://user-images.githubusercontent.com/54880948/173076888-c499c1cf-9a78-42d3-b222-5f6099d69268.png)

**Comment by tamlok** [comment]
Qt的界面问题，暂时先不管了
