### ISSUE TITLE
请教如何修改标签栏字体以及图标的大小？

### ISSUE THREAD

**Issue by ovmonk** [vnotex/vnote#2159]
<img width="960" alt="批注 2022-06-14 151329" src="https://user-images.githubusercontent.com/17329166/173516991-48afec65-90a7-4689-a03e-e2b3a03d1bb6.png">

如上图，标红区域中字体大小、图标大小以及该区域的上下宽度是否可以调整？编辑区图标、主工具栏图标都可以调节，唯独没找到这个区域的调整方式。

**Comment by tamlok** [comment]
hi，你可以参考一下Qt的QSS的样式说明，然后修改interface.qss文件对应的部件的样式，部件名字应该都比较好认的。如果还有问题，欢迎再提出。
