### ISSUE TITLE
正则模式搜索单个空格导致崩溃

### ISSUE THREAD

**Issue by Nriver** [vnotex/vnote#2163]
本来是想搜 `\.deb\ ` 结果把vnote搞挂了。
整理一下最快复现步骤，进入搜索界面，勾选正则表达式，搜索关键字 `\ ` （斜杠+空格），然后回车搜索会导致vnote崩溃。

日志里面输出了一堆
```
Warning:(:0) QString::indexOf: invalid QRegularExpression object
```

**Comment by HRS2049** [comment]
经测试，我这边没有出现同样的问题（上不了截图）。顺便，如果是匹配“\”本身，需要对这个元字符进行转义。

**Comment by HRS2049** [comment]
![Test](https://user-images.githubusercontent.com/96814608/175748806-16c908c9-2d13-4f1e-8077-12fd9f223fdf.png)

**Comment by Nriver** [comment]
啊, 我说的搜索不是编辑模式里的搜索, 而是左边的那个全局搜索, 也就是ctrl alt f 的那个. 只要是在正则模式下搜空格就会挂掉.

我试了新建一个笔记本, 随便建几个文件, 少量内容搜索没有问题. 我在怀疑是不是和我的笔记内容有关. 我的md文件目前一共有900个左右. 也许是里面的空格数量太多? 或者是有什么奇怪的字符? 我也不知道怎么定位问题.

**Comment by HRS2049** [comment]
啊，我试了一下，全局搜索的确会出现你说的问题。跟内容多少没有关系。如果你需要搜索的是“\ ”（反斜杠+空格），必须在\前面加多一条\，就是对它进行转义。这次不会出现按回车就闪退的情况，但是查找的结果看起来也是怪怪的，带空格和不带空格的\均可匹配，但是有的\又匹配不到。可能只有作者本人能回答了。
![image](https://user-images.githubusercontent.com/96814608/175796458-408983ee-2ad5-4612-8db2-a64bbd66e5b8.png)

**Comment by tamlok** [comment]
可以通过双引号来引用带空格的字符串进行搜索。

3.13.1好像复现不了。

**Comment by Nriver** [comment]
> 可以通过双引号来引用带空格的字符串进行搜索。
> 
> 3.13.1好像复现不了。

我用的就是 3.13.1 这个版本, linux和win都会崩掉. 复现不了的话很就可能是和我的笔记内容有关了.
