### ISSUE TITLE
markdown画流程图时文字和箭头不能正常显示

### ISSUE THREAD

**Issue by 1311008420zhang** [vnotex/vnote#2164]
**Describe the bug**
在软件上画流程图时文字和箭头不能正常显示
![image](https://user-images.githubusercontent.com/36984203/174997543-13812231-c5b8-4033-b910-e784e441b0ab.png)
导出成PDF时能够看到流程图上的文字和箭头
![image](https://user-images.githubusercontent.com/36984203/174997928-6bff9591-d328-498f-aa08-a0f15affafef.png)

**Comment by tamlok** [comment]
对于Mermaid，原地预览的确会有缺失的情况，这是由于Mermaid的本身实现导致的，目前无解。
