### ISSUE TITLE
鼠标在文档文件上的提示框能否换种形式？

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2166]
* vnote版本： 3.12.888
* 电脑：win10

# 描述
如下图，现在的状态是通过一个追踪鼠标的大框来显示有可能不全的文件名，和创建时间、修改时间。
但这个框太大了，遮挡面积比较大，而且这时候人的关注点就在文档上，可能正在找文档，而它此时却遮住了很多此时需要关注的信息，所以只能被迫鼠标移开才行。
![image](https://user-images.githubusercontent.com/40653617/175203213-78d46837-946f-4d3f-abd7-36ab70d58371.png)

# 建议
不要显示信息框了。创建时间、修改时间这两项不是频繁关注点，想看的话，右键=》属性就能看了。而文件名如果没有显示全，能否可以让它延伸到隔壁去？就像下图：
![image](https://user-images.githubusercontent.com/40653617/175203354-738cdbce-b1c8-4587-a7d8-a0caa44b6c1c.png)
如果这个不好实现的话，那能否将现有的信息框变窄，放置到隔壁空间，与当前文档标题同行，就像下面这样？
![image](https://user-images.githubusercontent.com/40653617/175204449-d5800fad-58ff-4968-b279-45f16cceb74b.png)

**Comment by feloxx** [comment]
好的，这个功能确实可以优化一下。我也觉得显示的信息不是很重要，且还有点遮挡了。

**Comment by tamlok** [comment]
Fixed.
