### ISSUE TITLE
笔记本外接显示器的时候 外接显示器 显示不正常

### ISSUE THREAD

**Issue by zhuhaisto** [vnotex/vnote#2168]
![微信截图_20220624065053](https://user-images.githubusercontent.com/108032980/175427828-33ee8378-fb3d-4896-9268-cd894e11a03d.png)
如图请看大小有些字体就特别大
我笔记本是4k屏 外接的显示器是1080p的 我把笔记本盖起来的（也就是说外接显示器是唯一屏）
希望能更正 这是个bug吧

**Comment by tamlok** [comment]
请从同一个显示器打开vnote并使用

**Comment by zhuhaisto** [comment]
我就是从同一个显示器啊
笔记本连接显示器 然后笔记本是盖住的 只有一个外接显示器是亮的
然后才打开的vnote

从 Windows 版邮件发送

发件人: Le Tan
发送时间: 2022年6月24日 10:25
收件人: vnotex/vnote
抄送: zhuhaisto; Author
主题: Re: [vnotex/vnote] 笔记本外接显示器的时候 外接显示器 显示不正常 (Issue #2168)

请从同一个显示器打开vnote并使用

**Comment by tamlok** [comment]
右键，属性，PDI什么的，设置一下看看？

**Comment by zhuhaisto** [comment]
屏幕分辨率？22寸 1920 1080 还是说vnote可以调整dpi？
像这样？



如果是这样我晚点回家去测试下看看行不行！再回你




从 Windows 版邮件发送

发件人: Le Tan
发送时间: 2022年6月24日 19:40
收件人: vnotex/vnote
抄送: zhuhaisto; Author
主题: Re: [vnotex/vnote] 笔记本外接显示器的时候 外接显示器 显示不正常 (Issue #2168)

右键，属性，PDI什么的，设置一下看看？
