### ISSUE TITLE
快捷CloseOtherTabs和CloseTabsToTheRight无论指定什么快捷键都无效

### ISSUE THREAD

**Issue by haigear** [vnotex/vnote#2169]
CloseOtherTabs和CloseTabsToTheRight尝试指定了Ctrl+G, W，尝试了指定Ctrl+Alt+W，尝试了指定Ctrl+Shift+W都无效，是不是我理解错了。CloseOtherTabs应该是关闭除当前激活状态的文件意外的任何文件吧。CloseTabsToTheRight应该是关闭当前文件之后（向右为后）的所有文件吧。这个两个快捷键的如果是这样的功能，的确会有很好的体验。期待修复。

**Comment by feloxx** [comment]
因为这2个功能还没开发与快捷键的映射，等下个版本把

**Comment by zhuhaisto** [comment]
目前生效的快捷键有哪些

**Comment by feloxx** [comment]
已经生效的都会在界面上有显示，或者参考配置文件里已有的。

正在迁移开发的可以参考这里

https://github.com/vnotex/vnote/issues/2090

**Comment by haigear** [comment]
@feloxx  感谢回答，静候下个版本！

**Comment by tamlok** [comment]
忘记加了，这是一个bug。@feloxx 你能帮忙添加到`ViewArea::setupShortcuts()`这个函数里面吗？参照`CloseTab`的实现。

**Comment by feloxx** [comment]
https://github.com/vnotex/vnote/pull/2173

这个 bug 的修复 pr

**Comment by Fxiao1** [comment]
> #2173
> 
> 这个 bug 的修复 pr

您好，请问能添加一个 `F2`快捷键映射到“重命名”这个功能上吗？

**Comment by feloxx** [comment]
> > #2173
> > 这个 bug 的修复 pr
> 
> 您好，请问能添加一个 `F2`快捷键映射到“重命名”这个功能上吗？

![image](https://user-images.githubusercontent.com/8359848/178127907-8df71fa1-2472-49cd-8fb0-c51ef5bd98b7.png)

最新的版本，或者持续集成版本，已经实现该功能。

**Comment by feloxx** [comment]
> #2173
> 
> 这个 bug 的修复 pr

已经合并到主分支，等下个版本，或者使用持续集成版本即可。
