### ISSUE TITLE
3.13.1部分markdown文档阅读模式无法预览

### ISSUE THREAD

**Issue by je45** [vnotex/vnote#2171]
阅读模式有些文档无法预览，显示一片空白，F12调试模式提示

DevTools was disconnected from the page,
Once page is reloaded, DevTools will automatically reconnect.

出现问题的版本是3.13.1，最新构建版本也有这个问题，使用3.13.0正常。

 - OS: [e.g. Windows 7]
 - Version [e.g. 3.13.1]

日志：
Info:(main.cpp:139) "VNote (v3.13.1) started at 周三 六月 29 09:48:32 2022 (windows)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1j  16 Feb 2021"
Warning:(main.cpp:148) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:91) using theme "pure"
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default
Info:(singleinstanceguard.cpp:24) guarding is off
Info:(main.cpp:139) "VNote (v3.13.1) started at 周三 六月 29 09:48:53 2022 (windows)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1j  16 Feb 2021"
Warning:(main.cpp:148) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:91) using theme "pure"
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default
Warning:(:0) unknown token "Invalid"
Warning:(:0) unknown token "Invalid"
Warning:(:0) unknown token "Invalid"
...
Warning:(:0) request reply error QNetworkReply::ProtocolUnknownError QUrl("")
Warning:(:0) request reply error QNetworkReply::ProtocolUnknownError QUrl("")
Warning:(:0) request reply error QNetworkReply::ProtocolUnknownError QUrl("")
...
Info:(singleinstanceguard.cpp:24) guarding is off

**Comment by tamlok** [comment]
看看置顶issue弄一下OpenGL？

**Comment by je45** [comment]
> 看看置顶issue弄一下OpenGL？

试了OpenGL设置，三种都试了，我的问题是部分markdown阅读模式无法预览，有些是可以的，不知道是不是markdown文件内容过多导致的？（不确定），内容较小的文档都可以预览

**Comment by je45** [comment]
> 不能浏览的文档发我邮箱一份？

已发

**Comment by sxdok** [comment]
你好 我遇到了相同的情况 在OpenGL设置为Software时会出现，操作速度较快时会出现OpenGL的提示
![屏幕截图 2022-07-03 154714](https://user-images.githubusercontent.com/72053445/177030686-0136f2a2-e033-41b6-98c2-94aaa02ced17.png)
我的显卡驱动版本应该没有问题

**Comment by tamlok** [comment]
> 你好 我遇到了相同的情况 在OpenGL设置为Software时会出现，操作速度较快时会出现OpenGL的提示 ![屏幕截图 2022-07-03 154714](https://user-images.githubusercontent.com/72053445/177030686-0136f2a2-e033-41b6-98c2-94aaa02ced17.png) 我的显卡驱动版本应该没有问题 @tamlok

你试试其他值

**Comment by DrPeaboss** [comment]
本人测试发现对于部分较大的文件（至少我测的大于60KB），3.13.1及开发版本存在此问题，3.13.0没有。

虽然我没看过软件源码和git提交记录，但是根据经验判断发现了问题，原因非常奇特。

问题居然出在了文件的**TAB**字符上！！！

原先我是发现一个100多K的文件打开不能预览，删了部分还是不行，然后仔细看发现该文件用了大量TAB符号来排版，然后又写了个小程序把所有TAB符号替换成了4个空格，发现可以了（尽管排版有点乱，因为原文件TAB和空格混搭）。

接着想确定是不是大文件TAB符号的问题，就写了个小程序自动从原文件拷贝一部分生成新文件，发现当这个文件比较小的时候可以预览，文件大了就不行。

所以作者可以查一下是不是哪些改动影响TAB字符的渲染了。

发现问题的文件在此[仓库](https://github.com/FreeBlues/PwML)，文件名是 Common Lisp 初学者快速入门指导.md (125KB)

**Comment by Duter2016** [comment]
遇到同样的问题！
从linuxmint 20.3（基于ubuntu20.04） 升级到linuxmint 21（基于 22.04），突然不能预览了，显示空白，编辑模式正常！
把vnote从3.13升级到3.14同样不能预览！

**Comment by tamlok** [comment]
> 遇到同样的问题！ 从linuxmint 20.3（基于ubuntu20.04） 升级到linuxmint 21（基于 22.04），突然不能预览了，显示空白，编辑模式正常！ 把vnote从3.13升级到3.14同样不能预览！

使用--no-sandbox

**Comment by tamlok** [comment]
> 本人测试发现对于部分较大的文件（至少我测的大于60KB），3.13.1及开发版本存在此问题，3.13.0没有。
> 
> 虽然我没看过软件源码和git提交记录，但是根据经验判断发现了问题，原因非常奇特。
> 
> 问题居然出在了文件的**TAB**字符上！！！
> 
> 原先我是发现一个100多K的文件打开不能预览，删了部分还是不行，然后仔细看发现该文件用了大量TAB符号来排版，然后又写了个小程序把所有TAB符号替换成了4个空格，发现可以了（尽管排版有点乱，因为原文件TAB和空格混搭）。
> 
> 接着想确定是不是大文件TAB符号的问题，就写了个小程序自动从原文件拷贝一部分生成新文件，发现当这个文件比较小的时候可以预览，文件大了就不行。
> 
> 所以作者可以查一下是不是哪些改动影响TAB字符的渲染了。
> 
> 发现问题的文件在此[仓库](https://github.com/FreeBlues/PwML)，文件名是 Common Lisp 初学者快速入门指导.md (125KB)

试试3.14.0 的qt5.15版本。

**Comment by Duter2016** [comment]
> > 遇到同样的问题！ 从linuxmint 20.3（基于ubuntu20.04） 升级到linuxmint 21（基于 22.04），突然不能预览了，显示空白，编辑模式正常！ 把vnote从3.13升级到3.14同样不能预览！
> 
> 使用--no-sandbox

谢谢，可以预览了
