### ISSUE TITLE
QtWebEngineProcess.exe - 应用程序错误

### ISSUE THREAD

**Issue by 18183883296** [vnotex/vnote#2189]
每当我打开VNote软件，不久就会弹出“QtWebEngineProcess.exe - 应用程序错误”的弹窗
预览功能随之失效，我尝试过切换OpenGL等工作，都无法解决这个问题
![QQ截图20220719234952](https://user-images.githubusercontent.com/89304297/179794514-6af7d817-e8bb-4b1a-a0db-21e63600f8cf.jpg)
![QQ截图20220719235133](https://user-images.githubusercontent.com/89304297/179794531-75508add-63ce-4401-92d3-240699deb5b3.jpg)

**Comment by tamlok** [comment]
试试下载x86的版本跑一下？

**Comment by tamlok** [comment]
试试这个：https://github.com/vnotex/vnote/releases/download/v3.14.0/vnote-win-x64-qt5.15.2_v3.14.0.zip
