### ISSUE TITLE
编辑模式的行号对齐有待优化

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2190]
# 平台

* 电脑 win10
* vnote:  3.13.1

# 问题描述

在编辑模式的时候，多行代码如果过长会自动换行，这时候行号对齐是上下居中对齐的（如下图所示），看不清75、76、77行究竟对应的是哪一行。 

![image](https://user-images.githubusercontent.com/40653617/179890375-28d9f686-7f2a-4e23-b607-7d337b98920c.png)

# 改进建议

1. 能否修改成这种行内顶部顶部对齐的方式，只跟实际行的顶部对齐就行了。这样就能清晰的看到这行文字从哪里开始到哪里结束了。
![image](https://user-images.githubusercontent.com/40653617/179890904-1533999c-4d53-47e3-80ca-70fce242e64e.png)

2. 同时**多行代码**能否直接改成不自动换行？让编辑模式和预览模式看到的效果一样

**Comment by tamlok** [comment]
Fixed in 3.14.0.
