### ISSUE TITLE
期待能优化一下“多功能粘贴”的体验，现在的逻辑比较绕

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2191]
# 平台
* 电脑： win10
* vnote: 1.31.1

# 描述

复制粘贴纯文本的时候依然会弹窗询问粘贴为链接还是纯文本，并且默认选项是“链接”。想要正确粘贴需要
ctrl+v
down
enter
三步，感觉有点绕路了

# 改进建议

个人愚见： 对于纯文本，绝大多数人的预期应该还是直接响应为“粘贴为文本”的，所以能否对于纯文本“ctrl+v”就直接粘了。而“ctrl+shift+v”的逻辑则继续统一保留为：忽略粘贴对象类型（文本、链接、图片文件、普通文件），强制粘贴为纯文本

**Comment by tamlok** [comment]
这个设置里面可以修改默认选项的。

链接是不是你的文本是一个链接的内容呢？VNote是检测到剪切板有url之类的才会弹是否粘贴为链接。

**Comment by Fxiao1** [comment]
> 这个设置里面可以修改默认选项的。
> 
> 链接是不是你的文本是一个链接的内容呢？VNote是检测到剪切板有url之类的才会弹是否粘贴为链接。

1. 默认为多功能粘贴也没毛病，否则复制文件后直接 ctrl+v会粘贴路径而不是文件，所以希望能其他的不用动，就文本这个逻辑改成纯文本粘贴，其他的（链接、剪切板图片、图片文件、普通文件）等类型还是调用多功能粘贴

2. 真的是纯文本，不是链接
![GIF 2022-7-20 15-14-31](https://user-images.githubusercontent.com/40653617/179920464-ee786009-12a0-4162-81a1-e9ecaa05e482.gif)

**Comment by tamlok** [comment]
这个纯文本你是从哪里复制来的？能试试从记事本里面复制过来嘛？

**Comment by Fxiao1** [comment]
> 这个纯文本你是从哪里复制来的？能试试从记事本里面复制过来嘛？

在任意地方复制都行，我那个“纯文本”是在那个界面手打的

**Comment by Fxiao1** [comment]
比较奇怪的是，如果真的选择“链接”了，会粘贴一串不知道什么东西的字符进来

![GIF 2022-7-20 15-14-31](https://user-images.githubusercontent.com/40653617/179929490-1f388394-548e-4cc9-8219-74346e85b8a3.gif)

**Comment by tamlok** [comment]
已经修复了。

**Comment by Fxiao1** [comment]
> 已经修复了。可以等下一个版本或者持续构建。

辛苦了，谢谢

**Comment by Fxiao1** [comment]
> 已经修复了。可以等下一个版本或者持续构建。

经测试 3.14.0 版本中，对于链接的定义还是有点宽泛了 `resultMap="UserResult"` 这个都能被识别成链接
![image](https://user-images.githubusercontent.com/40653617/182591760-c3f80c8c-c30e-419e-9a90-6e00bc63fad2.png)
粘贴为连接后效果如下：

![image](https://user-images.githubusercontent.com/40653617/182591945-7f249c4b-ae2a-4c0f-b22b-36edaab54bd5.png)

期待能否将链接定义的严格一点，比如必须符合这样的正则 `^http[s]{0,1}://` 才能定义为链接？

**Comment by tamlok** [comment]
Hi, 我这边测试没有问题呀，是不是你启动错误的版本了？帮助里面的关于看看版本？

**Comment by Fxiao1** [comment]
> Hi, 我这边测试没有问题呀，是不是你启动错误的版本了？帮助里面的关于看看版本？

奇怪了，我昨天明明测试是会出现多功能弹窗的，早上测试就正常了，或许真的是打开错版本了，实在抱歉

**Comment by Fxiao1** [comment]
> Hi, 我这边测试没有问题呀，是不是你启动错误的版本了？帮助里面的关于看看版本？

**现在知道怎么复现了**，从idea里粘贴过来的话就会出现弹窗了，可能是带格式了，因为我发现哪怕是复制大段代码过来，在vnote这里粘贴的时候都会提示是否要粘贴为链接
![GIF 2022-8-5 12-27-16](https://user-images.githubusercontent.com/40653617/183001960-d7785405-36a6-41d9-8886-0ebc0613c146.gif)
