### ISSUE TITLE
ubuntu 18 无法输入中文

### ISSUE THREAD

**Issue by zhuangzihan** [vnotex/vnote#2193]
**Describe the bug**
使用系统自带的输入法无法输入中文，输入后是英文

**To Reproduce**
应用内任何能输入的数据地方都能复现，包括但不限于新建笔记的名字、笔记正文内容

**Expected behavior**
能够输入中文

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04.6 LTS

**Additional context**
- vnote version: 3.13.1
- 输入法: IBus 智能拼音 1.11.0

**Comment by tamlok** [comment]
下载的appimage吗？可以搜一下 qt5 ibus 两个关键词，应该全网挺多解决方案的。

**Comment by zhuangzihan** [comment]
> 下载的appimage吗？可以搜一下 qt5 ibus 两个关键词，应该全网挺多解决方案的。

**Comment by zhuangzihan** [comment]
> 下载的appimage吗？可以搜一下 qt5 ibus 两个关键词，应该全网挺多解决方案的。
