### ISSUE TITLE
字符“\.”  阅读模式下 斜杠没有了

### ISSUE THREAD

**Issue by linhua55** [vnotex/vnote#2194]
粘贴   C:\Users\linhua\.android\debug.keystore
阅读模式下 变为 C:\Users\linhua.android\debug.keystore
\. 中的 斜杠没有了

看来是markdown 的问题，希望粘贴的时候 处理一下

**Comment by tamlok** [comment]
md就是要转义的，或者你用行内代码。或者你直接用多功能粘贴，让vnote帮你处理

**Comment by linhua55** [comment]
谢谢
