### ISSUE TITLE
小毛病：图片路径处理

### ISSUE THREAD

**Issue by sir2k** [vnotex/vnote#2196]
**Describe the bug**
图片只能使用Linux 风格的 “/” ，不支持 Winodws 风格的“\”。

**To Reproduce**
1. 创建图片目录，名为 imgs
2. 生成 md 文件
3. 插入图片: `![](imgs\test01.png)`， marktext 显示图片， vnote 不显示图片， 两者导出的 pdf 都不含有图片。
vnote 不显示图片：
![image](https://user-images.githubusercontent.com/1161975/181864409-d0582731-806e-4d25-99c7-450ac0914e6d.png)

marktext 显示图片:
![image](https://user-images.githubusercontent.com/1161975/181864318-bf52c0c6-2d43-4349-9eb4-4fdaefe5048b.png)

4. 插入图片: `![](imgs/test01.png)`，marktext 和 vnote 都能够显示图片，两者导出的 pdf 含有图片。
--> 以后插入图片，在路径中必须使用“/” 来分隔目录。

**Expected behavior**
路径中使用 /、\，应该都能显示图片。
又，知道原因才能处理问题，关键是碰到上述问题时不知道原因，前后折腾了两个小时才找出原因。

**Comment by tamlok** [comment]
你好，url的规范就是使用/的哦，直接在vnote中插入图片，vnote会自动处理好。
