### ISSUE TITLE
部分图标太小了，且不能设置（优先级：低

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2203]
# 环境
* win10
* 屏幕分辨率：1920*1080
* vnote版本： 3.14.0
# 描述
![image](https://user-images.githubusercontent.com/40653617/182997111-936a6f0a-bbda-4805-8da9-bf5adeba0c31.png)
![image](https://user-images.githubusercontent.com/40653617/182997166-0602bf9d-6d2d-4a09-8e1c-356cd88635fc.png)
这两个地方都设置了，但是界面中还有一些地方不能调大。
有没有可能在一个位置可以统一设置全局所有图标大小，从而避免了整个界面上图标大的大小的小，非常不协调。比如下图那样，绿色是我调大了的，比较合适了。红色是太小了，不方便点击，但又调整不了的。

![image](https://user-images.githubusercontent.com/40653617/182998290-5abd2b53-21d3-4309-8b70-bb693f84007d.png)

**Comment by tamlok** [comment]
为什么你的侧边栏那几个图标是白色底色的？是自定义主题？

**Comment by tamlok** [comment]
我的图标大小相对是这样的：

<img width="411" alt="image" src="https://user-images.githubusercontent.com/5763157/183005498-e6bff5a6-5b9a-45df-a63b-f6f49f75d79f.png">


 要不你删除默认配置文件夹，然后重启一下？

**Comment by Fxiao1** [comment]
> 为什么你的侧边栏那几个图标是白色底色的？是自定义主题？

这几个图标吗？

![image](https://user-images.githubusercontent.com/40653617/183005309-669cac69-efaf-4ea0-9685-d9da3ee1a4e9.png)

不是白色，是灰色呀，确实有自定义主题基于前面几个版本的纯净主题改的。那为了排除影响，我换成默认主题了。但是图标大小好像没有变化
![image](https://user-images.githubusercontent.com/40653617/183005466-91057123-bf85-4c2a-be7f-0304d067a2e8.png)

**Comment by tamlok** [comment]
用户文件夹里面的vnotex.json可以修改下面选项：

<img width="469" alt="image" src="https://user-images.githubusercontent.com/5763157/183006037-09a9e64c-a381-4828-8b88-43d67eefb82b.png">


可以看到其实两者的图标大小是一致的。

**Comment by Fxiao1** [comment]
> 我的图标大小相对是这样的：
> 
> <img alt="image" width="411" src="https://user-images.githubusercontent.com/5763157/183005498-e6bff5a6-5b9a-45df-a63b-f6f49f75d79f.png">
> 
> 要不你删除默认配置文件夹，然后重启一下？

好像确实有变化，你这几个图标好像是跟着侧边栏的宽度自适应的是吧看的出来现在主题把这个侧边栏加宽了。恩，我知道是我的原因了，那我基于现在的主题再捯饬捯饬吧。

主要是默认主题有一些特性需要调整不调整的话用着不舒服，比如

* 代码浏览模式限制最大高度
* 图片加一个像素的边框（有的图片颜色跟背景颜色一样，不加边框都看不出来了
* 单行代码样式更改
* 引用样式更改
* 更多，像下图所示

![image](https://user-images.githubusercontent.com/40653617/183006255-92a84c09-a7f6-4f19-84c2-d8c5373c339e.png)

**Comment by tamlok** [comment]
你可以diff一下主题的变化，然后相应添加到你的主题上面。

**Comment by Fxiao1** [comment]
> 你可以diff一下主题的变化，然后相应添加到你的主题上面。

好的，谢谢啦

**Comment by Fxiao1** [comment]
> 用户文件夹里面的vnotex.json可以修改下面选项：
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/5763157/183006037-09a9e64c-a381-4828-8b88-43d67eefb82b.png">
> 
> 可以看到其实两者的图标大小是一致的。

默认的确实是18，但我觉得太小了，所以将能调整的调成23了，但是侧边栏这里没法调，所以就还是18。
我的意思是，有没有个地方可以一调整后所有地方的图标都能统一调整成用户设置的大小。 ^o^

**Comment by Fxiao1** [comment]
> 用户文件夹里面的vnotex.json可以修改下面选项：
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/5763157/183006037-09a9e64c-a381-4828-8b88-43d67eefb82b.png">
> 
> 可以看到其实两者的图标大小是一致的。

感谢，这样可以调整，已经将其设置成23了，感觉18太小了，哈哈
