### ISSUE TITLE
正则表达式全部替换时出错

### ISSUE THREAD

**Issue by jumbojing** [vnotex/vnote#2212]
**Describe the bug**
正则表达式,包括分组,全部替换时,出错...
> 原始文本👇🏻
![image](https://user-images.githubusercontent.com/10215735/184258535-9f79202c-cfb6-4d08-be6d-ae7412ebc1e4.png)

> Replace 成功 👇
![image](https://user-images.githubusercontent.com/10215735/184258268-654dc9ea-e76d-4d64-b717-cb54db8c4fad.png)

> Replace All 出错 👇
![image](https://user-images.githubusercontent.com/10215735/184258220-cf585a0b-2e66-4a99-b21f-63890661e334.png)

**Comment by jumbojing** [comment]
原文本:

> # test
> ### 在切片器环境中运行 Python 脚本文件[¶](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#run-a-python-script-file-in-the-slicer-environment "Permalink to this heading")
> 
> 在 Windows 上运行 Python 脚本（存储在脚本文件中），而不显示任何图形用户界面：
> 
> Slicer.exe --python-script "/full/path/to/myscript.py" --no-splash --no-main-window
> 
> 在 MacOS 上运行 Python 脚本（存储在脚本文件中），而不显示任何图形用户界面：
> 
> /Applications/Slicer.app/Contents/MacOS/Slicer --no-splash --no-main-window --python-script "/full/path/to/myscript.py"

这是正则表达式:Find: `^(#*? )` ; Replace All `> \1` .

**Comment by tamlok** [comment]
It should be a bug. Will fix it in next version! Thanks!

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/commit/5865519402b594b6672f5330509eeb2331038057
