### ISSUE TITLE
编辑模式和阅读模式的大代码块高亮显示不一致

### ISSUE THREAD

**Issue by cainb** [vnotex/vnote#2223]
如标题所示，两个模式下的代码块高亮渲染不一致。

> 而且编辑模式下的代码块高亮特别丑（~

示例：

编辑模式：

![image](https://user-images.githubusercontent.com/48700331/186471160-dad24958-8eae-4e39-9bda-f78f04477648.png)

阅读模式：

![image](https://user-images.githubusercontent.com/48700331/186471779-52359308-e423-422c-8364-099f994fb49b.png)

> ps: VNote 版本：3.9.0

**Comment by tamlok** [comment]
更新到最新版本

**Comment by cainb** [comment]
> 更新到最新版本

已更新，实测正常
