### ISSUE TITLE
设置项重复

### ISSUE THREAD

**Issue by cainb** [vnotex/vnote#2224]
设置里的 `行结尾` 设置项是否重复了？

> ps: VNote 版本：3.14.0

![image](https://user-images.githubusercontent.com/48700331/186491117-ec28490d-8ffb-43b1-a847-8a56bd632c1e.png)

![image](https://user-images.githubusercontent.com/48700331/186491176-ca7e80c2-0079-4391-a1a4-e7640c7ffa28.png)

**Comment by tamlok** [comment]
一个是配置文件的行为，一个是编辑器的行为
