### ISSUE TITLE
[建议]智能表格增加格式化源码相关处理

### ISSUE THREAD

**Issue by qiang-l** [vnotex/vnote#2227]
智能表格对应的源码部分看着太不美观了
建议增加一个类似Typora那种对表格格式化源码的处理

附当前智能表格对应的源代码：
```
| head1 |                 标题2                 |
| :-------: | :-----------------------------------: |
|    aaa    | 测试111111111111111 |
| 测试2  |                  bbbb                  |
```

typora格式化后的表格源码：
```
| head1 |        标题2        |
| :---: | :-----------------: |
|  aaa  | 测试111111111111111 |
| 测试2 |        bbbb         |
```

**Comment by tamlok** [comment]
现在不就有吗？

**Comment by qiang-l** [comment]
> 现在不就有吗？

没找到啊 在哪个位置

**Comment by tamlok** [comment]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/5763157/187060406-be7430ad-2370-4ed5-8e8d-576d77f30f61.png">

**Comment by qiang-l** [comment]
> <img alt="image" width="598" src="https://user-images.githubusercontent.com/5763157/187060406-be7430ad-2370-4ed5-8e8d-576d77f30f61.png">

重点在于md文件要使用纯文本程序查看
步骤
1.创建md文件 使用vnote打开
2.选择smart table模式 复制表格内容到vnote
3.使用另外的文本软件(如notepad)打开该md文件
4.使用Typora 重复1～3 在Typora中使用表格格式化源码
5.在notepad中比较2个md文件的内容 得到最开始我附上的2种结果

**Comment by tamlok** [comment]
不懂。。。在vnote里面编辑表格，vnote会实时调整表格格式。其他就不管了。

**Comment by qiang-l** [comment]
> 不懂。。。在vnote里面编辑表格，vnote会实时调整表格格式。其他就不管了。

但是vnote调整表格之后 再用notepad打开 内容排版就变得很差了
vnote调整表格格式的时候 能不能既调整好表格格式 又调整好实际的纯文本内容

**Comment by tamlok** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/5763157/187070935-de450656-3200-4d5a-bcc0-2a0999b49dce.png">

就是通过调整纯文本内容来调整的。

上面是notepad++的截图。

**Comment by qiang-l** [comment]
> <img alt="image" width="573" src="https://user-images.githubusercontent.com/5763157/187070935-de450656-3200-4d5a-bcc0-2a0999b49dce.png">
> 
> 就是通过调整纯文本内容来调整的。
> 
> 上面是notepad++的截图。
> 
> notepad的字体是不是和vnote的设置不一样，所以导致宽度不一样。vnote使用的是等宽字体。
> 
> 解决办法就是你看一下vnote的文档，修改主题里面的text-editor.theme里面的表格的字体。

是这个原因 系统为ubuntu20.04 可能是某些字体缺失 导致主题使用了非等宽字体
