### ISSUE TITLE
M1 mac适配

### ISSUE THREAD

**Issue by shuai06** [vnotex/vnote#2237]
M1 还没适配吗，催一下开发者啦~

**Comment by feloxx** [comment]
m1 可以直接装呀，Apple M1 Pro都配置流畅运行，一点不卡

**Comment by shuai06** [comment]
@feloxx 好的谢谢，我下载用几天试试，我是看还行显示的intel x86

**Comment by feloxx** [comment]
> @feloxx 好的谢谢，我下载用几天试试，我是看还行显示的intel x86

现在在m1里会用 苹果自带的兼容模式运行。我这边开发环境也是的，性能还凑合。

后续迭代到qt6，可以编译个arm架构的。

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/releases/download/continuous-build/VNote-3.17.0-mac-universal.dmg 求帮忙测试一下
