### ISSUE TITLE
content area is empty in view mode

### ISSUE THREAD

**Issue by ribezzz** [vnotex/vnote#2240]
**Describe the bug**
the content area is empty in view mode. Is visible only in edit mode

**To Reproduce**
1. Open a markdown page
2. the content area is empty in view mode

**Expected behavior**
the content of the markdown page should appears

**Screenshots**
![immagine](https://user-images.githubusercontent.com/67312083/190268919-4e700bfe-8013-4e04-8730-2c0e9b1ca058.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21 Cinnamon
 - Version 3.15.0

**Comment by tamlok** [comment]
add --no-sandbox arg

**Comment by ribezzz** [comment]
thank you for the tip
