### ISSUE TITLE
bug：在windows上频繁切换shift中文/英文输出后，会导致所有的全角中文字符固定为半角英文字符无法切换

### ISSUE THREAD

**Issue by pawx2** [vnotex/vnote#2241]
bug：在windows上频繁切换shift中文/英文输出后，会导致所有的全角中文字符固定为半角英文字符无法切换

**Comment by tamlok** [comment]
这个时候还能输入中文吗？用的是什么输入法？

**Comment by pawx2** [comment]
sorry：通过排查发现是微软输入法默认设置了使用`Ctrl + .`会切换中英文符号输入，造成这一问题的原因是输入法功能+误触热键，与VNote程序并不相关，其无这方面的bug存在。
