### ISSUE TITLE
程序闪退，无法打开了

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#2243]
**Describe the bug**
今早，第一天上班，启动vnote的时候，启动就闪退，重启系统后仍然闪退。
没有其他任何操作。

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] win10
 - Version 2.10

**Additional context**
在家办公时是笔记本电脑，只有一个显示器，桌面缩放尺寸125%；
公司办公时外接了一个显示器，但拔掉这个外接显示器也没用，仍然闪退。

log文件内容如下：

Info:(main.cpp:211) VNote started "2.10" "周四 9月 15 09:13:14 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周五 9月 16 08:27:12 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 08:32:58 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 09:53:46 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 09:53:56 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 09:56:40 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 09:56:58 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 10:02:43 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 10:03:40 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839
Info:(main.cpp:211) VNote started "2.10" "周一 9月 19 10:09:30 2022"
Info:(main.cpp:223) openGL 0
Info:(main.cpp:224) openSSL "OpenSSL 1.0.2t  10 Sep 2019" 268443839

**Comment by tamlok** [comment]
1. 试试去用户配置文件夹删除`session.json`然后启动看看？C:\Users\xxx\AppData\Roaming\vnote
2. 这时候如果不闪退，然后打开文件闪退，可以设置一下opengl的值，然后重启

**Comment by jackydi** [comment]
> 1. 试试去用户配置文件夹删除`session.json`然后启动看看？C:\Users\xxx\AppData\Roaming\vnote
> 2. 这时候如果不闪退，然后打开文件闪退，可以设置一下opengl的值，然后重启

升级到3.15了

**Comment by jackydi** [comment]
不过你的这个方法应该是有效的，刚刚启动2.10的时候，没闪退，只是提示笔记本不正确。

**Comment by jackydi** [comment]
不过感觉问题不出在这里，可能是哪个文件损坏了，刚刚打开2.10的时候，提示笔记本错误，关闭对话框后就闪退了。应该是文件损坏的原因，估计是哪个qt5***.dll

**Comment by tamlok** [comment]
笔记本错误的后看看是不是笔记本数据出错了？比如数据挪地方了。你删除session后，新建一个测试笔记本看看有没有闪退情况？

**Comment by tamlok** [comment]
不过升级了就好了😁

**Comment by tamlok** [comment]
如果是dll损坏，可以重新下载解压的，release里面有历史版本。

**Comment by jackydi** [comment]
谢谢，覆盖2.10后，可以正常打开了，不过数据已经升到了版本3，就不回退了。慢慢适应一下吧
