### ISSUE TITLE
Feature Request: Auto formatting markdown tables

### ISSUE THREAD

**Issue by dwu** [vnotex/vnote#225]
VNote renders markdown tables perfectly, however it currently lacks the feature of auto formatting a table's textual markdown representation.

Table auto formatting is a common feature in many markdown editors, e.g. Emacs' markdown-mode or the :TableFormat command in vim-markdown. It simplifies table editing and helps keeping notes with tables easily readable when looking at their markdown representation.

Here's an example of the expected behavior. Using table auto format converts the input

```
| foo | baaaaar | baaaz |
|-|-|-|
| asdf | asdf | asdf |
```

to

```
| foo  | baaaaar | baaaz |
|------|---------|-------|
| asdf | asdf    | asdf  |
```

Looking at other markdown editors there seem to be two common ways to trigger table auto format:

* a command executed manually by the user while the cursor is inside the table or the table is selected (e.g. the aforementioned `:TableFormat` command in vim-markdown)

* the editor being "table-aware" with support for navigating between the cells of a table via `TAB` and `RETURN` and trigging auto format automatically on a cell navigation operation (e.g. Emacs' markdown mode)

**Comment by Symbian9** [comment]
@dwu and @tamlok, today I also think: "Why there no tables creating features in VNote yet?" and after little search on Github found this tool:

- https://github.com/ozh/ascii-tables

Maybe, it's possible add such plug-in into VNote directly?

It has online demonstration website too:

- https://ozh.github.io/ascii-tables/

![ASCII Tables](http://i.imgur.com/0e7713a.png)

**Comment by tamlok** [comment]
It is supported already in VNote 2.0 and will be migrated to 3.0 soon.
