### ISSUE TITLE
菜单按钮不好用

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#2250]
**Describe the bug**
编辑模式下，选择一行文本，然后点菜单栏的加粗、斜体、删除线等都不好用。

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version 3.15

下图框起来的按钮都不好用。

![image](https://user-images.githubusercontent.com/50565266/191391206-bf5df3cd-3f4d-4c0b-9362-0fe443331e1a.png)

**Comment by jackydi** [comment]
怎么回事？那会儿打死都不好用，刚刚看了一下快捷键配置，啥也没改，突然就好用了。

**Comment by jackydi** [comment]
看来这个问题还不是选择文本长短的问题，重新测试，发现有时短的文本也不行，就一个字都不行。

**Comment by jackydi** [comment]
> opengl设置试试？

不好用，几个模式都设置了，全都不好用

**Comment by jackydi** [comment]
> opengl设置试试？

刚刚又发现个新现象，还在之前的文档里，这儿文档比较长，连图片带文本，差不多800多行。

我在前面的部分都不能操作按钮，在后面就可以。

![image](https://user-images.githubusercontent.com/50565266/191452705-2b79228d-d937-4860-b5dd-3fc7fccafc48.png)

![按钮不好用1](https://user-images.githubusercontent.com/50565266/191453223-8084184a-22ea-42dc-befd-d462aceef255.gif)

**Comment by jackydi** [comment]
这个文档里更过分，相差一行都不能用。

![按钮不好用2](https://user-images.githubusercontent.com/50565266/191680795-37754ddb-4395-4b42-81f0-4067d69ef3a3.gif)

**Comment by tamlok** [comment]
能把上面这个文档发给我看一下嘛？tamlokveer at gmail.com

**Comment by jackydi** [comment]
> tamlokveer

已发送，请查收

**Comment by tamlok** [comment]
修复了，居然是一个低级错误造成的影响很严重的bug，bug会造成一般只有靠后面的位置才能生效，前面的基本不会生效。

https://github.com/vnotex/vnote/commit/749c4006a2b4a7cae154390589991d7e5cbc4ef9

**Comment by StarLeet** [comment]
> 修复了，居然是一个低级错误造成的影响很严重的bug，bug会造成一般只有靠后面的位置才能生效，前面的基本不会生效。
> 
> https://github.com/vnotex/vnote/commit/749c4006a2b4a7cae154390589991d7e5cbc4ef9

这个问题我在二月份的时候就反馈过了😂，当时你还问的我内容哪来的，我说是从网页博客里摘录的，后面你解释说是含不可见字符导致的，我还特意写代码挨个查了字符😂，我当时怎么也没想明白怎么回事，后面靠快捷插入，用着用着也就习惯了

**Comment by tamlok** [comment]
大意了
