### ISSUE TITLE
插入行内公式快捷键出错

### ISSUE THREAD

**Issue by yuralandau** [vnotex/vnote#2255]
**Describe the bug**
插入行内公式使用快捷键ctrl+.时出错，但是按钮正常，插入其他的快捷键也正常。
但是当我按住ctrl+G此时不松开，连续点两次.键，可以插入行内公式。

**To Reproduce**
如简介

**Expected behavior**
按ctrl+.插入行内公式

**Desktop (please complete the following information):**
版本	Windows 11 家庭中文版
版本	21H2

**Additional context**

**Comment by tamlok** [comment]
请参考文档更换快捷键

**Comment by haigear** [comment]
win11,行内公式插入，按照文档更换快捷键，快捷键不灵，更换前也不灵。

**Comment by haigear** [comment]
前面是alt+F，不行，更改为Ctrl+M，重新启动后生效了。

**Comment by yuralandau** [comment]
我找了qq啊微信啊所有的快捷键冲突, 最后才发现 ctrl+. 是被微软输入法占了.
