### ISSUE TITLE
目录排序有BUG?

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#2258]
**Describe the bug**
按照名称排序的规则时啥样的？我的理解是英文按照字母顺序排序，中文按照汉字的拼音排序，但实际上却不是这样的。

![2022-09-27_15-19-32](https://user-images.githubusercontent.com/50565266/192461406-2023ac54-03a6-4d56-a1bf-96e9f0f53d76.png)

 - OS: win10
 - Version 3.15.2

**Comment by StarLeet** [comment]
你学C++不知道这个吗……代码里面哪有什么拼音，不都是Unicode码

**Comment by jackydi** [comment]
> 你学C++不知道这个吗……代码里面哪有什么拼音，不都是Unicode码

好吧，你是老大，你说了算。

不过我在window文件管理器中按照名称排序的时候，英文是按照字母顺序，中文是按照拼音顺序排序的，我还是习惯这种方式。

**Comment by tamlok** [comment]
暂时还做不到按照拼音这么智能

**Comment by jackydi** [comment]
> 暂时还做不到按照拼音这么智能

好的，期待3.x中添加这个功能，我记得2.x中好像是可以的，也可能是我记错了。
