### ISSUE TITLE
最新版本的快捷键问题

### ISSUE THREAD

**Issue by p4hi** [vnotex/vnote#2262]
win10、3.15.0版本，大纲的快捷键ctrl+G,2有时候不生效，非要先使用ctrl+alt+f进入搜索的时候再使用快捷键ctrl+G,2才能进入大纲，或者快捷键ctrl+G,1进入导航。

**Comment by tamlok** [comment]
大纲是`Ctrl+G, U`?

**Comment by p4hi** [comment]
是在左侧的大纲，不是右上的大纲

**Comment by tamlok** [comment]
那个是`Ctrl+G, A`?

**Comment by p4hi** [comment]
现在正常了，之前用的2版本，直接运行的3版本。重新把c盘的vnote的配置文件都清空了，现在`Ctrl+G, U`是右侧的大纲了。
有个2个新问题，`Ctrl+G, U`打开大纲，但不像v2大版本一样再使用`Ctrl+G, U`可以关闭大纲。
还有就是片段的快捷键00、01、02那些是什么，怎么使用

**Comment by tamlok** [comment]
设计的就是激活面板，没有关闭的功能。
