### ISSUE TITLE
从剪贴板插入能否添加快捷键？

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#2263]
每次选择一个目录链接后，我想使用文本的方式插入到文档里，总需要先Ctrl-v，然后再按几下下箭头才行，能否给这些选项做个快捷键？这样可以一次性用某个格式插入到文档里。

![image](https://user-images.githubusercontent.com/50565266/192761171-96ea057d-7777-4172-825e-3d2023cb8204.png)

**Comment by tamlok** [comment]
直接按前面的字母即可

设置里面可以设置默认纯文本粘贴

ctrl-shift-v 纯文本粘贴

**Comment by jackydi** [comment]
前面的图标里还有字母啊，你不说我还没注意到，一直在文本的后面找，没想到放在前面的图标里了。
