### ISSUE TITLE
高亮背景颜色是否可以更改

### ISSUE THREAD

**Issue by mousexiaoyao2** [vnotex/vnote#2266]
请问mark标签的默认黄色背景可以更改吗，需要用不同颜色来高亮不同类型的内容。现在我能找到的办法就是在mark标签加入style属性来修改，但是要高亮的内容多了就十分麻烦。请问现在vnote支持更改颜色吗，或者支持自定义自己的标签吗，谢谢

**Comment by tamlok** [comment]
`mark`是一个内置标记，颜色什么的都是都过css样式表指定的。如果你不需要兼容性，应该可以自定义自己的任意标签，然后在css里面添加对应的颜色，类似`redmark`, `bluemark`等等。
