### ISSUE TITLE
[功能求助] 请问可以对编辑模式下，纯编辑和预览模式的辅助编辑添加一个快捷键吗

### ISSUE THREAD

**Issue by xh542428798** [vnotex/vnote#2269]
希望能加这个快捷键
![b9930c41d1581a86ebc01c1a05e7fd8](https://user-images.githubusercontent.com/49368033/194447935-88d8ca05-0eed-4d98-9be6-6176477f1281.jpg)

**Comment by feloxx** [comment]
最新版 cmd+g，v

**Comment by xh542428798** [comment]
> 最新版 cmd+g，v

感谢！
