### ISSUE TITLE
公式 align* 出错

### ISSUE THREAD

**Issue by yuralandau** [vnotex/vnote#2271]
**Describe the bug**
多行公式在编辑器编辑状态时, 可以正常显示. 但是在阅读状态下, 无法加载出来. 测试了一下导出也不正常.
另外地, 把公式放在一个短文章里, 正常显示了.

**To Reproduce**

出错的公式:
```
$$
\begin{align*}
\cot{\Theta_{max}} &= \frac{V^2-v^2_0+V^2v^2_0\frac{V^2-v_0^2}{V^2v_0^2}}{2Vv\sqrt{1-V^2}\sqrt{\frac{V^2-v_0^2}{V^2v_0^2}}} \\

&= \frac{2(V^2-v^2_0)}{2\sqrt{1-V^2}\sqrt{(V^2-v^2_0)}} \\

&= \frac{\sqrt{V^2-v^2_0}}{\sqrt{1-V^2}}\\

\frac{\cos\Theta_{max}}{\sin\Theta_{max}}&=\sqrt{\frac{V^2-v^2_0}{1-V^2}} \\

\cos^2{\Theta_{max}} &= \frac{V^2-v^2_0}{1-V^2}\sin^2\Theta_{max}\\

1-\sin^2\Theta_{max} &= \frac{V^2-v^2_0}{1-V^2}\sin^2\Theta_{max}\\

1 &= \frac{1-v^2_0}{1-V^2}\sin^2\Theta_{max}\\

\sin\Theta_{max} &= \sqrt{\frac{1-v^2_0}{1-V^2}} \\

\Theta_{max} &= \arcsin\sqrt{\frac{1-v^2_0}{1-V^2}} \tag{8}
\end{align*}
$$
```

**Expected behavior**
正常显示, 正常导出

**Screenshots**
![image](https://user-images.githubusercontent.com/46567201/194735200-cc7830a7-834d-410e-aa2a-ed55d453b49c.png)
1. 在编辑中正常显示的公式

![image](https://user-images.githubusercontent.com/46567201/194735259-1989dadd-7235-47d1-969c-f67ffc1a7840.png)
2. 在阅读中错误显示的公式

![image](https://user-images.githubusercontent.com/46567201/194735297-3917ac3a-424d-400b-be0c-5f827ab26267.png)
3 在短文章正确显示的公式

**Desktop (please complete the following information):**
win11

**Additional context**

**Comment by tamlok** [comment]
第一个$$之前多加一个空行

**Comment by yuralandau** [comment]
> 第一个$$之前多加一个空行

并没有多加空格. 如有必要我可以提供原始的.md文件.

**Comment by tamlok** [comment]
> > 第一个$$之前多加一个空行
> 
> 并没有多加空格. 如有必要我可以提供原始的.md文件.

我是说你应该要在第一个$$前面多加一个空行再试试

**Comment by yuralandau** [comment]
> > > 第一个$$之前多加一个空行
> > 
> > 
> > 并没有多加空格. 如有必要我可以提供原始的.md文件.
> 
> 我是说你应该要在第一个$$前面多加一个空行再试试

那样的话, 编辑状态里的公式也无法显示. 阅读状态里仍然无法正常显示.

![image](https://user-images.githubusercontent.com/46567201/194735859-3aa85778-e78d-45c0-9364-a5f34487f4a1.png)
![image](https://user-images.githubusercontent.com/46567201/194735896-39e74624-44f2-4cc8-95b9-53b22ee94a45.png)

**Comment by tamlok** [comment]
你这里没加空行呀

```
abc

$$
abc
$$

def
```

**Comment by yuralandau** [comment]
> 你这里没加空行呀

抱歉我的错误. 我刚刚看成" 空格" 了. 问题已解决.
说真的, 你们的软件是我见过支持最好用的markdown了.
