### ISSUE TITLE
文档改名后会自动关闭？

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#2280]
**Describe the bug**
打开一个文档的时候，如果修改它的名称，这个文档会被自动关闭，不知道就是这么设计的，还是一个bug？2.x下是不用关闭文档就能改名的。

**Comment by tamlok** [comment]
目前为了简单省事，是这样设计的。

**Comment by jackydi** [comment]
> 目前为了简单省事，是这样设计的。

好的，谢谢回复。
