### ISSUE TITLE
Disable View

### ISSUE THREAD

**Issue by it19862** [vnotex/vnote#2282]
**Current status.**
I open the note.
The Note program opens the note editor and view the note
![18 10 2022_15-25-13](https://user-images.githubusercontent.com/18245828/196429293-5b4b0b93-68d1-4820-b3c3-1d18a3cea6ea.png)

**Expectations.**
I open the note.
The Note program opens only the note editor.
![18 10 2022_15-25-14](https://user-images.githubusercontent.com/18245828/196429578-fbb5594d-ea78-40d3-8166-54eca490ba49.png)

**Comment by tamlok** [comment]
check the tool button of the editor one by one. there is one viewmode button.
