### ISSUE TITLE
自动删除图片

### ISSUE THREAD

**Issue by StarLeet** [vnotex/vnote#2283]
印象中，我使用2月份的版本的时候，vnote检测到笔记中没有路径引用图片时，会提示删除图片文件夹里的图片，以节约空间。但是好像最近使用3.10+版本以来，这个提示就再也没有出现过。我还特意做了一个不严苛的测试，事实证明确实没有这个提示了。设置里是勾了清除无用图片的。这个功能有什么触发条件吗？

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.10+]

**Comment by tamlok** [comment]
你试试粘贴插入一个图片到笔记，保存，然后删除图片，保存。

**Comment by Primokorn** [comment]
Hello,
As far as I understand I have the same issue. I have VNote 3.15.1 on Win10.
I didn't notice from which version this feature stopped working.

**Comment by StarLeet** [comment]
> Hello, As far as I understand I have the same issue. I have VNote 3.15.1 on Win10. I didn't notice from which version this feature stopped working.

![demo](https://user-images.githubusercontent.com/89691566/196623629-34162cc2-fe51-4340-8896-ecd346f18d64.gif)
After testing, it seems  no problem. But there is no notification

**Comment by StarLeet** [comment]
> 你试试粘贴插入一个图片到笔记，保存，然后删除图片，保存。

我新建了一个空白笔记本,按照你说的测试了一下,确实是在运行.只不过没有那个让你点确认的通知提示了.这个功能会被什么操作影响吗?比如说,如果我在几个笔记中引用这张图片.过了一段时间后,我将笔记中的引用逐一删除,最终,这张图片变成了无用图片,那么这种情况,图片也会被vnote清理吗?

**Comment by tamlok** [comment]
Hi,

## How to detect obsolete images?
When opening a note, VNote will parse the contents to fetch all referenced local images. "Local" means images locate in relative folder. When inserting a new image, VNote will record it as a referenced image, too. When closing the note, VNote will now parse the saved contents again to fetch all referenced local images. Compared to the previous images, we can detect the obsolete images.

## Why no notification?
Change the `false` to `true' in the user configuration file.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/5763157/196631112-36fa9b5f-79f5-4da2-9b81-77703ca60768.png">

**Comment by StarLeet** [comment]
> Hi,
> 
> ## How to detect obsolete images?
> When opening a note, VNote will parse the contents to fetch all referenced local images. "Local" means images locate in relative folder. When inserting a new image, VNote will record it as a referenced image, too. When closing the note, VNote will now parse the saved contents again to fetch all referenced local images. Compared to the previous images, we can detect the obsolete images.
> 
> The obsolete is scoped in one single note. Please do not share the same image among several notes.
> 
> ## Why no notification?
> Change the `false` to `true` in the user configuration file.
> 
> <img alt="image" width="295" src="https://user-images.githubusercontent.com/5763157/196631112-36fa9b5f-79f5-4da2-9b81-77703ca60768.png">

i see , thanks for replying

**Comment by StarLeet** [comment]
> Hi,
> 
> ## How to detect obsolete images?
> When opening a note, VNote will parse the contents to fetch all referenced local images. "Local" means images locate in relative folder. When inserting a new image, VNote will record it as a referenced image, too. When closing the note, VNote will now parse the saved contents again to fetch all referenced local images. Compared to the previous images, we can detect the obsolete images.
> 
> The obsolete is scoped in one single note. Please do not share the same image among several notes.
> 
> ## Why no notification?
> Change the `false` to `true` in the user configuration file.
> 
> <img alt="image" width="295" src="https://user-images.githubusercontent.com/5763157/196631112-36fa9b5f-79f5-4da2-9b81-77703ca60768.png">

So there may be a situation, a notebook's images folder may contain multiple identical pictures, but they are named differently, right?

**Comment by tamlok** [comment]
> > Hi,
> > ## How to detect obsolete images?
> > When opening a note, VNote will parse the contents to fetch all referenced local images. "Local" means images locate in relative folder. When inserting a new image, VNote will record it as a referenced image, too. When closing the note, VNote will now parse the saved contents again to fetch all referenced local images. Compared to the previous images, we can detect the obsolete images.
> > The obsolete is scoped in one single note. Please do not share the same image among several notes.
> > ## Why no notification?
> > Change the `false` to `true` in the user configuration file.
> > <img alt="image" width="295" src="https://user-images.githubusercontent.com/5763157/196631112-36fa9b5f-79f5-4da2-9b81-77703ca60768.png">
> 
> So there may be a situation, a notebook's images folder may contain multiple identical pictures, but they are named differently, right?

Yes! Detecting image reference across notes globally may cost too much, as we do not have a strong central controlled DB.
