### ISSUE TITLE
笔记导出后再次导入出现目录紊乱

### ISSUE THREAD

**Issue by Print1n** [vnotex/vnote#2285]
1. 使用macOS导出笔记，正常笔记目录见下图
![1](https://user-images.githubusercontent.com/73928418/197395049-bebdccb7-21f9-4eff-a78a-33a439a73764.jpg)

2. 使用windows相同版本3.15.1导入文件夹功能，生成的笔记目录见下图
![2](https://user-images.githubusercontent.com/73928418/197395086-bd766d71-da53-4d40-86f0-ba0777deb7b7.jpg)

新生成的目录会以文件的名字再次生成一个文件夹名字

**Comment by tamlok** [comment]
导入和导出不是这样用的。同一个笔记本直接打开即可，不用重新导入。导入是指导入外部文件。

**Comment by Print1n** [comment]
感谢，问题已解决
