### ISSUE TITLE
将3.12.888版本压缩后换到新的机器上，程序一直闪退。

### ISSUE THREAD

**Issue by 231599447** [vnotex/vnote#2289]
由于换了一台新电脑，我将VNote3.12.888和笔记本文件夹，同时压缩到一个rar中，转移到了新的电脑上。
然后Vnote在新电脑上每隔10分钟左右就会闪退。。
我更换了最新的版本Vnote3.15.1 仍然有这个问题。
两台电脑都是windows10的版本。。我删除了 vnotex.json 仍然不行。

日志好像也并未有异常。。就好像程序被强制停止了。。
`
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default
Info:(main.cpp:144) "VNote (v3.15.1) started at 周四 11月 3 10:52:37 2022 (windows)"
Info:(main.cpp:149) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1j  16 Feb 2021"
Warning:(main.cpp:153) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:209) locale: "zh_CN"
Info:(thememgr.cpp:98) using theme "pure"
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default
Info:(main.cpp:139) "VNote (v3.12.888) started at 周四 11月 3 10:58:54 2022 (windows)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1j  16 Feb 2021"
Warning:(main.cpp:148) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:91) using theme "pure"
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default
Info:(main.cpp:139) "VNote (v3.12.888) started at 周四 11月 3 11:07:17 2022 (windows)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1j  16 Feb 2021"
Warning:(main.cpp:148) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:91) using theme "pure"
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default

`

**Comment by tamlok** [comment]
你尝试把用户配置文件夹和默认配置文件夹都删除，然后启动新解压的vnote，先不要打开原来的笔记本，然后新建一个笔记本，看看10分钟左右会不会有问题。

**Comment by 231599447** [comment]
我删除了以下两个文件夹：
C:\Users\***\AppData\Local\VNote
C:\Users\***\AppData\Roaming\VNote

然后重新下载使用了Vnote3.14.0，新建笔记本，新建笔记，然后停留在Vnote界面，5分钟后Vnote闪退。
很像是进程突然就被杀掉了。

Info:(main.cpp:139) "VNote (v3.14.0) started at 周四 11月 3 14:16:15 2022 (windows)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1j  16 Feb 2021"
Warning:(main.cpp:148) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:98) using theme "pure"
Warning:(:0) No language dictionaries for the language: "zh_CN" trying to load en_US as default
Info:(main.cpp:139) "VNote (v3.14.0) started at 周四 11月 3 14:23:02 2022 (windows)"
Info:(main.cpp:144) OpenSSL build version: "OpenSSL 1.1.1g  21 Apr 2020" link version: "OpenSSL 1.1.1j  16 Feb 2021"
Warning:(main.cpp:148) versions of the built and linked OpenSSL mismatch, network may not work
Info:(main.cpp:204) locale: "zh_CN"
Info:(thememgr.cpp:98) using theme "pure"

**Comment by 231599447** [comment]
观察了一段时间 基本稳定在5分钟左右 闪退。

**Comment by tamlok** [comment]
那是有什么杀毒软件之类的吗？

**Comment by 231599447** [comment]
公司杀毒软件都是一样的。。其他同事都被我安利了VNote，都没有问题。。。我也是今天换了一台新电脑才出现问题。。也是很奇怪。。

**Comment by tamlok** [comment]
那试试打开vnote后，什么都不操作呢？

闪退后去windows事件里面看看有没有什么原因？

**Comment by 231599447** [comment]
打开vnote什么都不操作，也会闪退。
windows事件，有看到这个。。
![image](https://user-images.githubusercontent.com/3711440/199680010-42fcf92c-853f-4d2d-85c4-611366c2a865.png)
![image](https://user-images.githubusercontent.com/3711440/199680095-6e4a985d-2700-4707-877e-818a40909bd9.png)

**Comment by tamlok** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/app-crash-with-ntdlldll/9aa59f80-99a1-4f3c-b2f0-7eb72df05b2a

**Comment by 231599447** [comment]
链接上的方法不能解决问题，我下载了3.11.0的版本，可以正常使用。。

我也在微软提出了求助：
https://answers.microsoft.com/zh-hans/windows/forum/windows_10-hardware/ntdlldll%e5%af%bc%e8%87%b4%e5%ba%94%e7%94%a8/3cb9b2b6-bb11-48e3-bd8a-da84bb978eeb

**Comment by tamlok** [comment]
你也可以试试x86的版本看看？

**Comment by 231599447** [comment]
x86的版本 依然不行。。我先用3.11.0的版本吧。。
