### ISSUE TITLE
vnote打开html文件的优化

### ISSUE THREAD

**Issue by StarLeet** [vnotex/vnote#2291]
我最近在做有关git的笔记，为了方便参照，我下载了git官方文档的html(大概19.3MB)，同样地，我也下载了电子书版本和pdf版。

点击电子书版本和pdf版本会用默认程序打开，但是当点击html文件时，vnote就卡死住了(100%发生)。

开发者是否能对这种情况做出优化？比如对html文件先进行评估(可以是内容，也可以是大小)再决定是否在vnote内打开从而避免卡死现象发生。

环境： win10 2022 LTSC
版本：3.15.1 (记不清了，反正是目前最新版)

**Comment by tamlok** [comment]
暂时可以在设置里面设置文件关联

**Comment by StarLeet** [comment]
> 暂时可以在设置里面设置文件关联

搞定了。这样确实可以绕路子解决了😃，而且非常灵活。

我个人的建议是，在打开前对文件进行研判，对于可能会导致vnote卡慢或者卡死的内容，提示"文件过大，无法预览"之类的告示，避免直接地卡死，这样体验有点糟糕😂。在上一次有过这样体验的时候还是设置里查看日志的时候，不过现在修复了。
