### ISSUE TITLE
删掉的笔记还在历史记录里面这个应该删除

### ISSUE THREAD

**Issue by zhuhaisto** [vnotex/vnote#2293]
![V6DQ78T$~NJKQ_D(0M`Y$ 6](https://user-images.githubusercontent.com/108032980/201563651-e39ac168-6a02-4060-bc36-6e98888355e2.png)
比如像这样的 有些笔记明明都已经删除了 还是在历史记录里面 点击的时候
1. 打不开 
2. 也没反应 
 
我记得有些笔记软件都没有目录的 只有历史记录和标签来组织的。而且很多时候我们看笔记就看最近记录 就处理 修改迭代最近的笔记记录和感想，所以建议优化这个最近记录的逻辑
1. 删掉的笔记是不应该在历史记录里
2. 假设我新建笔记 随便选择了个目录 但我修整好内容后 我可能就会把它剪接到其他目录里面去 这个时候剪接过去 应该就把这个文件也要加入到历史记录 这样才好

总之就是这样的

**Comment by feloxx** [comment]
arrange

**Comment by feloxx** [comment]
#2297
