### ISSUE TITLE
markdown preview is blank

### ISSUE THREAD

**Issue by laur89** [vnotex/vnote#2295]
**Describe the bug**
Markdown preview does not render - it's just blank. It's case for both `in-place preview` and full review (the mode accessed via `ctrl+T`).

**To Reproduce**
1. write some valid markdown
2. Click on `in-place preview` OR press `Ctrl+T`
3. See nothing rendered

**Expected behavior**
Rendered markdown preview

**Screenshots**
![image](https://user-images.githubusercontent.com/4551018/203639152-374c41c8-0321-4d59-bfd0-861bef47b3e9.png)

**Desktop (please complete the following information):**
 - OS: debian testing
 - VNote 3.15.0

**Comment by tamlok** [comment]
use 3.15.1 please

**Comment by laur89** [comment]
Ah didn't realize new release was out.
Is binary zip no longer provided for linux x64?

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/releases/tag/v3.15.1

**Comment by tamlok** [comment]
> zips are provided only for win, linux only has an Appimage there. Compare that to 3.15.0 release that included https://github.com/vnotex/vnote/releases/download/v3.15.0/vnote-linux-x64_v3.15.0.zip

We unwrap the zip in 3.15.1.

**Comment by laur89** [comment]
Ah so the binary in zip in prior releases was really an appimage as well?
