### ISSUE TITLE
更改侧边栏 "片段" 中 "显示内建片段" 选项默认值

### ISSUE THREAD

**Issue by Shiina18** [vnotex/vnote#2296]
窗口 -> 片段 (侧边栏) -> 显示内建片段
可以取消勾选 (即不显示内建片段), 但是 VNote 重启后会恢复到默认的勾选状态
希望用户取消勾选后, VNote 能保存这个设置

**Comment by feloxx** [comment]
arrange

**Comment by feloxx** [comment]
#2300
