### ISSUE TITLE
无法重置主窗口布局

### ISSUE THREAD

**Issue by sswwa11** [vnotex/vnote#2302]
关闭一些窗口后，无法重置主窗口布局到最原初的样子

**Comment by tamlok** [comment]
右上角重置布局：

<img width="507" alt="image" src="https://user-images.githubusercontent.com/5763157/204678088-dbd9d728-7edd-44c3-80dc-2ec0dd6d1d2e.png">

**Comment by tamlok** [comment]
或者右上角窗口
<img width="478" alt="image" src="https://user-images.githubusercontent.com/5763157/204678129-8f3a445b-63b5-4020-bbff-e7f1a707a007.png">
