### ISSUE TITLE
有没有可能出实时渲染功能和高亮功能

### ISSUE THREAD

**Issue by Eyxxxxx** [vnotex/vnote#2306]
实时渲染就是指编辑窗口和预览窗口不分开的那种。
高亮功能：希望利用语法`==内容==`  对内容进行高亮黄。

**Comment by tamlok** [comment]
* 目前VNote提供原地预览的方式，编辑器工具栏左边的“查看模式”里面可以选择；
* 这个目前是通过`<mark>`来实现的，主要是为了便携性；后面会考虑加入作为可选语法。

**Comment by tamlok** [comment]
这个对于cpp实现太费力不讨好了，暂时不会推出。
