### ISSUE TITLE
After an emergency shutdown of the computer, Notebooks disappeared

### ISSUE THREAD

**Issue by it19862** [vnotex/vnote#2310]
After an emergency shutdown of the computer, Notebooks disappeared

The computer shut down in an emergency.
I'm launching VNote.
I can't see my Notebooks.

The number of my Notebooks is 10 pieces.
To add them to VNote, I need to register its path to each Notebook in VNote.
It's difficult.

And if the number of Notebooks is 20, 30, 50, 100 pieces?
Do I need to register a path in VNote for 100 pieces of Notebooks?
Or is it possible to add a list of paths to Notebooks to the VNote configuration file so that VNote connects multiple Notebooks?
Is there a configuration file where you can add paths to Notebooks as a list?

**Question:** What program can I use that can work with the Notebooks that VNote creates?
I have a lot of work to do. I would not like to stop because of the breakdown of VNote.

**Is used:**
	Windows	- 10
	VNote	- 3.15.1

![15 12 2022_08-56-35](https://user-images.githubusercontent.com/18245828/207815087-1e2e351d-2252-436e-b139-b619262584c4.png)

---

**I'm trying to solve the problem:**
	- Add an existing Notebook - VNote adds an existing Notebook;
![15 12 2022_11-56-20](https://user-images.githubusercontent.com/18245828/207816711-81acf6c3-660c-4aa8-9556-e4dedd74fb17.png)

- Create a new Notebook - VNote creates a new Notebook.
![15 12 2022_11-56-25](https://user-images.githubusercontent.com/18245828/207816731-6cefefad-f4d5-41e7-b958-f1b039cbb684.png)

---

**But there were problems:**
	- VNote does not switch between Notebooks.
	- VNote does not navigate through Notebook folders.
	- VNote does not open md file Notebook.

I was restarting the computer - it didn't solve my problem.
I was rebooting the program - it didn't solve my problem.
I downloaded VNote-3.15.1 again to a separate folder, opened it - it didn't solve my problem.

---
**The logic of changing a Notebook (switching between Notebooks).**
- VNote displays the current notebook - Notebook-1 
- The user went to the Notebooks list;
- The user has selected Notebook-2 to go to;
- VNote did not switch to the selected Notebook-2;
- The user has rebooted VNote;
- VNote displays Notebook-2 as the current notebook;

---
**List of all problems:**
1. How do I add an existing Notebook to VNote?
2. VNote does not switch between Notebooks.
3. VNote does not switch between folders and Note open Notebook.
If you click on folders and Note, then VNote does not navigate through folders, but displays the name of the Note.
4. VNote does not open md files.
3. The interface is broken.
Everything is mixed up.
The window splitter is not working.

I have been working with VNote-3.15.1 for several months. I liked everything.
I am an experienced computer user.

---

<details>
      <summary id="foto_1" ><b>GIF. The main problems. Expand</b></summary>
        <img src="https://user-images.githubusercontent.com/18245828/207810348-91c38556-d560-4694-9d27-7de76677bb7c.gif ">
</details>

--- 

<details>
      <summary id="foto_2" ><b>GIF. VNote does not open files and folders, but displays the names in the title of the program VNote. Expand</b></summary>
        <img src="https://user-images.githubusercontent.com/18245828/207810996-fbcfe342-eab1-4948-b8ff-cae04db5c33a.gif">
</details>

<details>
      <summary id="foto_2" ><b>Picture. VNote does not open files and folders, but displays the names in the title of the program VNote. Expand</b></summary>
        <img src="https://user-images.githubusercontent.com/18245828/207811833-cef588d7-1ac4-4594-b2f9-2a620af17c22.png">
        <img src="https://user-images.githubusercontent.com/18245828/207811839-89df43fc-4e0c-4087-bcdb-72c044492e2d.png">
</details>

--- 

<details>
      <summary id="foto_2" ><b>GIF. Changing folders only after restarting VNote. Expand</b></summary>
        <img src="https://user-images.githubusercontent.com/18245828/207812108-674b07d1-3416-49c2-92fb-eaab3fec87be.gif">
</details>

<details>
      <summary id="foto_2" ><b>Picture. Changing folders only after restarting VNote. Expand</b></summary>
        <img src="https://user-images.githubusercontent.com/18245828/207814573-b0f414e0-e7a7-4c8a-a21e-9f1e0e06d779.png">
        <img src="https://user-images.githubusercontent.com/18245828/207814577-51259c10-798e-4f86-91f1-c0fec41e6889.png">
        <img src="https://user-images.githubusercontent.com/18245828/207814578-c3c44d92-a2af-4756-b18f-7d214a02430c.png">
        <img src="https://user-images.githubusercontent.com/18245828/207814585-964028db-2d42-48ac-8af3-4ec7610c0e12.png">
</details>

---
**Update-1**
I closed, opened Vote, the interface became normal.
Other problems remained
![15 12 2022_11-54-54](https://user-images.githubusercontent.com/18245828/207815737-ed6213b5-e979-40bf-b353-193b6455b594.png)

---

**Update-2**
**Decision. Result: It didn't help.**
**Completed.**
- made a copy C:\Users\Root\AppData\Local\VNote\VNote
- copied all files from C:\Users\Root\AppData\Roaming\VNote\VNote in C:\Users\Root\AppData\Local\VNote\VNote
- rebooted VNote.

Result: It didn't help.

Folder C:\Users\Root\AppData\Local\VNote\VNote restored to the previous state.

**Comment by tamlok** [comment]
Hi,

There is a session file named `session.json` and there is a section `notebooks` to keep track of all the notebooks.

Please delete `C:\Users\Root\AppData\Local\VNote\VNote` and `C:\Users\Root\AppData\Roaming\VNote\VNote in C:\Users\Root\AppData\Local\VNote\VNote` and restart VNote. Then try to create two **NEW** blank notebooks and try whether it can switch between these two notebooks.

If fine, then open your notebooks again and check. Otherwise, please check the OPENGL option in the Settings page.

**Comment by it19862** [comment]
@tamlok 

**Problem-1. The problem is solved.**
I used:
- Settings -> General -> OpenGL = OpenGL ES.
	

**Note.** 
I used:
OpenGL = None - it didn't work;
 OpenGL = Desktop - it didn't work;
 OpenGL = OpenGL ES - it helped.
 
Previously, this computer had `OpenGL = None` and everything worked.
The other computer also has `OpenGL = None` installed and everything works.
	

**Problem-2. In the process of solving.**
How do I add an existing Notebook?
Should I use the menu: Notebook-> Open Other Notebooks?

![16 12 2022_07-54-30](https://user-images.githubusercontent.com/18245828/208025475-4a8ae68d-8a1e-413d-8672-7c4a86440182.png)

**Comment by tamlok** [comment]
> @tamlok
> 
> **Problem-1. The problem is solved.** I used:
> 
> * Settings -> General -> OpenGL = OpenGL ES.
> 
> **Note.** I used: OpenGL = None - it didn't work; OpenGL = Desktop - it didn't work; OpenGL = OpenGL ES - it helped.
> 
> Previously, this computer had `OpenGL = None` and everything worked. The other computer also has `OpenGL = None` installed and everything works.
> 
> **Problem-2. In the process of solving.** How do I add an existing Notebook? Should I use the menu: Notebook-> Open Other Notebooks?

Yes.


> 
> ![16 12 2022_07-54-30](https://user-images.githubusercontent.com/18245828/208025475-4a8ae68d-8a1e-413d-8672-7c4a86440182.png)

**Comment by it19862** [comment]
@tamlok 

Is it possible to open two (or more) instances of `VNote`?
I want to say:
  - the user clicked once on `vnote.exe`; 
  - as a result, the `instance-1` `Vnote` was started;
  - the user clicked once more on `vnote.exe`; 
  - as a result, the `instance-2` `Vnote` was started.

**Comment by tamlok** [comment]
No, that will intro complicated lock and sync mechanism.

**Comment by feloxx** [comment]
![image](https://user-images.githubusercontent.com/8359848/208667912-f6bdd1ac-7a9d-4336-98f1-4486c238d196.png)

Or set this to reset the layout.
