### ISSUE TITLE
【3.15.1版本】搜索功能搜不到任何结果，有遇到过的人吗？怎么解决？

### ISSUE THREAD

**Issue by mymach** [vnotex/vnote#2313]
如下图：

![image](https://user-images.githubusercontent.com/24400068/209034137-61416093-4cb7-484e-8613-07cd3d7e3056.png)

实际比较本里面肯定是可以匹配到的

**Comment by tamlok** [comment]
目标里面勾上文件和文件夹。

**Comment by mymach** [comment]
这个都试过，勾了也不行，全勾上也试过，都一样的

**Comment by tamlok** [comment]
文件模式里面的预编译删掉吧

**Comment by feloxx** [comment]
应该是他的笔记包含了 `预编译` 三个字，一般这里我们建议是写上正则。比如

`预编译*.md` 或 `*预编译*`

**Comment by mymach** [comment]
感谢各位，就是 "预编译"  三个字导致的，删除了就好了 ，可能是自己手滑输入的，然后一直以为是默认的模式...
