### ISSUE TITLE
使用vnote管理非md文件的建议

### ISSUE THREAD

**Issue by chenbong** [vnotex/vnote#232]
- [x] 开启“单击在当前标签页打开”的功能时，单击打开非md文件，会把当前的md笔记页面关闭，希望能实现打开非md 文件时不关闭当前笔记页面。
- [x] 希望支持使用vnote打开和编辑代码源文件（.c .java .py ...）,并可以实现代码高亮。

**Comment by znmlr** [comment]
建议深耕md格式，其余格式的文件已经有太多太多经典工具了，很难竞争！！

**Comment by tamlok** [comment]
VNote 3.0 now supports opening plain text and has syntax highlight.
