### ISSUE TITLE
正则表达式搜索，反向零宽无效

### ISSUE THREAD

**Issue by sinolover** [vnotex/vnote#2321]
**Describe the bug**
正则表达式搜索，反向零宽无效

**To Reproduce**
字符串：        ## 第2节：高速路上的小朋友
正则表达式： (?<=第\d+)节
**Expected behavior**
希望查找定位到 节 上

**Comment by tamlok** [comment]
Ref: https://doc.qt.io/qt-6/qregexp.html#assertions
