### ISSUE TITLE
希望能集成Mermaid

### ISSUE THREAD

**Issue by ccpwcn** [vnotex/vnote#2332]
Mermaid是一个非常优秀的在线工具，但是在国外，加载太慢了，我看Mermaid的官方文档，MIT协议的，而且集成也很容易，可否集成进来？Mermaid画的流程图、时序图都非常棒，比Markdown原生的图好看太多了。或者不方便集成的话，弄一个插件功能，让用户自己集成也行。

**Comment by ccpwcn** [comment]
其实PlantUML的功能也很强大，就是有点丑。

**Comment by tamlok** [comment]
```mermaid
    ```

这样输入mermaid片段即可。

**Comment by ccpwcn** [comment]
> ```
> ```mermaid
> A -> B
> ```
> ```
> 
> 这样输入mermaid片段即可。

反复试了半天，确实支持了mermaid，但是不知道为什么，**对mermaid支持的不完整**，sequenceDiagram中没有actor时可以，有actor就不行了。vnote版本3.16.0。

下面的代码不能展示：
![vnote不支持sequenceDiagram的actor](https://user-images.githubusercontent.com/5465756/212544235-1229d305-66ec-4f86-80f9-8877f77ac19a.jpg)

即使再添加participant指令也不行。

改为这样就可以了：

![vnote支持sequenceDiagram无actor](https://user-images.githubusercontent.com/5465756/212544289-620d1098-59e6-43c9-80cb-4352fa44d5b4.jpg)

**Comment by tamlok** [comment]
VNote里面的mermaid是离线集成的，所以对于新功能可能不支持，需要更新mermaid版本。有空我会更新一次。

**Comment by feloxx** [comment]
https://plantuml.com/zh/

**Comment by ccpwcn** [comment]
@tamlok 几个多月都过去了，啥时候更新一下vnote中集成的mermaid呢？毕竟再额外安装一个其他软件，没必要了呀。

**Comment by tamlok** [comment]
> @tamlok 几个多月都过去了，啥时候更新一下vnote中集成的mermaid呢？毕竟再额外安装一个其他软件，没必要了呀。

Sorry, 最近加班比较厉害。4月份会有一波更新。

**Comment by zbzpo2002** [comment]
我手动更新了  mermaid.min.js， 好像没有用啊。

**Comment by tamlok** [comment]
> 我手动更新了 mermaid.min.js， 好像没有用啊。

手动更新的话，需要看一下debug信息，F12即可。
