### ISSUE TITLE
Search Button or Advance Search Button to search all files or all notes

### ISSUE THREAD

**Issue by passionate2023** [vnotex/vnote#2335]
Does it have a universal search button to search all files or all notes?

Please make is visible and add it in help with screenshot if possible.

If not available, is it possible to add a search button for quick search

**Comment by feloxx** [comment]
1. Ctrl + Alt + F
2. Ctrl + G, G

**Comment by tamlok** [comment]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/5763157/212833837-fdca9ddc-7014-4e10-8f5a-515fc084b41d.png">

**Comment by passionate2023** [comment]
Thank you so much...Can you please add an icon or help or visible search and advance search box if possible?
