### ISSUE TITLE
建议增加个沉浸模式

### ISSUE THREAD

**Issue by yangbangli** [vnotex/vnote#2349]
建议添加个沉浸模式，只显示当前编辑的markdown文件，不显示左右侧栏
![微信图片_20230208140500](https://user-images.githubusercontent.com/50435933/217448268-cc5c8b64-d171-4741-aa2a-b39803383834.png)

**Comment by tamlok** [comment]
你好，界面右上角有一个扩展内容编辑区的按钮，按了就可以了。在扩展的时候具体要显示哪些工具窗口，可以在设置里面配置。
