### ISSUE TITLE
V2.10，初始运行最大化显示BUG

### ISSUE THREAD

**Issue by mt6595** [vnotex/vnote#2352]
![image](https://user-images.githubusercontent.com/37893468/218407171-b0d88769-1ac6-49d9-8976-d16f51fc6d89.png)

使VNote处于最大化界面，然后关闭，再打开，必然发生这个现象

**Comment by tamlok** [comment]
看置顶Issue，设置一下OpenGL：

https://github.com/vnotex/vnote/issues/853
