### ISSUE TITLE
能否升级一下Mermaid版本?

### ISSUE THREAD

**Issue by NeutronT** [vnotex/vnote#2362]
现在Mermaid版本已经到了10.0.2了，有很多新的好用的特性，希望能够更新一下。当前的vnote中的mermaid版本还停留在8.9.1。很多图都渲染不了，影响使用。

**Comment by jackydi** [comment]
3.15支持mermaid吗？

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/2377

**Comment by tamlok** [comment]
> 3.15支持mermaid吗？

都支持了
