### ISSUE TITLE
全屏模式下偶尔会出现界面闪烁

### ISSUE THREAD

**Issue by sumengmsm** [vnotex/vnote#2363]
**Describe the bug**
全屏模式下鼠标在不同区域移动会出现界面闪烁，例如鼠标从编辑工作区移向退出全屏菜单栏。
但是录屏时，录屏界面没有出现问题，而退出录屏后还是有问题。无奈之下就用手机录的。

**To Reproduce**
1. 打开全屏
2. 鼠标移向退出全屏菜单
3. 界面闪烁

**Screenshots**
录屏文件：
https://wwpc.lanzouf.com/iDxVC0pum1rg
密码:bp97

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [e.g. 3.16.0]

**Additional context**
另外还有一个问题就是，有时候在导航栏从A文件切换到B文件时，偶尔会闪回到A文件界面，然后又返回到B文件界面，不过这个问题不好复现，我就提一下。

**Comment by tamlok** [comment]
置顶opengl isseu看一下

**Comment by sumengmsm** [comment]
尝试了一下OpenGl ES，确实改善了，另外两个倒是没啥效果。
