### ISSUE TITLE
搜索功能取消了么？怎么看不到了

### ISSUE THREAD

**Issue by littleheary** [vnotex/vnote#2372]
新版本搜索功能不见了么？看不到了呀
![image](https://user-images.githubusercontent.com/26987382/229347160-0ecc6624-8910-4dd7-815f-5ced95738627.png)

**Comment by Fxiao1** [comment]
是不是关了？在这里可以重新打开
![1](https://user-images.githubusercontent.com/40653617/229417456-4a0337f9-f54d-44a7-a358-108572d47c60.jpg)
