### ISSUE TITLE
请问如何配置mermaid，使其用曲线渲染？

### ISSUE THREAD

**Issue by Fxiao1** [vnotex/vnote#2376]
vnote的mermaid画出来的图的线条是直线，图比较复杂之后，线条容易重合、遮挡，请问怎样能将其配置成曲线呢？我看mermaid支持曲线的。

**Comment by tamlok** [comment]
可能需要更新mermaid的新版本，我看mermaid是支持指令的，所以应该是在图的定义里面写上一些指令就可以了。4月份会计划一个版本，升级mermaid。

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/issues/2377
