### ISSUE TITLE
Can't switch to command mode

### ISSUE THREAD

**Issue by halvabner** [vnotex/vnote#2388]
I can't switch to command mode when I press 'Esc'

Whenever I press 'Esc' or Ctrl+], it just stays in insert mode.

I am on Arch Linux

Linux hostname 6.3.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000 x86_64 GNU/Linux

installed it from AUR using this package build https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vnote

**Comment by tamlok** [comment]
Do you enable the Vi mode in the Settings page?

![image](https://user-images.githubusercontent.com/5763157/237057728-c448ce24-54a3-4757-8f7d-ea9791479e38.png)

**Comment by halvabner** [comment]
my bad, i didn't see that setting, thanks :)
