### ISSUE TITLE
一次只能看一个笔记本，还是我不知道怎么调？

### ISSUE THREAD

**Issue by 839781960** [vnotex/vnote#2395]
问题？
![image](https://github.com/vnotex/vnote/assets/114645865/53572849-b881-46cd-97a0-a711d3823c72)

特性
我需要所有笔记本全部打开而不是选择

**Comment by tamlok** [comment]
全部打开的意义是什么呢？

**Comment by 839781960** [comment]
> 全部打开的意义是什么呢？

方便啊，一天切个几回很难受啊。可以提供一个全部打开的选项吗

**Comment by Nriver** [comment]
那为什么不把他们放一个笔记本里？
