### ISSUE TITLE
Reading and Editing

### ISSUE THREAD

**Issue by CloudWizard-zts** [vnotex/vnote#2399]
The font on the editing page looks better, but it doesn't seem to apply to the reading page. Did I set it incorrectly or currently don't have this feature?
![image](https://github.com/vnotex/vnote/assets/50130277/a0db686b-62aa-4b32-8f6a-0b12c2370c2a)
![image](https://github.com/vnotex/vnote/assets/50130277/c4b3bdb2-d75d-4418-9380-2be9190c950c)

**Comment by tamlok** [comment]
Hi,

For read mode, you need to modify the CSS stylesheet. You can press F12 to debug current font famliy in read mode.

![image](https://github.com/vnotex/vnote/assets/5763157/eb53e233-60c8-4c60-a53b-16bee50a268a)

**Comment by ztszhangtingshuo** [comment]
thank you
