### ISSUE TITLE
开发者大大您好！现在写的文章好像只能添加一个标签。请问能不能提供为文章添加多级标签的功能。谢谢。

### ISSUE THREAD

**Issue by Iron-Man666** [vnotex/vnote#2400]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
可以添加任意多个标签呀：

![image](https://github.com/vnotex/vnote/assets/5763157/c0b40b3a-c77a-46e6-8c8e-b5809f03d170)

![image](https://github.com/vnotex/vnote/assets/5763157/6097c041-4f3c-4eab-b8a1-18f5c7d1ced5)

**Comment by Iron-Man666** [comment]
谢谢！
