### ISSUE TITLE
 vnote-win-x64-qt5.15.2.zip v3.16 数学公式無法渲染。

### ISSUE THREAD

**Issue by oversky** [vnotex/vnote#2411]
数学公式在 preview 里没正常渲染，是我少安装了什么吗？
只是很简单的平方及开根号。
OS: Win10 22H2
vnote 版本：v3.16 
https://i.imgur.com/1JgbdDM.png

我有试过 linux 版 vnote-linux-x64.AppImage 没有问题。
同样的 note 档用在 windows 下开就不行。

**Comment by tamlok** [comment]
尝试一下帮助里面的检查更新看看网络有没有问题。

另外就是查看一下日志文件。

**Comment by oversky** [comment]
谢谢。是防火墙挡住了。
