### ISSUE TITLE
ubuntu22.04 系统使用3.16.0版本没有vim模式？

### ISSUE THREAD

**Issue by EthanLee-Esther** [vnotex/vnote#2415]
![image](https://github.com/vnotex/vnote/assets/77041928/e8ef2fd6-fcd8-4135-9f72-43b71e4e97d9)

**Comment by tamlok** [comment]
在编辑器页面进行选择输入模式呢

**Comment by EthanLee-Esther** [comment]
谢谢，不好意思，刚刚没看到
