### ISSUE TITLE
已打开笔记本，不能正常显示。关闭后，重新打开也无效。从文件夹重新创建也无效

### ISSUE THREAD

**Issue by hgyhgyhgyhgyhgy** [vnotex/vnote#2416]
![image](https://github.com/vnotex/vnote/assets/101418318/8aba6a60-06b3-4f62-9f44-ed0e4633adec)

情况十分奇怪。

**Comment by tamlok** [comment]
Ctrl-G E 试试？不行就设置里面重置布局即可。
