### ISSUE TITLE
fedora 38上预览界面中文显示乱码

### ISSUE THREAD

**Issue by plopop** [vnotex/vnote#2421]
编辑界面中文能正常显示，预览界面遇到中文就显示方块中间一个叉X，从预览界面复出粘贴在其他地方可以正常显示

尝试过更换版本，3.16.0，3.15.1和5月8号的Pre-release
尝试过更换字体，系统字体
都没有效果

系统：fedora 38 x86_64
桌面：xfce 4.18

![截图_2023-08-13_22-11-56](https://github.com/vnotex/vnote/assets/4570553/ebe65afe-856d-4a2e-9d3b-eafa8ff98951)

克隆下来自己编译最新的可以正常显示
![截图_2023-08-13_22-42-33](https://github.com/vnotex/vnote/assets/4570553/a700140d-82a2-4fce-8b8b-b08bb6265cf4)
qt是6.5，要爆改一通，顺便问下有没有其他换行符能正常换行的markdown软件？

**Comment by tamlok** [comment]
你看看主题里面 web.css 文件对应的字体是哪个字体？或者右上角有一个调试的按钮，可以查看实际生效的是什么字体。

居然在Qt 6下面改通了VNote！！！要整理一下发PR吗？这个原本还在下一步计划中，准备迁移到Qt 6。

**Comment by plopop** [comment]
> 你看看主题里面 web.css 文件对应的字体是哪个字体？或者右上角有一个调试的按钮，可以查看实际生效的是什么字体。
> 
> 居然在Qt 6下面改通了VNote！！！要整理一下发PR吗？这个原本还在下一步计划中，准备迁移到Qt 6。

是看这里吗
![截图_2023-08-14_19-31-05](https://github.com/vnotex/vnote/assets/4570553/72d38417-14d6-4574-a4ac-bbdce4848dcf)

可以pr

**Comment by plopop** [comment]
> 对，你强制指定font family为你机器上的字体看看
可以！我把本机字体添加到主题配置文件中第一个，就显示正常了。
![截图_2023-08-14_22-37-26](https://github.com/vnotex/vnote/assets/4570553/4065b01d-e659-4dcb-85cf-aa5b634efd37)
不过恢复配置，本地编译的版本用原始的配置是正常的。
![截图_2023-08-14_22-39-16](https://github.com/vnotex/vnote/assets/4570553/f8cfaa8f-0f44-46cb-90e8-f5d918b3c147)
pr提交到哪个分支

**Comment by tamlok** [comment]
提交到master即可

**Comment by plopop** [comment]
恩。除了vnote，还有外链里的也改了
vtextedit
sonnet
syntax-highlighting
