### ISSUE TITLE
mermaid requirementDiagram not rendered

### ISSUE THREAD

**Issue by mikowiec** [vnotex/vnote#2424]
**Describe the bug**
Mermaid Requirement Diagram is not display in editor mode

**To Reproduce**
1. Insert next code block:
```mermaid
requirementDiagram
  requirement dark_theme {
    id: 1
    text: We need darkness
    risk: low
    verifymethod: inspection
  }
```
code in mermaid block
```
requirementDiagram
  requirement dark_theme {
    id: 1
    text: We need darkness
    risk: low
    verifymethod: inspection
  }
```

4. See the rendering error as edit mode so read mode

**Expected behavior**
Mermaid diagram should be rendered.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 3.16.0], [Continuous Build, May 8](https://github.com/vnotex/vnote/releases/tag/continuous-build)

**Additional context**

**Comment by tamlok** [comment]
Should have been fixed.
