### ISSUE TITLE
vue-light 主题能像《纯净》主题一样自适应宽度嘛

### ISSUE THREAD

**Issue by Yifengzis** [vnotex/vnote#2428]
vue-light 主题能像《纯净》主题一样自适应宽度嘛
vue-light 主题
![image](https://github.com/vnotex/vnote/assets/43021839/590b826c-98c8-410b-864f-2c1219e7176d)

《纯净》主题
![image](https://github.com/vnotex/vnote/assets/43021839/6918e400-090f-438b-beca-b901f1a9ee98)

**Comment by tamlok** [comment]
他这个主题应该就是设计成这样的，即考虑人的视野不能太宽，所以限制居中以及宽度。可以右上角自定义CSS样式修改一下。
