### ISSUE TITLE
Windows下无法显示路径中带“空格”的图片

### ISSUE THREAD

**Issue by q337** [vnotex/vnote#2432]
我在路径下创建了2个文件夹"Test1234.assets"和"Test 1234.assets"， 放入相同的图片
如果使用路径带空格，无法正常显示图片
![img](assets/Test 1234.assets/ec3eec66b559422d87ce906b91e4767e.png)  显示失败
如果使用的路径不带空格，可以正常显示图片
![img](assets/Test1234.assets/ec3eec66b559422d87ce906b91e4767e.png)   显示成功

使用的版本为Windows 3.17.0

**Comment by tamlok** [comment]
url规定使用20%来替代空格。如果是直接粘贴图片到vnote中，vnote会自动转换。

**Comment by q337** [comment]
额，了解了。。不过好像是%20？(笑哭）
