### ISSUE TITLE
希望增加自动保存功能

### ISSUE THREAD

**Issue by 3tbpa** [vnotex/vnote#2433]
如题，这是很多软件都有的一个功能，防止做到一半的笔记出现意外损失。

希望能像word那样，隔10分钟自动保存一次，要不然忘记保存后死机、后果很严重。

我的电脑有时会莫名其妙关机，所以经常要手动按Ctrl+S，太累。

**Comment by tamlok** [comment]
默认就开启了的。

![image](https://github.com/vnotex/vnote/assets/5763157/896c752b-a572-4173-981d-4571dc6d5f3e)
