### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by hbwhypw** [vnotex/vnote#2443]
列表嵌套的时候有问题
下面这是vnote的效果
![image](https://github.com/vnotex/vnote/assets/5007311/f2891529-3489-4ef1-aa9c-3d50097c3dad)

这是Typora的效果
![image](https://github.com/vnotex/vnote/assets/5007311/751a4ab1-3c2f-460e-b03f-21e7aca64fb0)

**Comment by tamlok** [comment]
Typora的语法不是标准语法。

嵌套列表之间不用空行。
