### ISSUE TITLE
Wayland下面QT6编译的vnote git崩溃 (segfault)

### ISSUE THREAD

**Issue by heavysink** [vnotex/vnote#2448]
**Describe the bug**
sway下面运行直接崩溃报segfault, gdb显示

Thread 1 "vnote" received signal SIGSEGV, Segmentation fault.
QHotkeyPrivateX11::nativeKeycode (this=<optimized out>, keycode=Qt::Key_U, ok=@0x7fffffffcfe0: false)
    at ../libs/QHotkey/QHotkey/../../../../libs/QHotkey/QHotkey/qhotkey_x11.cpp:135
135		Display *display = x11Interface->display();

需要强制QT_QPA_PLATFORM=xcb

**To Reproduce**
用QT6编译vnote-git，运行直接崩溃

**Desktop (please complete the following information):**
 - OS:Arch
 - Version GIT 
 - Compiled with QT6

**Comment by tamlok** [comment]
QHotKey是我们用的一个开源库，不知道是不是还没迁移好？

实在不行，后面我把这个库去掉吧。

**Comment by Limosine** [comment]
@tamlok This crash has been fixed [upstream](https://github.com/Skycoder42/QHotkey/commit/bb630252684d3556b79ac7a521616692f348fcf7).
Could you include this commit in your fork of QHotkey?

**Comment by tamlok** [comment]
Fixed: 84891fb2f294d0e7d44c11310ba5ed7fc2677241
