### ISSUE TITLE
配置中数字显示乱码

### ISSUE THREAD

**Issue by wuscloud** [vnotex/vnote#2472]
![image](https://github.com/vnotex/vnote/assets/12063279/5dd92920-ff82-4fb6-aee9-dfc8225bde47)
![image](https://github.com/vnotex/vnote/assets/12063279/e397ad25-dbe0-42ae-b4a4-8a49ee180ac8)
![image](https://github.com/vnotex/vnote/assets/12063279/afdc3074-558b-4062-aa89-e3c58da45641)

请问是什么原因？

**Comment by tamlok** [comment]
这是linux还是windows呀？

**Comment by wuscloud** [comment]
这是windows10。

**Comment by wuscloud** [comment]
问题解决了。把区域和语言配置成中国简体中文就没问题了。我前一段时间都改成了香港导致的。
![image](https://github.com/vnotex/vnote/assets/12063279/158d02b8-1882-41df-af46-e95a53196dfc)
