### ISSUE TITLE
Flatpak/Flathub build

### ISSUE THREAD

**Issue by faveoled** [vnotex/vnote#2473]
Hello,

Could you publish your application to [Flathub](https://flathub.org/) - the Linux AppStore? It's based on a cross-distro [Flatpak technology](https://docs.flatpak.org/en/latest/introduction.html).

Or: would you agree if someone else writes the necessary build files for you and sends them to the Flathub maintainers?

**Comment by tamlok** [comment]
Hi @faveoled , I am totally a stranger to the Flatapk packaging and have not much time for that. It would be great if someone can help the packaging and publishing. I can focus on the dev itself then.

**Comment by faveoled** [comment]
https://flathub.org/apps/fun.vnote.app.VNote

**Comment by erenoglu** [comment]
the flathub package is now outdated? Is there anybody maintaining it? 
What is the recommended way to use VNote? Use outdated Flathub or download appimage from here? 
I prefer Flathub as it's integrated to my system application manager, but not if it's outdated.
