### ISSUE TITLE
字体异常

### ISSUE THREAD

**Issue by ThemanRonin** [vnotex/vnote#2480]
vnote版本：vnote-win-x64-qt5.15.2_v3.17.0
Windows版本：Windows10 版本 22H2 (操作系统内部版本 19045.3930)
分辨率信息：3840x2160 150%缩放

vnote主页的中文字体看起来很奇怪。具体截图如下。 文字看起来并不是模糊，而是感觉像是**缺失了一些细节**
部分笔记中的字体也是和主页中的字体一样比较奇怪。但是提升缩放后就是正常了的，可能是字体问题？

<img width="427" alt="image_203" src="https://github.com/vnotex/vnote/assets/35099500/88f9c473-e902-4064-9210-defd5c97880c">

尝试更改高dpi缩放并没有解决问题

**Comment by tamlok** [comment]
新建一个qt.conf文件，然后输入：

[Platforms]
WindowsArguments = fontengine=freetype

保存，放在vnote.exe同目录下面。

**Comment by ThemanRonin** [comment]
> 新建一个qt.conf文件，然后输入：
> 
> [Platforms] WindowsArguments = fontengine=freetype
> 
> 保存，放在vnote.exe同目录下面。

这样显示是比较清晰了，但是字体变的很粗 😨
![image](https://github.com/vnotex/vnote/assets/35099500/6d555c8e-c6b9-4505-a972-e44b9282ab5b)

**Comment by tamlok** [comment]
这个是不是变成黑体了？

你系统上面有微软雅黑吗？这是主题里面配置得字体，你看要不要修改一下或者安装一个字体。或者切换别得主题看看。

QWidget {
    color: @widgets#qwidget#fg;
    background-color: @widgets#qwidget#bg;
    font-family: "冬青黑体", "YaHei Consolas Hybrid", "Microsoft YaHei", "微软雅黑", "Microsoft YaHei UI", "WenQuanYi Micro Hei", "文泉驿雅黑", "Dengxian", "等线体", "STXihei", "华文细黑", "Liberation Sans", "Droid Sans", "NSimSun", "新宋体", "SimSun", "宋体", "Helvetica", "sans-serif", "Tahoma", "Arial", "Verdana", "Geneva", "Georgia", "Times New Roman";
}
