### ISSUE TITLE
希望能修改界面的字体大小，icon可以调整，希望字体也能调整

### ISSUE THREAD

**Issue by lwxk** [vnotex/vnote#2493]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
通过自定义QSS，可以修改软件字体。

font-size: 16px;

**Comment by lwxk** [comment]
能麻烦具体点吗？想要修改框起来的这些字体大小，没找到修改的地方，只有一个user.css，改的应该是编辑器的字体，不是layout的字体。

![image](https://github.com/vnotex/vnote/assets/32501171/2e98db78-8c0b-4672-ba6c-b02252aad101)

**Comment by lwxk** [comment]
没做过QT

**Comment by lwxk** [comment]
已解决，感谢。
