### ISSUE TITLE
Can't type '@' character on Windows with german keyboard layout

### ISSUE THREAD

**Issue by JoeJoeTV** [vnotex/vnote#2502]
**Describe the bug**
When using a german QWERTZ keyboard layout, the '@' character is typed by pressing the "AltGr" modifier key and the "Q" key. When trying to type this in VNote on Windows, a prompt opens with the text "Please set up quick note schemes in the Settings dialog first" and no character is typed.
On Linux, this behaviour cannot be observed with the same keyboard layout and the character entry works fine.

**To Reproduce**
1. Open any Note in VNote
2. Try to enter the '@' character anywhere
3. Dialog opens and no character is typed

**Expected behavior**
The '@' character should be typed.

**Screenshots**
_None applicable_

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.17.0

**Additional context**
This does not happen when switching the layout used by Windows to the US QWERTY layout.

**Comment by JoeJoeTV** [comment]
Thanks! That works, I can now enter an '@' symbol. Is the 'AltGr' key not supported on Windows and just emulates pressing Control and Alt?

**Comment by tamlok** [comment]
I think it should be supported. But I don't know much about the Qt behavior in different keyboard layout.

**Comment by JoeJoeTV** [comment]
@tamlok Ok, so with the recent 4.7.0 update, this issue still exists (AltGr key being treated as Ctrl+Alt) and now the default GLOBAL hotkey for creating a new quick note is Ctrl+Alt+@, so until I disabled the hotkey I could not type the "@" character anywhere on the system, as long as VNote is running.

According to [this Microsoft Learn article](https://learn.microsoft.com/en-us/windows/win32/uxguide/inter-keyboard#choosing-shortcut-keys-what-not-to-do), one should avoid using Ctrl+Alt combinations on Windows, which is annoying.
Possibly having different default keybindings for Windows could be a solution?

**Comment by tamlok** [comment]
Hi @JoeJoeTV , so if you remove all the `Ctrl+Alt+...` shortcuts in vnotex.json, all work well, right?

I am totally new to the German keyboard layout. So it is hard for me to repro (even interpret) the issue.

**Comment by JoeJoeTV** [comment]
> Hi [@JoeJoeTV](https://github.com/JoeJoeTV) , so if you remove all the `Ctrl+Alt+...` shortcuts in vnotex.json, all work well, right?
> 
> I am totally new to the German keyboard layout. So it is hard for me to repro (even interpret) the issue.

So, the german QWERTZ keyboard layout does not have two Alt keys (in comparison to e.g. QWERTY), but instead of the right one, it has an extra modifier key called AltGr. Additionally, the symbol layout is quite a bit different and while the Alt key is mostly used for hotkeys, AltGr is used to type some of the symbols of the keyboard, such as @ (AltGr + Q), ~ (AltGr + +), | (AltGr + <). So the key is pretty important and one would not usually put hotkey for programs on it.
From what I can tell, keyboard layouts for other languages also have this key, so it's not unique to German.

Now, Qt on Windows (apparently not just Qt) seems to interpret the AltGr key as Ctrl+Alt, which is a totally different usecase in my opinion (Also see https://en.wikipedia.org/wiki/AltGr_key#Ctrl+Alt).
With the default global keyboard shortcuts mapped to e.g. Ctrl+Alt+Q in VNote, this essentially means that if the key combinations are not changed or disabled, while VNote is open, one just can't type the @ symbol anymore, as it would just open VNote.

As one has to open the configuration file to change keybinds, this can be a bit annoying and not that easy to figure out the root cause.
I just think there could be something that either notifies people of this issue or a change to the defaults, such that this does not happen. Just a suggestion though.

**Comment by tamlok** [comment]
Got it! Thanks for the explaination! Learned a lot!

I will think about how to notice user about the thing and might be adding a config entry in Settings page. In China, from my own experience, `Ctrl+Alt` is used quite often for global shortcuts.

**Comment by JoeJoeTV** [comment]
> In China, from my own experience, `Ctrl+Alt` is used quite often for global shortcuts.

Yeah, most of my machines are running Linux, where this is also not an issue (AltGr is treated separately) and I'm using Ctrl+Alt for shortcuts. I only have to use Windows for work, so I only have the issue on my Work PC(s).

I am also (slowly) working on providing German translations for VNote which could go hand-in-hand with this.

**Comment by tamlok** [comment]
Speaking of the translations, I could generate a German translation with AI and you could start from that I think (check whether there is anything inaccurate in the UI translations).

**Comment by JoeJoeTV** [comment]
> Speaking of the translations, I could generate a German translation with AI and you could start from that I think (check whether there is anything inaccurate in the UI translations).

Thanks for the suggestion, but I have already started (just need to update to the newest version and fill in the rest of the missing strings) so I would just do it myself.
Would have to go through all of them anyway for checking.
