### ISSUE TITLE
开启原地游览后,原地游览无法关闭

### ISSUE THREAD

**Issue by ACodeHX** [vnotex/vnote#2514]
**Describe the bug**
开启原地游览后,原地游览无法关闭.

我点击关闭原地游览,回到阅读模式在回到编辑模式仍然还有游览,然后我重启了软件还是一样.

**To Reproduce**

https://github.com/vnotex/vnote/assets/127362983/b94f29cf-2c71-4c66-9fb7-d23fb6d4506b

**Expected behavior**
我想点击"开启原地游览",游览出现,点击"关闭原地游览",游览消失.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows11 专业版 23H2
 - Vnote Version: 3.17.0 
 
**Additional context**

**Comment by tamlok** [comment]
你这个模式不是原地预览，是双边预览：

![image](https://github.com/vnotex/vnote/assets/5763157/9f9f3328-c5f5-4dff-9220-8c47d62ee4df)


原地预览是这种：

![image](https://github.com/vnotex/vnote/assets/5763157/b62d24ca-146f-490f-acf8-f918d84ea239)
