### ISSUE TITLE
编辑模式不支持缩放笔记内容

### ISSUE THREAD

**Issue by chenyz1984** [vnotex/vnote#2520]
**Describe the bug**
编辑模式不支持缩放笔记内容

**To Reproduce**
现象：编辑模式不支持 “Ctrl +/-” 或 “Ctrl+鼠标滚轮” 缩放笔记内容

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version：3.18

**Comment by tamlok** [comment]
Fixed: https://github.com/vnotex/vnote/commit/bed95b175706504555999cc8871e592a2ea1a4e5
