### ISSUE TITLE
<mark>不工作了

### ISSUE THREAD

**Issue by WinlCheng** [vnotex/vnote#2523]
3.18更新完==xx==标记后，试了一下软件自带的标记按钮，发现还是添加mark标记，与此同时渲染界面也不处理这个标记了
![屏幕截图 2024-07-06 143653](https://github.com/vnotex/vnote/assets/105507018/7023680e-908f-4b8f-a058-01964054c5d8)

**Comment by tamlok** [comment]
Fxied: b2fb5b1664c86841841a8d30beeb3dbb328c76f4

关于是使用mark还是==来表示，这里还是不变吧，等后面方便用户开关某个特性的时候再改变。
