### ISSUE TITLE
macOS Sonoma 14.5 不能正常安装

### ISSUE THREAD

**Issue by Robin1216** [vnotex/vnote#2525]
机型：Macbook Pro 
芯片：Apple M2 Max
macOS：Sonoma 14.5
安装一直提示“应用程序VNote.app无法打开”，已按照文档 https://app.vnote.fun/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md 的操作处理，依旧无效

**Comment by id-xray** [comment]
2024.7.14，我也遇到了同样的问题，下载了最新的安装包后，依照文档的操作后，依然无法正常打开应用
<img width="944" alt="图片" src="https://github.com/user-attachments/assets/9f32187e-ded2-4540-881f-5848a3fad9a6">

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/pull/2530
