### ISSUE TITLE
冷启动时异常的多窗口闪动

### ISSUE THREAD

**Issue by ccpwcn** [vnotex/vnote#2529]
**Describe the bug**
版本 3.18.0

进程完全没有启动时，打开VNote会有多个窗口连着快速闪动，闪过之后，启动成功，一切恢复正常。

如果VNote已经启动了（系统托盘图标存在、vnote.exe进程存在），则不会出现。

旧版本是没有这个问题的，新版本似乎基于QT6了，出现了此问题。我使用旧版本有年头了，没发现此问题。

**To Reproduce**

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/6c0187b0-704c-4799-8339-1115a3a57348

**Desktop (please complete the following information):**
 - OS: Windows 10专业版，64位。

**Additional context**

**Comment by tamlok** [comment]
Hi,

这个是Qt6 里面QWebEngineProcess切换opengl的问题导致闪烁，目前暂时无解。

**Comment by ccpwcn** [comment]
> Hi,
> 
> 这个是Qt6 里面QWebEngineProcess切换opengl的问题导致闪烁，目前暂时无解。
> 
> 要不就启动的时候闪，要不就第一次打开文档的时候闪。只能取其轻了。

在Github上看到一个名叫Notepad Next的软件，它也是基于Qt6的，似乎就没有这个问题，我还试过国人开发的Notepad--，也没有这个问题，这说明应该还是有解决办法的。

**Comment by tamlok** [comment]
> > Hi,
> > 这个是Qt6 里面QWebEngineProcess切换opengl的问题导致闪烁，目前暂时无解。
> > 要不就启动的时候闪，要不就第一次打开文档的时候闪。只能取其轻了。
> 
> 在Github上看到一个名叫Notepad Next的软件，它也是基于Qt6的，似乎就没有这个问题，我还试过国人开发的Notepad--，也没有这个问题，这说明应该还是有解决办法的。

他们应该都没有用到QWebEngingeProcess chrome内核。
