### ISSUE TITLE
html语法和plantuml无法渲染

### ISSUE THREAD

**Issue by lyh19930821** [vnotex/vnote#2533]
版本：3.18.1 基于最新版本

编辑模式显示：
![image](https://github.com/user-attachments/assets/b60fb46f-ac50-4ee0-b903-58dfcb36c9c0)
渲染后的页面：
![image](https://github.com/user-attachments/assets/3d98c63d-4af7-4cb2-bd77-d29f03d4ca59)

F12的显示内容：
![image](https://github.com/user-attachments/assets/9f22ae60-b844-4880-9087-c90b1f7b2a86)

**Comment by lyh19930821** [comment]
将vnote移动到C盘目录下，plantnuml可以成功渲染了，但是 `<font color=red>xxxx </font>` 还是无法渲染。

![image](https://github.com/user-attachments/assets/fa811f81-e17e-4373-955e-d71c967787be)

**Comment by tamlok** [comment]
右上角，编辑用户配置文件，把xss相关的那个配置改为false，重启即可。下一个版本会修复。

**Comment by lyh19930821** [comment]
感谢，测试一切正常
