### ISSUE TITLE
左侧笔记本支持以文件夹来区分

### ISSUE THREAD

**Issue by wenshi01** [vnotex/vnote#2536]
你好，建议在左侧的文件标题列，可以添加文件夹，笔记多了之后可以更快找到笔记文件。

像我这样没有办法命名分类查看，文件很难找到。
![image](https://github.com/user-attachments/assets/bcd49608-1091-4ca4-8eec-bbf120d55d7b)

**Comment by tamlok** [comment]
VNote支持文件夹的：

![image](https://github.com/user-attachments/assets/87517b61-ed44-4303-81b4-ec8df355e23f)
