### ISSUE TITLE
左侧的目录区域能不能增加笔记本折叠功能，并支持笔记文件拖动方式实现笔记在不同笔记本中的移动

### ISSUE THREAD

**Issue by Damon0307** [vnotex/vnote#2551]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tamlok** [comment]
您好， 笔记本折叠功能是指？

**Comment by Damon0307** [comment]
![image](https://github.com/user-attachments/assets/1142d0a8-42ef-4dcb-9e47-0db73032644d)
类似VSCode . 笔记本作为主菜单，然后子菜单中显示笔记本中的笔记，
![image](https://github.com/user-attachments/assets/35782937-9499-4b51-b87a-6704bcf433f7)
可以通过这个图标折叠笔记本。
提议这个功能的原因是想快速的移动不同笔记本中笔记的位置，而不是打开原生的 file explore 去操作

**Comment by Damon0307** [comment]
> 您好， 笔记本折叠功能是指？
image
类似VSCode . 笔记本作为主菜单，然后子菜单中显示笔记本中的笔记，
image
可以通过这个图标折叠笔记本。
提议这个功能的原因是想快速的移动不同笔记本中笔记的位置，而不是打开原生的 file explore 去操作

**Comment by tamlok** [comment]
目前能右键剪切然后跳转笔记本粘贴，无需去到文件浏览器操作。

暂时不考虑这个显示形式。

对于方便在笔记本之间移动笔记这个需求，可以考虑通过其他形式进行改进，目前这样的确来回切换比较麻烦。

**Comment by Damon0307** [comment]
ok, thanks
