### ISSUE TITLE
是否可以增加一个把缓冲区覆盖提示去掉，改为默认 `放弃` 的选项

### ISSUE THREAD

**Issue by draftman9** [vnotex/vnote#2560]
**Is your feature request related to a problem? Please describe.**

我在 gvim 中编辑 .md 源文件的，用 vnote 查看渲染后的效果。每当我在 .md 编辑了一段文字并保存后 (`:w`)，想回到 vnote 查看效果时，就会弹出下面的框，然后我需要用鼠标点一下`放弃`，才会呈现最新文件的效果。

![image](https://github.com/user-attachments/assets/0496a73a-2263-47ed-b202-10774a23b824)

**Describe the solution you'd like**

我希望可以有个选项，让我避免去手动点击 `放弃` 的选项，在我保存 .md 文件后， vnote 可以自动“放弃”原来缓冲区的文件，直接显示最新文件的效果。 我看到有人提过这个问题: #2030

**Comment by tamlok** [comment]
![image](https://github.com/user-attachments/assets/8ef51b82-50a3-4622-abe4-467a883ac56b)

**Comment by chenyz1984** [comment]
这个提示内容有些不够明确，我是用群晖的 drive 实现多终端（家、公司）同步。每次家里修改完，次日上班后，公司的电脑也会有这个提示，每次看到这个提示都得思考（懵逼）一会儿。😂

**Comment by tamlok** [comment]
一般建议在某个平台使用后，要关闭vnote。vnote能自动恢复会话，而且这样才可以加载最新的json文件。

**Comment by draftman9** [comment]
> ![image](https://private-user-images.githubusercontent.com/5763157/380006992-8ef51b82-50a3-4622-abe4-467a883ac56b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODE2OTYsIm5iZiI6MTczMDE4MTM5NiwicGF0aCI6Ii81NzYzMTU3LzM4MDAwNjk5Mi04ZWY1MWI4Mi01MGEzLTQ2MjItYWJlNC00NjdhODgzYWM1NmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMDU1NjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI3NzBlNTA0M2E4MDdkN2MxZGIwYjBiM2I2MDE2NTUzYmZhMGI0NmE0MGQ0YjAzYmRjOWE2ZDZiNjE1YzU5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.r0l42NF4HImew2v5lQUE1owBiDpeiuzsCeF4Oof7dQo)

太好啦，这个可以解决我的问题，我会关闭这个 issue 。但是……每次重新打开文件后，我都需要重新设置它为 Auto Reload ，请问有没有将 Auto Reload 设为永久设置的方法？
