### ISSUE TITLE
功能请求：支持右键菜单栏一键在当前打开的文档添加当前笔记本内的的其他文档的相对路径的超链接

### ISSUE THREAD

**Issue by Rqirus** [vnotex/vnote#2561]
**Is your feature request related to a problem? Please describe.**

不关联问题

**Describe the solution you'd like**

文档数较多时，有时搜寻起来会比较麻烦；
而在文档内添加超链接的过程需要自己计算相对路径，较为繁琐不便
希望能快捷的插入笔记本内的其他文档的相对路径的超链接

例如, 我需要添加笔记本内的其他文档的超链接，需要自己计算相对距离

```md
参考文档
[title](../../example/title.md)
```

**Comment by tamlok** [comment]
Hi,

目前你在文档树里面右键复制文件路径，然后在vnote里面粘贴，vnote会提示是否粘贴为相对路径。
