### ISSUE TITLE
建议vnote的项目配置文件于md文件分目录存放！

### ISSUE THREAD

**Issue by znmlr** [vnotex/vnote#295]
目前的做法是根目录下有``_v_recycle_bin``文件夹，每个目录下有``_vnote.json``，这样相当不优雅

说个实际用途吧，我在hexo的``source\_posts``中存放了大量的md文件。希望本地用VNote管理，目前似乎不太方便

**Comment by tamlok** [comment]
hi，

VNote的设计是为了能使用任意编辑器就能轻易维护和编辑笔记，所以一切都是纯文本，并且每个目录自解释。

把recycle_bin忽略，把json添加到版本管理，应该对于hexo没有冲突。

可以使用VNote的浏览器来浏览外部文件并编辑，作为一个编辑器使用。不过，目前VNote对hexo的图片支持不好，hexo的图片的路径略奇特，还需要后面的代码支持。

对于github等其他直接使用相对路径的服务，VNote是支持得很好的。

**Comment by lxq1** [comment]
我也是用的HEXO写的博客，找了好多markdown工具，最后还是发现vnote最好用了，我一般是建立其他的文件夹，然后需要发布到hexo的post工具的时候，就把写好的markdown文档复制粘贴过去，

**Comment by tamlok** [comment]
@lxq1 后面会适配Hexo，耐心等等:)

**Comment by losymear** [comment]
@lxq1 @znmlr 你们直接使用vote的话如何设置vnote和hexo渲染选项的？ 我复制过去还要做调整

**Comment by tamlok** [comment]
@losymear Hexo的图片路径好像和vnote的不太一样，建议使用一些小工具直接把复制的图片上传到图床，然后直接将图片链接粘贴到vnote里面。

VNote可以用作一个编辑器，编辑外部文件，直接用vnote左侧的“浏览器”面板浏览到你hexo的仓库中，打开文件进行正常编辑即可。
