### ISSUE TITLE
关于标题序列格式的建议

### ISSUE THREAD

**Issue by ghost** [vnotex/vnote#327]
VNote 中标题序列格式是 `1.`、`1.1.` 这种形式，而理工类文章一般要求为 `1`、`1.1` 这种形式。
建议提供多种格式选项。

**Comment by tamlok** [comment]
Fixed in https://github.com/vnotex/vnote/commit/2600d12fc2a20a1073d6dcbe2de9754a78c9c1d0

Make it the default style of the section number.
