### ISSUE TITLE
wkhtmltopdf转换PDF如何设置微软雅黑字体

### ISSUE THREAD

**Issue by wuscloud** [vnotex/vnote#389]
目前默认是宋体，网上也没找到wkhtmltopdf设置字体的参数，请问有办法吗？

**Comment by tamlok** [comment]
尝试修改CSS样式？

**Comment by wuscloud** [comment]
我想新增一个主题，发现拷贝配置文件重命名，重启vnote，并不能看到新主题，所以无法修改css

**Comment by tamlok** [comment]
看一下文档？

**Comment by wuscloud** [comment]
不行，修改CSS，只保留微软雅黑字体不行，导出来还是宋体
我使用的是pure主题，直接修改的v_pure.css文件，body中只保留了微软雅黑一个字体

**Comment by tamlok** [comment]
估计是wkhtmlpdf转换的时候在你机器上没有找到微软雅黑，所以就用替代字体了？

**Comment by wuscloud** [comment]
应该不是。我在两台windows下发现wkhtmlpdf转出来的就只能是宋体

**Comment by tamlok** [comment]
你试试命令行调用wkhtmlpdf来转一个。在阅读模式下已经是微软雅黑了吗？

**Comment by JeffreySE** [comment]
我尝试了使用vnote导出HTML（注意是导出并勾选“嵌入CSS样式、完整页面、嵌入图片“，不是保存页面），将雅黑字体放到`font-family`前面，删除其他中文字体，然后再使用`wkhtmltopdf`命令导出PDF，导出的字体没有问题；

分享下我遇到另外一个问题，如果笔记的代码块中出现单行很长的代码或者Shell命令输出的格式化文本（有点儿宽的那种像OpenStack的一些命令输出结果）导出的PDF代码会显示不全（因为代码块出现了横向滚动条）
可以将导出的HTML源文件中`pre code` CSS代码块部分样式`white-space:pre;`修改为`white-space:pre-wrap;` 代码可以换行了同时Shell命令输出的那种格式化文本样式也不会乱掉

如果还是不满意，可以尝试在`wkhtmltopdf`命令导出PDF时指定纸张为A3 `--page-size A3`横向`--orientation Landscape`，稍好一些，但导出的PDF就变得很宽了

**Comment by JeffreySE** [comment]
感谢提醒，我想起来有可能是我自定义主题样式导致的问题...
感谢vnote 😃

**Comment by tamlok** [comment]
@JeffreySE 你是用自定义导出格式来导出吗？如果是这个的话，可能这行代码没执行。

**Comment by JeffreySE** [comment]
![image](https://user-images.githubusercontent.com/12522179/45664904-f6ef9e80-bb40-11e8-9170-e57d8a220609.png)

使用的自定义主题，导出的格式选择为PDF
- 在不勾选“使用wkhtmltopdf”选项，不加其他参数的情况下，导出的样式很好看，和我主题的显示效果一致，只是导出的PDF没有大纲
- 选择了勾选“使用wkhtmltopdf”选项，导出的样式和主题显示效果字体不一致，可以导出大纲

问题应该还是在我自定义主题的CSS这块，我再调调看

**Comment by tamlok** [comment]
你可以添加一个导出专用的样式，导出的时候可以选择。放在配置文件夹下面的styles文件夹。具体可以看文档。
