### ISSUE TITLE
拼写检查功能

### ISSUE THREAD

**Issue by Sissuire** [vnotex/vnote#390]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**

您好，请问是否可以支持/扩展 `拼写检查` 功能呢？主要是涉及英文单词的拼写，防止一些明显的单词拼写错误。中文不要求。

谢谢~ 

******

OS Version (操作系统): Windows

VNote Version (VNote版本): v1.22

**Comment by ikelaiah** [comment]
I thought this would be a good feature too. If English spell check can be implemented, Chinese spell check could be implemented easily as well.

**Comment by DocNan** [comment]
是的，英语单词拼写检查是很重要的功能。平时主要是在整理的英文版的latex科研笔记，公式和单词都很多。如果增加单词拼写的检查就太好了。

**Comment by Sissuire** [comment]
still not supported...

Keep tracking.

**Comment by yankuocharles** [comment]
> 这个后面会支持！

等了一年半，仍在翘首以盼，这个功能太关键了。。

**Comment by tamlok** [comment]
@yankuocharles  正在重构中，再等等~~~

**Comment by SCLeoX** [comment]
@tamlok 

等了一年了... 这个功能确实太关键了...

**Comment by tamlok** [comment]
已经支持！
