### ISSUE TITLE
 大家好**「How are you」** is not bolded

### ISSUE THREAD

**Issue by seaspeak** [vnotex/vnote#421]
> **PLEASE elaborate the issue in detail**  
> **请详细描述问题**

******

OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): 1.22

Symptoms (表现):
大家好**「How are you」** is bolded in edit mode. But in preview mode it is not.

Adding a space between 是 and '**' solves the problem. But it is inconsistent.

How to Repro (如何复现):

**Comment by Warning-Forever** [comment]
I have an opposite problem.

`[**text**]` (also `[ **text** ]` ) is not bold in Edit Mode, but bold in Read Mode. VNote v2.
In the previous versions text in brackets was bold in Edit Mode.

**Comment by tamlok** [comment]
Similar issue as https://github.com/tamlok/vnote/issues/429#issuecomment-425692477

**Comment by ttimasdf** [comment]
Yeah, more spaces is a good practice. However, Adding spaces manually over times is tiring and easily forgotten, sometimes.
Could there be a possible enhancement adding spaces between normal and CJK characters, ONLY outside the recognized "embracing" elements. 
For example
```
大家好**「How are you」**你好我也好。
    ^ ^ ^            ^ ^
    1 2 3            4 5
```
that we only add a space between 1 and 5, not 2,3 and 4. Would this be easier than hacking the parser?

**Comment by tamlok** [comment]
@ttimasdf Hi, we only need to add one space before adding bold text, then `ctrl-B`, type the text, then `ctrl-B` again, add one more extra space, then type following words.

It is intuitive and simple. :) Space 2/3/4 are not needed now.
