### ISSUE TITLE
[Latest macOS] CPU Fan Running in High Speed and My Laptop Gets Very Hot

### ISSUE THREAD

**Issue by yanzhang0219** [vnotex/vnote#432]
OS Version (操作系统): macOS Mojave (10.14)

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
I updated my macOS to the latest version, macOS Mojave 10.14, and then when I opened VNote, the CPU fan starts to run immediately and my laptop got hot (very high temperature) very quickly. I don't know what lead to such an issue. Any suggestions? Many thanks.

How to Repro (如何复现):

**Comment by ikelaiah** [comment]
Did you resolve this problem?

**Comment by tamlok** [comment]
Any updates
