### ISSUE TITLE
Question: is there a way to recreate the .json files to update folder-contents?

### ISSUE THREAD

**Issue by sas-3** [vnotex/vnote#433]
OS Version (操作系统): Windows
VNote Version (VNote版本): Latest
Symptoms:

I use Markor on my android-phone to view and edits notes on the go. I face some problems with externally created / deleted notes, since vnote relies on the .json files to index folder contents.
 Is there a way to recreate the folder index? I thought "reload from disk" would do the trick but it doesn´t.

thx for the otherwise great tool!

How to Repro (如何复现):

**Comment by tamlok** [comment]
Hi,

I am afraid you need to write a simple python script to do the trick. Or just use VNote as an editor to edit external files.

Thanks.

**Comment by tamlok** [comment]
In VNote 3, VNote will display external files as external nodes. You could index it by simply clicking on it.
