### ISSUE TITLE
英语单词拼写检查，IOS版本开发

### ISSUE THREAD

**Issue by DocNan** [vnotex/vnote#456]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
1. 添加单词拼写检查非常有利于科研学术笔记的整理。里面有大量的英语单词和latex公式。
2. 开发IOS版本可以收费，相比android版本，可以获得更多的利润。因为在国内，安卓应用的用户几乎没有给应用付费的习惯，而IOS用户购买付费应用的比例更高一些。利用IOS版本付费应用获得的资金，可以支持后续建立数据服务器和对软件的持续开发和更新。

How to Repro (如何复现):

**Comment by tamlok** [comment]
拼写检查已经支持！
