### ISSUE TITLE
wkhtmltopdf生成的pdf，用鼠标点击[TOC]生成的目录不会发生跳转

### ISSUE THREAD

**Issue by zengjianwei** [vnotex/vnote#474]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):导出生成pdf的时候，选择使用wkhtmltopdf生成的pdf，这时文章中用[TOC]生成的目录鼠标点击不会发生跳转。

How to Repro (如何复现):1、在文章用[TOC]生成目录；2、导出生成pdf；3、导出设置页面中选择使用wkhtmltopdf生成的pdf；4、导出的pdf中，[TOC]生成的目录点击不会发生跳转。

**Comment by tamlok** [comment]
Hi,

This is a bug of wkhtmltopdf: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3486 https://github.com/wkhtmltopdf/wkhtmltopdf/pull/2957

Just need to wait for 0.12.6 release of wkhtmltopdf.

Thanks!
