### ISSUE TITLE
编辑和阅读的位置问题

### ISSUE THREAD

**Issue by kerhbal** [vnotex/vnote#484]
Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
编辑和阅读的位置不对应，常常看到某个地方需要改改，但是编辑和阅读两个模式的位置记忆貌似是独立的。
编辑模式似乎有自己的记忆，上次光标在哪这次还在哪
而阅读模式就很魔性了

How to Repro (如何复现):
取材是一篇vnote-posts里的文章
**阅读模式到编辑模式**：在阅读模式拉到中间然后点编辑
![1](https://user-images.githubusercontent.com/11629684/47969786-9d88f380-e04a-11e8-86ea-0e0f70d48685.gif)
**编辑模式到阅读模式**：在编辑模式拉到中间然后点对勾后先是跳到了“说来也是缘分”这一段，然后过了1秒又自动跳到了“文件关联”这一段，不知道是什么原因，可能因为“文件关联”是个小标题？
![2](https://user-images.githubusercontent.com/11629684/47969796-bb565880-e04a-11e8-9882-bce04215e176.gif)

总之希望编辑模式和阅读模式能同步，看到哪不对想改的时候能打开同样的位置，改好以后回到阅读模式也是同样的位置。谢谢！

**Comment by tamlok** [comment]
目前，两者之间的同步是粗粒度的。编辑模式转阅读模式，会跳转到光标所在小节的标题上。

**Comment by kerHbal** [comment]
@tamlok 感觉同步方面未来可以加强一下，因为现在vnote用的这种读写分离的一栏式情况下先天就有割裂感，尤其是阅读模式到编辑模式我觉得可以加强一下，要不然看到一半发现要改一改还得从头往下翻。短期内不好实现的话就当是个长期建议吧，谢谢~

**Comment by tamlok** [comment]
3.0已经加强
