### ISSUE TITLE
Cannot Open markdown file with vnote in Finder

### ISSUE THREAD

**Issue by luo-chuan** [vnotex/vnote#493]
OS Version (操作系统): macOS 10.14

VNote Version (VNote版本): Latest (最新) 2.1

Symptoms (表现):

Cannot Open markdown file with vnote in Finder.

**Comment by luo-chuan** [comment]
具体表现为在访达中双击markdown文件，可以打开vnote，但并没有打开文件。

**Comment by tamlok** [comment]
Should be fixed 280144f4eb758711be859a366dcb9e803a103f36

You could download the latest build to have a try.
