### ISSUE TITLE
【需求】编辑模式下TAB对齐显示，不用切换到阅读模式下查看是否已经对齐

### ISSUE THREAD

**Issue by yiltoncent** [vnotex/vnote#497]
OS Version (操作系统): Windows, Linux, macOS
Windows X86

VNote Version (VNote版本): Latest (最新)
V2.1

Symptoms (表现):
编辑模式下，TAB键的显示并没有占据对应的字符个数，导致看上去比较混乱，只能通过阅读模式看是否已经对齐，来回切换比较费时费力。
为了在编辑模式下达到”所见即所得“的效果，希望在阅读模式下对TAB键的显示进行优化。

How to Repro (如何复现):
如上

**Comment by tamlok** [comment]
2.2版本临时解决了这个问题。
