### ISSUE TITLE
当文件位于实时同步的文件夹中时，用vnote对其进行编辑会大概率会造成vnote客户端闪退

### ISSUE THREAD

**Issue by Zhikang-Zhang** [vnotex/vnote#498]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):
如题

How to Repro (如何复现):
尝试过的同步工具有onedrive, 坚果云和google drive, 问题均会出现

**Comment by tamlok** [comment]
暂时无法复现，请考虑是否是openGL的问题。可以下载2.2版本，然后在设置里面设置openGL的选项为software或其他值，重启试试。
