### ISSUE TITLE
阅读模式下查看mathjax代码的问题

### ISSUE THREAD

**Issue by mshdyh** [vnotex/vnote#510]
OS Version (操作系统): Windows, Linux, macOS
Win10

VNote Version (VNote版本): Latest (最新)
Vnote 2.1

Symptoms (表现):
在打开MathJax的阅读模式下，在公式上点击右键--Show Math As--Tex Commands，无法弹出新的窗口以供查看公式的mathjax代码

How to Repro (如何复现):

**Comment by tamlok** [comment]
Fxied in MathJax 3.0 now.

![image](https://user-images.githubusercontent.com/5763157/129464464-20bc7433-3f9b-4d16-babe-2ec3a69093dc.png)
