### ISSUE TITLE
希望能支持LF格式换行符

### ISSUE THREAD

**Issue by lixiao888** [vnotex/vnote#519]
希望能支持设置LF格式换行符，win平台默认的CRLF格式会影响diff比较，
否则git提交笔记的md文档报如下错误：
fatal: CRLF would be replaced by LF

**Comment by tamlok** [comment]
如果设置`git config core.autocrlf true`，让git自动转换，会怎么样呢？

VNote里面是Qt自动识别文件的换行符的。

**Comment by zhoujin7** [comment]
Windows 10, vnote新建笔记, 换行符是CRLF, 希望能指定默认的换行符为LF.

**Comment by yevision94** [comment]
建议可以像vscode那样，在右下角显示换行符的格式，当然要是也能进行转换就更好了

**Comment by pysense** [comment]
附议

**Comment by tamlok** [comment]
https://github.com/vnotex/vnote/releases/tag/v3.7.0
