### ISSUE TITLE
给文章添加备注信息

### ISSUE THREAD

**Issue by kolnick** [vnotex/vnote#536]

**Comment by tamlok** [comment]
也是说的很含糊。VNote支持FrontMatter，在文档开头通过以下信息可以插入元数据：

```yaml
---
Author: balabala
---

# Header
```

**Comment by kerHbal** [comment]
@tamlok 我想他的意思可能是无需打开笔记就能显示的备注，在这里：
![](https://i.imgur.com/yyvAoVN.png)

**Comment by tamlok** [comment]
@kerHbal 不清楚了，如果是这个的话得等插件了。
