### ISSUE TITLE
阅读模式中加粗渲染有问题

### ISSUE THREAD

**Issue by Li-Zhenghua** [vnotex/vnote#537]
OS Version (操作系统):  arch linux

VNote Version (VNote版本): Latest (最新) 

Symptoms (表现):

粗体在阅读模式中渲染失败

How to Repro (如何复现):

和 #490 #450 都不一样，中文，英文字母，中（英）文标点，数字都不能加粗。

`**abc**   **123**   **;;**   **，，**  **中文** ` 在阅读模式中都没有加粗

**Comment by tamlok** [comment]
1. Arch下面请使用`vnote-bin`或者AppImage，`vnote-git`因为是使用5.11编译，会有问题；
2. 请确认使用的是`markdown-it`渲染器；
3. 请新建一个笔记，仅包括上面这一行，测试是否有效果；

在Win下面测试没有问题，如果您测试还有问题，我再到Linux下面测试一下。

谢谢！

**Comment by Li-Zhenghua** [comment]
1. 使用的是`vnote-bin`
2. 使用的是`markdown-it`渲染器
3. 下面的文本在vnote中依然无法渲染 

```markdown
 **TESTING** , **测试** , **123** , **;;;;;;;**
```

**Comment by tamlok** [comment]
直接把有问题的那个测试笔记发出来？

**Comment by Li-Zhenghua** [comment]
[new_note_001.txt](https://github.com/tamlok/vnote/files/2667836/new_note_001.txt)
![2018-12-11 21-56-19](https://user-images.githubusercontent.com/43814319/49805250-a084ab80-fd8f-11e8-92bf-c3b6d1dcf384.png)
![2018-12-11 21-56-27](https://user-images.githubusercontent.com/43814319/49805252-a11d4200-fd8f-11e8-801b-d0cf7693dac2.png)

@tamlok

**Comment by tamlok** [comment]
openSUSE下测试没有问题。能把md原文件发出来吗？我是考虑会不会你测试的原文件带有不可见字符影响了渲染。另外，请尝试一下AppImage版本。AUR里面打包的都是热心用户提供的，和系统环境版本啥的可能有关系，我也不是很清楚。

谢谢！
