### ISSUE TITLE
空格占用的空间和一个英文字母占用的空间不一样？

### ISSUE THREAD

**Issue by roachsinai** [vnotex/vnote#580]
OS Version (操作系统): Linux

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):如下图所示，tab设置的4个空格但是好像只有两个空格

![screenshot_20190117_002526](https://user-images.githubusercontent.com/9500049/51263336-08618e00-19ef-11e9-92ec-fe1612fc842c.png)

**Comment by roachsinai** [comment]
不知能否顺便反应快捷键的问题：

> Ctrl+W进入编辑模式；Ctrl+R保存并进入阅读模式；Ctrl+E最大化编辑区；

这三个快捷键都无效，无论是否开启vim模式。

**Comment by kerhbal** [comment]
空格的问题猜测可能和字体有关？因为 ‘p’ 和 'i' 所占空间也不一样

**Comment by tamlok** [comment]
- 请确保vnote是最新版本；
- 请切换回默认主题测试，代码块里面应该是等宽字体，所有字母空格长度一样；
- 快捷键已经发生变化，请参考帮助菜单的快捷键说明。

**Comment by roachsinai** [comment]
快捷键已解决。`vnote`是最新的`2.2`版本。

刚才把`vnote`重置了，默认主题是`v_pure`(我当前主题)？

还是不等宽。

**Comment by tamlok** [comment]
你把整个themes文件夹删除，然后重启vnote试试。

**Comment by roachsinai** [comment]
![screenshot_20190117_114434](https://user-images.githubusercontent.com/9500049/51294294-45f50400-1a4d-11e9-8d23-a0fa69390388.png)

删除了，然后好像主题会自动生成，可是还是不行。。

**Comment by tamlok** [comment]
把这个文件发我邮箱，我这边看看吧。

**Comment by roachsinai** [comment]
我当前打开的么？

**Comment by tamlok** [comment]
是的。

另外，确保你的系统有以下字体之一：

    font-family: Consolas, Monaco, Andale Mono, Monospace, Courier New

**Comment by roachsinai** [comment]
好像确实是字体的原因。这些字体我想都没有。。我之前删除了一个字体导致`Monospace`指向的只替更换了。

```
➜  ~ fc-match monospace
DroidSansFallbackFull.ttf: "Droid Sans Fallback" "Regular"
➜  ~ 
```

刚才查了一下才知道`monospace` 是一个指向不是实在的字体。

但是，我这里安装了`Hack`，设置里面选中之后为什么也不行呢？

**Comment by tamlok** [comment]
你看你系统上有什么等宽字体，然后修改mdhl里面，把对应字体改为你系统的字体，重启vnote即可。

**Comment by roachsinai** [comment]
![screenshot_20190117_131005](https://user-images.githubusercontent.com/9500049/51296946-4e533c00-1a59-11e9-9feb-82b2ab78999d.png)

是这样么？可是并没有等宽：（

**Comment by tamlok** [comment]
你搜一下我上面给出的那一行是在哪里，替换掉就可以了，有两处。

**Comment by roachsinai** [comment]
emm 现在是编辑的时候正确，然后阅读的时候不是等宽，这个是正常情况么？

**Comment by tamlok** [comment]
自定义编辑字体是强制覆盖mdhl文件里面的样式的，而且仅仅是编辑器的全局样式，不是代码块的字体。

阅读模式一样，也需要修改字体，自行修改css文件。

其实最简单的还是安装一个monospace字体即可。

**Comment by roachsinai** [comment]
是这样的，我现在已经安装了monospace字体。就是说我什么主题配置都没有修改的情况下是：编辑的时候代码部分是等框字体，阅读的时候不是等宽。

**Comment by roachsinai** [comment]
```
➜  ~ vnote         
use user config "/home/roach/.config/vnote/vnote.ini"
user config: "global/version" QVariant(QString, "2.2")
user config: "global/theme" QVariant(QString, "v_detorte")
user config: "global/editor_style" QVariant(QString, "")
user config: "global/css_style" QVariant(QString, "")
user config: "global/code_block_css_style" QVariant(QString, "")
default config: "global/markdown_converter" QVariant(QString, "2")
default config: "global/tab_stop_width" QVariant(QString, "4")
default config: "global/is_expand_tab" QVariant(QString, "true")
default config: "global/highlight_cursor_line" QVariant(QString, "true")
default config: "global/highlight_selected_word" QVariant(QString, "true")
default config: "global/highlight_searched_word" QVariant(QString, "true")
default config: "global/custom_colors" QVariant(QStringList, ("White:#FFFFFF", "LightGrey:#EEEEEE"))
default config: "global/current_background_color" QVariant(QString, "System")
use editor style file "/home/roach/.config/vnote/themes/v_detorte/v_detorte.mdhl"
read file content: "/home/roach/.config/vnote/themes/v_detorte/v_detorte.mdhl"
matched font family "Liberation Sans"
matched font family "Monospace"
matched font family "Monospace"
unimplemented format attr type: 7
```

**Comment by tamlok** [comment]
你可以Chrome链接到VNote看看字体的情况。 参考 https://doc.qt.io/qt-5/qtwebengine-debugging.html ，应该就是声明一个环境变量`QTWEBENGINE_REMOTE_DEBUGGING=2000`，然后就可以`localhost:2000`访问页面了。

**Comment by tamlok** [comment]
chrome里面，点那个箭头，定位到页面中的代码块元素，自然就会显示对应的样式了。具体可以搜一下Chrome如何debug网页。

**Comment by Aloxaf** [comment]
遇到了类似的问题
默认主题下无论是预览还是编辑都不是等宽字体, 换到 vnext 主题以后预览是等宽字体了, 然而编辑模式仍然不是等宽

预览:
![图片](https://user-images.githubusercontent.com/17017672/71000361-2ad7bc00-2116-11ea-91c5-fb3423e46968.png)

编辑:
![图片](https://user-images.githubusercontent.com/17017672/71000418-40e57c80-2116-11ea-8653-4c389e938fbd.png)

**Comment by tamlok** [comment]
看你的高亮效果，是语法写错了吗？好像没有被识别为代码块。前后几行都粘贴出来看看吧。

**Comment by Aloxaf** [comment]
我只是挑了一段比较短的代码，其他部分也是这样的
![图片](https://user-images.githubusercontent.com/17017672/71053309-08cb5180-2189-11ea-8450-092ee9592c63.png)

奇怪的是用 `QTWEBENGINE_REMOTE_DEBUGGING=2000` 连上看了一下，这里明明已经使用等宽字体了 （Hack 是我手动加到前面的，原来用的是 Source Code Pro，不过仍然不对）
![图片](https://user-images.githubusercontent.com/17017672/71053489-83946c80-2189-11ea-8b62-057bcabe3fcc.png)

**Comment by tamlok** [comment]
编辑器的字体是由v_pure.mdhl决定的，修改一下那个文件看看。

**Comment by Aloxaf** [comment]
将所有的 `Consolas, Monaco, Andale Mono, Monospace, Courier New` 替换成了 `Hack`
仍然是这样

**Comment by tamlok** [comment]
能把你这个笔记发到我邮箱吗？

**Comment by Aloxaf** [comment]
这个笔记没什么特殊的，随便打开一个 MD 文档都是这个效果

我的系统也是 Linux，怀疑是不是 Linux 下工作有问题

**Comment by tamlok** [comment]
那你linux要不安装一下consolas这种宽字体看看？就样式里面列出的那几种。

**Comment by Aloxaf** [comment]
试着安装了 Monaco，仍然是这样的
不过 AppImage 的版本是正常的，难道是 Qt 版本的问题？（我的本地是 Qt 5.13.2

**Comment by tamlok** [comment]
好吧~~~原来是自行编译的~~~

vnote建议在qt 5.9.8下面编译，你可以单独下载一个qt 5.9.8的run文件安装到一个单独的目录。

**Comment by Aloxaf** [comment]
主要觉得预编译版体积太大了, 自己编译出来只有几兆.
应该是 bug, 就是不知道是 Qt 的还是 vnote 的. 等更新下个 Qt 版本后我再编译试试 (
