### ISSUE TITLE
用其他软件新建文件夹，vnote中不能显示，其他文件管理器新建文件，管理文件会方便许多，也可以假如一些其他格式的文件

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#587]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):
新建一个文件夹，vnote不能显示。新建.md，也不能显示。（对于.md，手动导入还是麻烦）

**Comment by tamlok** [comment]
hi

因为vnote是笔记软件，对于笔记本的管理还是需要通过vnote来操作。

如果需要频繁绕过vnote操作，建议使用浏览器功能来编辑外部文件。

后面会有改进。

**Comment by HgyHgyHgy** [comment]
那至少自动添加文件夹呀。
既然vnote采取文件夹结构，那个文件夹结构，也可以用于其他用途。比如在该目录新建些excell文件处理数据，然后把结果归纳到.md文件。
从逻辑上来说，直接就在对应的目录里处理，会方便许多，也不容易丢失。
就算它不自动识别其他文件，也关系不大。起码应该识别其他软件建的文件夹。
这个自动识别文件夹，好像也不是很难吧。

**Comment by HgyHgyHgy** [comment]
vnote的浏览器功能，还是不如其他软件方便的。譬如multi commander. 它可以用按钮实现，以输入字符做文件名新建某种文件并自动打开它。省了好几下点击和好些精力。

**Comment by HgyHgyHgy** [comment]
加入其他格式的文件，是说用其他软件可以在文件夹底下添加其他文件。不是说想让vnote处理其他格式文件。

**Comment by tamlok** [comment]
目前导入文件可以导入任意格式的，只是没有导入文件夹功能。自动添加文件的难处是怎么判断哪些文件需要加进来，比如图片和附件这些就不应该加进来。

实现都不难，主要是反锁和耗时间。后面再看怎么处理吧。

**Comment by HgyHgyHgy** [comment]
嗯。原来难点在于图片和附件文件夹等等？

可否把它们的文件夹弄个特别的首字母，譬如加个.的首字母在图标和附件文件夹之前。
这样就能把剩余的文件夹自动加进来了。

**Comment by HgyHgyHgy** [comment]
发现它们本来就有特别的命名规则，以_开头的。这样避免加它们进来，应该也容易呀。

如果要自动加入所有文件夹比较麻烦，退一步，弄个，自动加入当前文件夹的子文件夹这样一个功能，也是会方便很多的。

至于文件，也可以弄个自动加入当前文件夹的md文件这样一个功能。也会方便许多。（子文件夹下文件就不不用加入了）

这两个功能可以合二为一。

**Comment by HgyHgyHgy** [comment]
或者把这个作为打开文件夹前，自动执行“导入其子文件夹，以及.md文件”。这样就不用监督文件夹以及文件的变化了。

**Comment by HgyHgyHgy** [comment]
也可以在打开文件夹时，为该文件夹创建或打开一个同名的.md文件，这样每个节点都有内容。往往有一个这样的同名md文件，就已经足够的了。

**Comment by HgyHgyHgy** [comment]
或者弄个按钮，点击就扫面当前文件夹，然后弹出一个列表，可以让用户勾选需要加入的文件夹或md文件。
这样用户，可以新建一些临时文件夹，也不必加入到笔记本中。
让用户勾选，就避免了繁琐的判断了。可以简单一些。对性能的影响也更小一点。

**Comment by HgyHgyHgy** [comment]
和自动加入各有利弊。自动加入文件夹，就算加入了一些不必要文件夹，影响似乎也不大。这个可以让用户选择。

退一步，就算把图片文件夹或附件文件夹都显示出来，也不是大不了的事情。为了方便处理内容，这个是可以接受的。相比起来，这个毛病，不如“不能自动显示文件夹下所有内容”这问题严重。

若不希望显示，也可以关闭自动加入的功能。

**Comment by HgyHgyHgy** [comment]
就把那个“浏览器视图”改为自动加入文件夹和所有文件就好了。额外的浏览器视图并不必要。保持和笔记本一样的界面。浏览器视图的图标没那么好看，好像也不能直接新建笔记。

**Comment by kerhbal** [comment]
你没有理解作者所说含义。
“自动添加文件的难处是怎么判断哪些文件需要加进来，比如图片和附件这些就不应该加进来。”
此处是vnote或作者无法决定你导入的图片文件夹叫什么名字，这种命名方式完全取决于当初使用其他软件写md文件时的设置，既然你现在想要导入了说明md文件早就写好了，一万人电脑上存在一万种可能的文件结构，如果想要成功导入需要的是繁琐的识别任务。

其次，请勿把浏览器视图视为不必要的组件，浏览器视图适合于暂时编辑不想改变位置的笔记本外md文件，一旦加入所谓的“自动加入文件夹和所有文件”将对笔记本结构造成灾难性的后果。

最后，你评论完可以重新编辑自己的评论，想到什么附加修改的内容完全可以把之前的好好编辑一下，无需这么多条，也有利于体现条理性，方便作者阅读，谢谢

**Comment by tamlok** [comment]
其实，笔记本对应的是vnote作为笔记软件的角色，浏览器对应的是vnote作为编辑器的角色。

后面重构后会改善笔记本内外部文件的表达方式，比如显示为淡灰色，用户可以右键添加为笔记本内容。

**Comment by HgyHgyHgy** [comment]
>           你没有理解作者所说含义。
> “自动添加文件的难处是怎么判断哪些文件需要加进来，比如图片和附件这些就不应该加进来。”
> 此处是vnote或作者无法决定你导入的图片文件夹叫什么名字，这种命名方式完全取决于当初使用其他软件写md文件时的设置，既然你现在想要导入了说明md文件早就写好了，一万人电脑上存在一万种可能的文件结构，如果想要成功导入需要的是繁琐的识别任务。
> 其次，请勿把浏览器视图视为不必要的组件，浏览器视图适合于暂时编辑不想改变位置的笔记本外md文件，一旦加入所谓的“自动加入文件夹和所有文件”将对笔记本结构造成灾难性的后果。
> 最后，你评论完可以重新编辑自己的评论，想到什么附加修改的内容完全可以把之前的好好编辑一下，无需这么多条，也有利于体现条理性，方便作者阅读，谢谢

这个浏览器完全可以用“笔记本”代替，一个能显示所有文件，也同时具有笔记本文件所有功能。

这样不会减弱浏览器功能，也能实现在笔记本底下处理工作的要求。

现在浏览器的功能很简陋。既不能添加笔记，界面也不好看。还需要输入浏览根目录。

只需要简单地把笔记本弄成可以查看所有文件，就包括了这个浏览器的功能。

名字依旧称为浏览器，其实也没影响。

至于希望让笔记本更有条理，不显示多余文件，也不必把原来的笔记本功能改变或删除。只需把它扩展成能查看所有文件及文件夹，就能替代浏览器的功能了。

**Comment by HgyHgyHgy** [comment]
>           其实，笔记本对应的是vnote作为笔记软件的角色，浏览器对应的是vnote作为编辑器的角色。
> 后面重构后会改善笔记本内外部文件的表达方式，比如显示为淡灰色，用户可以右键添加为笔记本内容。

那个浏览器完全可以用“能显示所有文件的"笔记本代替吧？

有人只用这个能显示所有文件的笔记本浏览器，也有人想用那个原来的笔记本。显然都各有优缺点，看喜好不同。

当然，我决定最好就是添加一个切换按钮。可以把笔记本切换到显示所有文件和文件夹的状态。这样逻辑上更自然一些。它完全包括了浏览器和笔记本的两者功能了。而且它应该还简化了编程，只需显示所有文件和文件夹。

**Comment by kerhbal** [comment]
@HgyHgyHgy 烦请仔细看看作者和我的回复，笔记本是一个已知结构的空间，一切内容都是在vnote里用_vnote.json文件记录的，所以才能做到秒开，加标签什么的。而浏览器窗口对应的外部文件是属于vnote未知的空间，如果想要对其中文件进行改动后能有效地反馈到vnote下次加载时（例如标签，增减文章内图片等），则需要在这个未知的空间每一级用vnote打开过的目录里都写入_vnote.json，这对整个系统的目录是巨大的污染。
其次作者和我提到的图片，附件文件夹：vnote是支持文章内删除图片的同时将笔记本内图片文件移到回收站的，这是笔记管理的重要一环，想要如此就需要我所提到过的`匹配与识别一万人有一万种的图片或附件文件夹格式`，这对于vnote这种重量级的软件来说过于繁重了，这是一个浏览器内核该去干的事——**适配全世界**。
最后，笔记本结构稳定及确定的好处是便于同步，同样是笔记本内的json文件能告诉另一台计算机上的vnote着同步过来的是什么结构，而不是“什么鬼，这一堆是什么？”

**Comment by HgyHgyHgy** [comment]
这个打开速度并无差别呀。你用那个浏览器窗口打开.md和笔记本窗口打开.md文件并无差别。

至于加标签，这个也并无矛盾，也不会产生什么问题。当“在可以查看所有文件的状态”添加标签，只需把它加入到记录文件中即可。

这个可以查看所有文件，并具有笔记本所有功能的状态，显然不必额外生成新的json文件。

若要使用标签功能，它只需生成或使用现有的json文件即可。

所以这是很简单的。它只需要显示所有文件即可。

至于那个要正确显示其他格式的.md文件，这个和我说的没有一点关系呀。

vnote比较方便的地方就是能链接其他文件。这样可以把其他信息汇集到一个文件里。然后方便地理解和调用其他文件。可以作为一个工作空间。

其他文件浏览器就没那么方便，对于若干目录结构，不太容易理解，也不能用图+文件说明。


其实，我还发现vnote有个不太方便的地方。显然我们希望对文件夹有一个说明.md文件，帮助记忆或索引该文件夹底下的文件。不然当你打开一个文件夹的时候，容易想不起来该文件夹是干什么的？
当你点击某个文件夹的时候，若能同时打开一个和文件夹同名的md文件。这样我们就可以在该文件中对该文件夹进行备忘说明或索引的了。现在点击文件夹，很容易期待右边窗口弹出一些说明。

**Comment by kerhbal** [comment]
@HgyHgyHgy 
>这个打开速度并无差别呀
因为现在浏览器模式无需读取文件标签等**Windows文件系统没有的东西**，而笔记本视图里这些都是写在json文件里的。我所说的是如果你想要浏览器视图里有现在笔记本视图里的体验那么就需要对系统目录进行全方位的污染。
>只需把它加入到记录文件中即可
请问此记录文件准备如何更新？如果将笔记本与浏览器混淆那么你在vnote外对文件夹，文件做的改动是不是vnote每次打开都需要扫描一遍系统，然后更新记录文件中的每一样内容？这个东西有个学名，叫**分区表**，同样不是vnote这个重量级的软件干的事情。笔记本视图的好处在于这个笔记本根目录下的东西是通过vnote操作的，是已知且稳定的。
>至于那个要正确显示其他格式的.md文件，这个和我说的没有一点关系呀。
你最初不是想要导入文件夹内的笔记吗？这就涉及到让vnote识别这是个简单的文件夹还是某个笔记所引用图片，附件的文件夹。识别是笔记管理的前提，而不同软件生成的md文件有不同的引用路径，当你在一个笔记里删除图片的时候vnote会自动将对应文件夹里的图片删除，这是笔记管理与简单罗列文件进行管理的不同之一。
总之你想要的是一个支持md文件的系统级的文件管理软件，而vnote只是一个笔记本。你可以把桌子上零星的几页草稿纸夹到这个笔记本里，但你想在里面夹一本康熙字典，这就不是vnote的初衷了。

**Comment by HgyHgyHgy** [comment]
1.为什么要对所有目录新建json文件？完全可以保持原有笔记本的功能一丝不变。只需要弄个可以切换到能查看任何文件的按钮即可，能查看所有文件。它具有现在的浏览器的所有功能，也具有笔记本一样的界面和功能。

2.这个并无新的。添加到现有笔记本功能中对应的记录文件即可。把该文件夹，以及该文件加到目前的笔记本中即可。

3.我是希望它能同时用于笔记，也用于工作空间。.md文件可以建立图文说明，也可以链接到其他工作文件。这样就需要它能显示所有文件和文件夹。至于打开文件，只需调用默认打开文件的软件即可。
譬如，在md文件中链接若干excell文件或者mindmap文件。

**Comment by kerhbal** [comment]
@HgyHgyHgy 
>完全可以保持原有笔记本的功能一丝不变

笔记本功能是建立在vnote主管笔记本结构的基础上的，换句话说vnote“认识“笔记本文件夹中都有什么，这就需要对你打开过的目录新建json文件，而你没有办法控制用户打开哪个文件夹，这次和下次打开的文件夹是不是一样，时间一长所有你在vnote里进行过笔记操作的文件夹都会留下json文件。
>这个并无新的。添加到现有笔记本功能中对应的记录文件即可。

现有的记录文件都是在各个文件夹中的，且父文件夹的json文件还会记录子文件夹的信息，这些东西是牢牢绑定在一起的。你在新的文件夹里有任何操作都会留下痕迹。

>把该文件夹，以及该文件加到目前的笔记本中即可。

”加到笔记本中“是什么行为？是让vnote认为这是个笔记本？还是让vnote认为这是个笔记本中的一个结构？如果是一个结构的话在笔记本中这些被加入的笔记需要虚拟地指向不同位置？如果一个笔记本里的东西分布在整个文件系统的边边角角，请问该如何备份与同步？

至于你说的第三点，`调用默认软件打开其他格式文件`这个功能在浏览器视图是已有功能。关键的难点在于文件夹的识别上，这点也早已说过很多遍就不说了，作者第一条回复也说过这是很繁琐的东西，所以如果你需要这个功能可能需要有些耐心了。

**Comment by HgyHgyHgy** [comment]
你比较一下笔记本和那个浏览器，那个浏览器是完全显示所有文件的。
既然浏览能完全显示所有文件，就算采用和笔记本页面完全一样的界面，它也是能显示所有文件。
不必新建任何其他东西，也不会改变原来笔记本的功能。

假如你为某文件新建了便签，那只需为它新建一个记录文件即可。其他的，自然不必有什么记录文件，若没有什么便签。至于，vnote怎么查找标签，这本来就是原有的功能，不必考虑。

至于说文件夹底下有一大堆其他文件。这个完全就是用户自己建立的。你一个都不建也可以。如果建了，你想和其他电脑同步，自然也是想所有文件都同步。不然，你就不要把文件放到它们的文件夹之中。

**Comment by kerhbal** [comment]
@HgyHgyHgy 
>既然浏览能完全显示所有文件，就算采用和笔记本页面完全一样的界面，它也是能显示所有文件

麻烦看完我之前写的，光显示有什么用，重要的是管理，这才是笔记本视图和浏览器视图的区别。管理就意味着vnote知道某一篇笔记里某个图片所对应的文件夹是一个图片文件夹，在笔记里删除图片时需要在对应文件夹里也删除，还有标签等等功能。
>假如你为某文件新建了便签，那只需为它新建一个记录文件即可。其他的，自然不必有什么记录文件，若没有什么便签。

麻烦你到json文件里看看，便签只是笔记管理的一个方面，每个存在笔记的地方vnote都需要识别到笔记图片的文件夹，而这些东西都是写在json文件里面的。笔记的管理并不是简单列出来就完事了。。。
>至于，vnote怎么查找标签，这本来就是原有的功能，不必考虑。

这所谓”原有的功能“是建立在对笔记本内文件完全的主动管理的基础上的，没有json文件你让vnote去哪查找？
>你一个都不建也可以。

你能决定用户的行为吗？这里不是说我会怎么做，而是软件开发要考虑的是各种用户的行为，你能代表所有人不这样干吗？由此带来的管理混乱难道推给用户吗？
>不然，你就不要把文件放到它们的文件夹之中。

你能决定用户的行为吗？并不总是用户把一个笔记文件放入一个含有一大堆别的文件的文件夹内，更常见的是已经有一个含有一大堆别的文件的文件夹，用户在里面新建了一个md文件，此时为何不用vnote已有的浏览器模式来编辑呢？

一个软件既要考虑自己不要把自己玩死，也要考虑某些不成熟的功能开放给用户后会不会被用户玩死，毕竟用户不是自己。

**Comment by HgyHgyHgy** [comment]
你想像一下，你是喜欢在笔记本界面，按一下一个显示所有文件的按钮或快捷键，就能显示所有文件，同时含有那个浏览器和原来笔记本一样的功能。
还是希望，像现在这样点击一下那个浏览器按钮，再去寻找相应的路径？

我说的，其实是说把那个浏览器改为和笔记本完全一样的界面。既然有完全一样的界面，自然有完全一样的功能。那些功能是原来笔记本的功能，没有增加新的功能。

这样改成完全一样的界面，实现导入文件的功能会更加方便。在显示全部文件的界面下，右键点击，选择导入文件即可。

这明显更加方便和合乎逻辑。

**Comment by HgyHgyHgy** [comment]
即使在显示全部文件的界面，不能实现原有的功能。
用完全一样的界面显示，譬如已经打开的目录，它已经打开，这样也是比现在那样的浏览器好用许多。

**Comment by kerhbal** [comment]
@HgyHgyHgy 
>既然有完全一样的界面，自然有完全一样的功能。那些功能是原来笔记本的功能，没有增加新的功能。

。。。所以我的回复你都没有看是吗。笔记本的功能扩大到浏览器所涉及的vnote外部目录，参照我之前n条回复谢谢。
>这明显更加方便

这里一直讨论的都是开发上的难度，我想要一个钢铁侠的AI管家，这个更方便，但是软件不是打个响指就变出来的。

>即使在显示全部文件的界面，不能实现原有的功能。

显示而不能使用某些功能，不就是现在的浏览器模式吗？你需要的功能可以简单地完成：让vnote记住你在浏览器模式里上次打开的文件目录即可

**Comment by Memento1990** [comment]
1. :joy: 听你们说了半天，到最后我才发现还有一个浏览器功能......
2. 个人觉得，vnote 定位知识管理软件，这个浏览器功能可有可无，作为辅助功能可以锦上添花，没有其实也没什么。
3. 我体验了一下浏览器里面的功能，其实我在 windows 10 里一个 Win+E 快捷方式就出来，收藏、添加小推车、订到历史啥的，用“快速访问”的就解决了，自己用了几年的操作系统了，对目录文件谁还没个顺手的操作流程~（当然，如果以后开发移动端的话，那这个功能还是可以的~）
@HgyHgyHgy @kerhbal 
4. 不知道你们有没有用 VisuaStudio IDE，其中在 **解决方案资源管理器** 中包含一个功能 **显示所有文件**，以及对每个文件（夹）右键都有一个 **从项目中排除** / **包括在项目中** 的操作，我理解的 @HgyHgyHgy 是想要这个功能。默认 vnote 只管理自己标记过的文件，当选择“显示所有文件”时，那些未标记过的文件（当然还是在当前笔记本下）会以灰色状态显示，然后由用户在右键中选择是否加入笔记本，还是从笔记本中排除。我觉得可以参考一下这个~（当然主要还是对md文件处理比较好，其他格式的文件还是用附件管理比较好，鱼龙混杂会导致笔记管理依旧比较混乱）
5. BTW，你们两点都还在讨论也是够肝的~ 😋

**Comment by tamlok** [comment]
浏览器里面的根目录是可以收藏的，下次打开vnote就会记住。

**Comment by kerhbal** [comment]
@Memento1990 不算肝，我下午😅

**Comment by tamlok** [comment]
VNote 已经支持了
