### ISSUE TITLE
plant uml 渲染卡顿严重，CPU占用100%

### ISSUE THREAD

**Issue by wyufeng** [vnotex/vnote#610]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

当笔记中 plantuml比较多时，打开笔记 渲染显示非常卡顿，查看CPU占用率，使用达到100%

或从编辑模式(会实时预览uml图)，切换到演示模式也会重新渲染卡顿比较长时间。

建议缓存 plantuml 图片

How to Repro (如何复现):

**Comment by tamlok** [comment]
3.0应该修复了
