### ISSUE TITLE
可以编写与预览效果同时吗

### ISSUE THREAD

**Issue by hqwx2018** [vnotex/vnote#621]
OS Version (操作系统): Windows

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):

**Comment by HgyHgyHgy** [comment]
同意这个，可以多一个选择。尤其是编写一些公式的时候。
可以采用类似于latex的方式实现。预览窗口可以放出来，放到第二个屏幕。

**Comment by tamlok** [comment]
3.10.0实现了
