### ISSUE TITLE
可以有新建同级文件夹的功能（快捷）吗？当一个文件夹下面有很多文件夹的时候，找到父文件夹，再新建子文件夹就麻烦了

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#623]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):

How to Repro (如何复现):
可以有新建同级文件夹的功能（快捷）吗？当一个文件夹下面有很多文件夹的时候，找到父文件夹，再新建子文件夹就麻烦了

**Comment by tamlok** [comment]
按一下左箭头既可以跳到父文件夹。暂时不添加了，不然菜单太繁琐了。
