### ISSUE TITLE
建议：graphviz 语言识别标记增加graphviz。

### ISSUE THREAD

**Issue by wyufeng** [vnotex/vnote#636]
由于VScode 提供一些markdown比较有用的扩展功能。比如将Excel表格粘贴为markdown表格。
所以经常在vnote 和VScode 间切换编辑。而VSCODE 的graphviz 扩展使用的语言标记为graphviz 与Vnote使用的dot不兼用。建议Vnote增加graphviz语言标记识别

**Comment by tamlok** [comment]
VNote也支持将Excel表格解析为Markdown，编辑器上右键解析为Markdown即可。标记后面会允许自定义。

**Comment by wyufeng** [comment]
> VNote也支持将Excel表格解析为Markdown，编辑器上右键解析为Markdown即可。标记后面会允许自定义。

OK TKS

**Comment by tamlok** [comment]
Added: e9799990f017b9d1e731800543d48645a8f7b85f
