### ISSUE TITLE
maven-metadata.xml 被占用？

### ISSUE THREAD

**Issue by scheninsp** [vnotex/vnote#638]
可能是网络波动，碰巧在关闭VNote时下载完成，已经没有问题了。

-----------------------------------------------------------------------------------

OS Version (操作系统): Windows10

VNote Version (VNote版本): 2.1

Symptoms (表现):
Android Studio3.0 在编译项目时， Gradle Sync时需要更新下载 
https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/maven-metadata.xml 。
但在打开VNote情况下一直卡住，关闭后才能更新成功。

How to Repro (如何复现):
使用Android Studio3.0 在任意项目中使用 Gradle Sync。

**Comment by tamlok** [comment]
这就奇怪了！试试把所有笔记都关闭了，然后关闭VNote，重新打开VNote，这时候不要做任何事情，看看能否复现问题。唯一有嫌疑的是VNote在阅读模式的时候会调用QtWebEngineProcess来显示网页。
