### ISSUE TITLE
Mac下，数字类emoji显示不正常

### ISSUE THREAD

**Issue by asok00000** [vnotex/vnote#639]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (VNote版本): Latest (最新)

Symptoms (表现):数字类的emoji显示不正常

How to Repro (如何复现):输入0️⃣这类数字类的emoji显示不正常

**Comment by tamlok** [comment]
感觉应该是和字体有关。

**Comment by asok00000** [comment]
emmm可以解决么，没有数字emoji很不好啊

**Comment by asok00000** [comment]
字体是默认字体，系统有color emoji字体

**Comment by tamlok** [comment]
你可以打开配置文件夹，找到当前主题的css样式文件，编辑其中的font-family的值，然后重启vnote或者重新打开当前笔记，看看效果有没有改善。

**Comment by asok00000** [comment]
不行
