### ISSUE TITLE
以托盘模式启动程序？

### ISSUE THREAD

**Issue by UM-Li** [vnotex/vnote#656]
OS Version: Linux

VNote Version: 2.2

您好，请问 Vnote 能否通过命令行参数以托盘模式启动？

谢谢！

**Comment by tamlok** [comment]
Hi,

VNote设置对话框里面有一个设置是是否允许VNote常驻系统托盘的，请查看一下？

**Comment by Siheyuan98** [comment]
感谢回复！

可能我没有表述清楚；想问的是有无办法让程序在启动时直接最小化到托盘？我想设置开机自启，但不希望自启动时弹出主窗口。

**Comment by tamlok** [comment]
这个暂时还没有实现，后面会添加。

**Comment by Siheyuan98** [comment]
好的，谢谢！

**Comment by tamlok** [comment]
先开着吧，我怕我忘了~~

**Comment by roachsinai** [comment]
遇到个情况。

Manjaro KDE, 设置不允许VNote常驻系统托盘，还是在系统托盘显示。

**Comment by tamlok** [comment]
两个不是同一个问题。

只是显示而已吧？关闭vnote后就没有了吧？

**Comment by roachsinai** [comment]
嗯嗯，关闭之后没有。那这个设置不是没起效果嘛。

**Comment by tamlok** [comment]
那个设置是开启以后，关闭VNote主窗口，VNote并不会退出，但无论开启与否平时是一直会显示托盘程序的。

**Comment by roachsinai** [comment]
OO，明白了。

**Comment by tamlok** [comment]
I think it is common for a global tool like a dict app to start and minimize. It is not usual for a note-taking app. So postpone this request for now.
