### ISSUE TITLE
[Error]Win7下，运行Vnote，切换至Vnote后任务栏点击其余程序皆无法正常切换，而是保留Vnote在最前面，同时会导致缩小Vnote后其余程序之间的正常切换功能

### ISSUE THREAD

**Issue by JiuMengDz** [vnotex/vnote#659]
OS Version (操作系统): Windows7

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
Win7下，运行Vnote，切换至Vnote程序界面后任务栏点击其余程序皆无法正常切换，而是保留Vnote在最前面，同时会导致缩小Vnote后其余程序之间的正常切换功能。重启任务栏后可恢复，但打开Vnote后继续出现同样的问题。

How to Repro (如何复现):
使用Windows7操作系统，打开最新的Vnote后尝试切换其他程序。

**Comment by tamlok** [comment]
这个比较诡异。在VNote的设置里面有一个opengl的选项，可以尝试切换为software或其他选项，然后重启vnote试试。

谢谢！
