### ISSUE TITLE
设置的字体无法渲染到代码块中

### ISSUE THREAD

**Issue by yousifun** [vnotex/vnote#668]
OS Version (操作系统): win10 1809

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3,
Symptoms (表现):无论是编辑模式还是预览模式，在代码块中的中文字体都是“宋体”，无法渲染为设置的字体微软雅黑。
![20190314090041.png](https://i.loli.net/2019/03/14/5c89a8cda7849.png)
![20190314090123.png](https://i.loli.net/2019/03/14/5c89a8c35cc19.png)
How to Repro (如何复现): 没有做其他设置，开箱使用这程序从2.2到2.3版本在我电脑中都小问题

**Comment by tamlok** [comment]
Hi,

代码块里面的字体默认是等宽字体，和正文字体是有区别的，具体可以参考文档，看对应主题文件夹下面的mdhl和css文件。

另外，在`实例`下面代码块前面，需要添加一个空行，这样才是真正的代码块，代码块结束后建议也添加一个空行。代码块第一行三个反引号后面可以添加语言标记，这样就有语法高亮。具体参考帮助菜单的语法指南。

谢谢！

**Comment by yousifun** [comment]
好的，非常感谢。已经通过css配置文件设置好了。 @tamlok
