### ISSUE TITLE
不能切换至中文输入法

### ISSUE THREAD

**Issue by caojm** [vnotex/vnote#674]
OS Version (操作系统): Debian Linux 9
VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现):
不能打开中文输入法，编辑模式按Ctrl+Space无反应

How to Repro (如何复现):
编辑模式按Ctrl+Space

**Comment by Memento1990** [comment]
看是不是快捷键冲突了呀~

**Comment by tamlok** [comment]
- 自行编译的还是AppImage？
- Fcitx输入法？`fcitx-diagnose`输出什么？是否正确配置Qt5的配置？

**Comment by zx120144** [comment]
自行编译，fcitx输入下无法切换使用中文输入法

**Comment by tamlok** [comment]
@zx120144 自行编译的需要自己处理一下qt5的fcitx输入法问题。可以搜已关闭的issue，也可以搜网上。qt5的普遍问题，并非vnote特有。

**Comment by zx120144** [comment]
qt5编辑模式下已经能正常切换输入法并键入中文，重新编译了一下vnote，在vnote下仍不能切换使用中文输入法

**Comment by tamlok** [comment]
@zx120144 qtcreator里面能输入中文和编译出来的程序能输入中文是两码事，你再搜一下吧，很多文章介绍的，需要把相关的so文件拷贝到qt对应目录下重新编译。

**Comment by SourceLink** [comment]
参考下这个吧 https://www.jianshu.com/p/8ddbf9d6248a
