### ISSUE TITLE
建议增加导出chm格式的功能

### ISSUE THREAD

**Issue by ssjwap** [vnotex/vnote#678]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):建议增加导出chm格式的功能

How to Repro (如何复现):rt

**Comment by tamlok** [comment]
Hi,

VNote支持自定义导出，可以调用任意的工具进行导出，例如Pandoc来转换成chm。具体参考 https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%AF%BC%E5%87%BA.md#toc_10

**Comment by ssjwap** [comment]
@tamlok 
谢谢，我已经成功的导出成chm格式了。不过通过chm打开每个页面，都会报脚本错误：行386，对象不支持addEventListener。我猜测可能是因为chm的浏览器内核是IE，我是先生成的html，再转成chm，这些html网页应该是对IE支持的不好，可以把转成的html优化一下吗，对IE能支持的好一些呢？
或者就是直接提供导出chm格式最好了，自定义导出感觉很不方便，而且用你说的Pandoc好像没办法导出chm格式。

**Comment by tamlok** [comment]
前端开发对IE都很怕，我就不折腾这个了。
