### ISSUE TITLE
在左侧目录下双击打开md文件会卡顿

### ISSUE THREAD

**Issue by helax000** [vnotex/vnote#680]
OS Version (操作系统): Windows
VNote Version (Help - About VNote - Version: )(VNote版本): 2.3 ,  fcfc1ca9767  etc..

在左侧目录下双击打开md文件会卡死

**Comment by tamlok** [comment]
应该是显卡驱动问题，可以尝试更新显卡，或者设置里面更改一下opengl的值。具体参考文档 https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.md#toc_5
