### ISSUE TITLE
关于增加文档交叉索引和附件信息管理功能

### ISSUE THREAD

**Issue by zhaoruiyang98** [vnotex/vnote#689]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

问题:
目前vnote的笔记之间似乎只能以笔记本树形结构组织，但是有时候需要交叉联系。譬如，在一个笔记内交叉引用/跳转到另外一个笔记，或者一篇笔记和很多其他笔记本中的笔记内容有关联，需要记录这种关联的信息。

附件功能过于简单，如果给一个笔记添加不少附件，有时候需要记录附件相关的信息，记录这些信息需要自定义的简单填表式的功能。

建议:
一个笔记可能会和很多信息关联，我觉得可以将附件、笔记信息、标签这些功能整合起来，作为一个笔记的元数据。界面应该尽可能简单易编辑，下面是文献管理工具zotero的条目信息，这种样式可能可以参考一下？

![(例图](https://user-images.githubusercontent.com/43402887/54898484-7ce10d80-4f07-11e9-9bb6-89c03372ba22.png)

对每个附件提供一个信息档案/只对笔记提供一个可以让用户自己添加栏目（可以做模板之类的），用户可以通过浏览笔记本添加关联的笔记，之后使用时只要点击就能跳转。

笔记内交叉引用的话，onenote有类似的功能，但是可能和markdown兼容性不是很好。

**Comment by tamlok** [comment]
目前vnote可以直接插入另一个笔记的路径，vnote会提示是否插入相对路径链接，插入即可实现关联跳转。

不过路径改动后，会失效。后面会优化。
