### ISSUE TITLE
macOS启动闪退

### ISSUE THREAD

**Issue by hadix-lin** [vnotex/vnote#699]
OS Version (操作系统):  macOS 10.14.4

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3, 通过`brew cask install vnote`安装.

Symptoms (表现):
启动无法显示界面,dock显示一下图标,直接退出.
Vnote -d  输出如下
fail to create shared memory segment
fail to attach to the shared memory segment "QSharedMemoryPrivate::initKey: unable to set key on lock"

How to Repro (如何复现):
启动vnote即可重现.

**Comment by tamlok** [comment]
可能需要重启系统，参考 https://github.com/tamlok/vnote/issues/591
