### ISSUE TITLE
切换笔记本之后，上一个笔记本中打开的文档还显示在标签栏中

### ISSUE THREAD

**Issue by Mlearn** [vnotex/vnote#702]
OS Version (操作系统): Windows 10

VNote Version (Help - About VNote - Version: )(VNote版本): 2.3

Symptoms (表现):

切换笔记本之后，在标签栏中的上一个笔记本中打开的标签页还是存在（显示）的，层级归属比较混乱。

Hope (希望):

将标签页归属到对应笔记本之下。当切换笔记本后，相当于是一个新的工作区，不应该还显示上一个笔记本打开的笔记。

**Comment by tamlok** [comment]
VNote里面编辑区域里面的标签页是自由管理的，不会因为切换目录或者笔记本而强行切换。这应该是一个优点，比如有道云那样是切换文件夹都会将当前打开的文件切换的（没有标签页的概念），而OneNote则是切换笔记本后全部都切换，如果想在两个笔记本的两个笔记之间互相参考，简直是一个灾难。

我了解您说的关于工作区(session)的概念，目前这个还没有在VNote里面支持，但我觉得即使支持工作区，也不应该按照笔记本来强行划分，而是允许用户组合相关的标签页作为一个工作区。

谢谢！

**Comment by Mlearn** [comment]
首先对于您的考虑表示理解。您说的这种场景我确实很少用到，也没有考虑这一点。就软件来说，与别家的不同就是自身的优势。

说一下我自己的看法：
1、一个笔记本代表的含义是说当前笔记本下的内容是同一个领域的知识。不同笔记本之间的笔记间的参考会有，但是概率不知道大不大，另外如果两个不同笔记本之间的笔记间关联性比较强，是否应该放到同一个笔记本内的不同目录下呢？
2、就传统纸质笔记本来说，当我们切换不同笔记本时，我们的整体思路其实是做了一个切换的，如果保留大量的上个笔记本的标签页是否会影响人的思路？同时是不是要考虑一下标签栏的有限空间？
3、对于您说的需求场景，我觉得可以如下实现（不知道难度如何）：a) 可以将上一个笔记本中需要参考的标签固定住，在切换笔记本的时候只有那些没有被固定住的标签才会隐藏；b) 将归属于不同笔记本的标签页设定不同的标签颜色；
4、像您说的，允许用户组合相关的标签页作为一个工作区，是一个很棒的想法。简单点说，可以认为当前显示的所有标签页都属于一个工作区，延申来说，软件可以维护多个工作区，在不同的工作区之间来回切换，而每一个工作区内的标签页又来自于不同的笔记本。。。

最后再次感谢作者带来的好软件，当前版本的功能已经满足我的需求了，会一直用下去的。

**Comment by LuoshuiTianyi** [comment]
那么可以考虑加上一项标签页相关的设置？在几种模式中切换如何？

**Comment by tamlok** [comment]
VNote 3 已经支持工作空间。
