### ISSUE TITLE
能否右键把某个笔记设置成在左侧文件夹树形图中显示出来？把它作为类似文件夹的方式显示出来，不必有后缀，无文件夹图标就能表示是笔记

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#708]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
默认可以隐藏，但最好可以右键设置，让某个笔记本能够像文件夹一样显示到树形图中。

How to Repro (如何复现):
如果能这样，笔记有时能够更加一目了然。树形图中就能看到笔记名字和打开笔记了。

**Comment by tamlok** [comment]
目前暂时不行，后面vnotex会支持

**Comment by ux910** [comment]
需要这个功能

**Comment by tamlok** [comment]
> 需要这个功能

VNote3 默认就是文件夹视图显示。

**Comment by ux910** [comment]
![image](https://github.com/vnotex/vnote/assets/140593906/e2bb2c60-a751-4c9e-b561-3f03e8d74c2b)
类似这种树状模型显示文件的功能
