### ISSUE TITLE
既然文件夹是由json文件记录的，可否让文件夹能支持任意字符？包括不允许作为文件夹名字的字符。实际的文件夹名字可以省略掉这些系统不支持的字符

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#709]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):
这样就不会对文件夹的名字有所限制的了。可以采用任意想用的字符。比如用一个路径名作为文件夹的名字。
由于文件夹名字能够直接显示在树形图中，把路径直接记录在文件夹上，可以更方便查看和复制。
笔记不能显示在树形图中。

由于文件夹名是由joson文件保存，那么应该可以支持文件名中换行等等。

**Comment by HgyHgyHgy** [comment]
由于文件夹名字能够直接显示在树形图中，把路径直接记录在文件夹上，可以更方便查看和复制。
笔记不能显示在树形图中。

**Comment by tamlok** [comment]
VNote的初衷是数据开放透明，能尽量用其他任意编辑器来编辑笔记，所以还是遵循和文件树一一对应的关系吧。现在有一个json文件，很多人都抱怨为啥自己添加了文件但在VNote里面没有展示，如果还不是一一对应的关系，估计很多人都会绕晕了。

**Comment by HgyHgyHgy** [comment]
那么，json文件，不就纯粹造成不便了？
有了它，就不方便用任意编辑器来编辑了。
还不如去掉它，或者发挥它的用途，支持任意文件夹或多行文件夹等等。两个方向都可以选择。不然，不上不下。

**Comment by tamlok** [comment]
就是保持一种折中吧。您说的那个方向，VNote也支持，就是作为一个简单的编辑器来编辑外部文件。如图。所以，VNote可以作为笔记软件，也可以作为编辑器。

![image](https://user-images.githubusercontent.com/5763157/55483505-4c147d00-5659-11e9-9207-3a49d8aa961e.png)

**Comment by HgyHgyHgy** [comment]
这和你说的用任意编辑器编辑，并不是一回事呀。
有了json文件，就不方便用其他编辑器来编辑了。它不会显示所有.md文件，也不会显示所有文件夹。

这个就不上不下了。不能方便用任意编辑器编辑。纯粹造成了不便。
还不如默认全部显示，然后用json文件来实现隐藏功能。

而你提到的那个浏览器界面，为什么不和普通界面一模一样的？只要显示所有文件，功能不就一摸一样的了？

**Comment by tamlok** [comment]
json一个作用是记录标签/附件等信息，一个作用是过滤掉没必要的内容（如附件和图片等文件就不希望被当作笔记来展示）。还是属于一种折中吧。

方便用其他编辑器编辑的意思是万一VNote某天不维护了，也不用担心数据导出或者整理，直接一个编辑器打开整个笔记本文件夹就可以正常浏览和编辑，这个时候json文件已经没用了。而在其生命周期之内，VNote是不希望普通用户绕过VNote软件来编辑和管理笔记的。

VNoteX会将浏览器功能和普通笔记本整合在一起。但VNote暂时不会，因为改动太大了。

**Comment by HgyHgyHgy** [comment]
那通过json文件实现任意文件名有什么害处呢？
在实际的文件夹名字的时候，有些可以用对应的中文字符代替，若不能，可用某个字段代替，比如其中文名代替，比如斜杆，回车。这样也不会影响阅读或使用。

这样避免建立许多不必要的.md文件的需要，比如直接把路径保存在文件夹名中即可，不必再建个md文件来保存

**Comment by Memento1990** [comment]
实现任意文件名有什么意义吗? 之前用过的其他笔记管理软件, 或者其他一些软件, 基本没见过要把目录结构做的这么复杂的. 你说你弄一个 "abc\d", "abc/d", "abc\nd" 的这些特殊字符的文件名, 先不说本地怎么存储有多麻烦, 对于这些名字又有什么意义吗? 如果出现这些情况, 或者你可以转变一个思路, 在同一个笔记文件里, 做好层次结构管理即可.

**Comment by HgyHgyHgy** [comment]
这个还是很有意义的，如果把文件用于记录笔记，而不是分类。
譬如，你记录一下，某个文件在服务器中的路径。如果你把它记到md文件中，那你就需要打开md文件才能看到。
