### ISSUE TITLE
mermaidjs渲染gantt图不支持axisFormat关键字

### ISSUE THREAD

**Issue by XeonForce** [vnotex/vnote#741]
**OS Version : Windows
VNote Version: 2.4**

**Symptoms (表现):**

mermaidjs渲染的甘特图，vnote默认是以周为单位显示横坐标
代码中带上`axisFormat`关键字以修改坐标轴时，vnote无法渲染，直接显示原代码

mermaid已支持该关键字，[相关issue](https://github.com/knsv/mermaid/issues/269#issuecomment-373229136)

**How to Repro (如何复现):**

测试代码
```
gantt
    dateFormat  YYYY-MM-DD
    axisFormat  %m/%d/%Y
    title Adding GANTT diagram functionality to mermaid

    section A section
    Completed task            :done,    des1, 2014-01-06,2014-01-08
    Active task               :active,  des2, 2014-01-09, 3d
    Future task               :         des3, after des2, 5d
    Future task2               :         des4, after des3, 5d
```
移除`axisFormat`后显示正常

**Comment by tamlok** [comment]
Should be fixed after updating the version of Mermaid.
