### ISSUE TITLE
文件列表的显示不够美观，不够容易识别，与文件夹树状图相反，可以考虑改善一下，譬如添加一个适当大小的圆点在文件名之前，引导视力到项目之上

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#776]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
文件夹列表之前的文件夹图标，对引导视力起到不少的作用。
反而文件列表，看起来就比较费力，容易有不适感，视线不容易聚焦于文件名上。

可考虑添加一个适当大小的黑色圆点，与文件名之间具有适当的距离。

这个可以参考一下幕布的小圆点，那个小圆点，对于快速查看项目，起到不少的作用。

目前的文件列表，看起来，有不舒服的感觉。多一个小黑点，会有很大的改善作用。这个黑点的大小，影响也不少。不能太小，也不能太大。

最好是可以选择是否显示小黑点。有可能其他人有不一样的感觉。

浏览界面视图，看起来费力，不容易识别项目，和这个视力引导有很大关系。若把浏览器界面的文件夹图标换为笔记界面的文件图标或者换成小圆点，将有很大的改善。这会让人容易找到所需的项目，容易看到需要看到的内容。

有很多类似树状管理软件，vnote之所以突出，就因为文件夹界面的文件夹图标，对引导视力起到更有效的作用。黄色的文件夹图标，不容易识别得到。（可能一些人对黄色图标比较容易识别，也说不定）反正我感觉黄色文件图标，不容易聚焦。

依此理，看来我应该找个办法把win10默认的文件夹图标替换掉。

How to Repro (如何复现):

**Comment by livingworld** [comment]
1.刚上手接触，感觉这部分确实效率很低，文件列表部分交给键盘上下左右来回切换，或许好于眼睛看着用鼠标点击。
2.workflowy 更简洁一些，或许参考更好一些。幕布这类软件没有学到到workflowy的精髓，多了太多无用的功能，越繁琐就越与简洁的追求背道而驰。

**Comment by HgyHgyHgy** [comment]
没任何突出的标识物。眼睛要移动到文件名开头部分，就不太方便，会费眼神。弄个小圆点或者图标，就会容易许多了。

**Comment by tamlok** [comment]
@livingworld 试试`ctrl-e w`导航模式，或者通用入口。

**Comment by livingworld** [comment]
@tamlok 

谢谢，体验了一下，如果用来定位某一区域或文件还是不错的。不过能像在 windows 下 enter 键进入文件夹后，再立即退出，进入下一个文件夹这种流畅的感觉就太好了。现在无论是笔记、小推车还是其他选中文件的部分，凡是 enter 选中之后，都直接锁定了，而不能立刻解锁，再键盘上下键去打开下一个文件，巡航导览功能的形式效率反而不高。

**Comment by HgyHgyHgy** [comment]
> @livingworld 试试ctrl-e w导航模式，或者通用入口。

不是点击或者选定的问题，主要是查看的问题啦。就像ppt中，有一个圆点，就更容易分辨条目。建议加个圆点。不加圆点，也可以和文件夹那样，有一个方形的图标也可以。

**Comment by tamlok** [comment]
Fxied
