### ISSUE TITLE
代码块显示行号后，空行会多一个空格

### ISSUE THREAD

**Issue by agppp** [vnotex/vnote#779]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.4

Symptoms (表现):
为代码块设置显示行号后，空行会多一个空格

How to Repro (如何复现):

不显示行号的时候，空行是正常的
![图片](https://user-images.githubusercontent.com/10527860/57203347-e150bb80-6fe1-11e9-8063-132ad73d2e76.png)

显示行号后，空行会多一个空格
![图片](https://user-images.githubusercontent.com/10527860/57203374-283eb100-6fe2-11e9-8e5a-c34f569988de.png)

**Comment by tamlok** [comment]
Hi,

VNote use this [plugin](https://github.com/wcoder/highlightjs-line-numbers.js/) for line numbers in highlight.js. Maybe we should report to upstream and fix it in the upstream.

**Comment by tamlok** [comment]
Should be fixed now.
