### ISSUE TITLE
建议缩小编辑模式下标题样式的字体大小，目前字体太大

### ISSUE THREAD

**Issue by Thomas-trian** [vnotex/vnote#796]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
编辑模式下标题字体太大，显得不和谐，而且极度引人注意。
建议缩小标题样式的字体大小。

How to Repro (如何复现):
从阅读模式进入编辑模式

**Comment by tamlok** [comment]
我以为标题就是要引人注目的。

可以自定义样式，修改主题下面的mdhl文件，具体看官方文档。

谢谢！

**Comment by jackydi** [comment]
就是要引人注目的，一看就知道是标题

**Comment by HgyHgyHgy** [comment]
是不和谐，和太引人注意。想看标题，也不用那么大呀！为什么要不断注意它？
过度，就没那么好了。这个可以参考ppt.

**Comment by beetaa** [comment]
修改主题的mdhl文件：

```css
H1
foreground: 999999
font-style: bold
font-size: +6

H2
foreground: 999999
font-style: bold
font-size: +5

H3
foreground: 999999
font-style: bold
font-size: +4

...
```

修改后需要重启生效。
