### ISSUE TITLE
使用git做同步时，_vnote.json不能忽略

### ISSUE THREAD

**Issue by xvusrmqj** [vnotex/vnote#803]
目前使用git同步时，不能将_vnote.json文件忽略（即添加到.gitigonre文件中）。如果忽略的话，vnote就不能识别新pull过来的md文件。

但是不将其忽略的话，因为它是自动生成的文件，所以每次更新它都会变，每次都需要提交一个生成的文件，这块感觉用着不太舒服，不知道有没有好的解决办法？

**Comment by tamlok** [comment]
这个是索引文件，同时保存笔记的元数据，是笔记本数据的一部分，肯定是不能忽略的。多提交一个文件感觉还好吧？

如果实在觉得不舒服，可以不用笔记本，直接编辑外部文件，把vnote当做一个编辑器使用。左侧面板第三个tab是浏览器功能，能列出一个目录树结构。缺点仅仅是不能使用附件和标签。

**Comment by tamlok** [comment]
你可以新建一个sh或bat脚本笔记，vnote里面不能编辑，使用外部编辑器编辑，自动把这个笔记本目录的都add到index里面并提交。每次在vnote里面点击笔记或指定外部程序打开，估计就可以运行这个脚本。

**Comment by xvusrmqj** [comment]
> 这个是索引文件，同时保存笔记的元数据，是笔记本数据的一部分，肯定是不能忽略的。多提交一个文件感觉还好吧？
> 
> 如果实在觉得不舒服，可以不用笔记本，直接编辑外部文件，把vnote当做一个编辑器使用。左侧面板第三个tab是浏览器功能，能列出一个目录树结构。缺点仅仅是不能使用附件和标签。

能否像zim wiki那样，索引用sqlite保存，这样数据根目录中就完全是md文件了。这样的好处是数据很纯粹，不需要提交生成的文件，而且可以把用任何文件管理器做为文档的查看器。

**Comment by xvusrmqj** [comment]
> 你可以新建一个sh或bat脚本笔记，vnote里面不能编辑，使用外部编辑器编辑，自动把这个笔记本目录的都add到index里面并提交。每次在vnote里面点击笔记或指定外部程序打开，估计就可以运行这个脚本。

你的意思是提交的时候忽略_vnote.json文件，但是有一个脚本每次pull下来时运行一下能自动生成这个文件，生成之后再用vnote打开笔记本？

**Comment by tamlok** [comment]
提交不能忽略json文件，但你可以用一个脚本文件来自动化提交所有改动。

使用sqlite之类的是一种退步呀，vnote就是希望能够使用纯文本这种开放的数据结构来保存数据和信息，这样即使vnote后面不维护了，用户的数据也是用户的，用户很容易就可以读取和维护自己的数据。

比如现在你想绕过vnote添加一个笔记，那修改一下json文件即可。如果用数据库，那就不能办到了。仅仅是多一个json文件而已，用编辑器打开应该也不算太混乱。

**Comment by xvusrmqj** [comment]
其实也还好，**不过_vnote.json比markdown文件还多**，在github中用ostree插件查看是这样的。
![image](https://user-images.githubusercontent.com/2316516/58178011-fb73e480-7cd7-11e9-9776-f70fcf647103.png)

用sqlite只保存元数据，而不保存数据文件，我觉得这也是一种很好的办法，即使不用sqlite，把元数据统一放到根目录可以吗？我只是说一下我的想法，vnote还是我见过最好的笔记软件。

又或者将vnote自动检测数据文件变化，自动生成vnote.json文件。即同步过来的md文件即使没有元数据，也会自动生成，也不会影响它在笔记本中的可见性，即自动生成元数据，自动导入。不需要将元数据文件同步。这样最好了。

**Comment by tamlok** [comment]
现在vnote的架构改起来代码改动太大了，后面vnotex里面可以考虑集中化索引文件。

**Comment by tamlok** [comment]
vnote提供一个文件树浏览外部文件的，这样不会有元数据生成，你可以试一下。在左上角能切换。

**Comment by HgyHgyHgy** [comment]
那个浏览器，能否不显示哪些json文件以及json文件夹。显示它们完全一点用处都没有。
而且那个浏览器，似乎不能使用快捷键新建文件夹。
还有根目录路径和图片文件夹，占用了许多空间，同时也分散注意力。
还有md文件之前的图标也不美观。在笔记本视图，那条灰线感觉没什么问题，但在浏览器视图，就感觉那条灰线颜色太浅了。
我感觉那个文件夹的图标起了很重要的作用。
在浏览器视图，虽然我把图标改成了和笔记本视图一样的图标。由于有其他文件图标的存在，导致美观性，易识别方面有了很大的下降。
而且这个浏览器视图的快捷键支持方面也十分不足。

**Comment by HineBlack** [comment]
嗯，而且用浏览器的话，Ctrl+G 搜索起来没有在笔记本中搜索那么方便，支持集中化索引文件的思路。

**Comment by Creling** [comment]
> 
> 
> 你可以新建一个sh或bat脚本笔记，vnote里面不能编辑，使用外部编辑器编辑，自动把这个笔记本目录的都add到index里面并提交。每次在vnote里面点击笔记或指定外部程序打开，估计就可以运行这个脚本。

目前采用了这个方案，运行良好，附bat脚本如下
```
@setlocal EnableDelayedExpansion
cd /d %~dp0
git add .
set _date=%date:~3%
set _time=%time:~0,8%
set msg=%_date% %_time%
git commit -m"%msg%"
git push
```
