### ISSUE TITLE
vnote的一个突出的优点是在于界面方面好看。但也有改善的空间。

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#805]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
比如文件夹视图，都市黑白的，这有利于阅读。
问题是为什么笔记本那行，以及笔记本部分却出现了彩色的显示。如果说笔记本，浏览器切换等等，采用绿色，容易找到它的位置，下方的笔记本也采用绿色字体就不太好。
保持全部都是黑白感觉最好。
还有笔记本名字下方有一行，叫文件夹。这个是否有必要。比较去掉它和保留它的效果对比了吗？

不过，这些都是小问题，感觉vnote笔记本的真个界面都差不多都是黑白色，还是比其他软件要好。
此外，既然浏览器界面，有可以切换根目录的功能，笔记本界面应该也有这个功能，并支持快捷键。

win10可以开启一个黑白模式，发现开启黑白模式后，vnote的界面更好看了。
但在其他地方，黑白模式却有害处。比如这个git评论系统，那个update comment的绿色还是有积极作用。网页的许多地方的彩色，也有助于引导视线。

How to Repro (如何复现):

**Comment by HgyHgyHgy** [comment]
由于win10文件浏览器，支持了文件快速预览。使得使用txt文件变得十分方便。问题是其文件夹视图，还是vnote好，vnote的文件夹视图还是十分美观的。

**Comment by tamlok** [comment]
😂您的几个issue我都看了啦，就不一一回复了，我后面设计vnotex的时候会参考（比如界面都用黑白）。vnote由于代码耦合问题，目前暂时就不会有太大改动了，主要精力都在vnotex上面。

非常感谢您的建议！另外，有些问题如果能上个截图说明一下就更清晰了。😁

**Comment by tamlok** [comment]
现在就是全黑白了
