### ISSUE TITLE
关于文件夹的重新分类，对于已经按一个标准分类组织的文件夹，希望以另一个标准分类

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#813]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
如果只是简单地把文件夹复制粘贴到新的分类中，那么如果对某些内容更新了，在另外的分类中的内容不会更新。通过复制文件夹快捷键的方式，可以避免这个问题。但问题是vnote不能把文件夹快捷方式当作文件夹对待。

建议增加一个文件夹链接的功能，让文件夹链接具有和文件夹一模一样的的功能。不必有符号显示其是文件夹链接而不是文件夹。若链接的文件夹，本来就是vnote内的文件夹，那么它应该能正确识别相关的json文件，然后正确显示其下级文件夹以及文件。
这样就容易重新分类文件夹了。

如果文件标签对于文件夹也适用，能够一定程度地实现目的。但还是不如文件夹链接更好。

感觉用得最多的是vnote的文件夹功能，而不是md文件。md文件要额外点击才能打开。也没下级文件的概念。

How to Repro (如何复现):

**Comment by xvusrmqj** [comment]
这个是标签要做的事情吧！

**Comment by tamlok** [comment]
后面支持文件夹标签吧，快捷方式这种比较容易混淆。

**Comment by xvusrmqj** [comment]
目前好像还没有笔记使用软链接的方式来处理文件组织问题的。基本都是树形结构＋标签这两种组织方式。印象笔记使用的是树形标签，这种可能你是想要的功能，它的底层或许是用你说的软链接的方式来实现的。

**Comment by xvusrmqj** [comment]
> 后面支持文件夹标签吧，快捷方式这种比较容易混淆。

感觉文件夹还是不要支持标签，因为文件夹和标签是两种组织方式。它们应该是正交的。

**Comment by HgyHgyHgy** [comment]
windows自身就能够用快捷方式组织文件夹，问题只是在于显示的问题。

具体说来，就是如何用树状列表适当显示含有快捷方式的文件夹的问题。

只要vnote把文件夹的快捷方式当作文件夹一样显示即可。
其他操作方面，就用windows默认的操作即可。

文件夹快捷方式，只是一个快捷方式。删了它，不等于删除原来的文件夹。
但打开它后，更改里面的内容，删除里面的内容，这个不涉及文件夹快捷方式本身。

vnote的文件夹树形视图，本身就适合用来记录笔记，设置不必有md文件。
其他软件的文件夹视图，远远没有vnote的好看。
当然，其他笔记软件的树形笔记，也可以很好看。比如notekeeper。
但问题是它不是以文件夹记录内容，虽然也可以添加附件。但无法从外部搜索和打开相关的文件。
譬如你存一个excell文件，你就不容易更新其内容，也不容易用everything搜索其内容。

vnote的一个突出优点，就在于用文件夹记录内容，可以方便添加或更改其内容。在其中的文件，可以用外部程序打开和处理。

既然文件夹是vnote的关键优点，其功能应该增强。

其他软件，并不把文件夹用于记录笔记，导致多数软件的文件夹视图都不美观和方便记录内容。

如果你只是把vnote作为记录内容，不用于处理和分析内容，可能会感觉不到重新组织文件夹的必要性。

文件夹标签，也并不能重新组织内容，除非是树形标签。但就算是树形分级标签，也无法达成和文件夹快捷方式一样的功能呀。你不能把标签显示在某个文件夹底下，也不能改变调整其结构。

vnote用文件夹的形式保存内容，方便用作最高层的管理系统。支持快捷方式，就能方便调用其他软件和数据。
由于vnote不是可以把文件夹当作笔记本直接打开，导致vnote不容易作为其他系统的一个部分。
如果vnote能够打开任意文件夹当作笔记本打开，并在其中编辑，新建子文件等等，那vnote就能作为其统一系统的一个部分。还是比较希望增加这样的一个功能。比如，你想在某个目录底下处理数据，然后你可以新建一个文件夹，然后用vnote打开，然后在vnote中新建若个子文件夹分类，然后新建若干excell文件处理数据。既然笔记本本质上就是文件夹，那么vnote应该可以用于打开任意文件夹。
现在也可以这样做，但这会导致vnote中有数不清的笔记本，你要打开它，就麻烦了。
因为那个笔记本本身并不是一个树形的结构，而是一个平行的结构。

**Comment by tamlok** [comment]
浏览器功能就可以吧？

**Comment by tamlok** [comment]
@HgyHgyHgy 另外也可以看看win的软硬链接之类的，https://www.cnblogs.com/Akkuman/p/9688311.html，看能不能满足需求吧。

vnote里面左侧面板第三个tab是浏览器功能，能浏览本地文件，看来看去感觉也满足你的需求：

![image](https://user-images.githubusercontent.com/5763157/58447099-ee228400-8135-11e9-9f13-c3061284cdca.png)

**Comment by haskio** [comment]
类似win10中文件管理器中的创建一个快速访问的概念？

**Comment by tamlok** [comment]
@haskio 在第二个tab历史文件里面，可以钉住常见文件。

**Comment by HgyHgyHgy** [comment]
这个符号链接，是能解决快捷方式打不开的问题。
浏览器界面，也能够直接把符号链接作为子目录显示。

笔记本界面，也支持这个符号链接。可以把链接作为子目录显示。从功能上，确实完全解决了问题。
但问题是要修改json文件。
这样很不方便呀。你要重新组织文件夹，是要方便快速地复制粘贴，比如win+c复制，win+v粘贴到当下目录底下。
通过ahk，应该也能办到。先复制一个符号链接，然后再粘贴，再更新json文件。
这样基本的功能，还是希望能够内置支持呀。而且，内置支持，还可以在粘贴的时候，用一个特别一点的图标标记出它是符号链接。以便能够可以放心删除它。不然，vnote中都分不清它是符号链接，还是真实的目录。

这个功能其实很有用处的。
比如你一个编译目录底下，有一大堆的文件，你通过符号链接，就能方便导入某个目录的内容了。

**Comment by tamlok** [comment]
用浏览器功能浏览外部文件为啥还要修改json文件呢？

**Comment by tamlok** [comment]
你这种应用场景就老老实实用浏览器功能编辑外部文件好了，vnote笔记本不是设计为这样使用的。

**Comment by HgyHgyHgy** [comment]
#IfWinActive,VNote
!c::
send,^0
send,^c
sleep,300
start_pos:=InStr(clipboard,"[")
end_pos:=InStr(clipboard,"]")
folder_path:=SubStr(clipboard, start_pos+2, end_pos-start_pos-3)
StringReplace, folder_path, folder_path, /, \, All
clipboard=%folder_path%
send,{ctrl up}
Return
#IfWinActive,VNote
!v::
Original=%clipboard%
send,^0
send,^c
sleep,300
start_pos:=InStr(clipboard,"[")
end_pos:=InStr(clipboard,"]")
folder_path:=SubStr(clipboard, start_pos+2, end_pos-start_pos-3)
StringReplace, folder_path, folder_path, /, \, All
Run, *RunAs C:\junction64.exe "%folder_path%\test" "%Original%", , , ;
send,{ctrl up}
Return
复制粘贴，都可以，就差更新json文件了。

**Comment by HgyHgyHgy** [comment]
{
    "created_time": "2019-05-29T22:13:58Z",
    "files": [
    ],
    "sub_directories": [
        {
            "name": "(问题)"
        }
    ],
    "version": "1"
}
和
{
    "created_time": "2019-05-29T22:13:58Z",
    "files": [
    ],
    "sub_directories": [
        {
            "name": "(问题)"
        }
    ],
    "version": "1"
}
这个自动更新json文件很难做到呀！明明内容看起来一模一样，vnote自己产生的，或者在其产生的基础上用记事本编辑的，可以正确识别。用脚本产生的，就不能识别。用记事本编辑一下后保存，依然不能识别。
之前就发现用ultraedit编辑后，保存的格式vnote不能识别。后用记事本编辑后的可以识别。用记事本编辑不能识别的json文件后保存，依然不能识别。
而且这个json的格式好复杂，只有一项的时候，没有逗号，有多项的时候，前面的有逗号，后面的没逗号。
有那么多的符号。就不能一个个列出来就好了？

**Comment by HgyHgyHgy** [comment]
;#Include C:\software\建立符号链接\TF-master\TF-master\tf.ahk
#IfWinActive,VNote
=::
Original=%clipboard%
SplitPath, Original, name, dir, ext, name_no_ext, drive
send,^0
send,^c
sleep,300
start_pos:=InStr(clipboard,"[")
end_pos:=InStr(clipboard,"]")
folder_path:=SubStr(clipboard, start_pos+2, end_pos-start_pos-3)
StringReplace, folder_path, folder_path, /, \, All
send,{Tab} ;generate json file
sendinput,(%name_no_ext%){Enter}
sleep,300
FileRemoveDir, %folder_path%\(%name_no_ext%),1
sleep,500
send,{ctrl up}
Run, *RunAs C:\junction64.exe "%folder_path%\(%name_no_ext%)" "%Original%", , , ;
;F=%folder_path%\_vnote.json
;N_lines:=TF_CountLines(F)-3
;Msgbox %N_lines% 
;N_end:=N_lines+2
;Insert_text=            "name": "(%name_no_ext%)"
;Msgbox %Insert_text%
;TF_InsertLine("!" . F,%N_lines%,%N_lines%,Insert_text)
;TF_InsertLine("!" . F,6,6,"        }")  
;TF_InsertLine("!" . F,6,6,Insert_text) 
;TF_InsertLine("!" . F,6,6,"        {")
Return
换一个顺序可以曲折实现功能。

**Comment by HgyHgyHgy** [comment]
从磁盘重新加载，似乎没有快捷键。
