### ISSUE TITLE
刚刚发生了一次文件夹内容丢失的事情，vnote自动删除了一个文件夹底下的几个文件，并且其json文件被删除了

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#817]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
虽然该文件夹不重要，但以前没出现过这种删文件的情况发生。
该文件夹里的其中一个文件，还用其他软件打开了。
好像问题是由于文件夹中的文件长时间打开导致的。
电脑没发生死机的情况。
可能发生过vnote删除文件失败的情况发生。
但我以为删除失败，最多是删掉了json文件，而不会丢失文件。
不清楚为什么会发生这种情况。
查看_v_recycle_bin，只有一个删除了的文件，并无其他被错误删除了的文件。其中一个文件，还是正在打开未保存的文件。行为十分怪异。
难道json文件出错后，会导致vnote删除文件夹底下的文件？
这个隐患很大呀！
vnote不应该根据json文件来删除文件，而只应该在vnote中下达删除命令的时候，才删除文件。
万一json文件由于不知名原因出错了，就可能出现我现在这种自动删除文件的事情发生了。

感觉这个还是与删除文件失误导致的一连串错误。以前只是导致了错误，因为文件夹底下并无文件。今天第一次发生了文件夹底下文件丢失的情况。
这个删除机制要改善呀。

通过检查电脑回收站，还是可以找回被删除了的文件。
How to Repro (如何复现):

**Comment by tamlok** [comment]
vnote并不会自动删除笔记文件（只会自动清理图片文件）。而且，如果是vnote删除的，那肯定不可能在系统的回收站里面找到（早期就有用户误删整个d盘，找不回来，所以才添加了笔记本回收站的功能）。所以，可以怀疑一下是不是其他软件删除的。

**Comment by HgyHgyHgy** [comment]
这个肯定是vnote删除的。一个正在用其他软件编辑的文件，都被删除了。
而且，我测试了一下，先新建一个xlsx文件，然后再用vnote删除，可以在回收站能找到刚删除了的文件，删除时间就是现在。
我同时测试了一下新建一个md文件，然后用vnote删除，对于md文件，确实在回收站找不到md文件。
vnote肯定存在某些机制会导致删除文件。json文件出现过多次自动被删除了。这次是第一次其他文件被删除。

**Comment by tamlok** [comment]
鉴于你的使用场景比较复杂和多样，请给我一个能复现的具体步骤吧。

**Comment by HgyHgyHgy** [comment]
尝试了，手动删除json文件，或者手动删除json文件中的某一项目，并不会导致文件被删除。
删除文件失败，也不会导致json文件被删除，或者文件夹底下的文件被删除。

搞不清楚json文件或底下文件被删除的原因。
这应该和使用不是md文件有关。

复现，多使用不是md文件的其他格式文件，过一段时间，就会遇到这种问题。

既然唯一会自动被删除的文件是图片文件，有没有可能它把其他文件和json文件当作图片文件删除了？
为什么md文件删除，不会回到回收站，其他格式文件删除，就会回到回收站？

**Comment by tamlok** [comment]
vnote删除的文件真的不会到系统回收站的。如果到回收站，当初就没必要开发笔记本回收站了。

**Comment by HgyHgyHgy** [comment]
重新确认了一下，发现确实不会回到系统回收站。
那个文件是为了新建.xlsx而导入的同名文件，并非是被删了的文件。
由于那几个文件不重要，我没实际还原那几个文件，所以以为是删除到回收站了。
那不会回回收站，也不在笔记本回收站，不是更加危险了？

**Comment by tamlok** [comment]
你得给我一个明确的1/2/3/4步骤去复现这个问题，我才能知道是什么问题。我这边没有出现过自动删除文件的情况。目前已知bug是如果开启自动保存，会有概率误清除图片。其他暂时没遇到。
