### ISSUE TITLE
macOS Mojave 无法访问本地文件

### ISSUE THREAD

**Issue by gzqx** [vnotex/vnote#824]
OS Version (操作系统):macOS Mojave Version 10.14.5

VNote
Version: 2.3

Symptoms (表现):
无法browse本地文件系统
一旦企图插入图片时browse或者导出到PDF选择路径时browse即会直接卡死
但是拖动图片插入文档没有问题

How to Repro (如何复现):
如上，反复尝试均立即复现

**Comment by tamlok** [comment]
最新版试了一下没有问题。如果有问题欢迎再提issue.
