### ISSUE TITLE
智能表格的问题

### ISSUE THREAD

**Issue by jackydi** [vnotex/vnote#832]
OS Version (操作系统): Windows10

VNote Version :2.5

Symptoms (表现):

默认开启了智能表格功能，在表格中对内容加粗时，可能会删掉单元格中的内容。本来想抓个视频的，但又不知道上传到到哪里，只好语言描述一下了。

How to Repro (如何复现):

1. 打开智能表格功能。
2. 新建一个4*4的表格，在每个单元格中都填好内容。
3. 把2~4行的第二列单元格中的内容加粗（其实第几列应该都行，但必须是同一列）。
4. 下面是重点，一定按着说明来操作：在第二行第三列单元格的**内容前面**添加两个星号，必须是手动添加星号，然后这个单元格，及该行之后所有单元格的内容都被自动删除了。

测试了多次，都是这样。

发现了一个规律，只要在需要加粗的单元格前已经有加粗的单元格了，**下一行也有加粗了的单元格**，就会出现上面的问题。把第二行和第四行的第二列加粗，如果再加粗第二行的3、4列则不会出现问题，但是如果要加粗第三行的内容时就会出现上面的问题。

关闭智能表格就没有这些问题了。

**Comment by jackydi** [comment]
在上面的测试中，如果是先在内容的后面添加星号，再添加前面的星号，则不会出现问题。

**Comment by tamlok** [comment]
Hi,

这个是因为当输入*号时，这一行的两个*和下一行的两个*被解析成一个元素了，所以就在一个单元格里面，然后智障表格功能就会认为这一行的表格单元格数量不够，所以会自动补齐。 2.7里面会有一个延时然后才开始调整，所以目前只能在这个时间内赶紧把*号都输入完整了。

**Comment by jackydi** [comment]
> Hi,
> 
> 这个是因为当输入*号时，这一行的两个*和下一行的两个*被解析成一个元素了，所以就在一个单元格里面，然后智障表格功能就会认为这一行的表格单元格数量不够，所以会自动补齐。 2.7里面会有一个延时然后才开始调整，所以目前只能在这个时间内赶紧把*号都输入完整了。

1. 自动补齐单元格数量的时候为啥要把后面单元格的内容全部删除呢？最多也就是把|号换成\|呗，这个我觉得是比较合理的。
2. 自动调整之前使用一个延时是一个办法，但是我觉得不太好。针对我遇到的这种情况，可以判断同一行后面是否还有|号，如果有的话就不应该把下一行的两个*号连接到本行的*号上，没有的话可以连接为一个元素。
3. 这个**智障表格**是你故意的么？`(*∩_∩*)′

**Comment by jackydi** [comment]
而且这个延时也不好确定，有的人写的快些，有的人写的慢些，不能保证都会在这个延时时间内把*号都填上。

**Comment by freelyhx** [comment]
> Hi,
> 
> 这个是因为当输入*号时，这一行的两个*和下一行的两个*被解析成一个元素了，所以就在一个单元格里面，然后智障表格功能就会认为这一行的表格单元格数量不够，所以会自动补齐。 2.7里面会有一个延时然后才开始调整，所以目前只能在这个时间内赶紧把*号都输入完整了。

现在智能表格格式对齐之前加了延时是吗？我说怎么从2.4版本更新到2.7版本之后，表格自动对齐很慢，这个能加个配置吗？是否开启表格的延时或者手动设置延时时间。
个人不太喜欢延时，会给我一种很卡顿的感觉，如果有延时设置，可以自动关闭或者减少延时时间就太好了

**Comment by tamlok** [comment]
@freelyhx 是加了一个延时

`vnote.ini`加添一行自己配置：

https://github.com/tamlok/vnote/blob/add2e47f918b53f7c9095a7b7961d0d79b172062/src/resources/vnote.ini#L362

**Comment by freelyhx** [comment]
> @freelyhx 是加了一个延时
> 
> `vnote.ini`加添一行自己配置：
> 
> https://github.com/tamlok/vnote/blob/add2e47f918b53f7c9095a7b7961d0d79b172062/src/resources/vnote.ini#L362

好的，多谢
