### ISSUE TITLE
新增快捷键提议

### ISSUE THREAD

**Issue by xx299x** [vnotex/vnote#833]
![image](https://user-images.githubusercontent.com/23482348/58966888-b080c380-87e5-11e9-8bea-7f46b9c85b46.png)

如图所示，有些时候会为了查找一些文档而打开很多的文档，这个文档都会被打开，导致标签栏有巨多的文件，然而我我发现并没有设置相应的快捷键，我翻阅了文档的自定义快捷键部分，也不知在哪里添加，或者不支持。希望能得到解答
感谢您的付出！

**Comment by HgyHgyHgy** [comment]
可以设置关闭一个文档的快捷键，然后用ahk实现关闭所有标签的快捷键。

当然，如果能内置支持，自然更好。
有好多操作都没快捷键支持。只能右键点击。

**Comment by HgyHgyHgy** [comment]
建议增加一些快捷键，建议在自定义快捷键的地方为所有可能的操作都建立快捷键。

**Comment by tamlok** [comment]
Fixed fa7dd8c541c85c7a504cface9029b96ccbbed8b8

需要自行修改配置文件添加：

![image](https://user-images.githubusercontent.com/5763157/130316769-dbccf086-f463-4b74-a528-43e5ba679310.png)
