### ISSUE TITLE
Mermaid gantt 不支持 axisFormat 参数

### ISSUE THREAD

**Issue by liguang4lg** [vnotex/vnote#838]
OS Version (操作系统): Windows10 64bit

VNote Version (Help - About VNote - Version: )(VNote版本): 2.6

Symptoms (表现):
Mermaid gantt 不支持 axisFormat 参数, 但[Mermaid Live Editor](
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)是支持的.

How to Repro (如何复现):
```
gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    axisFormat %Y-%m-%d
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 20d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d
```

**Comment by tamlok** [comment]
这个应该是新加的特性，VNote自带的Mermaid版本可能比较旧，后面更新一下。
