### ISSUE TITLE
vnote的界面，能够为半屏使用优化一下？我一般把它放到左半屏，这样可以同时在右半屏查看其他

### ISSUE THREAD

**Issue by HgyHgyHgy** [vnotex/vnote#846]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
md在半屏显示时不会自动换行。会显示不全，对于半屏使用不友好。
vnote也并非对于半屏完全没有适应，但适应不全，依然会出现内容超出窗口的情况发生。其换行不能完成得很好。
md是纯文字，并无图片

如果换行调整比较麻烦。
是否可以把md编辑窗口在第二个屏幕显示？

或者md编辑界面和文件夹界面可以通过快捷键切换，这样就都能占满半个屏幕。譬如在md界面，加一个按钮，切换其是否占据整个vnote窗口，以及还原窗口。
这样对于半屏使用，会更友好一些。

How to Repro (如何复现):

**Comment by tamlok** [comment]
能截图说明一下怎么不换行吗？我使用过程中没有遇到这样的问题。github issue直接粘贴图片可以上传。

`ctrl-e e`即可把编辑窗口最大化。

**Comment by HgyHgyHgy** [comment]
建一个md文件，粘贴下面内容：
/lustre/atlas/proj-shared/fus049/guiyang/UC/444/binding_energy/2VumVc
然后把vnote在左半屏显示，就能看到换行不完全了。
也不是完全不换行。
![image](https://user-images.githubusercontent.com/46931372/59401003-49c05480-8d67-11e9-995e-7dcd72590f21.png)

**Comment by tamlok** [comment]
新版无法复现。
