### ISSUE TITLE
希望添加代码段注释里可以写MathJax  公式

### ISSUE THREAD

**Issue by feixin620** [vnotex/vnote#863]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):

How to Repro (如何复现):

**Comment by LuoshuiTianyi** [comment]
这并不符合 markdown 的语法，markdown 在引进 MathJax 数学公式后就一直不允许在代码块内使用数学公式 = =

**Comment by tamlok** [comment]
代码块的意思就是允许你在里面写任意字符都会保留为纯文本，所以对于标准Markdown来说，代码块里内嵌公式是办不到的~

**Comment by jdhao** [comment]
提问提前自己做点功课不好吗。。
