### ISSUE TITLE
是否可以支持自定义mermaid版本或者本地路径呢？

### ISSUE THREAD

**Issue by isr4z6er** [vnotex/vnote#884]
很好用的软件，感谢！

目前mermaid最新版本到8.0.0了，支持比如类图之类的，感觉渲染要比PlantUML快很多。不知道之后是否可以支持自定义mermaid本地路径呢？

**Comment by tamlok** [comment]
下一个版本我尝试更新到最新版本，自定义要等后面再做了。

**Comment by tamlok** [comment]
VNote 3 已经支持自定义路径
