### ISSUE TITLE
2.7内容丢失

### ISSUE THREAD

**Issue by Chen-gjy** [vnotex/vnote#901]
OS Version (操作系统): manjaro

VNote Version (Help - About VNote - Version: )(VNote版本):2.7

Symptoms (表现):
6万左右的内容保存后,过段时间重启机器,内容变成了2万.这个问题我在2.4也遇到过.
抱歉,不得不承认你是个优秀的开发者.但是我已经暂时不考虑使用了.希望你能在后续的版本发现这个隐藏的问题.

How to Repro (如何复现):不知道

**Comment by livingworld** [comment]
@tamlok 

OS Version (操作系统): windows7

VNote Version (Help - About VNote - Version: )(VNote版本):2.7

Symptoms (表现):

问题同上，多次打开保存同一文件，写了好多内容了，今天正常保存，打开后什么都没有了，哭~已经不是第一次了，若有版本管理该多好。

**Comment by tamlok** [comment]
@livingworld VNote版本是？具体操作步骤？实在是复现不了问题，我也没好办法呀！

**Comment by livingworld** [comment]
@tamlok 2.4 版本，就是突然跳窗提示要删除所有照片，我并没有删除图片，我选择关闭弹窗。在关闭文本时，提示保存，然后一保存，瞬间文件大小就变成零了。

**Comment by tamlok** [comment]
@livingworld 建议更新到2.7.2再看看，之前有一个原因是同时在两个标签页打开同一个文件，从而造成内容丢失。这个已经修复。

**Comment by livingworld** [comment]
@tamlok 好的，谢谢咯，这个问题我也检索到了，我更新升级咯，不过我记得自己没有并没有同时打开两个，我再用用吧，看还会不会碰到这个问题。
