### ISSUE TITLE
编辑模式下的表格和正文用的不是同一种字体？

### ISSUE THREAD

**Issue by hexawing** [vnotex/vnote#917]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1.

Symptoms (表现):
我选了一个「汉字宽度严格等于英文二倍」的字体（Mplus 2m），但是第二行的“| :--: |”和第三行的“| 内容 |”，明明应该对齐的可就是对不齐。虽然智能表格已经相当智能了，但这一点点对不齐让一个强迫症患者还是有点不爽。

我在正文里打“:--:”和“内容”，是能够对齐的。

![](http://wx3.sinaimg.cn/mw690/53170997gy1g5l9pfpw8cj205z051t8m.jpg)

仔细观察了一下我发现似乎是表格里用的宋体，而正文里用的是我选的那个字体。（可按道理来说，宋体不也应该是「汉字宽度严格等于英文二倍」的字体吗？）
How to Repro (如何复现):

**Comment by tamlok** [comment]
你需要编辑主题所属的`*.mdhl`文件改变样式，具体参考[文档](https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E4%B8%BB%E9%A2%98%E5%92%8C%E6%A0%B7%E5%BC%8F.md#toc_8)

**Comment by hexawing** [comment]
> 你需要编辑主题所属的`*.mdhl`文件改变样式，具体参考[文档](https://tamlok.github.io/vnote/zh_cn/#!docs/%E7%94%A8%E6%88%B7/%E4%B8%BB%E9%A2%98%E5%92%8C%E6%A0%B7%E5%BC%8F.md#toc_8)

谢谢！我去研究一下怎么玩，好像有点小复杂的样子……

**Comment by tamlok** [comment]
比如说你需要修改这一行来改变表格的字体：

https://github.com/tamlok/vnote/blob/782ee5995d359a00f4526563118dcf7a8f6d7b63/src/resources/themes/v_pure/v_pure.mdhl#L204
