### ISSUE TITLE
希望快捷键和vim保持一致

### ISSUE THREAD

**Issue by nber1994** [vnotex/vnote#927]
OS Version (操作系统): macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2
首先感谢作者的杰出贡献，我现在所有的日常note都已经深度依赖vnote了，同时我也是vim的深度用户。但是在使用过程中，还是希望mac下的ctrl键位仍然是ctrl，而不是Command键。同时希望把窗口相关的快捷键与vim保持一致，这样迁移起来是十分顺畅的。

**Comment by tamlok** [comment]
Hi，

在编辑器里面，mac下的ctrl应该也还是ctrl，不过其他窗口的`ctrl+j/k`可能不一定一致。

其他需要保持一致的快捷键有具体例子吗？列出来，讨论一下看看。

谢谢！

**Comment by nber1994** [comment]
hi,

首先ctrl键，在除了编辑模式以外，例如进入舰长模式的快捷键是Ctrl E但是mac下就是command E这类的。希望和vim保持一致，不用Command而用Ctrl。

保持一致的例子，
1.印象比较深刻的一个是，对于窗口操作，例如分割，移动与大小调整等，采用vim的Ctrl W快捷键。如果能实现的话，我个人认为会是一个很棒的功能。例如下图中的1234可以看做4个不同的窗口，通过Ctrl+W J等快捷键来切换窗口等操作
![image](https://user-images.githubusercontent.com/19227901/62764252-0280e680-bac0-11e9-9de3-fca55ab90e7b.png)
2.另一个就是tab切换，希望能和vim保持一致，支持gt Gt等操作

另外：
想和您了解一下vnote的设计哲学与定位。现在个人感觉vnote的功能很多平常都使用不到，例如灵犀页，片段等。能否出一个lite版本，只专注于文本的编辑，极简那种，大小也会更精简。说的比较乱，纯属个人的想法。最后这段可以忽略掉:P

还是十分感谢作者的杰出贡献！

**Comment by tamlok** [comment]
Hi,

Vim模式在VNote里面只是属于编辑器里面的一个模式，而其他的快捷键都是尽量模仿Vim的习惯。所以诸如`ctrl+s`和`ctrl+e`以及`ctrl+g`等等都是平台上的普通快捷键，和Vim无关。当然`ctrl+e`就模仿了Vim的前导键的思想。

因为快捷键资源比较稀缺，所以`ctrl+w`没有单独拿出来，而且`ctrl+w`在编辑模式里面也用于向前删除一个单词。所以，有一个导航模式，比如`ctrl+e w`就可以再按一个按键跳转到任意部件。当然这个也是模仿Vim插件easymotion的思想。

其实说白了，就是Vim在VNote里面只是一个可选的编辑器里面的按键模式，并非全局的；而我希望VNote给不使用Vim模式的用户也提供全面的快捷键支持。

所以，对于tab切换，直接`gt`就不现实了，因为其他没开Vim模式的就没有正常模式了，gt输入应该就是输入gt这两个字母。所以，VNote使用`ctrl+e j/k`或`ctrl+e 2`这种方式来跳转到特定tab。

VNote面向的很多用户都是不熟悉Vim的，所以Vim只能局限于编辑器中。当然，VNote的初衷也是希望能将代码编辑器（如Vim）的很多优点带到笔记软件中，带到其他普通用户群中。让他们知道，原来可以按一个快捷键`ctrl+g`，然后就可以实现任意查找和跳转的（模仿CtrlP插件）。

VNote定位的是笔记软件，希望能在个人知识管理方面有一技之长。当然，VNote是开源的，好处就是每个人觉得不爽了，都可以根据自己的想法对VNote进行裁剪；坏处就是，目前还没有用户能投入到VNote的开发或裁剪中。:)

谢谢！
