### ISSUE TITLE
存在XSS漏洞

### ISSUE THREAD

**Issue by g0h3aler** [vnotex/vnote#930]
Windows系统最新版2.7.2
![图片](https://user-images.githubusercontent.com/38587657/62842872-0d1dc480-bce8-11e9-9b69-5a40d02c0d39.png)
存在安全问题，存储型XSS，在文章里写入XSS的payload:<img src=1 onerror="alert(/xss/)">，以阅读模式打开即可弹框
![图片](https://user-images.githubusercontent.com/38587657/62842957-ca102100-bce8-11e9-9ad3-f65490695c31.png)

**Comment by tamlok** [comment]
Fixed. Turned off by default due to its personal use and perf issue.

https://github.com/vnotex/vnote/blob/315d5433998b122fdba68d2492dbd71290b13f44/src/data/core/vnotex.json#L222

Thanks!
