### ISSUE TITLE
支持通过外部文件引用的方式加入plantuml

### ISSUE THREAD

**Issue by Wood-Xia** [vnotex/vnote#937]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

Symptoms (表现):
当前对plantuml的支持，好像必须通过嵌入代码段的方式。如下所示：
`
```puml
A->B: message
```
`
目前貌似没法提供这样的功能。因此，采用的一个变通方法就是复制plantuml文件中的代码到markdown文件中。

**需求： 有时候我们希望plantuml文件可以单独编辑管理，然后用markdown来引用它。同时，和通过代码块方式一样 ，可以支持实时渲染展示**

How to Repro (如何复现):
N/A

**Comment by tamlok** [comment]
这种实现方式，一旦脱离vnote，就完全不可用了，大大消弱markdown的便携性呀！

**Comment by Wood-Xia** [comment]
不会呀，这个和插入其他图片一样的道理。整体上提高了灵活性：separate the concern.
当前我们自己用脚本处理markdown中的plantuml应用。
但是我发现VNote后，我觉这个东西真不错，如果能支持这样方式，会有利于基于VNote的文档管理。

**Comment by tamlok** [comment]
图片是Markdown的基础语法，所以md编辑器都支持。但是PlantUML，如果是以文件的方式来插入的话，例如：

```md
下面是一个类图：

@some-plantumlfile.puml

从上面类图中我们可以看到xxxxxxx
```

你的意思是在VNote里面，通过`@...`的方式来引入一个文件，然后渲染的时候将其转化为PlantUML图表，对吧？当这个md文件拿到别的编辑器下面的时候，就完全不会渲染了。这样就是我说的没有便携性了。

**Comment by Wood-Xia** [comment]
是的。我的本意就是这个。
这个功能是依赖于VNote的。
当用户使用这个功能时，就需要权衡。

**Comment by tamlok** [comment]
PlantUML 自身是可以支持引用文件的，但需要使用本地模式。

![image](https://github.com/vnotex/vnote/assets/5763157/6c7a46e9-4434-42f7-9cdb-bca89f7319f3)
