### ISSUE TITLE
mysql语法高亮问题

### ISSUE THREAD

**Issue by deathrush** [vnotex/vnote#942]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.1

Symptoms (表现):

mysql类型代码块:

```mysql
# 创建测试表
create table users(
userid int unsigned not null,
user_name varchar(64) default null,
primary key(userid)
) engine=innodb;

#  插入20000行测试数据
delimiter $$
drop procedure if exists proc_auto_insertdata$$
create procedure proc_auto_insertdata()
begin
    declare init_data integer default 1;
    while init_data<=20000 do
    insert into users values(init_data,concat('user', init_data));
    set init_data=init_data+1;
    end while;
end$$
delimiter ;
call proc_auto_insertdata();
```

How to Repro (如何复现):

会有奇怪的红色高亮

另外:
1. 能否将`#`也作为mysql语法中的注释。
2. 能否将`json`作为javascript语法的同义词。

**Comment by tamlok** [comment]
Hi,

VNote用的是[Highlight.js](https://highlightjs.org/static/demo/)，这里的demo貌似只有SQL语言。在不换掉Highlight.js的前提下，VNote是做不了什么事情了。

谢谢！

**Comment by tamlok** [comment]
Use `prism.js` now. Should be fixed.
