### ISSUE TITLE
怎样记住导出 PDF 的默认高级页面设置？

### ISSUE THREAD

**Issue by UM-Li** [vnotex/vnote#955]
**操作系统**：Linux（Manjaro）

**VNote 版本**：2.7.1（AUR vnote-bin 包）

**问题**：怎样让 VNote 记住导出 PDF 的高级页面设置？

**如何复现**：
1. 打开一个笔记文件；
2. Ctrl+E+O 打开导出窗口；
3. 选择目标格式为 PDF；
4. （此时纸张大小为 A4）点击“设置”按钮，设定纸张大小为 Letter 并调整页边距；
5. 确定并导出 PDF；
6. Ctrl+E+O 再次打开导出窗口，发现纸张大小变回 A4，页边距也恢复默认值。

**Comment by tamlok** [comment]
暂时好像没有记忆，后面加上。

**Comment by Siheyuan98** [comment]
谢谢！这边大量使用 Letter 纸打印，每次都要调就比较麻烦 :joy:

**Comment by tamlok** [comment]
新版应该可以记忆了。
