### ISSUE TITLE
反馈：vnote自动全屏

### ISSUE THREAD

**Issue by BitTsui** [vnotex/vnote#979]
我是win10，今天刚刚安装vnote。在使用过程中，我发现vnote会自动全屏、菜单栏失效，右上角没有红×。我只能通过win+D快捷键回到桌面，才能继续关掉vnote的客户端。但是重启后问题并没有消失。

**Comment by BitTsui** [comment]
看到上一个issue后，发现需要说明一下详细信息。那好吧，详细信息如下：
操作系统：Windows10专业版
vnote版本：2.7.2
具体操作：查看vnote的标签时，vnote客户端一闪，自动全屏，出现问题。
内部笔记：可以使用。

**Comment by tamlok** [comment]
hi，

显卡驱动造成opengl的问题，具体参考置顶issue处理:

https://github.com/tamlok/vnote/issues/853

谢谢！
