### ISSUE TITLE
需求：增加session.ini自动保存功能

### ISSUE THREAD

**Issue by ustczzh** [vnotex/vnote#982]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现): 目前session.ini只会在退出时保存，没有自动保存功能。我使用坚果云同步VNote文件夹时，必须先在A机器退出VNote，等同步后，在B机器打开VNote才能恢复上一个工作状态。能否增加session.ini自动保存功能。比如每隔1分钟保存一次，这样可以使用重启功能重新载入最新的session.ini。

How to Repro (如何复现):

**Comment by tamlok** [comment]
目前随时按需保存了，但不建议同步session.ini
