### ISSUE TITLE
反馈：修改自定义快捷键之后，alert 警告信息的渲染失效

### ISSUE THREAD

**Issue by lzm-cn** [vnotex/vnote#984]
OS Version (操作系统): Windows,

VNote Version (Help - About VNote - Version: )(VNote版本): 2.7.2

Symptoms (表现):
修改自定义快捷键之后，alert 警告信息的渲染失效

How to Repro (如何复现):
修改EditReadNote=Ctrl+R，然后重启VNote，发现 之前可以正常 渲染为蓝色的alert-info段落变成了常规文本。

**Comment by tamlok** [comment]
看看md菜单下面的渲染器是不是md-it？

**Comment by lzm-cn** [comment]
> 看看md菜单下面的渲染器是不是md-it？

是的，渲染器没有修改过

**Comment by tamlok** [comment]
把md文本贴一部分相关的上来，我这边试试。

**Comment by lzm-cn** [comment]
> 把md文本贴一部分相关的上来，我这边试试。

::: alert-info
你好
:::

**Comment by tamlok** [comment]
呃。。。没上下文没啥用的。你上下空一行了吗？

**Comment by lzm-cn** [comment]
> 呃。。。没上下文没啥用的。你上下空一行了吗？

空行了呢，你的机器上没有复现吗？

**Comment by tamlok** [comment]
复现不了，一定是其他的问题，快捷键和这个效果是毫不相关的。

![image](https://user-images.githubusercontent.com/5763157/65598532-3bbcd980-dfce-11e9-8313-80b212235612.png)
