### ISSUE TITLE
标签页上的序号，是否可以取消？

### ISSUE THREAD

**Issue by roro4ever** [vnotex/vnote#988]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
当打开标签页时，每个标签页自带一个编号，这个编号其实没有意义，有时候反而造成一些困扰，比如笔记标题本身就以编号开头的：笔记标签 5.1 路由选择，5.2 拥塞控制，变成了 1.5.1 路由选择 ......

就像chrome, firefox ，标签页也不需要带不拿好。

**Comment by tamlok** [comment]
标签页的序号主要是可以使用快捷键`Ctrl+E 5`跳转到第5个标签页。暂时没有可配置选项。

**Comment by roro4ever** [comment]
哦，这都不算bug，算个性化需求吧，其实打开的标签页一般就几个，不需要序号也能用 ctrl + E 。

**Comment by tamlok** [comment]
已经取消
