### ISSUE TITLE
Bug: 切换编辑模式和阅读模式时，会丢失编辑位置。

### ISSUE THREAD

**Issue by roro4ever** [vnotex/vnote#991]
OS Version (操作系统): Windows, Linux, macOS

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
编辑模式下，假设光标停在最后一行，切换到阅读模式再切换回来时，编辑位置往往会发生变化，有时会跑到第一行去。

我用的VIM模式，markdown经常出现这种情况。
How to Repro (如何复现):

**Comment by Hemmelfort** [comment]
不止是vim模式，普通模式也一样。好像是预览时不能翻页，一翻页就会丢失位置。貌似是想通过预览的位置来判断编辑点的位置，只是判断错了

**Comment by tamlok** [comment]
已支持双边预览： https://github.com/vnotex/vnote/releases/tag/v3.10.0
