### ISSUE TITLE
为什么在阅读模式下，复制整行最后会有空格

### ISSUE THREAD

**Issue by sundafa** [vnotex/vnote#994]
OS Version (操作系统): Windows

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..

Symptoms (表现):
为什么在阅读模式下，复制整行到其它文件中会有空格和换行

How to Repro (如何复现):
阅读模式下双击一行复制到其它地方

**Comment by tamlok** [comment]
你复制一下上面任意一行，粘贴也一样也空格哦。

**Comment by tamlok** [comment]
为什么在阅读模式下，复制整行到其它文件中会有空格和换行阅读模式下双击一行复制到其它地方
